import Foundation

extension Localization {
    static let en: [L10nKey: String] = [
        .appName: "Kontiva",
        .appTagline: "A calm, private view of your Swiss budget.",
        .notBetaNotice: "Early development build – not beta-ready, not V1.",

        .navOverview: "Overview",
        .navPlanning: "Monthly Planning",
        .navBills: "Bills",
        .navSettings: "Settings",
        .navReport: "Report a Problem",
        .navInsights: "Insights",
        .navSparen: "Savings",
        .sparenSubtitle: "Recurring savings contributions — and what has already added up.",
        .sparenEmpty: "No savings goals yet. Set up what you save for each month.",
        .sparenMonthlyTotal: "Savings / month",
        .sparenAccumulatedTotal: "Already saved",
        .sparenPerMonth: "/ month",
        .sparenContributions: "contributions",
        .sparenSince: "since",
        .sparenOpenEnded: "No target amount",
        .sparenGoalsLabel: "Goals",
        .savingsCatCar: "Car",
        .savingsCatVacation: "Vacation",
        .savingsCatHome: "Home",
        .savingsCatRetirement: "Pillar 3a / Retirement",
        .savingsCatEmergency: "Emergency fund",
        .savingsCatEducation: "Education",
        .savingsCatOther: "Other",
        .savingsCatWedding: "Wedding",
        .savingsCatFamily: "Family & children",
        .savingsCatRenovation: "Renovation & furnishing",
        .savingsCatElectronics: "Electronics",
        .savingsCatTaxes: "Tax reserve",
        .savingsCatInvestment: "Investments",
        .savingsCatHealth: "Health",
        .savingsCatGift: "Gifts",
        .overviewPlannedSavings: "Savings this month",
        .overviewShowCalculation: "Show calculation",
        .overviewTrendTitle: "Trend · 6 months",
        .overviewStatusGood: "Healthy surplus",
        .overviewStatusTight: "Tight",
        .overviewStatusNegative: "In the red",
        .overviewAllocationOf: "of net income",
        .formStartDate: "Saving since",
        .formStartingBalance: "Starting balance (optional)",
        .insightsSubtitle: "Guidance on your budget — where your money sits and where you can save.",
        .insightOverspending: "You're spending more than you earn",
        .insightTightBudget: "Little room this month",
        .insightHealthySurplus: "Healthy surplus",
        .insightHighFixed: "High fixed-cost burden",
        .insightHighHousing: "High housing costs",
        .insightLargestFixed: "Largest fixed-cost block",
        .insightLargestVariable: "Largest variable budget",
        .insightOverdue: "Overdue bills",
        .insightNoSavings: "No savings planned yet",
        .insightGoodSavings: "Good savings rate",
        .insightAllHealthy: "Your budget looks healthy",
        .insightHousingHint: "Guideline: at most a third of income",
        .insightNoSavingsDetail: "You have room — a savings goal could help.",
        .insightAllHealthyDetail: "Nothing stands out. Add more data for sharper insights.",
        .fragOfNetIncome: "of net income",
        .fragOfFixedCosts: "of fixed costs",
        .fragShortfall: "Shortfall",

        .commonAdd: "Add",
        .commonEdit: "Edit",
        .commonDelete: "Delete",
        .commonCancel: "Cancel",
        .commandsAdd: "Add entry",
        .billsAddCta: "Add your first bill",
        .sparenAddCta: "Create a savings goal",
        .overviewAddCta: "Add income",
        .commonSave: "Save",
        .commonSaved: "Saved",
        .commonClose: "Close",
        .commonDone: "Done",
        .commonShowSampleData: "Show sample data",
        .commonHideSampleData: "Hide sample data",
        .commonEmptyHint: "No data entered yet.",
        .commonCopy: "Copy",
        .commonOptions: "Options",
        .commonMoveUp: "Move up",
        .commonMoveDown: "Move down",
        .monthToday: "Today",

        .formName: "Name",
        .formAmount: "Amount (CHF)",
        .formStatus: "Status",
        .formNotes: "Note",
        .formInvalidAmount: "Please enter a valid amount.",
        .formThirteenthAmount: "13th salary (amount)",
        .formThirteenthModel: "13th salary model",
        .thirteenthModelSeparate: "Show separately",
        .thirteenthModelAveraged: "Spread over 12 months",
        .formTarget: "Savings target (amount)",
        .formSaved: "Already saved",
        .formMonthlyContribution: "Monthly contribution",
        .formCategory: "Category",
        .formLimitedDuration: "Limited standing order",
        .formLimitedDurationHint: "E.g. 6 tax instalments — counted only in those months, then dropped automatically.",
        .formStartMonth: "First instalment",
        .formInstallments: "Number of instalments",
        .planningStandingOrder: "Standing order",
        .catRent: "Rent",
        .catSubscription: "Subscription",
        .catLeasing: "Leasing",
        .catUtilities: "Utilities",
        .catTelecom: "Telecom",
        .catGroceries: "Groceries",
        .catFuel: "Fuel",
        .catTransport: "Transport",
        .catPersonal: "Personal",
        .catDining: "Dining out",
        .catHousehold: "Household",

        .overviewTitle: "Overview",
        .overviewAvailableThisMonth: "Available this month",
        .overviewNetIncome: "Net income this month",
        .overviewThirteenthSeparate: "13th salary (shown separately)",
        .overviewRecurringFixed: "Fixed costs",
        .overviewPlannedVariable: "Variable spending",
        .overviewBillsDueThisMonth: "Open bills due this month",
        .overviewOverdueBills: "Overdue bills",
        .overviewSavingsTarget: "Savings target",
        .overviewSecurityStatus: "Security status",
        .overviewFormulaExplainer: "Available = net income − fixed costs − variable budgets − open bills due this month − overdue bills. Paid and future bills do not reduce the amount.",
        .overviewEmpty: "Enter income and costs in Monthly Planning to see your overview.",
        .chartSpendingTitle: "Breakdown this month",
        .chartByCategory: "By category",

        .planningTitle: "Monthly Planning",
        .planningIncome: "Income",
        .planningFixed: "Fixed costs",
        .planningVariable: "Variable spending",
        .planningSavings: "Savings target",
        .planningFixedExplainer: "Fixed costs repeat every month: rent, insurance, subscriptions, leasing.",
        .planningVariableExplainer: "You plan variable budgets yourself: groceries, fuel, personal spending.",
        .planningOneOffHint: "One-off bills are managed under “Bills”.",
        .planningEmpty: "Start with your income, then add fixed costs and budgets.",
        .planningBalance: "Planned balance",

        .billsTitle: "Bills",
        .billsStatusOpen: "Open",
        .billsStatusPaid: "Paid",
        .billsStateOverdue: "Overdue",
        .billsStateDueThisMonth: "Due this month",
        .billsStateFuture: "Future",
        .billsAffectsBalance: "Reduces available amount",
        .billsNoBalanceImpact: "No effect on this month",
        .billsDueDate: "Due date",
        .billsProvider: "Provider",
        .billsEmpty: "No bills entered yet. One-off bills with a due date will appear here.",
        .billsMarkPaid: "Mark as paid",
        .billsMarkOpen: "Mark as open",
        .billsOpenTotal: "Open total",

        .navSchulden: "Debts",
        .schuldenSubtitle: "Keep an eye on overdue bills and debt-enforcement.",
        .schuldenEmpty: "No debts recorded. Overdue bills appear here automatically – and you can note debt-enforcement (Betreibung) or certificates of loss.",
        .schuldenAddCta: "Record a debt",
        .schuldenTotal: "Total debt",
        .schuldenOverdueBills: "Overdue bills",
        .schuldenRecorded: "Recorded debts",
        .schuldenManagedInBills: "Manage overdue bills under “Bills”.",
        .debtTypeOpenClaim: "Open claim",
        .debtTypeBetreibung: "Debt enforcement",
        .debtTypePfaendung: "Wage/asset seizure",
        .debtTypeVerlustschein: "Certificate of loss",
        .debtTypeOther: "Other debt",
        .debtCreditor: "Creditor",
        .debtReference: "Reference / case no.",
        .debtDate: "Date",
        .debtType: "Type",
        .schuldenGuidanceTitle: "Finding your way out of debt",
        .schuldenTipContactTitle: "Get in touch early",
        .schuldenTipContactBody: "Talk to creditors early. A written instalment plan is often possible and avoids formal enforcement.",
        .schuldenTipBetreibungTitle: "If enforcement starts",
        .schuldenTipBetreibungBody: "After the payment order you have 20 days to pay – or 10 days to file an objection (Rechtsvorschlag) if the claim is unjustified.",
        .schuldenTipExistenzminimumTitle: "Your subsistence minimum is protected",
        .schuldenTipExistenzminimumBody: "In a seizure your subsistence minimum stays untouchable – base amount, rent, health insurance and social contributions.",
        .schuldenTipVerlustscheinTitle: "Certificate of loss",
        .schuldenTipVerlustscheinBody: "A certificate of loss lapses only after 20 years. You can be pursued again only once you come into new assets.",
        .schuldenTipCounselingTitle: "Free debt counselling",
        .schuldenTipCounselingBody: "Debt counselling Switzerland, Caritas and budget advice help free and confidentially. Pay off the debts with the worst consequences first.",
        .schuldenDisclaimer: "General information, not legal advice.",

        .catInsurance: "Insurance",
        .catOther: "Other",
        .catMortgage: "Mortgage",
        .catHealthInsurance: "Health insurance",
        .catSerafe: "Radio/TV (Serafe)",
        .catPublicTransport: "Transit pass",
        .catChildcare: "Childcare",
        .catMembership: "Memberships",
        .catAlimony: "Alimony & support",
        .catTaxes: "Taxes",
        .catClothing: "Clothing",
        .catHealth: "Health",
        .catLeisure: "Leisure & hobbies",
        .catEntertainment: "Entertainment",
        .catChildren: "Children",
        .catPets: "Pets",
        .catGifts: "Gifts",
        .catTravel: "Travel",
        .catCharity: "Charity",
        .catEducation: "Education",

        .settingsTitle: "Settings",
        .settingsLanguage: "Language",
        .settingsTheme: "Colour theme",
        .themeSwissRed: "Swiss Red",
        .themeOrange: "Orange",
        .themeSand: "Sand",
        .themeGreen: "Green",
        .themeTeal: "Teal",
        .themeBlue: "Blue",
        .themePurple: "Purple",
        .themePink: "Pink",
        .settingsData: "Data",
        .settingsHousehold: "Household",
        .settingsCanton: "Canton",
        .settingsProfile: "Profile",
        .profileName: "Name",
        .profileChoosePicture: "Choose profile picture",
        .profileNoPicture: "No picture",
        .profileLocalNote: "Stored only locally on this device.",
        .settingsSecurity: "Security",
        .settingsAutoLock: "Auto-lock",
        .settingsChangePassphrase: "Change passphrase/PIN",
        .settingsBackup: "Encrypted backup",
        .settingsRestore: "Restore",
        .settingsPrivacy: "Privacy",
        .settingsDangerZone: "Danger zone",
        .settingsDeleteAll: "Delete all local data",
        .backupCreateTitle: "Create encrypted backup",
        .backupPassphrase: "Backup passphrase",
        .backupHint: "Choose a separate backup passphrase. It is required to restore — there is no recovery of the backup passphrase.",
        .restorePreview: "Preview",
        .restoreConfirm: "Replace all local data",
        .restoreWarning: "This permanently overwrites all local data.",
        .backupInvalid: "Invalid backup or wrong backup passphrase.",
        .backupSavedHint: "Keep the backup file and the backup passphrase in a safe place.",

        .reportTitle: "Report a Problem",
        .reportSummary: "Summary",
        .reportExpected: "Expected behavior",
        .reportActual: "Actual behavior",
        .reportSteps: "Steps to reproduce",
        .reportArea: "Affected area",
        .reportRedactionNote: "Sensitive details are removed locally. You review the report before copying.",
        .reportCopyHint: "The report is not sent automatically. You copy it yourself.",

        .exportReport: "Export report",
        .pdfTitle: "Financial overview",
        .pdfSubtitle: "Personal household report",
        .pdfSummary: "At a glance",
        .pdfGeneratedOn: "Generated on",
        .pdfConfidential: "Confidential",
        .pdfPage: "Page",
        .pdfTotal: "Total",
        .pdfColProgress: "Progress",
        .pdfUnencryptedNote: "The report is an unencrypted, readable PDF. Keep it somewhere safe.",
        .pdfNoData: "No data to export yet.",
        .pdfDefaultHousehold: "My household",

        .lockTitle: "Locked",
        .lockWelcomeSetup: "Welcome to Kontiva",
        .lockWelcomeBack: "Welcome back",
        .lockSetupTitle: "Set up passphrase",
        .lockEnterPassphrase: "Enter passphrase or PIN",
        .lockWrongPassphrase: "Wrong passphrase. Please try again.",
        .lockRecoveryWarning: "There is no recovery. Without your passphrase, your data cannot be accessed.",
        .lockRecoveryAcknowledge: "I understand there is no recovery.",
        .securityNote: "Your data is stored locally and encrypted (AES-256-GCM). No cloud, no server, no passphrase recovery.",

        .onboardingIntroBody: "Kontiva helps you keep a calm view of your Swiss household budget – entirely on this device.",
        .onboardingStart: "Get started",
        .onboardingProfileTitle: "Create a profile",
        .onboardingProfileBody: "Give yourself a name and pick a picture. Both stay only on this device.",
        .onboardingSkip: "Skip",
        .onboardingFeaturePrivate: "Fully local – no cloud, no tracking",
        .onboardingFeatureSecure: "Encrypted with AES-256",
        .onboardingFeatureMoney: "Accurate to the rappen, no rounding errors",
        .onboardingConfirmPassphrase: "Confirm passphrase",
        .onboardingPassphraseNote: "Write your passphrase down somewhere safe — it cannot be reset.",
        .backupNudgeText: "Create an encrypted backup. Without one, your data is lost if you forget the passphrase.",
        .commonNext: "Next",
        .navMore: "More",
        .actionLock: "Lock",
    ]
}
