import Foundation

extension Localization {
    static let zhHans: [L10nKey: String] = [
        .appName: "Kontiva",
        .appTagline: "平静、私密地纵览你的瑞士预算。",
        .notBetaNotice: "早期开发版本——非测试版，非 V1。",

        .navOverview: "概览",
        .navPlanning: "月度规划",
        .navBills: "账单",
        .navSettings: "设置",
        .navReport: "报告问题",
        .navInsights: "分析",
        .navSparen: "储蓄",
        .sparenSubtitle: "定期储蓄缴存——以及已经积累的金额。",
        .sparenEmpty: "尚无储蓄目标。确定你每月为何储蓄。",
        .sparenMonthlyTotal: "储蓄 / 月",
        .sparenAccumulatedTotal: "已储蓄",
        .sparenPerMonth: "/ 月",
        .sparenContributions: "笔缴存",
        .sparenSince: "自",
        .sparenOpenEnded: "无目标金额",
        .sparenGoalsLabel: "目标",
        .savingsCatCar: "汽车",
        .savingsCatVacation: "度假",
        .savingsCatHome: "住房",
        .savingsCatRetirement: "第三支柱 3a / 养老金",
        .savingsCatEmergency: "应急基金",
        .savingsCatEducation: "教育",
        .savingsCatOther: "其他",
        .savingsCatWedding: "婚礼",
        .savingsCatFamily: "家庭与子女",
        .savingsCatRenovation: "装修与布置",
        .savingsCatElectronics: "电子产品",
        .savingsCatTaxes: "税款储备",
        .savingsCatInvestment: "投资",
        .savingsCatHealth: "健康",
        .savingsCatGift: "礼物",
        .overviewPlannedSavings: "本月储蓄",
        .overviewShowCalculation: "显示计算",
        .overviewTrendTitle: "趋势 · 6 个月",
        .overviewStatusGood: "健康结余",
        .overviewStatusTight: "紧张",
        .overviewStatusNegative: "亏空",
        .overviewAllocationOf: "占净收入",
        .formStartDate: "储蓄起始",
        .formStartingBalance: "起始余额（可选）",
        .insightsSubtitle: "关于你预算的指引——你的钱在哪里、哪里可以节省。",
        .insightOverspending: "你的支出超过收入",
        .insightTightBudget: "本月余地不多",
        .insightHealthySurplus: "健康结余",
        .insightHighFixed: "固定开支较高",
        .insightHighHousing: "住房开支较高",
        .insightLargestFixed: "固定开支中最大的一项",
        .insightLargestVariable: "最大的可变预算",
        .insightOverdue: "逾期账单",
        .insightNoSavings: "尚未规划储蓄",
        .insightGoodSavings: "储蓄率良好",
        .insightAllHealthy: "你的预算看起来健康",
        .insightHousingHint: "参考：最多为收入的三分之一",
        .insightNoSavingsDetail: "你有余地——设定储蓄目标会有帮助。",
        .insightAllHealthyDetail: "没有突出之处。添加更多数据以获得更精准的分析。",
        .fragOfNetIncome: "占净收入",
        .fragOfFixedCosts: "占固定开支",
        .fragShortfall: "缺口",

        .commonAdd: "添加",
        .commonEdit: "编辑",
        .commonDelete: "删除",
        .commonCancel: "取消",
        .commandsAdd: "添加条目",
        .billsAddCta: "添加你的第一笔账单",
        .sparenAddCta: "创建储蓄目标",
        .overviewAddCta: "添加收入",
        .commonSave: "保存",
        .commonSaved: "已保存",
        .commonClose: "关闭",
        .commonDone: "完成",
        .commonShowSampleData: "显示示例数据",
        .commonHideSampleData: "隐藏示例数据",
        .commonEmptyHint: "尚未输入数据。",
        .commonCopy: "复制",
        .commonOptions: "选项",
        .commonMoveUp: "上移",
        .commonMoveDown: "下移",
        .monthToday: "今天",

        .formName: "名称",
        .formAmount: "金额 (CHF)",
        .formStatus: "状态",
        .formNotes: "备注",
        .formInvalidAmount: "请输入有效金额。",
        .formThirteenthAmount: "第 13 个月工资（金额）",
        .formThirteenthModel: "第 13 个月工资模式",
        .thirteenthModelSeparate: "单独显示",
        .thirteenthModelAveraged: "分摊到 12 个月",
        .formTarget: "储蓄目标（金额）",
        .formSaved: "已储蓄",
        .formMonthlyContribution: "每月缴存",
        .formCategory: "类别",
        .formLimitedDuration: "限期固定转账",
        .formLimitedDurationHint: "例如 6 期税款——仅在这些月份计入，之后自动移除。",
        .formStartMonth: "首期",
        .formInstallments: "期数",
        .planningStandingOrder: "固定转账",
        .catRent: "房租",
        .catSubscription: "订阅",
        .catLeasing: "租赁",
        .catUtilities: "水电费",
        .catTelecom: "通信",
        .catGroceries: "日用食品",
        .catFuel: "燃料",
        .catTransport: "交通",
        .catPersonal: "个人",
        .catDining: "外出就餐",
        .catHousehold: "家庭开支",

        .overviewTitle: "概览",
        .overviewAvailableThisMonth: "本月可用",
        .overviewNetIncome: "本月净收入",
        .overviewThirteenthSeparate: "第 13 个月工资（单独）",
        .overviewRecurringFixed: "固定开支",
        .overviewPlannedVariable: "可变支出",
        .overviewBillsDueThisMonth: "本月未付账单",
        .overviewOverdueBills: "逾期账单",
        .overviewSavingsTarget: "储蓄目标",
        .overviewSecurityStatus: "安全状态",
        .overviewFormulaExplainer: "可用 = 净收入 − 固定开支 − 可变预算 − 本月未付账单 − 逾期账单。已付和未来账单不减少金额。",
        .overviewEmpty: "在“月度规划”中输入收入和开支即可查看概览。",
        .chartSpendingTitle: "本月分布",
        .chartByCategory: "按类别",

        .planningTitle: "月度规划",
        .planningIncome: "收入",
        .planningFixed: "固定开支",
        .planningVariable: "可变支出",
        .planningSavings: "储蓄目标",
        .planningFixedExplainer: "固定开支每月重复：房租、保险、订阅、租赁。",
        .planningVariableExplainer: "可变预算由你自行规划：日用食品、燃料、个人支出。",
        .planningOneOffHint: "一次性账单在“账单”中管理。",
        .planningEmpty: "从收入开始，然后添加固定开支和预算。",
        .planningBalance: "计划余额",

        .billsTitle: "账单",
        .billsStatusOpen: "未付",
        .billsStatusPaid: "已付",
        .billsStateOverdue: "逾期",
        .billsStateDueThisMonth: "本月到期",
        .billsStateFuture: "未来",
        .billsAffectsBalance: "减少可用金额",
        .billsNoBalanceImpact: "本月无影响",
        .billsDueDate: "到期日",
        .billsProvider: "提供方",
        .billsEmpty: "尚无账单。带到期日的一次性账单会显示在此。",
        .billsMarkPaid: "标记为已付",
        .billsMarkOpen: "标记为未付",
        .billsOpenTotal: "未付总计",

        .navSchulden: "债务",
        .schuldenSubtitle: "关注逾期账单与强制催收。",
        .schuldenEmpty: "尚无记录债务。逾期账单会自动显示在此——你也可以记录强制催收 (Betreibung) 或损失证明。",
        .schuldenAddCta: "记录一笔债务",
        .schuldenTotal: "债务总额",
        .schuldenOverdueBills: "逾期账单",
        .schuldenRecorded: "已记录债务",
        .schuldenManagedInBills: "在“账单”中管理逾期账单。",
        .debtTypeOpenClaim: "未结债权",
        .debtTypeBetreibung: "强制催收",
        .debtTypePfaendung: "工资/财产扣押",
        .debtTypeVerlustschein: "损失证明",
        .debtTypeOther: "其他债务",
        .debtCreditor: "债权人",
        .debtReference: "参考 / 案件号",
        .debtDate: "日期",
        .debtType: "类型",
        .schuldenGuidanceTitle: "走出债务之路",
        .schuldenTipContactTitle: "尽早联系",
        .schuldenTipContactBody: "尽早与债权人沟通。书面分期还款计划通常可行，可避免正式催收程序。",
        .schuldenTipBetreibungTitle: "如果催收开始",
        .schuldenTipBetreibungBody: "收到付款令后，你有 20 天付款——若债权不成立，则有 10 天提出异议 (Rechtsvorschlag)。",
        .schuldenTipExistenzminimumTitle: "你的最低生活保障受到保护",
        .schuldenTipExistenzminimumBody: "在扣押时，你的最低生活保障不受触动——基本金额、房租、医疗保险和社会缴款。",
        .schuldenTipVerlustscheinTitle: "损失证明",
        .schuldenTipVerlustscheinBody: "损失证明在 20 年后才失效。只有当你获得新资产时才可能被再次追偿。",
        .schuldenTipCounselingTitle: "免费债务咨询",
        .schuldenTipCounselingBody: "Schuldenberatung Schweiz、Caritas 和预算咨询提供免费且保密的帮助。先偿还后果最严重的债务。",
        .schuldenDisclaimer: "一般信息，非法律咨询。",

        .catInsurance: "保险",
        .catOther: "其他",
        .catMortgage: "房贷",
        .catHealthInsurance: "医疗保险",
        .catSerafe: "广播电视费 (Serafe)",
        .catPublicTransport: "公交月票",
        .catChildcare: "托儿",
        .catMembership: "会员费",
        .catAlimony: "赡养费",
        .catTaxes: "税款",
        .catClothing: "衣物",
        .catHealth: "健康",
        .catLeisure: "休闲与爱好",
        .catEntertainment: "娱乐",
        .catChildren: "子女",
        .catPets: "宠物",
        .catGifts: "礼物",
        .catTravel: "旅行",
        .catCharity: "捐赠",
        .catEducation: "教育",

        .settingsTitle: "设置",
        .settingsLanguage: "语言",
        .settingsTheme: "配色主题",
        .themeSwissRed: "瑞士红",
        .themeOrange: "橙色",
        .themeSand: "沙色",
        .themeGreen: "绿色",
        .themeTeal: "青色",
        .themeBlue: "蓝色",
        .themePurple: "紫色",
        .themePink: "粉色",
        .settingsData: "数据",
        .settingsHousehold: "家庭",
        .settingsCanton: "州",
        .settingsProfile: "个人资料",
        .profileName: "名字",
        .profileChoosePicture: "选择头像",
        .profileNoPicture: "无图片",
        .profileLocalNote: "仅本地保存在此设备上。",
        .settingsSecurity: "安全",
        .settingsAutoLock: "自动锁定",
        .settingsChangePassphrase: "更改密码/PIN",
        .settingsBackup: "加密备份",
        .settingsRestore: "恢复",
        .settingsPrivacy: "隐私",
        .settingsDangerZone: "危险区域",
        .settingsDeleteAll: "删除所有本地数据",
        .backupCreateTitle: "创建加密备份",
        .backupPassphrase: "备份密码",
        .backupHint: "为备份选择一个单独的密码。恢复时需要它——密码无法找回。",
        .restorePreview: "预览",
        .restoreConfirm: "替换所有本地数据",
        .restoreWarning: "这将永久覆盖所有本地数据。",
        .backupInvalid: "备份无效或密码错误。",
        .backupSavedHint: "请将备份文件和密码保存在安全的地方。",

        .reportTitle: "报告问题",
        .reportSummary: "摘要",
        .reportExpected: "预期行为",
        .reportActual: "实际行为",
        .reportSteps: "重现步骤",
        .reportArea: "受影响区域",
        .reportRedactionNote: "敏感数据将在本地移除。你会在复制前查看报告。",
        .reportCopyHint: "报告不会自动发送。由你自行复制。",

        .exportReport: "导出报告",
        .pdfTitle: "财务概览",
        .pdfSubtitle: "个人家庭报告",
        .pdfSummary: "一览",
        .pdfGeneratedOn: "生成于",
        .pdfConfidential: "机密",
        .pdfPage: "页",
        .pdfTotal: "合计",
        .pdfColProgress: "进度",
        .pdfUnencryptedNote: "报告是可读的未加密 PDF。请保存在安全的地方。",
        .pdfNoData: "尚无可导出的数据。",
        .pdfDefaultHousehold: "我的家庭",

        .lockTitle: "已锁定",
        .lockWelcomeSetup: "欢迎使用 Kontiva",
        .lockWelcomeBack: "欢迎回来",
        .lockSetupTitle: "设置密码",
        .lockEnterPassphrase: "输入密码或 PIN",
        .lockWrongPassphrase: "密码错误。请重试。",
        .lockRecoveryWarning: "无法恢复。没有你的密码，将无法访问你的数据。",
        .lockRecoveryAcknowledge: "我明白无法恢复。",
        .securityNote: "你的数据以加密方式本地保存 (AES-256-GCM)。无云端、无服务器、无密码恢复。",

        .onboardingIntroBody: "Kontiva 帮助你平静地纵览瑞士家庭预算——完全在此设备上。",
        .onboardingStart: "开始",
        .onboardingProfileTitle: "创建个人资料",
        .onboardingProfileBody: "给自己取个名字并选择一张图片。两者都仅保留在此设备上。",
        .onboardingSkip: "跳过",
        .onboardingFeaturePrivate: "完全本地——无云端、无追踪",
        .onboardingFeatureSecure: "采用 AES-256 加密",
        .onboardingFeatureMoney: "精确到分，无四舍五入误差",
        .onboardingConfirmPassphrase: "确认密码",
        .onboardingPassphraseNote: "请将密码记在安全的地方——它无法重置。",
        .backupNudgeText: "创建加密备份。没有它，若忘记密码你将丢失数据。",
        .commonNext: "下一步",
        .navMore: "更多",
        .actionLock: "锁定",
    ]
}
