import Foundation

// Tamil. Best-effort — flagged as a high priority for native-speaker review.
extension Localization {
    static let ta: [L10nKey: String] = [
        .appName: "Kontiva",
        .appTagline: "உங்கள் சுவிஸ் பட்ஜெட்டின் அமைதியான, தனிப்பட்ட பார்வை.",
        .notBetaNotice: "ஆரம்ப கட்ட பதிப்பு – பீட்டா அல்ல, V1 அல்ல.",

        .navOverview: "கண்ணோட்டம்",
        .navPlanning: "மாதாந்திர திட்டமிடல்",
        .navBills: "பில்கள்",
        .navSettings: "அமைப்புகள்",
        .navReport: "சிக்கலைப் புகாரளி",
        .navInsights: "பகுப்பாய்வு",
        .navSparen: "சேமிப்பு",
        .sparenSubtitle: "வழக்கமான சேமிப்பு பங்களிப்புகள் – மற்றும் ஏற்கனவே சேர்த்தது.",
        .sparenEmpty: "இன்னும் சேமிப்பு இலக்குகள் இல்லை. ஒவ்வொரு மாதமும் எதற்காக சேமிக்கிறீர்கள் என்பதைத் தீர்மானியுங்கள்.",
        .sparenMonthlyTotal: "சேமிப்பு / மாதம்",
        .sparenAccumulatedTotal: "ஏற்கனவே சேமித்தது",
        .sparenPerMonth: "/ மாதம்",
        .sparenContributions: "பங்களிப்புகள்",
        .sparenSince: "முதல்",
        .sparenOpenEnded: "இலக்குத் தொகை இல்லை",
        .sparenGoalsLabel: "இலக்குகள்",
        .savingsCatCar: "கார்",
        .savingsCatVacation: "விடுமுறை",
        .savingsCatHome: "வீடு",
        .savingsCatRetirement: "தூண் 3a / ஓய்வூதியம்",
        .savingsCatEmergency: "அவசர நிதி",
        .savingsCatEducation: "கல்வி",
        .savingsCatOther: "மற்றவை",
        .savingsCatWedding: "திருமணம்",
        .savingsCatFamily: "குடும்பம் மற்றும் குழந்தைகள்",
        .savingsCatRenovation: "புதுப்பித்தல் மற்றும் அலங்காரம்",
        .savingsCatElectronics: "மின்னணு சாதனங்கள்",
        .savingsCatTaxes: "வரிக்கான ஒதுக்கீடு",
        .savingsCatInvestment: "முதலீடுகள்",
        .savingsCatHealth: "ஆரோக்கியம்",
        .savingsCatGift: "பரிசுகள்",
        .overviewPlannedSavings: "இந்த மாத சேமிப்பு",
        .overviewShowCalculation: "கணக்கீட்டைக் காட்டு",
        .overviewTrendTitle: "போக்கு · 6 மாதங்கள்",
        .overviewStatusGood: "ஆரோக்கியமான உபரி",
        .overviewStatusTight: "இறுக்கமானது",
        .overviewStatusNegative: "பற்றாக்குறையில்",
        .overviewAllocationOf: "நிகர வருமானத்தில்",
        .formStartDate: "சேமிப்பு தொடக்கம்",
        .formStartingBalance: "தொடக்க இருப்பு (விருப்பம்)",
        .insightsSubtitle: "உங்கள் பட்ஜெட்டுக்கான வழிகாட்டுதல் – உங்கள் பணம் எங்கே, எங்கே சேமிக்கலாம்.",
        .insightOverspending: "சம்பாதிப்பதை விட அதிகம் செலவழிக்கிறீர்கள்",
        .insightTightBudget: "இந்த மாதம் இடைவெளி குறைவு",
        .insightHealthySurplus: "ஆரோக்கியமான உபரி",
        .insightHighFixed: "அதிக நிலையான செலவுகள்",
        .insightHighHousing: "அதிக வீட்டுச் செலவுகள்",
        .insightLargestFixed: "நிலையான செலவில் மிகப் பெரிய பகுதி",
        .insightLargestVariable: "மிகப் பெரிய மாறும் பட்ஜெட்",
        .insightOverdue: "தாமதமான பில்கள்",
        .insightNoSavings: "இன்னும் சேமிப்பு திட்டமிடப்படவில்லை",
        .insightGoodSavings: "நல்ல சேமிப்பு விகிதம்",
        .insightAllHealthy: "உங்கள் பட்ஜெட் ஆரோக்கியமாகத் தெரிகிறது",
        .insightHousingHint: "வழிகாட்டுதல்: வருமானத்தில் அதிகபட்சம் மூன்றில் ஒரு பங்கு",
        .insightNoSavingsDetail: "உங்களுக்கு இடம் உள்ளது – ஒரு சேமிப்பு இலக்கு உதவலாம்.",
        .insightAllHealthyDetail: "எதுவும் தனித்து தெரியவில்லை. கூர்மையான பகுப்பாய்வுக்கு மேலும் தரவைச் சேர்க்கவும்.",
        .fragOfNetIncome: "நிகர வருமானத்தில்",
        .fragOfFixedCosts: "நிலையான செலவில்",
        .fragShortfall: "பற்றாக்குறை",

        .commonAdd: "சேர்",
        .commonEdit: "திருத்து",
        .commonDelete: "நீக்கு",
        .commonCancel: "ரத்து",
        .commandsAdd: "உள்ளீட்டைச் சேர்",
        .billsAddCta: "உங்கள் முதல் பில்லைச் சேர்க்கவும்",
        .sparenAddCta: "ஒரு சேமிப்பு இலக்கை உருவாக்கவும்",
        .overviewAddCta: "வருமானத்தைச் சேர்",
        .commonSave: "சேமி",
        .commonSaved: "சேமிக்கப்பட்டது",
        .commonClose: "மூடு",
        .commonDone: "முடிந்தது",
        .commonShowSampleData: "மாதிரி தரவைக் காட்டு",
        .commonHideSampleData: "மாதிரி தரவை மறை",
        .commonEmptyHint: "இன்னும் தரவு உள்ளிடப்படவில்லை.",
        .commonCopy: "நகலெடு",
        .commonOptions: "விருப்பங்கள்",
        .commonMoveUp: "மேலே நகர்த்து",
        .commonMoveDown: "கீழே நகர்த்து",
        .monthToday: "இன்று",

        .formName: "பெயர்",
        .formAmount: "தொகை (CHF)",
        .formStatus: "நிலை",
        .formNotes: "குறிப்பு",
        .formInvalidAmount: "சரியான தொகையை உள்ளிடவும்.",
        .formThirteenthAmount: "13வது மாத ஊதியம் (தொகை)",
        .formThirteenthModel: "13வது ஊதிய மாதிரி",
        .thirteenthModelSeparate: "தனியாகக் காட்டு",
        .thirteenthModelAveraged: "12 மாதங்களில் பகிர்",
        .formTarget: "சேமிப்பு இலக்கு (தொகை)",
        .formSaved: "ஏற்கனவே சேமித்தது",
        .formMonthlyContribution: "மாதாந்திர பங்களிப்பு",
        .formCategory: "வகை",
        .formLimitedDuration: "வரையறுக்கப்பட்ட நிலையான கட்டளை",
        .formLimitedDurationHint: "எ.கா. 6 வரித் தவணைகள் – அந்த மாதங்களில் மட்டுமே கணக்கிடப்பட்டு பின்னர் தானாக நீக்கப்படும்.",
        .formStartMonth: "முதல் தவணை",
        .formInstallments: "தவணைகளின் எண்ணிக்கை",
        .planningStandingOrder: "நிலையான கட்டளை",
        .catRent: "வாடகை",
        .catSubscription: "சந்தா",
        .catLeasing: "குத்தகை",
        .catUtilities: "பயன்பாட்டுச் செலவுகள் (மின்சாரம், நீர்)",
        .catTelecom: "தொலைத்தொடர்பு",
        .catGroceries: "மளிகை",
        .catFuel: "எரிபொருள்",
        .catTransport: "போக்குவரத்து",
        .catPersonal: "தனிப்பட்ட",
        .catDining: "வெளியில் உணவு",
        .catHousehold: "வீட்டுச் செலவு",

        .overviewTitle: "கண்ணோட்டம்",
        .overviewAvailableThisMonth: "இந்த மாதம் கிடைக்கும்",
        .overviewNetIncome: "இந்த மாத நிகர வருமானம்",
        .overviewThirteenthSeparate: "13வது மாத ஊதியம் (தனியாக)",
        .overviewRecurringFixed: "நிலையான செலவுகள்",
        .overviewPlannedVariable: "மாறும் செலவுகள்",
        .overviewBillsDueThisMonth: "இந்த மாதம் நிலுவையில் உள்ள பில்கள்",
        .overviewOverdueBills: "தாமதமான பில்கள்",
        .overviewSavingsTarget: "சேமிப்பு இலக்கு",
        .overviewSecurityStatus: "பாதுகாப்பு நிலை",
        .overviewFormulaExplainer: "கிடைக்கும் = நிகர வருமானம் − நிலையான செலவுகள் − மாறும் பட்ஜெட்டுகள் − இந்த மாதம் நிலுவையில் உள்ள பில்கள் − தாமதமான பில்கள். செலுத்தப்பட்ட மற்றும் எதிர்கால பில்கள் தொகையைக் குறைக்காது.",
        .overviewEmpty: "உங்கள் கண்ணோட்டத்தைக் காண மாதாந்திர திட்டமிடலில் வருமானத்தையும் செலவையும் உள்ளிடவும்.",
        .chartSpendingTitle: "இந்த மாத பகிர்வு",
        .chartByCategory: "வகை வாரியாக",

        .planningTitle: "மாதாந்திர திட்டமிடல்",
        .planningIncome: "வருமானம்",
        .planningFixed: "நிலையான செலவுகள்",
        .planningVariable: "மாறும் செலவுகள்",
        .planningSavings: "சேமிப்பு இலக்கு",
        .planningFixedExplainer: "நிலையான செலவுகள் ஒவ்வொரு மாதமும் மீண்டும் வரும்: வாடகை, காப்பீடுகள், சந்தாக்கள், குத்தகை.",
        .planningVariableExplainer: "மாறும் பட்ஜெட்டுகளை நீங்களே திட்டமிடுகிறீர்கள்: மளிகை, எரிபொருள், தனிப்பட்ட செலவுகள்.",
        .planningOneOffHint: "ஒருமுறை பில்கள் „பில்கள்” இல் நிர்வகிக்கப்படுகின்றன.",
        .planningEmpty: "உங்கள் வருமானத்துடன் தொடங்கி, பின்னர் நிலையான செலவுகளையும் பட்ஜெட்டுகளையும் சேர்க்கவும்.",
        .planningBalance: "திட்டமிட்ட இருப்பு",

        .billsTitle: "பில்கள்",
        .billsStatusOpen: "நிலுவையில்",
        .billsStatusPaid: "செலுத்தப்பட்டது",
        .billsStateOverdue: "தாமதம்",
        .billsStateDueThisMonth: "இந்த மாதம் செலுத்த வேண்டியது",
        .billsStateFuture: "எதிர்காலம்",
        .billsAffectsBalance: "கிடைக்கும் தொகையைக் குறைக்கிறது",
        .billsNoBalanceImpact: "இந்த மாதம் பாதிப்பில்லை",
        .billsDueDate: "செலுத்த வேண்டிய தேதி",
        .billsProvider: "வழங்குநர்",
        .billsEmpty: "இன்னும் பில்கள் இல்லை. செலுத்த வேண்டிய தேதியுடன் கூடிய ஒருமுறை பில்கள் இங்கே தோன்றும்.",
        .billsMarkPaid: "செலுத்தியதாகக் குறி",
        .billsMarkOpen: "நிலுவையாகக் குறி",
        .billsOpenTotal: "மொத்த நிலுவை",

        .navSchulden: "கடன்கள்",
        .schuldenSubtitle: "தாமதமான பில்கள் மற்றும் வசூலைக் கண்காணிக்கவும்.",
        .schuldenEmpty: "பதிவு செய்யப்பட்ட கடன்கள் இல்லை. தாமதமான பில்கள் இங்கே தானாகத் தோன்றும் – மேலும் வசூல் (Betreibung) அல்லது இழப்புச் சான்றிதழ்களைக் குறிக்கலாம்.",
        .schuldenAddCta: "ஒரு கடனைப் பதிவு செய்",
        .schuldenTotal: "மொத்த கடன்",
        .schuldenOverdueBills: "தாமதமான பில்கள்",
        .schuldenRecorded: "பதிவு செய்யப்பட்ட கடன்கள்",
        .schuldenManagedInBills: "தாமதமான பில்களை „பில்கள்” இல் நிர்வகிக்கவும்.",
        .debtTypeOpenClaim: "நிலுவையில் உள்ள கோரிக்கை",
        .debtTypeBetreibung: "வசூல் நடவடிக்கை",
        .debtTypePfaendung: "ஊதியம்/சொத்து பறிமுதல்",
        .debtTypeVerlustschein: "இழப்புச் சான்றிதழ்",
        .debtTypeOther: "மற்ற கடன்",
        .debtCreditor: "கடனளிப்பவர்",
        .debtReference: "குறிப்பு / வழக்கு எண்",
        .debtDate: "தேதி",
        .debtType: "வகை",
        .schuldenGuidanceTitle: "கடனிலிருந்து வெளியேறும் வழி",
        .schuldenTipContactTitle: "முன்கூட்டியே தொடர்பு கொள்ளுங்கள்",
        .schuldenTipContactBody: "கடனளிப்பவர்களுடன் முன்கூட்டியே பேசுங்கள். எழுத்துப்பூர்வ தவணை திட்டம் பெரும்பாலும் சாத்தியம், முறையான நடவடிக்கையைத் தவிர்க்கிறது.",
        .schuldenTipBetreibungTitle: "வசூல் தொடங்கினால்",
        .schuldenTipBetreibungBody: "செலுத்த கட்டளைக்குப் பிறகு செலுத்த 20 நாட்கள் – அல்லது கோரிக்கை நியாயமற்றதாக இருந்தால் ஆட்சேபனை (Rechtsvorschlag) தெரிவிக்க 10 நாட்கள் உள்ளன.",
        .schuldenTipExistenzminimumTitle: "உங்கள் வாழ்வாதார குறைந்தபட்சம் பாதுகாக்கப்படுகிறது",
        .schuldenTipExistenzminimumBody: "பறிமுதலின் போது உங்கள் வாழ்வாதார குறைந்தபட்சம் தீண்டப்படாமல் இருக்கும் – அடிப்படைத் தொகை, வாடகை, சுகாதாரக் காப்பீடு மற்றும் சமூகப் பங்களிப்புகள்.",
        .schuldenTipVerlustscheinTitle: "இழப்புச் சான்றிதழ்",
        .schuldenTipVerlustscheinBody: "இழப்புச் சான்றிதழ் 20 ஆண்டுகளுக்குப் பிறகே காலாவதியாகும். புதிய சொத்து பெறும்போது மட்டுமே மீண்டும் வசூலிக்கப்படலாம்.",
        .schuldenTipCounselingTitle: "இலவச கடன் ஆலோசனை",
        .schuldenTipCounselingBody: "Schuldenberatung Schweiz, Caritas மற்றும் பட்ஜெட் ஆலோசனை இலவசமாகவும் ரகசியமாகவும் உதவுகின்றன. மிக மோசமான விளைவுகளைக் கொண்ட கடன்களை முதலில் செலுத்துங்கள்.",
        .schuldenDisclaimer: "பொதுவான தகவல், சட்ட ஆலோசனை அல்ல.",

        .catInsurance: "காப்பீடு",
        .catOther: "மற்றவை",
        .catMortgage: "வீட்டுக் கடன்",
        .catHealthInsurance: "சுகாதாரக் காப்பீடு",
        .catSerafe: "வானொலி/தொலைக்காட்சி (Serafe)",
        .catPublicTransport: "பயணச் சீட்டு",
        .catChildcare: "குழந்தை பராமரிப்பு",
        .catMembership: "உறுப்பினர் கட்டணம்",
        .catAlimony: "ஜீவனாம்சம்",
        .catTaxes: "வரிகள்",
        .catClothing: "ஆடைகள்",
        .catHealth: "ஆரோக்கியம்",
        .catLeisure: "ஓய்வு மற்றும் பொழுதுபோக்கு",
        .catEntertainment: "பொழுதுபோக்கு",
        .catChildren: "குழந்தைகள்",
        .catPets: "செல்லப்பிராணிகள்",
        .catGifts: "பரிசுகள்",
        .catTravel: "பயணம்",
        .catCharity: "தொண்டு",
        .catEducation: "கல்வி",

        .settingsTitle: "அமைப்புகள்",
        .settingsLanguage: "மொழி",
        .settingsTheme: "வண்ண தீம்",
        .themeSwissRed: "சுவிஸ் சிவப்பு",
        .themeOrange: "ஆரஞ்சு",
        .themeSand: "மணல்",
        .themeGreen: "பச்சை",
        .themeTeal: "நீல-பச்சை",
        .themeBlue: "நீலம்",
        .themePurple: "ஊதா",
        .themePink: "இளஞ்சிவப்பு",
        .settingsData: "தரவு",
        .settingsHousehold: "குடும்பம்",
        .settingsCanton: "கேன்டன்",
        .settingsProfile: "சுயவிவரம்",
        .profileName: "பெயர்",
        .profileChoosePicture: "சுயவிவரப் படத்தைத் தேர்ந்தெடு",
        .profileNoPicture: "படம் இல்லை",
        .profileLocalNote: "இந்த சாதனத்தில் மட்டுமே உள்ளூரில் சேமிக்கப்படுகிறது.",
        .settingsSecurity: "பாதுகாப்பு",
        .settingsAutoLock: "தானியங்கு பூட்டு",
        .settingsChangePassphrase: "கடவுச்சொல்/PIN மாற்று",
        .settingsBackup: "மறையாக்கப்பட்ட காப்புப்பிரதி",
        .settingsRestore: "மீட்டமை",
        .settingsPrivacy: "தனியுரிமை",
        .settingsDangerZone: "ஆபத்து மண்டலம்",
        .settingsDeleteAll: "அனைத்து உள்ளூர் தரவையும் நீக்கு",
        .backupCreateTitle: "மறையாக்கப்பட்ட காப்புப்பிரதியை உருவாக்கு",
        .backupPassphrase: "காப்புப்பிரதி கடவுச்சொல்",
        .backupHint: "காப்புப்பிரதிக்கு தனி கடவுச்சொல்லைத் தேர்ந்தெடுக்கவும். மீட்டெடுக்க இது தேவை – கடவுச்சொல்லை மீட்டெடுக்க முடியாது.",
        .restorePreview: "முன்னோட்டம்",
        .restoreConfirm: "அனைத்து உள்ளூர் தரவையும் மாற்று",
        .restoreWarning: "இது அனைத்து உள்ளூர் தரவையும் நிரந்தரமாக மேலெழுதும்.",
        .backupInvalid: "தவறான காப்புப்பிரதி அல்லது தவறான கடவுச்சொல்.",
        .backupSavedHint: "காப்புப்பிரதி கோப்பையும் கடவுச்சொல்லையும் பாதுகாப்பான இடத்தில் வைக்கவும்.",

        .reportTitle: "சிக்கலைப் புகாரளி",
        .reportSummary: "சுருக்கம்",
        .reportExpected: "எதிர்பார்க்கப்பட்ட நடத்தை",
        .reportActual: "உண்மையான நடத்தை",
        .reportSteps: "மீளுருவாக்க படிகள்",
        .reportArea: "பாதிக்கப்பட்ட பகுதி",
        .reportRedactionNote: "முக்கியமான தரவு உள்ளூரில் அகற்றப்படுகிறது. நகலெடுப்பதற்கு முன் அறிக்கையை மதிப்பாய்வு செய்கிறீர்கள்.",
        .reportCopyHint: "அறிக்கை தானாக அனுப்பப்படாது. நீங்களே நகலெடுக்கிறீர்கள்.",

        .exportReport: "அறிக்கையை ஏற்றுமதி செய்",
        .pdfTitle: "நிதி கண்ணோட்டம்",
        .pdfSubtitle: "தனிப்பட்ட குடும்ப அறிக்கை",
        .pdfSummary: "ஒரே பார்வையில்",
        .pdfGeneratedOn: "உருவாக்கப்பட்டது",
        .pdfConfidential: "ரகசியம்",
        .pdfPage: "பக்கம்",
        .pdfTotal: "மொத்தம்",
        .pdfColProgress: "முன்னேற்றம்",
        .pdfUnencryptedNote: "அறிக்கை படிக்கக்கூடிய, மறையாக்கப்படாத PDF. அதை பாதுகாப்பான இடத்தில் வைக்கவும்.",
        .pdfNoData: "ஏற்றுமதி செய்ய இன்னும் தரவு இல்லை.",
        .pdfDefaultHousehold: "என் குடும்பம்",

        .lockTitle: "பூட்டப்பட்டது",
        .lockWelcomeSetup: "Kontiva-வுக்கு வரவேற்கிறோம்",
        .lockWelcomeBack: "மீண்டும் வரவேற்கிறோம்",
        .lockSetupTitle: "கடவுச்சொல்லை அமை",
        .lockEnterPassphrase: "கடவுச்சொல் அல்லது PIN உள்ளிடவும்",
        .lockWrongPassphrase: "தவறான கடவுச்சொல். மீண்டும் முயற்சிக்கவும்.",
        .lockRecoveryWarning: "மீட்பு இல்லை. உங்கள் கடவுச்சொல் இல்லாமல் உங்கள் தரவை அணுக முடியாது.",
        .lockRecoveryAcknowledge: "மீட்பு இல்லை என்பதை நான் புரிந்துகொள்கிறேன்.",
        .securityNote: "உங்கள் தரவு உள்ளூரில் மற்றும் மறையாக்கப்பட்டு சேமிக்கப்படுகிறது (AES-256-GCM). கிளவுட் இல்லை, சர்வர் இல்லை, கடவுச்சொல் மீட்பு இல்லை.",

        .onboardingIntroBody: "Kontiva உங்கள் சுவிஸ் குடும்ப பட்ஜெட்டை அமைதியாகப் பார்க்க உதவுகிறது – முழுவதும் இந்த சாதனத்தில்.",
        .onboardingStart: "தொடங்கு",
        .onboardingProfileTitle: "ஒரு சுயவிவரத்தை உருவாக்கு",
        .onboardingProfileBody: "உங்களுக்கு ஒரு பெயரிட்டு ஒரு படத்தைத் தேர்ந்தெடுக்கவும். இரண்டும் இந்த சாதனத்தில் மட்டுமே இருக்கும்.",
        .onboardingSkip: "தவிர்",
        .onboardingFeaturePrivate: "முழுவதும் உள்ளூர் – கிளவுட் இல்லை, கண்காணிப்பு இல்லை",
        .onboardingFeatureSecure: "AES-256 மூலம் மறையாக்கம்",
        .onboardingFeatureMoney: "சண்டிம் வரை துல்லியம், முழுமைப்படுத்தல் பிழை இல்லை",
        .onboardingConfirmPassphrase: "கடவுச்சொல்லை உறுதிப்படுத்து",
        .onboardingPassphraseNote: "உங்கள் கடவுச்சொல்லை பாதுகாப்பான இடத்தில் எழுதி வைக்கவும் – அதை மீட்டமைக்க முடியாது.",
        .backupNudgeText: "மறையாக்கப்பட்ட காப்புப்பிரதியை உருவாக்கவும். இல்லாவிட்டால், கடவுச்சொல்லை மறந்தால் உங்கள் தரவை இழப்பீர்கள்.",
        .commonNext: "அடுத்து",
        .navMore: "மேலும்",
        .actionLock: "பூட்டு",
        .pinSetTitle: "குறியீட்டை அமை",
        .pinConfirmTitle: "குறியீட்டை உறுதிப்படுத்து",
        .pinRequirementNote: "குறைந்தது 6 இலக்கங்கள் · மீட்பு இல்லை",
        .pinMismatch: "குறியீடுகள் பொருந்தவில்லை",
    ]
}
