#!/usr/bin/env python3
"""
Transpile the iOS Swift localization tables (KontivaKit/.../Localization*.swift)
into Kotlin, preserving every string 1:1 across all 35 languages.

Source of truth: ../../KontivaKit/Sources/KontivaCore/Localization*.swift
Output:          ../app/src/main/java/ch/kontiva/android/core/l10n/

  - L10nKey.kt           enum class with all 279 keys (order preserved)
  - Loc_<lang>.kt        one map per language (var name == AppLanguage case)

Re-run whenever the iOS strings change so the two platforms stay in sync.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "KontivaKit/Sources/KontivaCore"
OUT = ROOT / "kontiva-android/app/src/main/java/ch/kontiva/android/core/l10n"
PKG = "ch.kontiva.android.core.l10n"

LOC_FILE = SRC / "Localization.swift"

# --- 1. keys (ordered) from the L10nKey enum ----------------------------------
key_re = re.compile(r"^\s*case\s+([A-Za-z][A-Za-z0-9]*)\s*$", re.M)
keys = key_re.findall(LOC_FILE.read_text(encoding="utf-8"))
if len(keys) != len(set(keys)):
    sys.exit("duplicate L10nKey case names")
print(f"L10nKey cases: {len(keys)}")

# --- 2. per-language tables ---------------------------------------------------
# matches:  static let <lang>: [L10nKey: String] = [ ... \n ]
table_re = re.compile(
    r"static let (\w+):\s*\[L10nKey:\s*String\]\s*=\s*\[(.*?)\n\s*\]",
    re.S,
)
# matches one entry:  .key: "value (with \" escapes)"
entry_re = re.compile(r'\.(\w+)\s*:\s*"((?:\\.|[^"\\])*)"')

def kotlin_escape(swift_val: str) -> str:
    # Swift escapes (\" \n \t \\) are valid in Kotlin too. Kotlin additionally
    # treats $ as interpolation, so it must be escaped. Reject Swift interpolation.
    if "\\(" in swift_val:
        raise ValueError(f"Swift interpolation in table value: {swift_val!r}")
    return swift_val.replace("$", "\\$")

langs = {}
for f in sorted(SRC.glob("Localization*.swift")):
    text = f.read_text(encoding="utf-8")
    for lang, body in table_re.findall(text):
        entries = entry_re.findall(body)
        d = {}
        for k, v in entries:
            d[k] = kotlin_escape(v)
        langs[lang] = d

print(f"languages: {len(langs)}")

# --- 3. parity check ----------------------------------------------------------
keyset = set(keys)
problems = 0
for lang, d in sorted(langs.items()):
    missing = keyset - set(d)
    extra = set(d) - keyset
    if missing or extra:
        problems += 1
        print(f"  ! {lang}: missing={len(missing)} extra={len(extra)} "
              f"{sorted(missing)[:3]}{sorted(extra)[:3]}")
if problems:
    sys.exit(f"{problems} language(s) failed parity")
print("parity OK: every language has all 279 keys")

# --- 4. emit L10nKey.kt -------------------------------------------------------
OUT.mkdir(parents=True, exist_ok=True)
HEADER = ("// GENERATED by tools/transpile_l10n.py from the iOS Swift tables.\n"
          "// Do not edit by hand — re-run the transpiler to regenerate.\n")
enum_body = ",\n    ".join(keys)
(OUT / "L10nKey.kt").write_text(
    f"{HEADER}package {PKG}\n\n"
    f"/** Every user-facing string key in Kontiva (1:1 with the iOS L10nKey). */\n"
    f"enum class L10nKey {{\n    {enum_body}\n}}\n",
    encoding="utf-8",
)

# --- 5. emit one map file per language ---------------------------------------
for lang, d in sorted(langs.items()):
    lines = [f'    L10nKey.{k} to "{d[k]}",' for k in keys]  # iOS key order
    body = "\n".join(lines)
    (OUT / f"Loc_{lang}.kt").write_text(
        f"{HEADER}package {PKG}\n\n"
        f"internal val LOC_{lang}: Map<L10nKey, String> = mapOf(\n{body}\n)\n",
        encoding="utf-8",
    )

print(f"wrote L10nKey.kt + {len(langs)} Loc_*.kt to {OUT.relative_to(ROOT)}")
print("langs:", ", ".join(sorted(langs)))
