import Foundation

extension Localization {
    static let tr: [L10nKey: String] = [
        .appName: "Kontiva",
        .appTagline: "İsviçre bütçenize sakin, özel bir bakış.",
        .notBetaNotice: "Erken geliştirme sürümü – beta değil, V1 değil.",

        .navOverview: "Genel bakış",
        .navPlanning: "Plan",
        .navBills: "Faturalar",
        .navSettings: "Ayarlar",
        .navReport: "Sorun bildir",
        .navInsights: "Analizler",
        .navSparen: "Tasarruf",
        .sparenSubtitle: "Düzenli tasarruf katkıları – ve şimdiye dek birikenler.",
        .sparenEmpty: "Henüz tasarruf hedefi yok. Her ay ne için biriktirdiğinizi belirleyin.",
        .sparenMonthlyTotal: "Tasarruf / ay",
        .sparenAccumulatedTotal: "Şimdiye dek biriken",
        .sparenPerMonth: "/ ay",
        .sparenContributions: "katkı",
        .sparenSince: "şu tarihten beri",
        .sparenOpenEnded: "Hedef tutar yok",
        .sparenGoalReached: "Hedefe ulaşıldı",
        .sparenGoalReachedMessage: "Tebrikler! Birikim hedefine ulaştın. Nasıl devam etmek istersin?",
        .sparenGoalIncrease: "Hedefi yükselt",
        .sparenGoalComplete: "Tamamlandı olarak işaretle",
        .sparenGoalKeep: "Birikime devam et",
        .sparenGoalCompleted: "Tamamlandı",
        .sparenGoalReopen: "Yeniden etkinleştir",
        .sparenGoalsLabel: "Hedefler",
        .sparenSortBy: "Sırala",
        .sparenSortStartMonth: "Başlangıç ayı",
        .savingsCatCar: "Araba",
        .savingsCatVacation: "Tatil",
        .savingsCatHome: "Konut",
        .savingsCatRetirement: "Sütun 3a / Emeklilik",
        .savingsCatEmergency: "Acil durum fonu",
        .savingsCatEducation: "Eğitim",
        .savingsCatOther: "Diğer",
        .savingsCatWedding: "Düğün",
        .savingsCatFamily: "Aile ve çocuklar",
        .savingsCatRenovation: "Tadilat ve döşeme",
        .savingsCatElectronics: "Elektronik",
        .savingsCatTaxes: "Vergi karşılığı",
        .savingsCatInvestment: "Yatırımlar",
        .savingsCatHealth: "Sağlık",
        .savingsCatGift: "Hediyeler",
        .overviewPlannedSavings: "Bu ay tasarruf",
        .overviewShowCalculation: "Hesaplamayı göster",
        .overviewTrendTitle: "Eğilim · 6 ay",
        .overviewStatusGood: "Sağlıklı fazla",
        .overviewStatusTight: "Sıkışık",
        .overviewStatusNegative: "Eksideki",
        .overviewAllocationOf: "net gelirin",
        .formStartDate: "Şu tarihten beri biriktiriyor",
        .formStartingBalance: "Başlangıç bakiyesi (isteğe bağlı)",
        .insightsSubtitle: "Bütçeniz için rehberlik – paranızın nerede olduğu ve nerede tasarruf edebileceğiniz.",
        .insightOverspending: "Kazandığınızdan fazla harcıyorsunuz",
        .insightTightBudget: "Bu ay az hareket alanı",
        .insightHealthySurplus: "Sağlıklı fazla",
        .insightHighFixed: "Yüksek sabit giderler",
        .insightHighHousing: "Yüksek konut giderleri",
        .insightLargestFixed: "En büyük sabit gider kalemi",
        .insightLargestVariable: "En büyük değişken bütçe",
        .insightOverdue: "Vadesi geçmiş faturalar",
        .insightNoSavings: "Henüz planlanmış tasarruf yok",
        .insightGoodSavings: "İyi tasarruf oranı",
        .insightAllHealthy: "Bütçeniz sağlıklı görünüyor",
        .insightHousingHint: "Yönerge: gelirin en çok üçte biri",
        .insightNoSavingsDetail: "Hareket alanınız var – bir tasarruf hedefi yardımcı olabilir.",
        .insightAllHealthyDetail: "Öne çıkan bir şey yok. Daha keskin analizler için daha fazla veri ekleyin.",
        .insightExtraIncome: "Bu ay ek gelir",
        .insightGoalProgress: "Birikim hedefi yaklaştı",
        .insightBillsDueSoon: "Bu ay ödenecekler",
        .insightGettingStarted: "Hadi başlayalım",
        .insightGettingStartedDetail: "Kişisel analizler için gelirini ekle.",
        .schuldenEncourageTitle: "Adım adım",
        .schuldenEncourageBody: "Üstesinden geliyorsun. İşte somut sonraki adımlar.",
        .fragOfNetIncome: "net gelirin",
        .fragOfFixedCosts: "sabit giderlerin",
        .fragShortfall: "Açık",

        .commonAdd: "Ekle",
        .commonEdit: "Düzenle",
        .commonActivate: "Etkinleştir",
        .commonDelete: "Sil",
        .commonCancel: "İptal",
        .commandsAdd: "Kayıt ekle",
        .billsAddCta: "İlk faturanızı ekleyin",
        .sparenAddCta: "Bir tasarruf hedefi oluşturun",
        .overviewAddCta: "Gelir ekle",
        .commonSave: "Kaydet",
        .commonSaved: "Kaydedildi",
        .commonClose: "Kapat",
        .commonDone: "Bitti",
        .commonShowSampleData: "Örnek verileri göster",
        .commonHideSampleData: "Örnek verileri gizle",
        .commonEmptyHint: "Henüz veri girilmedi.",
        .commonCopy: "Kopyala",
        .commonOptions: "Seçenekler",
        .commonMoveUp: "Yukarı taşı",
        .commonMoveDown: "Aşağı taşı",
        .monthToday: "Bugün",

        .formName: "Ad",
        .formAmount: "Tutar (CHF)",
        .formStatus: "Durum",
        .formNotes: "Not",
        .formInvalidAmount: "Geçerli bir tutar girin.",
        .formThirteenthAmount: "13. maaş (tutar)",
        .formThirteenthModel: "13. maaş modeli",
        .incomeBonuses: "Ek ödemeler",
        .formMonth: "Ay",
        .thirteenthModelSeparate: "Ayrı göster",
        .thirteenthModelAveraged: "12 aya dağıt",
        .formTarget: "Tasarruf hedefi (tutar)",
        .formSaved: "Şimdiye dek biriken",
        .formMonthlyContribution: "Aylık katkı",
        .formCategory: "Kategori",
        .formLimitedDuration: "Süreli otomatik ödeme talimatı",
        .formLimitedDurationHint: "Örn. 6 vergi taksiti – yalnızca o aylarda sayılır ve sonra otomatik kaldırılır.",
        .formStartMonth: "İlk taksit",
        .formInstallments: "Taksit sayısı",
        .planningStandingOrder: "Otomatik ödeme talimatı",
        .catRent: "Kira",
        .catSubscription: "Abonelik",
        .catLeasing: "Kiralama (leasing)",
        .catUtilities: "Faturalar (su, elektrik)",
        .catTelecom: "Telekom",
        .catGroceries: "Market",
        .catFuel: "Yakıt",
        .catTransport: "Ulaşım",
        .catPersonal: "Kişisel",
        .catDining: "Dışarıda yemek",
        .catHousehold: "Ev işleri",

        .overviewTitle: "Genel bakış",
        .overviewAvailableThisMonth: "Bu ay kullanılabilir",
        .overviewNetIncome: "Bu ay net gelir",
        .overviewThirteenthSeparate: "13. maaş (ayrı)",
        .overviewRecurringFixed: "Sabit giderler",
        .overviewPlannedVariable: "Değişken harcamalar",
        .overviewBillsDueThisMonth: "Bu ayki faturalar",
        .overviewOverdueBills: "Vadesi geçmiş faturalar",
        .overviewSavingsTarget: "Tasarruf hedefi",
        .overviewSecurityStatus: "Güvenlik durumu",
        .overviewFormulaExplainer: "Kullanılabilir = net gelir − sabit giderler − değişken bütçeler − bu ay açık faturalar − vadesi geçmiş faturalar. Ödenmiş ve gelecekteki faturalar tutarı azaltmaz.",
        .overviewEmpty: "Genel bakışı görmek için Aylık planlama'ya gelir ve gider girin.",
        .chartSpendingTitle: "Bu ay dağılım",
        .chartByCategory: "Kategoriye göre",

        .planningTitle: "Aylık planlama",
        .planningIncome: "Gelir",
        .planningFixed: "Sabit giderler",
        .planningVariable: "Değişken harcamalar",
        .planningSavings: "Tasarruf hedefi",
        .planningFixedExplainer: "Sabit giderler her ay tekrarlanır: kira, sigortalar, abonelikler, leasing.",
        .planningVariableExplainer: "Değişken bütçeleri kendiniz planlarsınız: market, yakıt, kişisel harcamalar.",
        .planningOneOffHint: "Tek seferlik faturalar „Faturalar” bölümünde yönetilir.",
        .planningEmpty: "Gelirinizle başlayın, sonra sabit giderler ve bütçeler ekleyin.",
        .planningBalance: "Planlanan bakiye",

        .billsTitle: "Faturalar",
        .billsStatusOpen: "Açık",
        .billsStatusPaid: "Ödendi",
        .billsStateOverdue: "Vadesi geçmiş",
        .billsStateDueThisMonth: "Bu ay vadesi dolan",
        .billsStateFuture: "Gelecek",
        .billsAffectsBalance: "Kullanılabilir tutarı azaltır",
        .billsNoBalanceImpact: "Bu ay etkisi yok",
        .billsDueDate: "Vade tarihi",
        .billsProvider: "Sağlayıcı",
        .billsEmpty: "Henüz fatura yok. Vade tarihli tek seferlik faturalar burada görünür.",
        .billsMarkPaid: "Ödendi olarak işaretle",
        .billsMarkOpen: "Açık olarak işaretle",
        .billsOpenTotal: "Toplam açık",

        .navSchulden: "Borçlar",
        .schuldenSubtitle: "Vadesi geçmiş faturaları ve icra takibini izleyin.",
        .schuldenEmpty: "Kayıtlı borç yok. Vadesi geçmiş faturalar burada otomatik görünür – ve icra takibini (Betreibung) veya zarar belgelerini not edebilirsiniz.",
        .schuldenAddCta: "Bir borç kaydet",
        .schuldenTotal: "Toplam borç",
        .schuldenOverdueBills: "Vadesi geçmiş faturalar",
        .schuldenRecorded: "Kayıtlı borçlar",
        .schuldenManagedInBills: "Vadesi geçmiş faturaları „Faturalar” bölümünde yönetin.",
        .debtTypeOpenClaim: "Açık alacak",
        .debtTypeBetreibung: "İcra takibi",
        .debtTypePfaendung: "Maaş/mal haczi",
        .debtTypeVerlustschein: "Zarar belgesi",
        .debtTypeOther: "Diğer borç",
        .debtCreditor: "Alacaklı",
        .debtReference: "Referans / dosya no.",
        .debtDate: "Tarih",
        .debtType: "Tür",
        .schuldenGuidanceTitle: "Borçtan çıkış yolu",
        .schuldenTipContactTitle: "Erken iletişime geçin",
        .schuldenTipContactBody: "Alacaklılarla erken konuşun. Yazılı bir taksitli ödeme planı genellikle mümkündür ve resmi takibi önler.",
        .schuldenTipBetreibungTitle: "Takip başlarsa",
        .schuldenTipBetreibungBody: "Ödeme emrinden sonra ödemek için 20 gününüz – ya da alacak haksızsa itiraz (Rechtsvorschlag) için 10 gününüz vardır.",
        .schuldenTipExistenzminimumTitle: "Geçim minimumunuz korunur",
        .schuldenTipExistenzminimumBody: "Hacizde geçim minimumunuz dokunulmaz kalır – temel tutar, kira, sağlık sigortası ve sosyal katkılar.",
        .schuldenTipVerlustscheinTitle: "Zarar belgesi",
        .schuldenTipVerlustscheinBody: "Zarar belgesi ancak 20 yıl sonra zaman aşımına uğrar. Yalnızca yeni varlık edindiğinizde tekrar takip edilebilirsiniz.",
        .schuldenTipCounselingTitle: "Ücretsiz borç danışmanlığı",
        .schuldenTipCounselingBody: "Schuldenberatung Schweiz, Caritas ve bütçe danışmanlığı ücretsiz ve gizli yardım eder. Önce en ağır sonuçları olan borçları ödeyin.",
        .schuldenDisclaimer: "Genel bilgi, hukuki tavsiye değildir.",
        .schuldenAsFixed: "Sabit gider olarak",
        .schuldenAsBill: "Fatura olarak",
        .schuldenAsVariable: "Değişken bütçe olarak",

        .catInsurance: "Sigorta",
        .catOther: "Diğer",
        .catMortgage: "Konut kredisi",
        .catHealthInsurance: "Sağlık sigortası",
        .catSerafe: "Radyo/TV (Serafe)",
        .catPublicTransport: "Ulaşım kartı",
        .catChildcare: "Çocuk bakımı",
        .catMembership: "Üyelikler",
        .catAlimony: "Nafaka",
        .catTaxes: "Vergiler",
        .catRatenzahlung: "Taksit",
        .catStreaming: "Yayın",
        .catCreditCard: "Kredi kartı",
        .catClothing: "Giyim",
        .catHealth: "Sağlık",
        .catLeisure: "Boş zaman ve hobiler",
        .catEntertainment: "Eğlence",
        .catChildren: "Çocuklar",
        .catPets: "Evcil hayvanlar",
        .catGifts: "Hediyeler",
        .catTravel: "Seyahat",
        .catCharity: "Bağışlar",
        .catEducation: "Eğitim",

        .settingsTitle: "Ayarlar",
        .settingsLanguage: "Dil",
        .settingsTheme: "Renk teması",
        .themeCustom: "Özel tema",
        .themeSwissRed: "İsviçre kırmızısı",
        .themeOrange: "Turuncu",
        .themeSand: "Kum",
        .themeGreen: "Yeşil",
        .themeTeal: "Turkuaz",
        .themeBlue: "Mavi",
        .themePurple: "Mor",
        .themePink: "Pembe",
        .settingsData: "Veriler",
        .settingsHousehold: "Hane",
        .settingsCanton: "Kanton",
        .settingsProfile: "Profil",
        .profileName: "Ad",
        .profileChoosePicture: "Profil fotoğrafı seç",
        .profileNoPicture: "Fotoğraf yok",
        .profileLocalNote: "Yalnızca bu cihazda yerel olarak saklanır.",
        .settingsSecurity: "Güvenlik",
        .settingsAutoLock: "Otomatik kilit",
        .settingsBiometric: "Biyometrik kilit açma",
        .settingsChangePassphrase: "Parolayı/PIN'i değiştir",
        .settingsBackup: "Şifreli yedek",
        .settingsRestore: "Geri yükle",
        .settingsPrivacy: "Gizlilik",
        .settingsDangerZone: "Tehlikeli bölge",
        .settingsDeleteAll: "Tüm yerel verileri sil",
        .backupCreateTitle: "Şifreli yedek oluştur",
        .backupPassphrase: "Yedek parolası",
        .backupHint: "Yedek için ayrı bir parola seçin. Geri yükleme için gereklidir – parola kurtarılamaz.",
        .restorePreview: "Önizleme",
        .restoreConfirm: "Tüm yerel verileri değiştir",
        .restoreWarning: "Bu, tüm yerel verileri kalıcı olarak üzerine yazar.",
        .backupInvalid: "Geçersiz yedek veya yanlış parola.",
        .backupSavedHint: "Yedek dosyasını ve parolayı güvenli bir yerde saklayın.",

        .reportTitle: "Sorun bildir",
        .reportSummary: "Özet",
        .reportExpected: "Beklenen davranış",
        .reportActual: "Gerçek davranış",
        .reportSteps: "Yeniden oluşturma adımları",
        .reportArea: "Etkilenen alan",
        .reportRedactionNote: "Hassas veriler yerel olarak kaldırılır. Kopyalamadan önce raporu gözden geçirirsiniz.",
        .reportCopyHint: "Rapor otomatik gönderilmez. Kendiniz kopyalarsınız.",

        .exportReport: "Raporu dışa aktar",
        .pdfTitle: "Mali genel bakış",
        .pdfSubtitle: "Kişisel hane raporu",
        .pdfSummary: "Bir bakışta",
        .pdfGeneratedOn: "Oluşturulma",
        .pdfConfidential: "Gizli",
        .pdfPage: "Sayfa",
        .pdfTotal: "Toplam",
        .pdfColProgress: "İlerleme",
        .pdfUnencryptedNote: "Rapor okunabilir, şifresiz bir PDF'tir. Güvenli bir yerde saklayın.",
        .pdfNoData: "Henüz dışa aktarılacak veri yok.",
        .pdfDefaultHousehold: "Hanem",

        .lockTitle: "Kilitli",
        .lockWelcomeSetup: "Kontiva'ya hoş geldiniz",
        .lockWelcomeBack: "Tekrar hoş geldiniz",
        .lockSetupTitle: "Parola belirle",
        .lockEnterPassphrase: "Parola veya PIN girin",
        .lockWrongPassphrase: "Yanlış parola. Tekrar deneyin.",
        .lockRecoveryWarning: "Kurtarma yoktur. Parolanız olmadan verilerinize erişilemez.",
        .lockRecoveryAcknowledge: "Kurtarma olmadığını anlıyorum.",
        .securityNote: "Verileriniz yerel olarak ve şifreli saklanır (AES-256-GCM). Bulut yok, sunucu yok, parola kurtarma yok.",

        .onboardingIntroBody: "Kontiva, İsviçre hanenizin bütçesine sakin bir bakış sürdürmenize yardımcı olur – tamamen bu cihazda.",
        .onboardingStart: "Başla",
        .onboardingProfileTitle: "Bir profil oluştur",
        .onboardingProfileBody: "Kendinize bir ad verin ve bir resim seçin. İkisi de yalnızca bu cihazda kalır.",
        .onboardingSkip: "Atla",
        .onboardingFeaturePrivate: "Tamamen yerel – bulut yok, izleme yok",
        .onboardingFeatureSecure: "AES-256 ile şifreli",
        .onboardingFeatureMoney: "Santime kadar kesin, yuvarlama hatası yok",
        .onboardingConfirmPassphrase: "Parolayı onayla",
        .onboardingPassphraseNote: "Parolanızı güvenli bir yere yazın – sıfırlanamaz.",
        .backupNudgeText: "Şifreli bir yedek oluşturun. O olmadan, parolanızı unutursanız verilerinizi kaybedersiniz.",
        .commonNext: "İleri",
        .navMore: "Daha fazla",
        .actionLock: "Kilitle",
        .pinSetTitle: "Kod belirle",
        .pinConfirmTitle: "Kodu onayla",
        .pinRequirementNote: "En az 6 hane · kurtarma yok",
        .pinMismatch: "Kodlar eşleşmiyor",
    ]
}
