import Foundation

extension Localization {
    static let itCH: [L10nKey: String] = [
        .appName: "Kontiva",
        .appTagline: "Una visione calma e privata del vostro budget svizzero.",
        .notBetaNotice: "Versione di sviluppo iniziale – non pronta per la beta, non V1.",

        .navOverview: "Panoramica",
        .navPlanning: "Pianificazione mensile",
        .navBills: "Fatture",
        .navSettings: "Impostazioni",
        .navReport: "Segnala un problema",
        .navInsights: "Analisi",
        .navSparen: "Risparmio",
        .sparenSubtitle: "Versamenti di risparmio ricorrenti – e quanto si è già accumulato.",
        .sparenEmpty: "Ancora nessun obiettivo di risparmio. Definite per cosa risparmiate ogni mese.",
        .sparenMonthlyTotal: "Risparmio / mese",
        .sparenAccumulatedTotal: "Già risparmiato",
        .sparenPerMonth: "/ mese",
        .sparenContributions: "versamenti",
        .sparenSince: "da",
        .sparenOpenEnded: "Senza importo obiettivo",
        .sparenGoalsLabel: "Obiettivi",
        .savingsCatCar: "Auto",
        .savingsCatVacation: "Vacanze",
        .savingsCatHome: "Abitazione",
        .savingsCatRetirement: "Pilastro 3a / Previdenza",
        .savingsCatEmergency: "Riserva d’emergenza",
        .savingsCatEducation: "Formazione",
        .savingsCatOther: "Altro",
        .savingsCatWedding: "Matrimonio",
        .savingsCatFamily: "Famiglia & figli",
        .savingsCatRenovation: "Ristrutturazione & arredamento",
        .savingsCatElectronics: "Elettronica",
        .savingsCatTaxes: "Riserva imposte",
        .savingsCatInvestment: "Investimenti",
        .savingsCatHealth: "Salute",
        .savingsCatGift: "Regali",
        .overviewPlannedSavings: "Risparmio questo mese",
        .overviewShowCalculation: "Mostra calcolo",
        .overviewTrendTitle: "Andamento · 6 mesi",
        .overviewStatusGood: "Avanzo sano",
        .overviewStatusTight: "Limitato",
        .overviewStatusNegative: "In rosso",
        .overviewAllocationOf: "del reddito netto",
        .formStartDate: "Risparmio da",
        .formStartingBalance: "Saldo iniziale (facoltativo)",
        .insightsSubtitle: "Indicazioni sul vostro budget – dove va il denaro e dove risparmiare.",
        .insightOverspending: "Spendete più di quanto guadagnate",
        .insightTightBudget: "Poco margine questo mese",
        .insightHealthySurplus: "Avanzo sano",
        .insightHighFixed: "Costi fissi elevati",
        .insightHighHousing: "Costi abitativi elevati",
        .insightLargestFixed: "Maggiore voce di costi fissi",
        .insightLargestVariable: "Maggiore budget variabile",
        .insightOverdue: "Fatture scadute",
        .insightNoSavings: "Nessun risparmio pianificato",
        .insightGoodSavings: "Buon risparmio",
        .insightAllHealthy: "Il vostro budget sembra sano",
        .insightHousingHint: "Riferimento: al massimo un terzo del reddito",
        .insightNoSavingsDetail: "Avete margine – un obiettivo di risparmio potrebbe aiutare.",
        .insightAllHealthyDetail: "Nulla da segnalare. Inserite più dati per indicazioni precise.",
        .fragOfNetIncome: "del reddito netto",
        .fragOfFixedCosts: "dei costi fissi",
        .fragShortfall: "Disavanzo",

        .commonAdd: "Aggiungi",
        .commonEdit: "Modifica",
        .commonDelete: "Elimina",
        .commonCancel: "Annulla",
        .commandsAdd: "Aggiungi voce",
        .billsAddCta: "Aggiungi la prima fattura",
        .sparenAddCta: "Crea un obiettivo di risparmio",
        .overviewAddCta: "Inserisci un reddito",
        .commonSave: "Salva",
        .commonSaved: "Salvato",
        .commonClose: "Chiudi",
        .commonDone: "Fatto",
        .commonShowSampleData: "Mostra dati di esempio",
        .commonHideSampleData: "Nascondi dati di esempio",
        .commonEmptyHint: "Nessun dato inserito finora.",
        .commonCopy: "Copia",
        .commonOptions: "Opzioni",
        .commonMoveUp: "Sposta su",
        .commonMoveDown: "Sposta giù",
        .monthToday: "Oggi",

        .formName: "Denominazione",
        .formAmount: "Importo (CHF)",
        .formStatus: "Stato",
        .formNotes: "Nota",
        .formInvalidAmount: "Inserire un importo valido.",
        .formThirteenthAmount: "13a mensilità (importo)",
        .formThirteenthModel: "Modello 13a mensilità",
        .thirteenthModelSeparate: "Indicare separatamente",
        .thirteenthModelAveraged: "Distribuire su 12 mesi",
        .formTarget: "Obiettivo di risparmio (importo)",
        .formSaved: "Già risparmiato",
        .formMonthlyContribution: "Contributo mensile",
        .formCategory: "Categoria",
        .formLimitedDuration: "Ordine permanente limitato",
        .formLimitedDurationHint: "Es. 6 rate fiscali – conta solo in quei mesi, poi rimosso automaticamente.",
        .formStartMonth: "Prima rata",
        .formInstallments: "Numero di rate",
        .planningStandingOrder: "Ordine permanente",
        .catRent: "Affitto",
        .catSubscription: "Abbonamento",
        .catLeasing: "Leasing",
        .catUtilities: "Spese accessorie",
        .catTelecom: "Telecom",
        .catGroceries: "Spesa",
        .catFuel: "Carburante",
        .catTransport: "Trasporti",
        .catPersonal: "Spese personali",
        .catDining: "Ristorante",
        .catHousehold: "Casa",

        .overviewTitle: "Panoramica",
        .overviewAvailableThisMonth: "Disponibile questo mese",
        .overviewNetIncome: "Reddito netto questo mese",
        .overviewThirteenthSeparate: "13a mensilità (indicata separatamente)",
        .overviewRecurringFixed: "Costi fissi",
        .overviewPlannedVariable: "Spese variabili",
        .overviewBillsDueThisMonth: "Fatture aperte questo mese",
        .overviewOverdueBills: "Fatture scadute",
        .overviewSavingsTarget: "Obiettivo di risparmio",
        .overviewSecurityStatus: "Stato di sicurezza",
        .overviewFormulaExplainer: "Disponibile = reddito netto − costi fissi − budget variabili − fatture aperte questo mese − fatture scadute. Le fatture pagate e future non riducono l’importo.",
        .overviewEmpty: "Inserite redditi e costi nella pianificazione mensile per vedere la panoramica.",
        .chartSpendingTitle: "Ripartizione questo mese",
        .chartByCategory: "Per categoria",

        .planningTitle: "Pianificazione mensile",
        .planningIncome: "Reddito",
        .planningFixed: "Costi fissi",
        .planningVariable: "Spese variabili",
        .planningSavings: "Obiettivo di risparmio",
        .planningFixedExplainer: "I costi fissi si ripetono ogni mese: affitto, assicurazioni, abbonamenti, leasing.",
        .planningVariableExplainer: "I budget variabili li pianificate voi: spesa, carburante, spese personali.",
        .planningOneOffHint: "Le fatture singole si gestiscono in «Fatture».",
        .planningEmpty: "Iniziate dal reddito, poi aggiungete costi fissi e budget.",
        .planningBalance: "Saldo pianificato",

        .billsTitle: "Fatture",
        .billsStatusOpen: "Aperta",
        .billsStatusPaid: "Pagata",
        .billsStateOverdue: "Scaduta",
        .billsStateDueThisMonth: "In scadenza questo mese",
        .billsStateFuture: "Futura",
        .billsAffectsBalance: "Riduce l’importo disponibile",
        .billsNoBalanceImpact: "Senza effetto su questo mese",
        .billsDueDate: "Data di scadenza",
        .billsProvider: "Fornitore",
        .billsEmpty: "Nessuna fattura inserita. Le fatture singole con scadenza appariranno qui.",
        .billsMarkPaid: "Segna come pagata",
        .billsMarkOpen: "Segna come aperta",
        .billsOpenTotal: "Totale aperto",

        .navSchulden: "Debiti",
        .schuldenSubtitle: "Tenete d'occhio fatture scadute ed esecuzioni.",
        .schuldenEmpty: "Nessun debito registrato. Le fatture scadute appaiono qui automaticamente – e potete annotare esecuzioni o attestati di carenza beni.",
        .schuldenAddCta: "Registra un debito",
        .schuldenTotal: "Debiti totali",
        .schuldenOverdueBills: "Fatture scadute",
        .schuldenRecorded: "Debiti registrati",
        .schuldenManagedInBills: "Gestite le fatture scadute in «Fatture».",
        .debtTypeOpenClaim: "Credito aperto",
        .debtTypeBetreibung: "Esecuzione",
        .debtTypePfaendung: "Pignoramento",
        .debtTypeVerlustschein: "Attestato di carenza beni",
        .debtTypeOther: "Altro debito",
        .debtCreditor: "Creditore",
        .debtReference: "Riferimento / pratica",
        .debtDate: "Data",
        .debtType: "Tipo",
        .schuldenGuidanceTitle: "Uscire dai debiti",
        .schuldenTipContactTitle: "Contattate per tempo",
        .schuldenTipContactBody: "Rivolgetevi presto ai creditori. Un pagamento rateale scritto è spesso possibile ed evita un'esecuzione.",
        .schuldenTipBetreibungTitle: "In caso di esecuzione",
        .schuldenTipBetreibungBody: "Dopo il precetto esecutivo avete 20 giorni per pagare – oppure 10 giorni per fare opposizione se la pretesa è ingiustificata.",
        .schuldenTipExistenzminimumTitle: "Il minimo esistenziale è protetto",
        .schuldenTipExistenzminimumBody: "In caso di pignoramento il vostro minimo esistenziale resta intoccabile – importo base, affitto, cassa malati e contributi sociali.",
        .schuldenTipVerlustscheinTitle: "Attestato di carenza beni",
        .schuldenTipVerlustscheinBody: "Un attestato di carenza beni si prescrive dopo 20 anni. Potete però essere escussi di nuovo solo se tornate a nuovi beni.",
        .schuldenTipCounselingTitle: "Consulenza debiti gratuita",
        .schuldenTipCounselingBody: "Consulenza debiti Svizzera, Caritas e la consulenza di budget aiutano gratuitamente e in modo riservato. Estinguete prima i debiti con le conseguenze più gravi.",
        .schuldenDisclaimer: "Informazioni generali, nessuna consulenza legale.",

        .catInsurance: "Assicurazione",
        .catOther: "Altro",
        .catMortgage: "Ipoteca",
        .catHealthInsurance: "Cassa malati",
        .catSerafe: "Radio/TV (Serafe)",
        .catPublicTransport: "Abbonamento trasporti",
        .catChildcare: "Custodia bambini",
        .catMembership: "Abbonamenti & associazioni",
        .catAlimony: "Alimenti",
        .catTaxes: "Imposte",
        .catClothing: "Abbigliamento",
        .catHealth: "Salute",
        .catLeisure: "Tempo libero & hobby",
        .catEntertainment: "Intrattenimento",
        .catChildren: "Figli",
        .catPets: "Animali domestici",
        .catGifts: "Regali",
        .catTravel: "Viaggi",
        .catCharity: "Donazioni",
        .catEducation: "Formazione",

        .settingsTitle: "Impostazioni",
        .settingsLanguage: "Lingua",
        .settingsTheme: "Tema colore",
        .themeSwissRed: "Rosso svizzero",
        .themeOrange: "Arancione",
        .themeSand: "Sabbia",
        .themeGreen: "Verde",
        .themeTeal: "Turchese",
        .themeBlue: "Blu",
        .themePurple: "Viola",
        .themePink: "Rosa",
        .settingsData: "Dati",
        .settingsHousehold: "Economia domestica",
        .settingsCanton: "Cantone",
        .settingsProfile: "Profilo",
        .profileName: "Nome",
        .profileChoosePicture: "Scegli immagine del profilo",
        .profileNoPicture: "Nessuna immagine",
        .profileLocalNote: "Salvato solo localmente su questo dispositivo.",
        .settingsSecurity: "Sicurezza",
        .settingsAutoLock: "Blocco automatico",
        .settingsChangePassphrase: "Cambia passphrase/PIN",
        .settingsBackup: "Backup cifrato",
        .settingsRestore: "Ripristina",
        .settingsPrivacy: "Privacy",
        .settingsDangerZone: "Zona sensibile",
        .settingsDeleteAll: "Elimina tutti i dati locali",
        .backupCreateTitle: "Crea backup cifrato",
        .backupPassphrase: "Passphrase del backup",
        .backupHint: "Scegliete una passphrase di backup separata. È necessaria per il ripristino – non è possibile recuperarla.",
        .restorePreview: "Anteprima",
        .restoreConfirm: "Sostituisci tutti i dati locali",
        .restoreWarning: "Questa operazione sovrascrive definitivamente tutti i dati locali.",
        .backupInvalid: "Backup non valido o passphrase errata.",
        .backupSavedHint: "Conservate il file di backup e la passphrase in un luogo sicuro.",

        .reportTitle: "Segnala un problema",
        .reportSummary: "Riepilogo",
        .reportExpected: "Comportamento atteso",
        .reportActual: "Comportamento effettivo",
        .reportSteps: "Passi per riprodurre",
        .reportArea: "Area interessata",
        .reportRedactionNote: "I dati sensibili vengono rimossi localmente. Verificate il rapporto prima di copiarlo.",
        .reportCopyHint: "Il rapporto non viene inviato automaticamente. Lo copiate voi.",

        .exportReport: "Esporta il rapporto",
        .pdfTitle: "Panoramica finanziaria",
        .pdfSubtitle: "Rapporto domestico personale",
        .pdfSummary: "A colpo d’occhio",
        .pdfGeneratedOn: "Generato il",
        .pdfConfidential: "Riservato",
        .pdfPage: "Pagina",
        .pdfTotal: "Totale",
        .pdfColProgress: "Avanzamento",
        .pdfUnencryptedNote: "Il rapporto è un PDF non cifrato e leggibile. Conservatelo in un luogo sicuro.",
        .pdfNoData: "Ancora nessun dato da esportare.",
        .pdfDefaultHousehold: "La mia economia domestica",

        .lockTitle: "Bloccato",
        .lockWelcomeSetup: "Benvenuti in Kontiva",
        .lockWelcomeBack: "Bentornati",
        .lockSetupTitle: "Configura la passphrase",
        .lockEnterPassphrase: "Inserire passphrase o PIN",
        .lockWrongPassphrase: "Passphrase errata. Riprovare.",
        .lockRecoveryWarning: "Non è possibile alcun recupero. Senza passphrase i vostri dati non sono accessibili.",
        .lockRecoveryAcknowledge: "Capisco che non è possibile alcun recupero.",
        .securityNote: "I vostri dati sono memorizzati localmente e cifrati (AES-256-GCM). Nessun cloud, nessun server, nessun recupero della passphrase.",

        .onboardingIntroBody: "Kontiva vi aiuta a tenere sotto controllo con serenità il budget familiare svizzero – interamente su questo dispositivo.",
        .onboardingStart: "Iniziamo",
        .onboardingProfileTitle: "Crea un profilo",
        .onboardingProfileBody: "Scegliete un nome e un'immagine. Entrambi restano solo su questo dispositivo.",
        .onboardingSkip: "Salta",
        .onboardingFeaturePrivate: "Completamente locale – nessun cloud, nessun tracciamento",
        .onboardingFeatureSecure: "Cifrato con AES-256",
        .onboardingFeatureMoney: "Preciso al centesimo, senza errori di arrotondamento",
        .onboardingConfirmPassphrase: "Conferma passphrase",
        .onboardingPassphraseNote: "Annotate la passphrase in un luogo sicuro – non può essere reimpostata.",
        .backupNudgeText: "Crea un backup cifrato. Senza, i tuoi dati vanno persi se dimentichi la passphrase.",
        .commonNext: "Avanti",
    ]
}
