import Foundation

extension Localization {
    static let pl: [L10nKey: String] = [
        .appName: "Kontiva",
        .appTagline: "Spokojny, prywatny wgląd w Twój szwajcarski budżet.",
        .notBetaNotice: "Wczesna wersja rozwojowa – jeszcze nie beta, nie V1.",

        .navOverview: "Przegląd",
        .navPlanning: "Plan",
        .navBills: "Rachunki",
        .navSettings: "Ustawienia",
        .navReport: "Zgłoś problem",
        .navInsights: "Analizy",
        .navSparen: "Oszczędności",
        .sparenSubtitle: "Regularne wpłaty oszczędnościowe – i to, co już udało się odłożyć.",
        .sparenEmpty: "Brak celów oszczędnościowych. Określ, na co odkładasz co miesiąc.",
        .sparenMonthlyTotal: "Oszczędności / mies.",
        .sparenAccumulatedTotal: "Już odłożono",
        .sparenPerMonth: "/ mies.",
        .sparenContributions: "wpłaty",
        .sparenSince: "od",
        .sparenOpenEnded: "Bez kwoty docelowej",
        .sparenGoalsLabel: "Cele",
        .sparenSortBy: "Sortuj",
        .sparenSortStartMonth: "Miesiąc rozpoczęcia",
        .savingsCatCar: "Samochód",
        .savingsCatVacation: "Wakacje",
        .savingsCatHome: "Mieszkanie",
        .savingsCatRetirement: "Filar 3a / Emerytura",
        .savingsCatEmergency: "Fundusz awaryjny",
        .savingsCatEducation: "Edukacja",
        .savingsCatOther: "Inne",
        .savingsCatWedding: "Ślub",
        .savingsCatFamily: "Rodzina i dzieci",
        .savingsCatRenovation: "Remont i wyposażenie",
        .savingsCatElectronics: "Elektronika",
        .savingsCatTaxes: "Rezerwa na podatki",
        .savingsCatInvestment: "Inwestycje",
        .savingsCatHealth: "Zdrowie",
        .savingsCatGift: "Prezenty",
        .overviewPlannedSavings: "Oszczędności w tym miesiącu",
        .overviewShowCalculation: "Pokaż obliczenia",
        .overviewTrendTitle: "Trend · 6 miesięcy",
        .overviewStatusGood: "Zdrowa nadwyżka",
        .overviewStatusTight: "Napięty budżet",
        .overviewStatusNegative: "Na minusie",
        .overviewAllocationOf: "dochodu netto",
        .formStartDate: "Oszczędzam od",
        .formStartingBalance: "Saldo początkowe (opcjonalnie)",
        .insightsSubtitle: "Wskazówki dotyczące budżetu – gdzie są Twoje pieniądze i gdzie możesz zaoszczędzić.",
        .insightOverspending: "Wydajesz więcej, niż zarabiasz",
        .insightTightBudget: "Mało miejsca w tym miesiącu",
        .insightHealthySurplus: "Zdrowa nadwyżka",
        .insightHighFixed: "Wysokie koszty stałe",
        .insightHighHousing: "Wysokie koszty mieszkania",
        .insightLargestFixed: "Największa pozycja kosztów stałych",
        .insightLargestVariable: "Największy budżet zmienny",
        .insightOverdue: "Zaległe rachunki",
        .insightNoSavings: "Brak zaplanowanych oszczędności",
        .insightGoodSavings: "Dobra stopa oszczędności",
        .insightAllHealthy: "Twój budżet wygląda zdrowo",
        .insightHousingHint: "Zalecenie: maksymalnie jedna trzecia dochodu",
        .insightNoSavingsDetail: "Masz zapas – cel oszczędnościowy może pomóc.",
        .insightAllHealthyDetail: "Nic się nie wyróżnia. Dodaj więcej danych, by uzyskać dokładniejsze analizy.",
        .fragOfNetIncome: "dochodu netto",
        .fragOfFixedCosts: "kosztów stałych",
        .fragShortfall: "Niedobór",

        .commonAdd: "Dodaj",
        .commonEdit: "Edytuj",
        .commonActivate: "Włącz",
        .commonDelete: "Usuń",
        .commonCancel: "Anuluj",
        .commandsAdd: "Dodaj wpis",
        .billsAddCta: "Dodaj pierwszy rachunek",
        .sparenAddCta: "Utwórz cel oszczędnościowy",
        .overviewAddCta: "Dodaj dochód",
        .commonSave: "Zapisz",
        .commonSaved: "Zapisano",
        .commonClose: "Zamknij",
        .commonDone: "Gotowe",
        .commonShowSampleData: "Pokaż dane przykładowe",
        .commonHideSampleData: "Ukryj dane przykładowe",
        .commonEmptyHint: "Nie wprowadzono jeszcze danych.",
        .commonCopy: "Kopiuj",
        .commonOptions: "Opcje",
        .commonMoveUp: "W górę",
        .commonMoveDown: "W dół",
        .monthToday: "Dziś",

        .formName: "Nazwa",
        .formAmount: "Kwota (CHF)",
        .formStatus: "Status",
        .formNotes: "Notatka",
        .formInvalidAmount: "Wprowadź prawidłową kwotę.",
        .formThirteenthAmount: "13. pensja (kwota)",
        .formThirteenthModel: "Model 13. pensji",
        .incomeBonuses: "Dodatkowe wypłaty",
        .formMonth: "Miesiąc",
        .thirteenthModelSeparate: "Pokaż osobno",
        .thirteenthModelAveraged: "Rozłóż na 12 miesięcy",
        .formTarget: "Cel oszczędnościowy (kwota)",
        .formSaved: "Już odłożono",
        .formMonthlyContribution: "Miesięczna wpłata",
        .formCategory: "Kategoria",
        .formLimitedDuration: "Zlecenie stałe na czas określony",
        .formLimitedDurationHint: "Np. 6 rat podatku – liczone tylko w tych miesiącach, potem usuwane automatycznie.",
        .formStartMonth: "Pierwsza rata",
        .formInstallments: "Liczba rat",
        .planningStandingOrder: "Zlecenie stałe",
        .catRent: "Czynsz",
        .catSubscription: "Subskrypcja",
        .catLeasing: "Leasing",
        .catUtilities: "Media",
        .catTelecom: "Telekomunikacja",
        .catGroceries: "Zakupy spożywcze",
        .catFuel: "Paliwo",
        .catTransport: "Transport",
        .catPersonal: "Osobiste",
        .catDining: "Jedzenie na mieście",
        .catHousehold: "Dom",

        .overviewTitle: "Przegląd",
        .overviewAvailableThisMonth: "Dostępne w tym miesiącu",
        .overviewNetIncome: "Dochód netto w tym miesiącu",
        .overviewThirteenthSeparate: "13. pensja (osobno)",
        .overviewRecurringFixed: "Koszty stałe",
        .overviewPlannedVariable: "Wydatki zmienne",
        .overviewBillsDueThisMonth: "Rachunki w tym miesiącu",
        .overviewOverdueBills: "Zaległe rachunki",
        .overviewSavingsTarget: "Cel oszczędnościowy",
        .overviewSecurityStatus: "Status bezpieczeństwa",
        .overviewFormulaExplainer: "Dostępne = dochód netto − koszty stałe − budżety zmienne − rachunki do zapłaty w tym miesiącu − zaległe rachunki. Opłacone i przyszłe rachunki nie obniżają kwoty.",
        .overviewEmpty: "Wprowadź dochody i koszty w Planie miesięcznym, aby zobaczyć przegląd.",
        .chartSpendingTitle: "Podział w tym miesiącu",
        .chartByCategory: "Według kategorii",

        .planningTitle: "Plan miesięczny",
        .planningIncome: "Dochód",
        .planningFixed: "Koszty stałe",
        .planningVariable: "Wydatki zmienne",
        .planningSavings: "Cel oszczędnościowy",
        .planningFixedExplainer: "Koszty stałe powtarzają się co miesiąc: czynsz, ubezpieczenia, subskrypcje, leasing.",
        .planningVariableExplainer: "Budżety zmienne planujesz samodzielnie: zakupy, paliwo, wydatki osobiste.",
        .planningOneOffHint: "Rachunki jednorazowe znajdziesz w sekcji „Rachunki”.",
        .planningEmpty: "Zacznij od dochodu, a następnie dodaj koszty stałe i budżety.",
        .planningBalance: "Planowane saldo",

        .billsTitle: "Rachunki",
        .billsStatusOpen: "Otwarty",
        .billsStatusPaid: "Opłacony",
        .billsStateOverdue: "Zaległy",
        .billsStateDueThisMonth: "Termin w tym miesiącu",
        .billsStateFuture: "Przyszły",
        .billsAffectsBalance: "Obniża dostępną kwotę",
        .billsNoBalanceImpact: "Bez wpływu w tym miesiącu",
        .billsDueDate: "Termin płatności",
        .billsProvider: "Dostawca",
        .billsEmpty: "Brak rachunków. Rachunki jednorazowe z terminem płatności pojawią się tutaj.",
        .billsMarkPaid: "Oznacz jako opłacony",
        .billsMarkOpen: "Oznacz jako otwarty",
        .billsOpenTotal: "Suma otwartych",

        .navSchulden: "Długi",
        .schuldenSubtitle: "Miej oko na zaległe rachunki i postępowania windykacyjne.",
        .schuldenEmpty: "Brak zarejestrowanych długów. Zaległe rachunki pojawiają się tutaj automatycznie – możesz też zanotować postępowanie windykacyjne (Betreibung) lub zaświadczenia o niewypłacalności.",
        .schuldenAddCta: "Zarejestruj dług",
        .schuldenTotal: "Łączny dług",
        .schuldenOverdueBills: "Zaległe rachunki",
        .schuldenRecorded: "Zarejestrowane długi",
        .schuldenManagedInBills: "Zaległymi rachunkami zarządzaj w sekcji „Rachunki”.",
        .debtTypeOpenClaim: "Otwarte roszczenie",
        .debtTypeBetreibung: "Postępowanie windykacyjne",
        .debtTypePfaendung: "Zajęcie wynagrodzenia/mienia",
        .debtTypeVerlustschein: "Zaświadczenie o niewypłacalności",
        .debtTypeOther: "Inny dług",
        .debtCreditor: "Wierzyciel",
        .debtReference: "Numer / sygnatura sprawy",
        .debtDate: "Data",
        .debtType: "Typ",
        .schuldenGuidanceTitle: "Jak wyjść z długów",
        .schuldenTipContactTitle: "Skontaktuj się wcześnie",
        .schuldenTipContactBody: "Porozmawiaj z wierzycielami wcześnie. Pisemny plan ratalny jest często możliwy i pozwala uniknąć formalnego postępowania.",
        .schuldenTipBetreibungTitle: "Gdy rozpoczyna się postępowanie",
        .schuldenTipBetreibungBody: "Po nakazie zapłaty masz 20 dni na zapłatę – albo 10 dni na wniesienie sprzeciwu (Rechtsvorschlag), jeśli roszczenie jest nieuzasadnione.",
        .schuldenTipExistenzminimumTitle: "Twoje minimum egzystencji jest chronione",
        .schuldenTipExistenzminimumBody: "Przy zajęciu Twoje minimum egzystencji pozostaje nienaruszalne – kwota podstawowa, czynsz, ubezpieczenie zdrowotne i składki socjalne.",
        .schuldenTipVerlustscheinTitle: "Zaświadczenie o niewypłacalności",
        .schuldenTipVerlustscheinBody: "Zaświadczenie o niewypłacalności przedawnia się dopiero po 20 latach. Ponownie można Cię ścigać tylko wtedy, gdy uzyskasz nowy majątek.",
        .schuldenTipCounselingTitle: "Bezpłatne doradztwo dłużników",
        .schuldenTipCounselingBody: "Schuldenberatung Schweiz, Caritas i poradnie budżetowe pomagają bezpłatnie i poufnie. Najpierw spłać długi o najgorszych konsekwencjach.",
        .schuldenDisclaimer: "Informacja ogólna, nie porada prawna.",

        .catInsurance: "Ubezpieczenie",
        .catOther: "Inne",
        .catMortgage: "Kredyt hipoteczny",
        .catHealthInsurance: "Ubezpieczenie zdrowotne",
        .catSerafe: "Radio/TV (Serafe)",
        .catPublicTransport: "Bilet komunikacji",
        .catChildcare: "Opieka nad dziećmi",
        .catMembership: "Składki członkowskie",
        .catAlimony: "Alimenty i utrzymanie",
        .catTaxes: "Podatki",
        .catClothing: "Odzież",
        .catHealth: "Zdrowie",
        .catLeisure: "Czas wolny i hobby",
        .catEntertainment: "Rozrywka",
        .catChildren: "Dzieci",
        .catPets: "Zwierzęta",
        .catGifts: "Prezenty",
        .catTravel: "Podróże",
        .catCharity: "Darowizny",
        .catEducation: "Edukacja",

        .settingsTitle: "Ustawienia",
        .settingsLanguage: "Język",
        .settingsTheme: "Motyw kolorystyczny",
        .themeSwissRed: "Szwajcarska czerwień",
        .themeOrange: "Pomarańczowy",
        .themeSand: "Piaskowy",
        .themeGreen: "Zielony",
        .themeTeal: "Morski",
        .themeBlue: "Niebieski",
        .themePurple: "Fioletowy",
        .themePink: "Różowy",
        .settingsData: "Dane",
        .settingsHousehold: "Gospodarstwo domowe",
        .settingsCanton: "Kanton",
        .settingsProfile: "Profil",
        .profileName: "Imię",
        .profileChoosePicture: "Wybierz zdjęcie profilowe",
        .profileNoPicture: "Bez zdjęcia",
        .profileLocalNote: "Przechowywane wyłącznie lokalnie na tym urządzeniu.",
        .settingsSecurity: "Bezpieczeństwo",
        .settingsAutoLock: "Automatyczna blokada",
        .settingsBiometric: "Odblokowanie biometryczne",
        .settingsChangePassphrase: "Zmień hasło/PIN",
        .settingsBackup: "Zaszyfrowana kopia zapasowa",
        .settingsRestore: "Przywróć",
        .settingsPrivacy: "Prywatność",
        .settingsDangerZone: "Strefa zagrożenia",
        .settingsDeleteAll: "Usuń wszystkie dane lokalne",
        .backupCreateTitle: "Utwórz zaszyfrowaną kopię zapasową",
        .backupPassphrase: "Hasło kopii zapasowej",
        .backupHint: "Wybierz osobne hasło do kopii zapasowej. Jest wymagane do przywrócenia – nie ma sposobu jego odzyskania.",
        .restorePreview: "Podgląd",
        .restoreConfirm: "Zastąp wszystkie dane lokalne",
        .restoreWarning: "To trwale nadpisuje wszystkie dane lokalne.",
        .backupInvalid: "Nieprawidłowa kopia lub błędne hasło.",
        .backupSavedHint: "Przechowuj plik kopii i hasło w bezpiecznym miejscu.",

        .reportTitle: "Zgłoś problem",
        .reportSummary: "Podsumowanie",
        .reportExpected: "Oczekiwane zachowanie",
        .reportActual: "Rzeczywiste zachowanie",
        .reportSteps: "Kroki do odtworzenia",
        .reportArea: "Obszar, którego dotyczy",
        .reportRedactionNote: "Dane wrażliwe są usuwane lokalnie. Przejrzyj zgłoszenie przed skopiowaniem.",
        .reportCopyHint: "Zgłoszenie nie jest wysyłane automatycznie. Kopiujesz je samodzielnie.",

        .exportReport: "Eksportuj raport",
        .pdfTitle: "Przegląd finansowy",
        .pdfSubtitle: "Osobisty raport gospodarstwa domowego",
        .pdfSummary: "W skrócie",
        .pdfGeneratedOn: "Wygenerowano",
        .pdfConfidential: "Poufne",
        .pdfPage: "Strona",
        .pdfTotal: "Razem",
        .pdfColProgress: "Postęp",
        .pdfUnencryptedNote: "Raport to czytelny, niezaszyfrowany plik PDF. Przechowuj go w bezpiecznym miejscu.",
        .pdfNoData: "Brak danych do wyeksportowania.",
        .pdfDefaultHousehold: "Moje gospodarstwo",

        .lockTitle: "Zablokowano",
        .lockWelcomeSetup: "Witamy w Kontiva",
        .lockWelcomeBack: "Witaj ponownie",
        .lockSetupTitle: "Ustaw hasło",
        .lockEnterPassphrase: "Wprowadź hasło lub PIN",
        .lockWrongPassphrase: "Błędne hasło. Spróbuj ponownie.",
        .lockRecoveryWarning: "Nie ma odzyskiwania. Bez hasła dostęp do danych jest niemożliwy.",
        .lockRecoveryAcknowledge: "Rozumiem, że nie ma odzyskiwania.",
        .securityNote: "Twoje dane są przechowywane lokalnie i zaszyfrowane (AES-256-GCM). Bez chmury, bez serwera, bez odzyskiwania hasła.",

        .onboardingIntroBody: "Kontiva pomaga zachować spokojny wgląd w budżet Twojego szwajcarskiego gospodarstwa domowego – w całości na tym urządzeniu.",
        .onboardingStart: "Zaczynamy",
        .onboardingProfileTitle: "Utwórz profil",
        .onboardingProfileBody: "Nadaj sobie imię i wybierz obrazek. Oba pozostaną tylko na tym urządzeniu.",
        .onboardingSkip: "Pomiń",
        .onboardingFeaturePrivate: "W pełni lokalnie – bez chmury, bez śledzenia",
        .onboardingFeatureSecure: "Szyfrowane za pomocą AES-256",
        .onboardingFeatureMoney: "Dokładność co do groszy, bez błędów zaokrągleń",
        .onboardingConfirmPassphrase: "Potwierdź hasło",
        .onboardingPassphraseNote: "Zapisz hasło w bezpiecznym miejscu – nie można go zresetować.",
        .backupNudgeText: "Utwórz zaszyfrowaną kopię zapasową. Bez niej utracisz dane, jeśli zapomnisz hasła.",
        .commonNext: "Dalej",
        .navMore: "Więcej",
        .actionLock: "Zablokuj",
        .pinSetTitle: "Ustaw kod",
        .pinConfirmTitle: "Potwierdź kod",
        .pinRequirementNote: "Min. 6 cyfr · brak odzyskiwania",
        .pinMismatch: "Kody nie pasują do siebie",
    ]
}
