import Foundation

extension Localization {
    static let deCH: [L10nKey: String] = [
        .appName: "Kontiva",
        .appTagline: "Ruhige, private Übersicht über Ihr Schweizer Budget.",
        .notBetaNotice: "Frühe Entwicklungsversion – nicht beta-bereit, nicht V1.",

        .navOverview: "Übersicht",
        .navPlanning: "Planung",
        .navBills: "Rechnungen",
        .navSettings: "Einstellungen",
        .navReport: "Problem melden",
        .navInsights: "Erkenntnisse",
        .navSparen: "Sparen",
        .sparenSubtitle: "Wiederkehrende Sparbeiträge – und was bereits zusammengekommen ist.",
        .sparenEmpty: "Noch keine Sparziele. Legen Sie an, wofür Sie monatlich sparen.",
        .sparenMonthlyTotal: "Sparbeiträge / Monat",
        .sparenAccumulatedTotal: "Bereits angespart",
        .sparenPerMonth: "/ Monat",
        .sparenContributions: "Beiträge",
        .sparenSince: "seit",
        .sparenOpenEnded: "Ohne Zielbetrag",
        .sparenGoalsLabel: "Sparziele",
        .sparenSortBy: "Sortieren",
        .sparenSortStartMonth: "Startmonat",
        .savingsCatCar: "Auto",
        .savingsCatVacation: "Ferien",
        .savingsCatHome: "Eigenheim",
        .savingsCatRetirement: "Säule 3a / Vorsorge",
        .savingsCatEmergency: "Notgroschen",
        .savingsCatEducation: "Ausbildung",
        .savingsCatOther: "Sonstiges",
        .savingsCatWedding: "Hochzeit",
        .savingsCatFamily: "Familie & Kinder",
        .savingsCatRenovation: "Renovation & Einrichtung",
        .savingsCatElectronics: "Elektronik",
        .savingsCatTaxes: "Steuerrücklage",
        .savingsCatInvestment: "Investitionen",
        .savingsCatHealth: "Gesundheit",
        .savingsCatGift: "Geschenke",
        .overviewPlannedSavings: "Sparen diesen Monat",
        .overviewShowCalculation: "Berechnung anzeigen",
        .overviewTrendTitle: "Verlauf · 6 Monate",
        .overviewStatusGood: "Gesunder Überschuss",
        .overviewStatusTight: "Knapp",
        .overviewStatusNegative: "Im Minus",
        .overviewAllocationOf: "des Nettoeinkommens",
        .formStartDate: "Sparen seit",
        .formStartingBalance: "Startguthaben (optional)",
        .insightsSubtitle: "Hinweise zu Ihrem Budget – wo Ihr Geld liegt und wo Sie sparen können.",
        .insightOverspending: "Sie geben mehr aus, als Sie einnehmen",
        .insightTightBudget: "Wenig Spielraum diesen Monat",
        .insightHealthySurplus: "Gesunder Überschuss",
        .insightHighFixed: "Hohe Fixkostenlast",
        .insightHighHousing: "Hohe Wohnkosten",
        .insightLargestFixed: "Grösster Fixkostenblock",
        .insightLargestVariable: "Grösstes variables Budget",
        .insightOverdue: "Überfällige Rechnungen",
        .insightNoSavings: "Noch kein Sparbeitrag geplant",
        .insightGoodSavings: "Guter Sparbeitrag",
        .insightAllHealthy: "Ihr Budget sieht gesund aus",
        .insightHousingHint: "Richtwert: höchstens ein Drittel des Einkommens",
        .insightNoSavingsDetail: "Sie haben Spielraum – ein Sparziel könnte helfen.",
        .insightAllHealthyDetail: "Keine Auffälligkeiten. Erfassen Sie mehr Daten für genauere Hinweise.",
        .fragOfNetIncome: "des Nettoeinkommens",
        .fragOfFixedCosts: "der Fixkosten",
        .fragShortfall: "Fehlbetrag",

        .commonAdd: "Hinzufügen",
        .commonEdit: "Bearbeiten",
        .commonActivate: "Aktivieren",
        .commonDelete: "Löschen",
        .commonCancel: "Abbrechen",
        .commandsAdd: "Eintrag hinzufügen",
        .billsAddCta: "Erste Rechnung hinzufügen",
        .sparenAddCta: "Erstes Sparziel anlegen",
        .overviewAddCta: "Einkommen erfassen",
        .commonSave: "Speichern",
        .commonSaved: "Gespeichert",
        .commonClose: "Schliessen",
        .commonDone: "Fertig",
        .commonShowSampleData: "Beispieldaten anzeigen",
        .commonHideSampleData: "Beispieldaten ausblenden",
        .commonEmptyHint: "Noch keine Daten erfasst.",
        .commonCopy: "Kopieren",
        .commonOptions: "Optionen",
        .commonMoveUp: "Nach oben",
        .commonMoveDown: "Nach unten",
        .monthToday: "Heute",

        .formName: "Bezeichnung",
        .formAmount: "Betrag (CHF)",
        .formStatus: "Status",
        .formNotes: "Notiz",
        .formInvalidAmount: "Bitte einen gültigen Betrag eingeben.",
        .formThirteenthAmount: "13. Monatslohn (Betrag)",
        .formThirteenthModel: "Modell 13. Monatslohn",
        .thirteenthModelSeparate: "Separat ausweisen",
        .thirteenthModelAveraged: "Auf 12 Monate verteilen",
        .formTarget: "Sparziel (Betrag)",
        .formSaved: "Bereits gespart",
        .formMonthlyContribution: "Monatlicher Beitrag",
        .formCategory: "Kategorie",
        .formLimitedDuration: "Befristeter Dauerauftrag",
        .formLimitedDurationHint: "Z. B. 6 Steuerraten – zählt nur in diesen Monaten, danach automatisch weg.",
        .formStartMonth: "Erste Rate",
        .formInstallments: "Anzahl Raten",
        .planningStandingOrder: "Dauerauftrag",
        .catRent: "Miete",
        .catSubscription: "Abonnement",
        .catLeasing: "Leasing",
        .catUtilities: "Nebenkosten",
        .catTelecom: "Telekom",
        .catGroceries: "Lebensmittel",
        .catFuel: "Treibstoff",
        .catTransport: "Transport",
        .catPersonal: "Persönliches",
        .catDining: "Auswärts essen",
        .catHousehold: "Haushalt",

        .overviewTitle: "Übersicht",
        .overviewAvailableThisMonth: "Diesen Monat verfügbar",
        .overviewNetIncome: "Nettoeinkommen diesen Monat",
        .overviewThirteenthSeparate: "13. Monatslohn (separat ausgewiesen)",
        .overviewRecurringFixed: "Fixkosten",
        .overviewPlannedVariable: "Variable Ausgaben",
        .overviewBillsDueThisMonth: "Rechnungen diesen Monat",
        .overviewOverdueBills: "Überfällige Rechnungen",
        .overviewSavingsTarget: "Sparziel",
        .overviewSecurityStatus: "Sicherheitsstatus",
        .overviewFormulaExplainer: "Verfügbar = Nettoeinkommen − Fixkosten − variable Budgets − offene Rechnungen diesen Monat − überfällige Rechnungen. Bezahlte und zukünftige Rechnungen reduzieren den Betrag nicht.",
        .overviewEmpty: "Erfassen Sie Einkommen und Kosten in der Monatsplanung, um Ihre Übersicht zu sehen.",
        .chartSpendingTitle: "Aufteilung diesen Monat",
        .chartByCategory: "Nach Kategorie",

        .planningTitle: "Monatsplanung",
        .planningIncome: "Einkommen",
        .planningFixed: "Fixkosten",
        .planningVariable: "Variable Ausgaben",
        .planningSavings: "Sparziel",
        .planningFixedExplainer: "Fixkosten wiederholen sich jeden Monat: Miete, Versicherungen, Abonnemente, Leasing.",
        .planningVariableExplainer: "Variable Budgets planen Sie selbst: Lebensmittel, Treibstoff, persönliche Ausgaben.",
        .planningOneOffHint: "Einmalige Rechnungen verwalten Sie unter «Rechnungen».",
        .planningEmpty: "Beginnen Sie mit Ihrem Einkommen, dann ergänzen Sie Fixkosten und Budgets.",
        .planningBalance: "Geplanter Saldo",

        .billsTitle: "Rechnungen",
        .billsStatusOpen: "Offen",
        .billsStatusPaid: "Bezahlt",
        .billsStateOverdue: "Überfällig",
        .billsStateDueThisMonth: "Fällig diesen Monat",
        .billsStateFuture: "Zukünftig",
        .billsAffectsBalance: "Reduziert den verfügbaren Betrag",
        .billsNoBalanceImpact: "Ohne Einfluss auf diesen Monat",
        .billsDueDate: "Fälligkeitsdatum",
        .billsProvider: "Anbieter",
        .billsEmpty: "Noch keine Rechnungen erfasst. Einmalige Rechnungen mit Fälligkeitsdatum erscheinen hier.",
        .billsMarkPaid: "Als bezahlt markieren",
        .billsMarkOpen: "Als offen markieren",
        .billsOpenTotal: "Offen gesamt",

        .navSchulden: "Schulden",
        .schuldenSubtitle: "Überfällige Rechnungen und Betreibungen im Blick behalten.",
        .schuldenEmpty: "Keine Schulden erfasst. Überfällige Rechnungen erscheinen hier automatisch – und Sie können Betreibungen oder Verlustscheine festhalten.",
        .schuldenAddCta: "Schuld erfassen",
        .schuldenTotal: "Gesamtschulden",
        .schuldenOverdueBills: "Überfällige Rechnungen",
        .schuldenRecorded: "Erfasste Schulden",
        .schuldenManagedInBills: "Überfällige Rechnungen verwalten Sie unter «Rechnungen».",
        .debtTypeOpenClaim: "Offene Forderung",
        .debtTypeBetreibung: "Betreibung",
        .debtTypePfaendung: "Pfändung",
        .debtTypeVerlustschein: "Verlustschein",
        .debtTypeOther: "Sonstige Schuld",
        .debtCreditor: "Gläubiger",
        .debtReference: "Referenz / Aktenzeichen",
        .debtDate: "Datum",
        .debtType: "Art",
        .schuldenGuidanceTitle: "Wege aus den Schulden",
        .schuldenTipContactTitle: "Früh Kontakt aufnehmen",
        .schuldenTipContactBody: "Sprechen Sie Gläubiger früh an. Eine schriftliche Ratenzahlung ist oft möglich und verhindert eine Betreibung.",
        .schuldenTipBetreibungTitle: "Bei einer Betreibung",
        .schuldenTipBetreibungBody: "Nach dem Zahlungsbefehl haben Sie 20 Tage Zeit zu zahlen – oder 10 Tage, um Rechtsvorschlag zu erheben, falls die Forderung unberechtigt ist.",
        .schuldenTipExistenzminimumTitle: "Existenzminimum ist geschützt",
        .schuldenTipExistenzminimumBody: "Bei einer Pfändung bleibt Ihr Existenzminimum unantastbar – Grundbetrag, Miete, Krankenkasse und Sozialbeiträge.",
        .schuldenTipVerlustscheinTitle: "Verlustschein",
        .schuldenTipVerlustscheinBody: "Ein Verlustschein verjährt erst nach 20 Jahren. Neu betrieben werden Sie aber erst, wenn Sie zu neuem Vermögen kommen.",
        .schuldenTipCounselingTitle: "Kostenlose Schuldenberatung",
        .schuldenTipCounselingBody: "Schuldenberatung Schweiz, Caritas und Budgetberatung helfen kostenlos und vertraulich. Tilgen Sie zuerst Schulden mit den schwersten Folgen.",
        .schuldenDisclaimer: "Allgemeine Informationen, keine Rechtsberatung.",

        .catInsurance: "Versicherung",
        .catOther: "Sonstiges",
        .catMortgage: "Hypothek",
        .catHealthInsurance: "Krankenkasse",
        .catSerafe: "Radio/TV (Serafe)",
        .catPublicTransport: "ÖV-Abonnement",
        .catChildcare: "Kinderbetreuung",
        .catMembership: "Mitgliedschaften",
        .catAlimony: "Unterhalt & Alimente",
        .catTaxes: "Steuern",
        .catClothing: "Kleidung",
        .catHealth: "Gesundheit",
        .catLeisure: "Freizeit & Hobby",
        .catEntertainment: "Unterhaltung",
        .catChildren: "Kinder",
        .catPets: "Haustiere",
        .catGifts: "Geschenke",
        .catTravel: "Reisen",
        .catCharity: "Spenden",
        .catEducation: "Aus- & Weiterbildung",

        .settingsTitle: "Einstellungen",
        .settingsLanguage: "Sprache",
        .settingsTheme: "Farbthema",
        .themeSwissRed: "Schweizer Rot",
        .themeOrange: "Orange",
        .themeSand: "Sand",
        .themeGreen: "Grün",
        .themeTeal: "Türkis",
        .themeBlue: "Blau",
        .themePurple: "Violett",
        .themePink: "Pink",
        .settingsData: "Daten",
        .settingsHousehold: "Haushalt",
        .settingsCanton: "Kanton",
        .settingsProfile: "Profil",
        .profileName: "Name",
        .profileChoosePicture: "Profilbild wählen",
        .profileNoPicture: "Kein Bild",
        .profileLocalNote: "Nur lokal auf diesem Gerät gespeichert.",
        .settingsSecurity: "Sicherheit",
        .settingsAutoLock: "Automatische Sperre",
        .settingsBiometric: "Biometrisches Entsperren",
        .settingsChangePassphrase: "Passphrase/PIN ändern",
        .settingsBackup: "Verschlüsseltes Backup",
        .settingsRestore: "Wiederherstellen",
        .settingsPrivacy: "Datenschutz",
        .settingsDangerZone: "Gefahrenzone",
        .settingsDeleteAll: "Alle lokalen Daten löschen",
        .backupCreateTitle: "Verschlüsseltes Backup erstellen",
        .backupPassphrase: "Backup-Passphrase",
        .backupHint: "Wählen Sie eine separate Backup-Passphrase. Sie wird zum Wiederherstellen benötigt – es gibt keine Wiederherstellung der Backup-Passphrase.",
        .restorePreview: "Vorschau",
        .restoreConfirm: "Alle lokalen Daten ersetzen",
        .restoreWarning: "Dies überschreibt alle lokalen Daten unwiderruflich.",
        .backupInvalid: "Backup ungültig oder falsche Backup-Passphrase.",
        .backupSavedHint: "Bewahren Sie die Backup-Datei und die Backup-Passphrase sicher auf.",

        .reportTitle: "Problem melden",
        .reportSummary: "Zusammenfassung",
        .reportExpected: "Erwartetes Verhalten",
        .reportActual: "Tatsächliches Verhalten",
        .reportSteps: "Schritte zur Reproduktion",
        .reportArea: "Betroffener Bereich",
        .reportRedactionNote: "Sensible Angaben werden lokal entfernt. Sie prüfen den Bericht vor dem Kopieren.",
        .reportCopyHint: "Der Bericht wird nicht automatisch gesendet. Sie kopieren ihn selbst.",

        .exportReport: "Bericht exportieren",
        .pdfTitle: "Finanzübersicht",
        .pdfSubtitle: "Persönlicher Haushaltsbericht",
        .pdfSummary: "Auf einen Blick",
        .pdfGeneratedOn: "Erstellt am",
        .pdfConfidential: "Vertraulich",
        .pdfPage: "Seite",
        .pdfTotal: "Total",
        .pdfColProgress: "Fortschritt",
        .pdfUnencryptedNote: "Der Bericht ist ein unverschlüsseltes, lesbares PDF. Bewahren Sie ihn sicher auf.",
        .pdfNoData: "Noch keine Daten zum Exportieren.",
        .pdfDefaultHousehold: "Mein Haushalt",

        .lockTitle: "Gesperrt",
        .lockWelcomeSetup: "Willkommen bei Kontiva",
        .lockWelcomeBack: "Willkommen zurück",
        .lockSetupTitle: "Passphrase einrichten",
        .lockEnterPassphrase: "Passphrase oder PIN eingeben",
        .lockWrongPassphrase: "Falsche Passphrase. Bitte erneut versuchen.",
        .lockRecoveryWarning: "Es gibt keine Wiederherstellung. Ohne Passphrase sind Ihre Daten nicht zugänglich.",
        .lockRecoveryAcknowledge: "Ich verstehe, dass es keine Wiederherstellung gibt.",
        .securityNote: "Ihre Daten werden lokal und verschlüsselt gespeichert (AES-256-GCM). Keine Cloud, kein Server, keine Wiederherstellung der Passphrase.",

        .onboardingIntroBody: "Kontiva hilft Ihnen, Ihr Schweizer Haushaltsbudget ruhig im Blick zu behalten – komplett auf diesem Gerät.",
        .onboardingStart: "Los geht's",
        .onboardingProfileTitle: "Profil erstellen",
        .onboardingProfileBody: "Geben Sie sich einen Namen und wählen Sie ein Bild. Beides bleibt nur auf diesem Gerät.",
        .onboardingSkip: "Überspringen",
        .onboardingFeaturePrivate: "Komplett lokal – keine Cloud, kein Tracking",
        .onboardingFeatureSecure: "Verschlüsselt mit AES-256",
        .onboardingFeatureMoney: "Rappengenau, ohne Rundungsfehler",
        .onboardingConfirmPassphrase: "Passphrase bestätigen",
        .onboardingPassphraseNote: "Notieren Sie Ihre Passphrase an einem sicheren Ort – sie lässt sich nicht zurücksetzen.",
        .backupNudgeText: "Erstellen Sie ein verschlüsseltes Backup. Ohne Backup sind Ihre Daten verloren, falls Sie die Passphrase vergessen.",
        .commonNext: "Weiter",
        .navMore: "Mehr",
        .actionLock: "Sperren",
        .pinSetTitle: "Code festlegen",
        .pinConfirmTitle: "Code bestätigen",
        .pinRequirementNote: "Mind. 6 Ziffern · keine Wiederherstellung",
        .pinMismatch: "Codes stimmen nicht überein",
    ]
}
