import Foundation

extension Localization {
    static let es: [L10nKey: String] = [
        .appName: "Kontiva",
        .appTagline: "Una visión serena y privada de tu presupuesto suizo.",
        .notBetaNotice: "Versión en desarrollo temprano: no es beta, no es V1.",

        .navOverview: "Resumen",
        .navPlanning: "Plan",
        .navBills: "Facturas",
        .navSettings: "Ajustes",
        .navReport: "Informar de un problema",
        .navInsights: "Análisis",
        .navSparen: "Ahorros",
        .sparenSubtitle: "Aportaciones de ahorro periódicas, y lo que ya has acumulado.",
        .sparenEmpty: "Aún no hay objetivos de ahorro. Define para qué ahorras cada mes.",
        .sparenMonthlyTotal: "Ahorro / mes",
        .sparenAccumulatedTotal: "Ya ahorrado",
        .sparenPerMonth: "/ mes",
        .sparenContributions: "aportaciones",
        .sparenSince: "desde",
        .sparenOpenEnded: "Sin importe objetivo",
        .sparenGoalReached: "Meta alcanzada",
        .sparenGoalReachedMessage: "¡Felicidades! Has alcanzado tu meta de ahorro. ¿Cómo quieres continuar?",
        .sparenGoalIncrease: "Aumentar la meta",
        .sparenGoalComplete: "Marcar como hecho",
        .sparenGoalKeep: "Seguir ahorrando",
        .sparenGoalCompleted: "Completado",
        .sparenGoalReopen: "Reactivar",
        .sparenGoalsLabel: "Objetivos",
        .sparenSortBy: "Ordenar",
        .sparenSortStartMonth: "Mes de inicio",
        .savingsCatCar: "Coche",
        .savingsCatVacation: "Vacaciones",
        .savingsCatHome: "Vivienda",
        .savingsCatRetirement: "Pilar 3a / Jubilación",
        .savingsCatEmergency: "Fondo de emergencia",
        .savingsCatEducation: "Formación",
        .savingsCatOther: "Otros",
        .savingsCatWedding: "Boda",
        .savingsCatFamily: "Familia e hijos",
        .savingsCatRenovation: "Reforma y mobiliario",
        .savingsCatElectronics: "Electrónica",
        .savingsCatTaxes: "Reserva para impuestos",
        .savingsCatInvestment: "Inversiones",
        .savingsCatHealth: "Salud",
        .savingsCatGift: "Regalos",
        .overviewPlannedSavings: "Ahorro este mes",
        .overviewShowCalculation: "Mostrar cálculo",
        .overviewTrendTitle: "Tendencia · 6 meses",
        .overviewStatusGood: "Superávit saludable",
        .overviewStatusTight: "Ajustado",
        .overviewStatusNegative: "En números rojos",
        .overviewAllocationOf: "de los ingresos netos",
        .formStartDate: "Ahorrando desde",
        .formStartingBalance: "Saldo inicial (opcional)",
        .insightsSubtitle: "Orientación sobre tu presupuesto: dónde está tu dinero y dónde puedes ahorrar.",
        .insightOverspending: "Gastas más de lo que ingresas",
        .insightTightBudget: "Poco margen este mes",
        .insightHealthySurplus: "Superávit saludable",
        .insightHighFixed: "Alta carga de costes fijos",
        .insightHighHousing: "Costes de vivienda elevados",
        .insightLargestFixed: "Mayor bloque de costes fijos",
        .insightLargestVariable: "Mayor presupuesto variable",
        .insightOverdue: "Facturas vencidas",
        .insightNoSavings: "Aún no hay ahorro previsto",
        .insightGoodSavings: "Buena tasa de ahorro",
        .insightAllHealthy: "Tu presupuesto parece saludable",
        .insightHousingHint: "Recomendación: como máximo un tercio de los ingresos",
        .insightNoSavingsDetail: "Tienes margen: un objetivo de ahorro podría ayudar.",
        .insightAllHealthyDetail: "Nada destaca. Añade más datos para obtener análisis más precisos.",
        .insightExtraIncome: "Ingreso extra este mes",
        .insightGoalProgress: "Meta de ahorro al alcance",
        .insightBillsDueSoon: "Pendiente de pago este mes",
        .insightGettingStarted: "Empecemos",
        .insightGettingStartedDetail: "Añade tus ingresos para ver tus análisis personales.",
        .schuldenEncourageTitle: "Paso a paso",
        .schuldenEncourageBody: "Lo estás afrontando. Aquí tienes próximos pasos concretos.",
        .fragOfNetIncome: "de los ingresos netos",
        .fragOfFixedCosts: "de los costes fijos",
        .fragShortfall: "Déficit",

        .commonAdd: "Añadir",
        .commonEdit: "Editar",
        .commonActivate: "Activar",
        .commonDelete: "Eliminar",
        .commonCancel: "Cancelar",
        .commandsAdd: "Añadir entrada",
        .billsAddCta: "Añade tu primera factura",
        .sparenAddCta: "Crear un objetivo de ahorro",
        .overviewAddCta: "Añadir ingresos",
        .commonSave: "Guardar",
        .commonSaved: "Guardado",
        .commonClose: "Cerrar",
        .commonDone: "Hecho",
        .commonShowSampleData: "Mostrar datos de ejemplo",
        .commonHideSampleData: "Ocultar datos de ejemplo",
        .commonEmptyHint: "Aún no se han introducido datos.",
        .commonCopy: "Copiar",
        .commonOptions: "Opciones",
        .commonMoveUp: "Subir",
        .commonMoveDown: "Bajar",
        .monthToday: "Hoy",

        .formName: "Nombre",
        .formAmount: "Importe (CHF)",
        .formStatus: "Estado",
        .formNotes: "Nota",
        .formInvalidAmount: "Introduce un importe válido.",
        .formThirteenthAmount: "Decimotercer salario (importe)",
        .formThirteenthModel: "Modelo de decimotercer salario",
        .incomeBonuses: "Pagos extra",
        .formMonth: "Mes",
        .thirteenthModelSeparate: "Mostrar por separado",
        .thirteenthModelAveraged: "Repartir en 12 meses",
        .formTarget: "Objetivo de ahorro (importe)",
        .formSaved: "Ya ahorrado",
        .formMonthlyContribution: "Aportación mensual",
        .formCategory: "Categoría",
        .formLimitedDuration: "Orden permanente limitada",
        .formLimitedDurationHint: "P. ej. 6 plazos de impuestos: se cuentan solo en esos meses y luego se eliminan automáticamente.",
        .formStartMonth: "Primer plazo",
        .formInstallments: "Número de plazos",
        .planningStandingOrder: "Orden permanente",
        .catRent: "Alquiler",
        .catSubscription: "Suscripción",
        .catLeasing: "Leasing",
        .catUtilities: "Suministros",
        .catTelecom: "Telecomunicaciones",
        .catGroceries: "Alimentación",
        .catFuel: "Combustible",
        .catTransport: "Transporte",
        .catPersonal: "Personal",
        .catDining: "Comer fuera",
        .catHousehold: "Hogar",

        .overviewTitle: "Resumen",
        .overviewAvailableThisMonth: "Disponible este mes",
        .overviewNetIncome: "Ingresos netos este mes",
        .overviewThirteenthSeparate: "Decimotercer salario (por separado)",
        .overviewRecurringFixed: "Costes fijos",
        .overviewPlannedVariable: "Gastos variables",
        .overviewBillsDueThisMonth: "Facturas de este mes",
        .overviewOverdueBills: "Facturas vencidas",
        .overviewSavingsTarget: "Objetivo de ahorro",
        .overviewSecurityStatus: "Estado de seguridad",
        .overviewFormulaExplainer: "Disponible = ingresos netos − costes fijos − presupuestos variables − facturas pendientes de este mes − facturas vencidas. Las facturas pagadas y futuras no reducen el importe.",
        .overviewEmpty: "Introduce ingresos y gastos en Planificación mensual para ver tu resumen.",
        .chartSpendingTitle: "Desglose de este mes",
        .chartByCategory: "Por categoría",

        .planningTitle: "Planificación mensual",
        .planningIncome: "Ingresos",
        .planningFixed: "Costes fijos",
        .planningVariable: "Gastos variables",
        .planningSavings: "Objetivo de ahorro",
        .planningFixedExplainer: "Los costes fijos se repiten cada mes: alquiler, seguros, suscripciones, leasing.",
        .planningVariableExplainer: "Los presupuestos variables los planificas tú: alimentación, combustible, gastos personales.",
        .planningOneOffHint: "Las facturas puntuales se gestionan en «Facturas».",
        .planningEmpty: "Empieza por tus ingresos y luego añade costes fijos y presupuestos.",
        .planningBalance: "Saldo previsto",

        .billsTitle: "Facturas",
        .billsStatusOpen: "Pendiente",
        .billsStatusPaid: "Pagada",
        .billsStateOverdue: "Vencida",
        .billsStateDueThisMonth: "Vence este mes",
        .billsStateFuture: "Futura",
        .billsAffectsBalance: "Reduce el importe disponible",
        .billsNoBalanceImpact: "Sin efecto este mes",
        .billsDueDate: "Fecha de vencimiento",
        .billsProvider: "Proveedor",
        .billsEmpty: "Aún no hay facturas. Las facturas puntuales con fecha de vencimiento aparecerán aquí.",
        .billsMarkPaid: "Marcar como pagada",
        .billsMarkOpen: "Marcar como pendiente",
        .billsOpenTotal: "Total pendiente",

        .navSchulden: "Deudas",
        .schuldenSubtitle: "No pierdas de vista las facturas vencidas y los procedimientos de cobro.",
        .schuldenEmpty: "No hay deudas registradas. Las facturas vencidas aparecen aquí automáticamente, y puedes anotar procedimientos de cobro (Betreibung) o certificados de insolvencia.",
        .schuldenAddCta: "Registrar una deuda",
        .schuldenTotal: "Deuda total",
        .schuldenOverdueBills: "Facturas vencidas",
        .schuldenRecorded: "Deudas registradas",
        .schuldenManagedInBills: "Gestiona las facturas vencidas en «Facturas».",
        .debtTypeOpenClaim: "Reclamación pendiente",
        .debtTypeBetreibung: "Procedimiento de cobro",
        .debtTypePfaendung: "Embargo de salario/bienes",
        .debtTypeVerlustschein: "Certificado de insolvencia",
        .debtTypeOther: "Otra deuda",
        .debtCreditor: "Acreedor",
        .debtReference: "Referencia / n.º de expediente",
        .debtDate: "Fecha",
        .debtType: "Tipo",
        .schuldenGuidanceTitle: "Cómo salir de las deudas",
        .schuldenTipContactTitle: "Contacta pronto",
        .schuldenTipContactBody: "Habla con los acreedores cuanto antes. A menudo es posible un plan de pago a plazos por escrito que evita el procedimiento formal.",
        .schuldenTipBetreibungTitle: "Si comienza el procedimiento",
        .schuldenTipBetreibungBody: "Tras la orden de pago dispones de 20 días para pagar, o de 10 días para presentar una objeción (Rechtsvorschlag) si la reclamación es injustificada.",
        .schuldenTipExistenzminimumTitle: "Tu mínimo vital está protegido",
        .schuldenTipExistenzminimumBody: "En un embargo, tu mínimo vital queda intocable: importe básico, alquiler, seguro de salud y cotizaciones sociales.",
        .schuldenTipVerlustscheinTitle: "Certificado de insolvencia",
        .schuldenTipVerlustscheinBody: "Un certificado de insolvencia prescribe solo a los 20 años. Solo pueden volver a reclamarte cuando tengas nuevos bienes.",
        .schuldenTipCounselingTitle: "Asesoramiento de deudas gratuito",
        .schuldenTipCounselingBody: "Schuldenberatung Schweiz, Caritas y los servicios de asesoría presupuestaria ayudan de forma gratuita y confidencial. Paga primero las deudas con peores consecuencias.",
        .schuldenDisclaimer: "Información general, no asesoramiento jurídico.",
        .schuldenAsFixed: "Como gasto fijo",
        .schuldenAsBill: "Como factura",
        .schuldenAsVariable: "Como presupuesto variable",

        .catInsurance: "Seguros",
        .catOther: "Otros",
        .catMortgage: "Hipoteca",
        .catHealthInsurance: "Seguro de salud",
        .catSerafe: "Radio/TV (Serafe)",
        .catPublicTransport: "Abono de transporte",
        .catChildcare: "Cuidado de niños",
        .catMembership: "Cuotas y membresías",
        .catAlimony: "Pensiones y manutención",
        .catTaxes: "Impuestos",
        .catRatenzahlung: "Pago a plazos",
        .catStreaming: "Streaming",
        .catCreditCard: "Tarjeta de crédito",
        .catClothing: "Ropa",
        .catHealth: "Salud",
        .catLeisure: "Ocio y aficiones",
        .catEntertainment: "Entretenimiento",
        .catChildren: "Niños",
        .catPets: "Mascotas",
        .catGifts: "Regalos",
        .catTravel: "Viajes",
        .catCharity: "Donaciones",
        .catEducation: "Formación",

        .settingsTitle: "Ajustes",
        .settingsLanguage: "Idioma",
        .settingsTheme: "Tema de color",
        .themeSwissRed: "Rojo suizo",
        .themeOrange: "Naranja",
        .themeSand: "Arena",
        .themeGreen: "Verde",
        .themeTeal: "Verde azulado",
        .themeBlue: "Azul",
        .themePurple: "Morado",
        .themePink: "Rosa",
        .settingsData: "Datos",
        .settingsHousehold: "Hogar",
        .settingsCanton: "Cantón",
        .settingsProfile: "Perfil",
        .profileName: "Nombre",
        .profileChoosePicture: "Elegir foto de perfil",
        .profileNoPicture: "Sin foto",
        .profileLocalNote: "Se guarda solo localmente en este dispositivo.",
        .settingsSecurity: "Seguridad",
        .settingsAutoLock: "Bloqueo automático",
        .settingsBiometric: "Desbloqueo biométrico",
        .settingsChangePassphrase: "Cambiar contraseña/PIN",
        .settingsBackup: "Copia de seguridad cifrada",
        .settingsRestore: "Restaurar",
        .settingsPrivacy: "Privacidad",
        .settingsDangerZone: "Zona de peligro",
        .settingsDeleteAll: "Eliminar todos los datos locales",
        .backupCreateTitle: "Crear copia de seguridad cifrada",
        .backupPassphrase: "Contraseña de la copia",
        .backupHint: "Elige una contraseña aparte para la copia. Es necesaria para restaurar: no hay forma de recuperarla.",
        .restorePreview: "Vista previa",
        .restoreConfirm: "Reemplazar todos los datos locales",
        .restoreWarning: "Esto sobrescribe de forma permanente todos los datos locales.",
        .backupInvalid: "Copia no válida o contraseña incorrecta.",
        .backupSavedHint: "Guarda el archivo de la copia y su contraseña en un lugar seguro.",

        .reportTitle: "Informar de un problema",
        .reportSummary: "Resumen",
        .reportExpected: "Comportamiento esperado",
        .reportActual: "Comportamiento real",
        .reportSteps: "Pasos para reproducirlo",
        .reportArea: "Área afectada",
        .reportRedactionNote: "Los datos sensibles se eliminan localmente. Revisa el informe antes de copiarlo.",
        .reportCopyHint: "El informe no se envía automáticamente. Lo copias tú.",

        .exportReport: "Exportar informe",
        .pdfTitle: "Resumen financiero",
        .pdfSubtitle: "Informe personal del hogar",
        .pdfSummary: "De un vistazo",
        .pdfGeneratedOn: "Generado el",
        .pdfConfidential: "Confidencial",
        .pdfPage: "Página",
        .pdfTotal: "Total",
        .pdfColProgress: "Progreso",
        .pdfUnencryptedNote: "El informe es un PDF legible y sin cifrar. Guárdalo en un lugar seguro.",
        .pdfNoData: "Aún no hay datos para exportar.",
        .pdfDefaultHousehold: "Mi hogar",

        .lockTitle: "Bloqueado",
        .lockWelcomeSetup: "Te damos la bienvenida a Kontiva",
        .lockWelcomeBack: "Bienvenido de nuevo",
        .lockSetupTitle: "Definir contraseña",
        .lockEnterPassphrase: "Introduce la contraseña o el PIN",
        .lockWrongPassphrase: "Contraseña incorrecta. Inténtalo de nuevo.",
        .lockRecoveryWarning: "No hay recuperación. Sin tu contraseña no se puede acceder a tus datos.",
        .lockRecoveryAcknowledge: "Entiendo que no hay recuperación.",
        .securityNote: "Tus datos se guardan localmente y cifrados (AES-256-GCM). Sin nube, sin servidor, sin recuperación de contraseña.",

        .onboardingIntroBody: "Kontiva te ayuda a mantener una visión serena del presupuesto de tu hogar suizo, totalmente en este dispositivo.",
        .onboardingStart: "Empezar",
        .onboardingProfileTitle: "Crea un perfil",
        .onboardingProfileBody: "Ponte un nombre y elige una imagen. Ambos se quedan solo en este dispositivo.",
        .onboardingSkip: "Omitir",
        .onboardingFeaturePrivate: "Totalmente local: sin nube, sin seguimiento",
        .onboardingFeatureSecure: "Cifrado con AES-256",
        .onboardingFeatureMoney: "Preciso al céntimo, sin errores de redondeo",
        .onboardingConfirmPassphrase: "Confirmar contraseña",
        .onboardingPassphraseNote: "Anota tu contraseña en un lugar seguro: no se puede restablecer.",
        .backupNudgeText: "Crea una copia de seguridad cifrada. Sin ella, perderás tus datos si olvidas la contraseña.",
        .commonNext: "Siguiente",
        .navMore: "Más",
        .actionLock: "Bloquear",
        .pinSetTitle: "Definir código",
        .pinConfirmTitle: "Confirmar código",
        .pinRequirementNote: "Mín. 6 dígitos · sin recuperación",
        .pinMismatch: "Los códigos no coinciden",
    ]
}
