import Foundation

extension Localization {
    static let sq: [L10nKey: String] = [
        .appName: "Kontiva",
        .appTagline: "Një pamje e qetë dhe private e buxhetit tënd zviceran.",
        .notBetaNotice: "Version i hershëm zhvillimi – jo beta, jo V1.",

        .navOverview: "Përmbledhje",
        .navPlanning: "Plani",
        .navBills: "Faturat",
        .navSettings: "Cilësimet",
        .navReport: "Raporto një problem",
        .navInsights: "Analizat",
        .navSparen: "Kursime",
        .sparenSubtitle: "Kontribute kursimi të rregullta – dhe sa është mbledhur tashmë.",
        .sparenEmpty: "Ende pa qëllime kursimi. Përcakto për çfarë kursen çdo muaj.",
        .sparenMonthlyTotal: "Kursime / muaj",
        .sparenAccumulatedTotal: "Tashmë të kursyera",
        .sparenPerMonth: "/ muaj",
        .sparenContributions: "kontribute",
        .sparenSince: "që nga",
        .sparenOpenEnded: "Pa shumë të synuar",
        .sparenGoalsLabel: "Qëllimet",
        .sparenSortBy: "Rendit",
        .sparenSortStartMonth: "Muaji i fillimit",
        .savingsCatCar: "Makinë",
        .savingsCatVacation: "Pushime",
        .savingsCatHome: "Banesë",
        .savingsCatRetirement: "Shtylla 3a / Pensioni",
        .savingsCatEmergency: "Fond emergjence",
        .savingsCatEducation: "Arsim",
        .savingsCatOther: "Tjetër",
        .savingsCatWedding: "Dasmë",
        .savingsCatFamily: "Familje dhe fëmijë",
        .savingsCatRenovation: "Rinovim dhe mobilim",
        .savingsCatElectronics: "Elektronikë",
        .savingsCatTaxes: "Rezervë për taksat",
        .savingsCatInvestment: "Investime",
        .savingsCatHealth: "Shëndet",
        .savingsCatGift: "Dhurata",
        .overviewPlannedSavings: "Kursime këtë muaj",
        .overviewShowCalculation: "Shfaq llogaritjen",
        .overviewTrendTitle: "Tendenca · 6 muaj",
        .overviewStatusGood: "Tepricë e shëndetshme",
        .overviewStatusTight: "I ngushtë",
        .overviewStatusNegative: "Në minus",
        .overviewAllocationOf: "e të ardhurave neto",
        .formStartDate: "Duke kursyer që nga",
        .formStartingBalance: "Bilanci fillestar (opsional)",
        .insightsSubtitle: "Udhëzime për buxhetin tënd – ku janë paratë dhe ku mund të kursesh.",
        .insightOverspending: "Shpenzon më shumë se sa fiton",
        .insightTightBudget: "Pak hapësirë këtë muaj",
        .insightHealthySurplus: "Tepricë e shëndetshme",
        .insightHighFixed: "Kosto fikse të larta",
        .insightHighHousing: "Kosto të larta banimi",
        .insightLargestFixed: "Blloku më i madh i kostove fikse",
        .insightLargestVariable: "Buxheti më i madh i ndryshueshëm",
        .insightOverdue: "Fatura të vonuara",
        .insightNoSavings: "Ende pa kursime të planifikuara",
        .insightGoodSavings: "Normë e mirë kursimi",
        .insightAllHealthy: "Buxheti yt duket i shëndetshëm",
        .insightHousingHint: "Udhëzim: më së shumti një e treta e të ardhurave",
        .insightNoSavingsDetail: "Ke hapësirë – një qëllim kursimi mund të ndihmojë.",
        .insightAllHealthyDetail: "Asgjë nuk bie në sy. Shto më shumë të dhëna për analiza më të sakta.",
        .fragOfNetIncome: "e të ardhurave neto",
        .fragOfFixedCosts: "e kostove fikse",
        .fragShortfall: "Mungesë",

        .commonAdd: "Shto",
        .commonEdit: "Modifiko",
        .commonActivate: "Aktivizo",
        .commonDelete: "Fshi",
        .commonCancel: "Anulo",
        .commandsAdd: "Shto hyrje",
        .billsAddCta: "Shto faturën tënde të parë",
        .sparenAddCta: "Krijo një qëllim kursimi",
        .overviewAddCta: "Shto të ardhura",
        .commonSave: "Ruaj",
        .commonSaved: "U ruajt",
        .commonClose: "Mbyll",
        .commonDone: "U krye",
        .commonShowSampleData: "Shfaq të dhëna shembull",
        .commonHideSampleData: "Fshih të dhëna shembull",
        .commonEmptyHint: "Ende pa të dhëna të futura.",
        .commonCopy: "Kopjo",
        .commonOptions: "Opsione",
        .commonMoveUp: "Lëviz lart",
        .commonMoveDown: "Lëviz poshtë",
        .monthToday: "Sot",

        .formName: "Emri",
        .formAmount: "Shuma (CHF)",
        .formStatus: "Statusi",
        .formNotes: "Shënim",
        .formInvalidAmount: "Fut një shumë të vlefshme.",
        .formThirteenthAmount: "Paga e 13-të (shuma)",
        .formThirteenthModel: "Modeli i pagës së 13-të",
        .thirteenthModelSeparate: "Shfaq veçmas",
        .thirteenthModelAveraged: "Shpërndaj në 12 muaj",
        .formTarget: "Qëllimi i kursimit (shuma)",
        .formSaved: "Tashmë të kursyera",
        .formMonthlyContribution: "Kontributi mujor",
        .formCategory: "Kategoria",
        .formLimitedDuration: "Urdhërpagesë e përhershme e kufizuar",
        .formLimitedDurationHint: "P.sh. 6 këste taksash – numërohen vetëm në ato muaj dhe pastaj hiqen automatikisht.",
        .formStartMonth: "Kësti i parë",
        .formInstallments: "Numri i kësteve",
        .planningStandingOrder: "Urdhërpagesë e përhershme",
        .catRent: "Qira",
        .catSubscription: "Abonim",
        .catLeasing: "Lizing",
        .catUtilities: "Shërbime (ujë, energji)",
        .catTelecom: "Telekomunikacion",
        .catGroceries: "Ushqime",
        .catFuel: "Karburant",
        .catTransport: "Transport",
        .catPersonal: "Personale",
        .catDining: "Ngrënie jashtë",
        .catHousehold: "Shtëpiake",

        .overviewTitle: "Përmbledhje",
        .overviewAvailableThisMonth: "E disponueshme këtë muaj",
        .overviewNetIncome: "Të ardhura neto këtë muaj",
        .overviewThirteenthSeparate: "Paga e 13-të (veçmas)",
        .overviewRecurringFixed: "Kosto fikse",
        .overviewPlannedVariable: "Shpenzime të ndryshueshme",
        .overviewBillsDueThisMonth: "Faturat e këtij muaji",
        .overviewOverdueBills: "Fatura të vonuara",
        .overviewSavingsTarget: "Qëllimi i kursimit",
        .overviewSecurityStatus: "Statusi i sigurisë",
        .overviewFormulaExplainer: "E disponueshme = të ardhura neto − kosto fikse − buxhete të ndryshueshme − fatura të hapura këtë muaj − fatura të vonuara. Faturat e paguara dhe të ardhshme nuk e ulin shumën.",
        .overviewEmpty: "Fut të ardhura dhe kosto te Planifikimi mujor për të parë përmbledhjen.",
        .chartSpendingTitle: "Shpërndarja këtë muaj",
        .chartByCategory: "Sipas kategorisë",

        .planningTitle: "Planifikimi mujor",
        .planningIncome: "Të ardhura",
        .planningFixed: "Kosto fikse",
        .planningVariable: "Shpenzime të ndryshueshme",
        .planningSavings: "Qëllimi i kursimit",
        .planningFixedExplainer: "Kostot fikse përsëriten çdo muaj: qira, sigurime, abonime, lizing.",
        .planningVariableExplainer: "Buxhetet e ndryshueshme i planifikon vetë: ushqime, karburant, shpenzime personale.",
        .planningOneOffHint: "Faturat një herëshe menaxhohen te „Faturat”.",
        .planningEmpty: "Fillo me të ardhurat e tua, pastaj shto kosto fikse dhe buxhete.",
        .planningBalance: "Bilanci i planifikuar",

        .billsTitle: "Faturat",
        .billsStatusOpen: "E hapur",
        .billsStatusPaid: "E paguar",
        .billsStateOverdue: "E vonuar",
        .billsStateDueThisMonth: "Skadon këtë muaj",
        .billsStateFuture: "E ardhshme",
        .billsAffectsBalance: "Ul shumën e disponueshme",
        .billsNoBalanceImpact: "Pa efekt këtë muaj",
        .billsDueDate: "Data e skadimit",
        .billsProvider: "Ofruesi",
        .billsEmpty: "Ende pa fatura. Faturat një herëshe me datë skadimi shfaqen këtu.",
        .billsMarkPaid: "Shëno si të paguar",
        .billsMarkOpen: "Shëno si të hapur",
        .billsOpenTotal: "Totali i hapur",

        .navSchulden: "Borxhet",
        .schuldenSubtitle: "Mbaj nën vëzhgim faturat e vonuara dhe përmbarimin.",
        .schuldenEmpty: "Pa borxhe të regjistruara. Faturat e vonuara shfaqen këtu automatikisht – dhe mund të shënosh përmbarim (Betreibung) ose çertifikata humbjeje.",
        .schuldenAddCta: "Regjistro një borxh",
        .schuldenTotal: "Borxhi total",
        .schuldenOverdueBills: "Fatura të vonuara",
        .schuldenRecorded: "Borxhe të regjistruara",
        .schuldenManagedInBills: "Menaxho faturat e vonuara te „Faturat”.",
        .debtTypeOpenClaim: "Kërkesë e hapur",
        .debtTypeBetreibung: "Përmbarim",
        .debtTypePfaendung: "Sekuestrim page/pasurie",
        .debtTypeVerlustschein: "Çertifikatë humbjeje",
        .debtTypeOther: "Borxh tjetër",
        .debtCreditor: "Kreditor",
        .debtReference: "Referencë / nr. dosjeje",
        .debtDate: "Data",
        .debtType: "Lloji",
        .schuldenGuidanceTitle: "Si të dalësh nga borxhet",
        .schuldenTipContactTitle: "Kontakto herët",
        .schuldenTipContactBody: "Fol herët me kreditorët. Një plan pagese me këste me shkrim është shpesh i mundur dhe shmang procedurën formale.",
        .schuldenTipBetreibungTitle: "Nëse fillon përmbarimi",
        .schuldenTipBetreibungBody: "Pas urdhrit të pagesës ke 20 ditë për të paguar – ose 10 ditë për të bërë kundërshtim (Rechtsvorschlag), nëse kërkesa është e pabazuar.",
        .schuldenTipExistenzminimumTitle: "Minimumi yt jetik është i mbrojtur",
        .schuldenTipExistenzminimumBody: "Në një sekuestrim, minimumi yt jetik mbetet i paprekshëm – shuma bazë, qiraja, sigurimi shëndetësor dhe kontributet sociale.",
        .schuldenTipVerlustscheinTitle: "Çertifikatë humbjeje",
        .schuldenTipVerlustscheinBody: "Një çertifikatë humbjeje parashkruhet vetëm pas 20 vjetësh. Mund të ndiqesh sërish vetëm kur fiton pasuri të re.",
        .schuldenTipCounselingTitle: "Këshillim falas për borxhet",
        .schuldenTipCounselingBody: "Schuldenberatung Schweiz, Caritas dhe këshillimi buxhetor ndihmojnë falas dhe me konfidencialitet. Paguaj së pari borxhet me pasojat më të rënda.",
        .schuldenDisclaimer: "Informacion i përgjithshëm, jo këshillë ligjore.",

        .catInsurance: "Sigurim",
        .catOther: "Tjetër",
        .catMortgage: "Kredi hipotekare",
        .catHealthInsurance: "Sigurim shëndetësor",
        .catSerafe: "Radio/TV (Serafe)",
        .catPublicTransport: "Abonim transporti",
        .catChildcare: "Kujdesi për fëmijët",
        .catMembership: "Anëtarësime",
        .catAlimony: "Pension ushqimor",
        .catTaxes: "Taksa",
        .catClothing: "Veshje",
        .catHealth: "Shëndet",
        .catLeisure: "Kohë e lirë dhe hobi",
        .catEntertainment: "Argëtim",
        .catChildren: "Fëmijë",
        .catPets: "Kafshë shtëpiake",
        .catGifts: "Dhurata",
        .catTravel: "Udhëtime",
        .catCharity: "Bamirësi",
        .catEducation: "Arsim",

        .settingsTitle: "Cilësimet",
        .settingsLanguage: "Gjuha",
        .settingsTheme: "Tema e ngjyrave",
        .themeSwissRed: "E kuqe zvicerane",
        .themeOrange: "Portokalli",
        .themeSand: "Rëra",
        .themeGreen: "Jeshile",
        .themeTeal: "Bruz",
        .themeBlue: "Blu",
        .themePurple: "Vjollcë",
        .themePink: "Rozë",
        .settingsData: "Të dhënat",
        .settingsHousehold: "Familja",
        .settingsCanton: "Kantoni",
        .settingsProfile: "Profili",
        .profileName: "Emri",
        .profileChoosePicture: "Zgjidh foton e profilit",
        .profileNoPicture: "Pa foto",
        .profileLocalNote: "Ruhet vetëm lokalisht në këtë pajisje.",
        .settingsSecurity: "Siguria",
        .settingsAutoLock: "Kyçje automatike",
        .settingsBiometric: "Shkyçje biometrike",
        .settingsChangePassphrase: "Ndrysho fjalëkalimin/PIN-in",
        .settingsBackup: "Kopje rezervë e enkriptuar",
        .settingsRestore: "Rikthe",
        .settingsPrivacy: "Privatësia",
        .settingsDangerZone: "Zonë e rrezikshme",
        .settingsDeleteAll: "Fshi të gjitha të dhënat lokale",
        .backupCreateTitle: "Krijo kopje rezervë të enkriptuar",
        .backupPassphrase: "Fjalëkalimi i kopjes rezervë",
        .backupHint: "Zgjidh një fjalëkalim të veçantë për kopjen rezervë. Kërkohet për rikthim – fjalëkalimi nuk mund të rikuperohet.",
        .restorePreview: "Pamje paraprake",
        .restoreConfirm: "Zëvendëso të gjitha të dhënat lokale",
        .restoreWarning: "Kjo mbishkruan përgjithmonë të gjitha të dhënat lokale.",
        .backupInvalid: "Kopje rezervë e pavlefshme ose fjalëkalim i gabuar.",
        .backupSavedHint: "Ruaje skedarin e kopjes rezervë dhe fjalëkalimin në një vend të sigurt.",

        .reportTitle: "Raporto një problem",
        .reportSummary: "Përmbledhje",
        .reportExpected: "Sjellja e pritur",
        .reportActual: "Sjellja aktuale",
        .reportSteps: "Hapat për riprodhim",
        .reportArea: "Zona e prekur",
        .reportRedactionNote: "Të dhënat e ndjeshme hiqen lokalisht. E shqyrton raportin para se ta kopjosh.",
        .reportCopyHint: "Raporti nuk dërgohet automatikisht. E kopjon vetë.",

        .exportReport: "Eksporto raportin",
        .pdfTitle: "Përmbledhje financiare",
        .pdfSubtitle: "Raport personal i familjes",
        .pdfSummary: "Me një shikim",
        .pdfGeneratedOn: "Gjeneruar më",
        .pdfConfidential: "Konfidenciale",
        .pdfPage: "Faqja",
        .pdfTotal: "Totali",
        .pdfColProgress: "Përparimi",
        .pdfUnencryptedNote: "Raporti është një PDF i lexueshëm, i paenkriptuar. Ruaje në një vend të sigurt.",
        .pdfNoData: "Ende pa të dhëna për eksport.",
        .pdfDefaultHousehold: "Familja ime",

        .lockTitle: "I kyçur",
        .lockWelcomeSetup: "Mirë se vjen te Kontiva",
        .lockWelcomeBack: "Mirë se erdhe sërish",
        .lockSetupTitle: "Cakto fjalëkalimin",
        .lockEnterPassphrase: "Fut fjalëkalimin ose PIN-in",
        .lockWrongPassphrase: "Fjalëkalim i gabuar. Provo sërish.",
        .lockRecoveryWarning: "Nuk ka rikuperim. Pa fjalëkalimin tënd, të dhënat e tua nuk mund të aksesohen.",
        .lockRecoveryAcknowledge: "E kuptoj që nuk ka rikuperim.",
        .securityNote: "Të dhënat e tua ruhen lokalisht dhe të enkriptuara (AES-256-GCM). Pa re, pa server, pa rikuperim fjalëkalimi.",

        .onboardingIntroBody: "Kontiva të ndihmon të kesh një pamje të qetë mbi buxhetin e familjes tënde zvicerane – krejtësisht në këtë pajisje.",
        .onboardingStart: "Fillo",
        .onboardingProfileTitle: "Krijo një profil",
        .onboardingProfileBody: "Vendos një emër dhe zgjidh një foto. Të dyja mbeten vetëm në këtë pajisje.",
        .onboardingSkip: "Anashkalo",
        .onboardingFeaturePrivate: "Krejtësisht lokale – pa re, pa gjurmim",
        .onboardingFeatureSecure: "E enkriptuar me AES-256",
        .onboardingFeatureMoney: "E saktë deri në centim, pa gabime rrumbullakimi",
        .onboardingConfirmPassphrase: "Konfirmo fjalëkalimin",
        .onboardingPassphraseNote: "Shkruaje fjalëkalimin diku të sigurt – nuk mund të rivendoset.",
        .backupNudgeText: "Krijo një kopje rezervë të enkriptuar. Pa të, i humbet të dhënat nëse harron fjalëkalimin.",
        .commonNext: "Tjetra",
        .navMore: "Më shumë",
        .actionLock: "Kyç",
        .pinSetTitle: "Cakto kodin",
        .pinConfirmTitle: "Konfirmo kodin",
        .pinRequirementNote: "Min. 6 shifra · pa rikuperim",
        .pinMismatch: "Kodet nuk përputhen",
    ]
}
