import Foundation

// NOTE: Rumantsch Grischun. Best-effort machine-assisted translation —
// flagged as the highest priority for native-speaker review. Swiss-specific
// terms (Serafe, Betreibung, Pilaster 3a) kept close to the German source.
extension Localization {
    static let rm: [L10nKey: String] = [
        .appName: "Kontiva",
        .appTagline: "Ina survista quieta e privata da tes budget svizzer.",
        .notBetaNotice: "Versiun da svilup precoz – betg beta, betg V1.",

        .navOverview: "Survista",
        .navPlanning: "Plan",
        .navBills: "Quints",
        .navSettings: "Parameters",
        .navReport: "Rapportar in problem",
        .navInsights: "Invistas",
        .navSparen: "Spargn",
        .sparenSubtitle: "Contribuziuns da spargn regularas – e quai ch'è gia rimnà.",
        .sparenEmpty: "Anc nagins finamiras da spargn. Definescha per tge che ti spargnas mintga mais.",
        .sparenMonthlyTotal: "Spargn / mais",
        .sparenAccumulatedTotal: "Gia spargnà",
        .sparenPerMonth: "/ mais",
        .sparenContributions: "contribuziuns",
        .sparenSince: "dapi",
        .sparenOpenEnded: "Senza summa finala",
        .sparenGoalsLabel: "Finamiras",
        .sparenSortBy: "Zavrar",
        .sparenSortStartMonth: "Mais da partenza",
        .savingsCatCar: "Auto",
        .savingsCatVacation: "Vacanzas",
        .savingsCatHome: "Abitar",
        .savingsCatRetirement: "Pilaster 3a / Pensiun",
        .savingsCatEmergency: "Reserva d'urgenza",
        .savingsCatEducation: "Furmaziun",
        .savingsCatOther: "Auter",
        .savingsCatWedding: "Nozzas",
        .savingsCatFamily: "Famiglia ed uffants",
        .savingsCatRenovation: "Renovaziun ed indriz",
        .savingsCatElectronics: "Electronica",
        .savingsCatTaxes: "Reserva per taglias",
        .savingsCatInvestment: "Investiziuns",
        .savingsCatHealth: "Sanadad",
        .savingsCatGift: "Regals",
        .overviewPlannedSavings: "Spargn quest mais",
        .overviewShowCalculation: "Mussar il quint",
        .overviewTrendTitle: "Tendenza · 6 mais",
        .overviewStatusGood: "Surpli san",
        .overviewStatusTight: "Stretg",
        .overviewStatusNegative: "En minus",
        .overviewAllocationOf: "da l'entrada netta",
        .formStartDate: "Spargna dapi",
        .formStartingBalance: "Bilantsch da partenza (facultativ)",
        .insightsSubtitle: "Cussegls per tes budget – nua ch'è tes daners e nua che ti pos spargnar.",
        .insightOverspending: "Ti spendas dapli che ti gudognas",
        .insightTightBudget: "Pauc spazi quest mais",
        .insightHealthySurplus: "Surpli san",
        .insightHighFixed: "Auts custs fixs",
        .insightHighHousing: "Auts custs d'abitar",
        .insightLargestFixed: "La pli gronda posiziun dals custs fixs",
        .insightLargestVariable: "Il pli grond budget variabel",
        .insightOverdue: "Quints scrudads",
        .insightNoSavings: "Anc nagin spargn planisà",
        .insightGoodSavings: "Buna quota da spargn",
        .insightAllHealthy: "Tes budget para san",
        .insightHousingHint: "Recumandaziun: il pli ferm in terz da l'entrada",
        .insightNoSavingsDetail: "Ti has spazi – ina finamira da spargn pudess gidar.",
        .insightAllHealthyDetail: "Nagut sa distingua. Agiunta dapli datas per invistas pli precisas.",
        .insightExtraIncome: "Entrada supplementara quest mais",
        .insightGoalProgress: "Object da spargn a la portada",
        .insightBillsDueSoon: "Anc da pajar quest mais",
        .insightGettingStarted: "Ans laschain entschaiver",
        .insightGettingStartedDetail: "Agiunta tia entrada per vesair tias analisas persunalas.",
        .schuldenEncourageTitle: "Pass per pass",
        .schuldenEncourageBody: "Ti la fas frunt. Qua èn ils proxims pass concrets.",
        .fragOfNetIncome: "da l'entrada netta",
        .fragOfFixedCosts: "dals custs fixs",
        .fragShortfall: "Mancanza",

        .commonAdd: "Agiuntar",
        .commonEdit: "Modifitgar",
        .commonActivate: "Activar",
        .commonDelete: "Stizzar",
        .commonCancel: "Interrumper",
        .commandsAdd: "Agiuntar endataziun",
        .billsAddCta: "Agiunta tes emprim quint",
        .sparenAddCta: "Crear ina finamira da spargn",
        .overviewAddCta: "Agiuntar entrada",
        .commonSave: "Memorisar",
        .commonSaved: "Memorisà",
        .commonClose: "Serrar",
        .commonDone: "Finì",
        .commonShowSampleData: "Mussar datas d'exempel",
        .commonHideSampleData: "Zuppentar datas d'exempel",
        .commonEmptyHint: "Anc naginas datas endatadas.",
        .commonCopy: "Copiar",
        .commonOptions: "Opziuns",
        .commonMoveUp: "Spustar ensi",
        .commonMoveDown: "Spustar engiu",
        .monthToday: "Oz",

        .formName: "Num",
        .formAmount: "Summa (CHF)",
        .formStatus: "Status",
        .formNotes: "Annotaziun",
        .formInvalidAmount: "Endatescha ina summa valaivla.",
        .formThirteenthAmount: "13avla pajaglia (summa)",
        .formThirteenthModel: "Model da la 13avla pajaglia",
        .incomeBonuses: "Pajaments supplementars",
        .formMonth: "Mais",
        .thirteenthModelSeparate: "Mussar separà",
        .thirteenthModelAveraged: "Repartir sin 12 mais",
        .formTarget: "Finamira da spargn (summa)",
        .formSaved: "Gia spargnà",
        .formMonthlyContribution: "Contribuziun mensila",
        .formCategory: "Categoria",
        .formLimitedDuration: "Urden permanent limità",
        .formLimitedDurationHint: "P.ex. 6 ratas da taglia – quintadas mo en quels mais e silsuenter allontanadas automaticamain.",
        .formStartMonth: "Emprima rata",
        .formInstallments: "Dumber da ratas",
        .planningStandingOrder: "Urden permanent",
        .catRent: "Fittanza",
        .catSubscription: "Abunament",
        .catLeasing: "Leasing",
        .catUtilities: "Provediment (aua, electricitad)",
        .catTelecom: "Telecommunicaziun",
        .catGroceries: "Victualias",
        .catFuel: "Carburant",
        .catTransport: "Transport",
        .catPersonal: "Persunal",
        .catDining: "Mangiar ordadora",
        .catHousehold: "Chasada",

        .overviewTitle: "Survista",
        .overviewAvailableThisMonth: "Disponibel quest mais",
        .overviewNetIncome: "Entrada netta quest mais",
        .overviewThirteenthSeparate: "13avla pajaglia (separà)",
        .overviewRecurringFixed: "Custs fixs",
        .overviewPlannedVariable: "Expensas variablas",
        .overviewBillsDueThisMonth: "Quints quest mais",
        .overviewOverdueBills: "Quints scrudads",
        .overviewSavingsTarget: "Finamira da spargn",
        .overviewSecurityStatus: "Status da segirezza",
        .overviewFormulaExplainer: "Disponibel = entrada netta − custs fixs − budgets variabels − quints averts quest mais − quints scrudads. Quints pajads e futurs na reduceschan betg la summa.",
        .overviewEmpty: "Endatescha entradas e custs en la Planisaziun mensila per vesair tia survista.",
        .chartSpendingTitle: "Repartiziun quest mais",
        .chartByCategory: "Tenor categoria",

        .planningTitle: "Planisaziun mensila",
        .planningIncome: "Entrada",
        .planningFixed: "Custs fixs",
        .planningVariable: "Expensas variablas",
        .planningSavings: "Finamira da spargn",
        .planningFixedExplainer: "Ils custs fixs sa repetan mintga mais: fittanza, assicuranzas, abunaments, leasing.",
        .planningVariableExplainer: "Ils budgets variabels planiseschas ti svess: victualias, carburant, expensas persunalas.",
        .planningOneOffHint: "Quints unics vegnan administrads sut «Quints».",
        .planningEmpty: "Cumenza cun tia entrada, agiunta lura custs fixs e budgets.",
        .planningBalance: "Bilantsch planisà",

        .billsTitle: "Quints",
        .billsStatusOpen: "Avert",
        .billsStatusPaid: "Pajà",
        .billsStateOverdue: "Scrudà",
        .billsStateDueThisMonth: "Scada quest mais",
        .billsStateFuture: "Futur",
        .billsAffectsBalance: "Reducescha la summa disponibla",
        .billsNoBalanceImpact: "Nagin effect quest mais",
        .billsDueDate: "Data da scadenza",
        .billsProvider: "Purschider",
        .billsEmpty: "Anc nagins quints. Quints unics cun data da scadenza vegnan mussads qua.",
        .billsMarkPaid: "Marcar sco pajà",
        .billsMarkOpen: "Marcar sco avert",
        .billsOpenTotal: "Total avert",

        .navSchulden: "Debits",
        .schuldenSubtitle: "Tegna en egl ils quints scrudads e l'execuziun.",
        .schuldenEmpty: "Nagins debits registrads. Quints scrudads vegnan mussads qua automaticamain – e ti pos notar ina execuziun (Betreibung) u attestats da perdita.",
        .schuldenAddCta: "Registrar in debit",
        .schuldenTotal: "Debit total",
        .schuldenOverdueBills: "Quints scrudads",
        .schuldenRecorded: "Debits registrads",
        .schuldenManagedInBills: "Administrescha ils quints scrudads sut «Quints».",
        .debtTypeOpenClaim: "Pretensiun averta",
        .debtTypeBetreibung: "Execuziun",
        .debtTypePfaendung: "Impegnaziun da pajaglia/facultad",
        .debtTypeVerlustschein: "Attestat da perdita",
        .debtTypeOther: "Auter debit",
        .debtCreditor: "Crediter",
        .debtReference: "Referenza / nr. da dossier",
        .debtDate: "Data",
        .debtType: "Tip",
        .schuldenGuidanceTitle: "Sortida dals debits",
        .schuldenTipContactTitle: "Contactescha baud",
        .schuldenTipContactBody: "Discurra baud cun ils crediters. In plan da pajament a ratas en scrit è savens pussaivel ed evitescha l'execuziun formala.",
        .schuldenTipBetreibungTitle: "Sche l'execuziun cumenza",
        .schuldenTipBetreibungBody: "Suenter il cumond da pajament has ti 20 dis per pajar – u 10 dis per far opposiziun (Rechtsvorschlag), sche la pretensiun n'è betg giustifitgada.",
        .schuldenTipExistenzminimumTitle: "Tes minimum existenzial è protegì",
        .schuldenTipExistenzminimumBody: "Tar ina impegnaziun resta tes minimum existenzial intatg – summa da basa, fittanza, assicuranza da malsauns e contribuziuns socialas.",
        .schuldenTipVerlustscheinTitle: "Attestat da perdita",
        .schuldenTipVerlustscheinBody: "In attestat da perdita scada pir suenter 20 onns. Ti pos vegnir persequità danovamain mo sche ti acquistas nova facultad.",
        .schuldenTipCounselingTitle: "Cussegliaziun da debits gratuita",
        .schuldenTipCounselingBody: "Schuldenberatung Schweiz, Caritas e la cussegliaziun da budget gidan gratuitamain e confidenzialmain. Paja l'emprim ils debits cun las consequenzas las pli gravas.",
        .schuldenDisclaimer: "Infurmaziun generala, betg cussegliaziun giuridica.",

        .catInsurance: "Assicuranza",
        .catOther: "Auter",
        .catMortgage: "Ipoteca",
        .catHealthInsurance: "Assicuranza da malsauns",
        .catSerafe: "Radio/TV (Serafe)",
        .catPublicTransport: "Abunament da traffic",
        .catChildcare: "Tgira d'uffants",
        .catMembership: "Commembranzas",
        .catAlimony: "Alimentaziun",
        .catTaxes: "Taglias",
        .catClothing: "Vestgadira",
        .catHealth: "Sanadad",
        .catLeisure: "Temp liber e hobbis",
        .catEntertainment: "Divertiment",
        .catChildren: "Uffants",
        .catPets: "Animals da chasa",
        .catGifts: "Regals",
        .catTravel: "Viadis",
        .catCharity: "Donaziuns",
        .catEducation: "Furmaziun",

        .settingsTitle: "Parameters",
        .settingsLanguage: "Lingua",
        .settingsTheme: "Tema da colur",
        .themeSwissRed: "Cotschen svizzer",
        .themeOrange: "Oransch",
        .themeSand: "Sablun",
        .themeGreen: "Verd",
        .themeTeal: "Verd-blau",
        .themeBlue: "Blau",
        .themePurple: "Purpur",
        .themePink: "Rosa",
        .settingsData: "Datas",
        .settingsHousehold: "Chasada",
        .settingsCanton: "Chantun",
        .settingsProfile: "Profil",
        .profileName: "Num",
        .profileChoosePicture: "Tscherner maletg da profil",
        .profileNoPicture: "Nagin maletg",
        .profileLocalNote: "Memorisà mo localmain sin quest apparat.",
        .settingsSecurity: "Segirezza",
        .settingsAutoLock: "Serra automatica",
        .settingsBiometric: "Sbloccar biometric",
        .settingsChangePassphrase: "Midar pled-clav/PIN",
        .settingsBackup: "Copia da segirezza criptada",
        .settingsRestore: "Restaurar",
        .settingsPrivacy: "Protecziun da datas",
        .settingsDangerZone: "Zona privlusa",
        .settingsDeleteAll: "Stizzar tut las datas localas",
        .backupCreateTitle: "Crear ina copia da segirezza criptada",
        .backupPassphrase: "Pled-clav da la copia da segirezza",
        .backupHint: "Tscherna in pled-clav separà per la copia da segirezza. El è necessari per restaurar – el na po betg vegnir recuperà.",
        .restorePreview: "Prevista",
        .restoreConfirm: "Remplazzar tut las datas localas",
        .restoreWarning: "Quai surscriva permanentamain tut las datas localas.",
        .backupInvalid: "Copia da segirezza nunvalaivla u pled-clav fauss.",
        .backupSavedHint: "Tegna la datoteca da segirezza ed il pled-clav en in lieu segir.",

        .reportTitle: "Rapportar in problem",
        .reportSummary: "Resumaziun",
        .reportExpected: "Cumportament spetgà",
        .reportActual: "Cumportament real",
        .reportSteps: "Pass per reproducir",
        .reportArea: "Sectur pertutgà",
        .reportRedactionNote: "Datas sensiblas vegnan allontanadas localmain. Ti controlleschas il rapport avant che copiar.",
        .reportCopyHint: "Il rapport na vegn betg tramess automaticamain. Ti al copieschas svess.",

        .exportReport: "Exportar rapport",
        .pdfTitle: "Survista finanziala",
        .pdfSubtitle: "Rapport persunal da chasada",
        .pdfSummary: "Cun in'egliada",
        .pdfGeneratedOn: "Generà ils",
        .pdfConfidential: "Confidenzial",
        .pdfPage: "Pagina",
        .pdfTotal: "Total",
        .pdfColProgress: "Progress",
        .pdfUnencryptedNote: "Il rapport è in PDF legibel e betg criptà. Tegna el en in lieu segir.",
        .pdfNoData: "Anc naginas datas per exportar.",
        .pdfDefaultHousehold: "Mia chasada",

        .lockTitle: "Serrà",
        .lockWelcomeSetup: "Bainvegni tar Kontiva",
        .lockWelcomeBack: "Bainvegni enavos",
        .lockSetupTitle: "Definir in pled-clav",
        .lockEnterPassphrase: "Endatescha pled-clav u PIN",
        .lockWrongPassphrase: "Pled-clav fauss. Emprova danovamain.",
        .lockRecoveryWarning: "I na dat nagina recuperaziun. Senza tes pled-clav na pon tias datas betg vegnir cuntanschidas.",
        .lockRecoveryAcknowledge: "Jau chapesch ch'i na dat nagina recuperaziun.",
        .securityNote: "Tias datas vegnan memorisadas localmain e criptadas (AES-256-GCM). Nagin cloud, nagin server, nagina recuperaziun da pled-clav.",

        .onboardingIntroBody: "Kontiva ta gida da mantegnair ina survista quieta sin il budget da tia chasada svizra – cumplettamain sin quest apparat.",
        .onboardingStart: "Cumenzar",
        .onboardingProfileTitle: "Crear in profil",
        .onboardingProfileBody: "Dat a ti in num e tscherna in maletg. Omadus restan mo sin quest apparat.",
        .onboardingSkip: "Sursiglir",
        .onboardingFeaturePrivate: "Cumplettamain local – nagin cloud, nagin fil",
        .onboardingFeatureSecure: "Criptà cun AES-256",
        .onboardingFeatureMoney: "Exact fin al centesim, senza errurs d'arrotundament",
        .onboardingConfirmPassphrase: "Confermar pled-clav",
        .onboardingPassphraseNote: "Nota tes pled-clav en in lieu segir – el na po betg vegnir reinizialisà.",
        .backupNudgeText: "Crea ina copia da segirezza criptada. Senza ella perdas ti tias datas sche ti emblidas il pled-clav.",
        .commonNext: "Vinavant",
        .navMore: "Dapli",
        .actionLock: "Serrar",
        .pinSetTitle: "Definir il code",
        .pinConfirmTitle: "Confermar il code",
        .pinRequirementNote: "Almain 6 cifras · nagina recuperaziun",
        .pinMismatch: "Ils codes na correspundan betg",
    ]
}
