import Foundation

extension Localization {
    static let ja: [L10nKey: String] = [
        .appName: "Kontiva",
        .appTagline: "スイスの家計を、静かでプライベートに見渡す。",
        .notBetaNotice: "初期開発版 — ベータでも V1 でもありません。",

        .navOverview: "概要",
        .navPlanning: "月次プラン",
        .navBills: "請求書",
        .navSettings: "設定",
        .navReport: "問題を報告",
        .navInsights: "分析",
        .navSparen: "貯蓄",
        .sparenSubtitle: "定期的な貯蓄の積み立てと、すでに貯まった金額。",
        .sparenEmpty: "まだ貯蓄目標がありません。毎月何のために貯めるか決めましょう。",
        .sparenMonthlyTotal: "貯蓄 / 月",
        .sparenAccumulatedTotal: "貯蓄済み",
        .sparenPerMonth: "/ 月",
        .sparenContributions: "回の積み立て",
        .sparenSince: "開始",
        .sparenOpenEnded: "目標金額なし",
        .sparenGoalsLabel: "目標",
        .savingsCatCar: "車",
        .savingsCatVacation: "休暇",
        .savingsCatHome: "住まい",
        .savingsCatRetirement: "第3の柱 3a / 年金",
        .savingsCatEmergency: "緊急予備資金",
        .savingsCatEducation: "教育",
        .savingsCatOther: "その他",
        .savingsCatWedding: "結婚式",
        .savingsCatFamily: "家族と子ども",
        .savingsCatRenovation: "リフォームと家具",
        .savingsCatElectronics: "電子機器",
        .savingsCatTaxes: "税金の備え",
        .savingsCatInvestment: "投資",
        .savingsCatHealth: "健康",
        .savingsCatGift: "贈り物",
        .overviewPlannedSavings: "今月の貯蓄",
        .overviewShowCalculation: "計算を表示",
        .overviewTrendTitle: "推移 · 6か月",
        .overviewStatusGood: "健全な余剰",
        .overviewStatusTight: "ぎりぎり",
        .overviewStatusNegative: "赤字",
        .overviewAllocationOf: "手取り収入のうち",
        .formStartDate: "貯蓄開始",
        .formStartingBalance: "開始残高（任意）",
        .insightsSubtitle: "家計のためのガイド — お金がどこにあり、どこで節約できるか。",
        .insightOverspending: "収入より支出が多くなっています",
        .insightTightBudget: "今月は余裕が少なめ",
        .insightHealthySurplus: "健全な余剰",
        .insightHighFixed: "固定費が高い",
        .insightHighHousing: "住居費が高い",
        .insightLargestFixed: "固定費で最大の項目",
        .insightLargestVariable: "最大の変動予算",
        .insightOverdue: "支払期限を過ぎた請求",
        .insightNoSavings: "まだ貯蓄が計画されていません",
        .insightGoodSavings: "良好な貯蓄率",
        .insightAllHealthy: "家計は健全に見えます",
        .insightHousingHint: "目安：収入の最大3分の1",
        .insightNoSavingsDetail: "余裕があります — 貯蓄目標が役立つかもしれません。",
        .insightAllHealthyDetail: "目立つ点はありません。データを追加するとより精密な分析が得られます。",
        .fragOfNetIncome: "手取り収入のうち",
        .fragOfFixedCosts: "固定費のうち",
        .fragShortfall: "不足",

        .commonAdd: "追加",
        .commonEdit: "編集",
        .commonDelete: "削除",
        .commonCancel: "キャンセル",
        .commandsAdd: "項目を追加",
        .billsAddCta: "最初の請求書を追加",
        .sparenAddCta: "貯蓄目標を作成",
        .overviewAddCta: "収入を追加",
        .commonSave: "保存",
        .commonSaved: "保存しました",
        .commonClose: "閉じる",
        .commonDone: "完了",
        .commonShowSampleData: "サンプルデータを表示",
        .commonHideSampleData: "サンプルデータを非表示",
        .commonEmptyHint: "まだデータが入力されていません。",
        .commonCopy: "コピー",
        .commonOptions: "オプション",
        .commonMoveUp: "上に移動",
        .commonMoveDown: "下に移動",
        .monthToday: "今日",

        .formName: "名前",
        .formAmount: "金額 (CHF)",
        .formStatus: "状態",
        .formNotes: "メモ",
        .formInvalidAmount: "有効な金額を入力してください。",
        .formThirteenthAmount: "13か月目の給与（金額）",
        .formThirteenthModel: "13か月目の給与の方式",
        .thirteenthModelSeparate: "個別に表示",
        .thirteenthModelAveraged: "12か月に分散",
        .formTarget: "貯蓄目標（金額）",
        .formSaved: "貯蓄済み",
        .formMonthlyContribution: "毎月の積み立て",
        .formCategory: "カテゴリ",
        .formLimitedDuration: "期間限定の自動振込",
        .formLimitedDurationHint: "例：税金の6回払い — その月のみ計上し、その後自動的に削除されます。",
        .formStartMonth: "初回",
        .formInstallments: "回数",
        .planningStandingOrder: "自動振込",
        .catRent: "家賃",
        .catSubscription: "定期購読",
        .catLeasing: "リース",
        .catUtilities: "光熱費",
        .catTelecom: "通信",
        .catGroceries: "食料品",
        .catFuel: "燃料",
        .catTransport: "交通",
        .catPersonal: "個人",
        .catDining: "外食",
        .catHousehold: "家庭",

        .overviewTitle: "概要",
        .overviewAvailableThisMonth: "今月の利用可能額",
        .overviewNetIncome: "今月の手取り収入",
        .overviewThirteenthSeparate: "13か月目の給与（個別）",
        .overviewRecurringFixed: "固定費",
        .overviewPlannedVariable: "変動支出",
        .overviewBillsDueThisMonth: "今月の未払い請求",
        .overviewOverdueBills: "支払期限を過ぎた請求",
        .overviewSavingsTarget: "貯蓄目標",
        .overviewSecurityStatus: "セキュリティ状態",
        .overviewFormulaExplainer: "利用可能額 = 手取り収入 − 固定費 − 変動予算 − 今月の未払い請求 − 支払期限を過ぎた請求。支払済みおよび将来の請求は金額を減らしません。",
        .overviewEmpty: "「月次プラン」で収入と支出を入力すると概要が表示されます。",
        .chartSpendingTitle: "今月の内訳",
        .chartByCategory: "カテゴリ別",

        .planningTitle: "月次プラン",
        .planningIncome: "収入",
        .planningFixed: "固定費",
        .planningVariable: "変動支出",
        .planningSavings: "貯蓄目標",
        .planningFixedExplainer: "固定費は毎月繰り返されます：家賃、保険、定期購読、リース。",
        .planningVariableExplainer: "変動予算は自分で計画します：食料品、燃料、個人的な支出。",
        .planningOneOffHint: "一度きりの請求は「請求書」で管理します。",
        .planningEmpty: "収入から始めて、固定費と予算を追加しましょう。",
        .planningBalance: "計画残高",

        .billsTitle: "請求書",
        .billsStatusOpen: "未払い",
        .billsStatusPaid: "支払済み",
        .billsStateOverdue: "期限超過",
        .billsStateDueThisMonth: "今月が期限",
        .billsStateFuture: "将来",
        .billsAffectsBalance: "利用可能額を減らします",
        .billsNoBalanceImpact: "今月は影響なし",
        .billsDueDate: "支払期限",
        .billsProvider: "提供者",
        .billsEmpty: "まだ請求書がありません。支払期限のある一度きりの請求はここに表示されます。",
        .billsMarkPaid: "支払済みにする",
        .billsMarkOpen: "未払いにする",
        .billsOpenTotal: "未払い合計",

        .navSchulden: "負債",
        .schuldenSubtitle: "支払期限を過ぎた請求と強制取立てを把握しましょう。",
        .schuldenEmpty: "記録された負債はありません。期限超過の請求はここに自動表示されます — 強制取立て (Betreibung) や損失証明書も記録できます。",
        .schuldenAddCta: "負債を記録",
        .schuldenTotal: "負債総額",
        .schuldenOverdueBills: "支払期限を過ぎた請求",
        .schuldenRecorded: "記録された負債",
        .schuldenManagedInBills: "期限超過の請求は「請求書」で管理します。",
        .debtTypeOpenClaim: "未決済の債権",
        .debtTypeBetreibung: "強制取立て",
        .debtTypePfaendung: "給与・財産の差押え",
        .debtTypeVerlustschein: "損失証明書",
        .debtTypeOther: "その他の負債",
        .debtCreditor: "債権者",
        .debtReference: "参照 / 案件番号",
        .debtDate: "日付",
        .debtType: "種類",
        .schuldenGuidanceTitle: "負債から抜け出す道",
        .schuldenTipContactTitle: "早めに連絡を",
        .schuldenTipContactBody: "早めに債権者と話しましょう。書面での分割払い計画はしばしば可能で、正式な手続きを避けられます。",
        .schuldenTipBetreibungTitle: "取立てが始まったら",
        .schuldenTipBetreibungBody: "支払命令の後、支払いに20日間 — 請求が不当な場合は異議申立て (Rechtsvorschlag) に10日間あります。",
        .schuldenTipExistenzminimumTitle: "あなたの最低生活費は守られます",
        .schuldenTipExistenzminimumBody: "差押え時も最低生活費は手をつけられません — 基礎額、家賃、健康保険、社会保険料。",
        .schuldenTipVerlustscheinTitle: "損失証明書",
        .schuldenTipVerlustscheinBody: "損失証明書は20年後にようやく時効になります。新たな資産を得たときにのみ再び請求される可能性があります。",
        .schuldenTipCounselingTitle: "無料の負債相談",
        .schuldenTipCounselingBody: "Schuldenberatung Schweiz、Caritas、家計相談は無料かつ秘密厳守で支援します。まず最も影響の大きい負債から返済しましょう。",
        .schuldenDisclaimer: "一般的な情報であり、法的助言ではありません。",

        .catInsurance: "保険",
        .catOther: "その他",
        .catMortgage: "住宅ローン",
        .catHealthInsurance: "健康保険",
        .catSerafe: "放送受信料 (Serafe)",
        .catPublicTransport: "定期券",
        .catChildcare: "保育",
        .catMembership: "会費",
        .catAlimony: "扶養費",
        .catTaxes: "税金",
        .catClothing: "衣類",
        .catHealth: "健康",
        .catLeisure: "余暇と趣味",
        .catEntertainment: "娯楽",
        .catChildren: "子ども",
        .catPets: "ペット",
        .catGifts: "贈り物",
        .catTravel: "旅行",
        .catCharity: "寄付",
        .catEducation: "教育",

        .settingsTitle: "設定",
        .settingsLanguage: "言語",
        .settingsTheme: "カラーテーマ",
        .themeSwissRed: "スイスレッド",
        .themeOrange: "オレンジ",
        .themeSand: "サンド",
        .themeGreen: "グリーン",
        .themeTeal: "ティール",
        .themeBlue: "ブルー",
        .themePurple: "パープル",
        .themePink: "ピンク",
        .settingsData: "データ",
        .settingsHousehold: "世帯",
        .settingsCanton: "州（カントン）",
        .settingsProfile: "プロフィール",
        .profileName: "名前",
        .profileChoosePicture: "プロフィール画像を選択",
        .profileNoPicture: "画像なし",
        .profileLocalNote: "このデバイスにのみローカル保存されます。",
        .settingsSecurity: "セキュリティ",
        .settingsAutoLock: "自動ロック",
        .settingsChangePassphrase: "パスワード/PIN を変更",
        .settingsBackup: "暗号化バックアップ",
        .settingsRestore: "復元",
        .settingsPrivacy: "プライバシー",
        .settingsDangerZone: "危険な操作",
        .settingsDeleteAll: "すべてのローカルデータを削除",
        .backupCreateTitle: "暗号化バックアップを作成",
        .backupPassphrase: "バックアップのパスワード",
        .backupHint: "バックアップには別のパスワードを選びましょう。復元に必要です — パスワードは復元できません。",
        .restorePreview: "プレビュー",
        .restoreConfirm: "すべてのローカルデータを置き換え",
        .restoreWarning: "これはすべてのローカルデータを完全に上書きします。",
        .backupInvalid: "バックアップが無効か、パスワードが違います。",
        .backupSavedHint: "バックアップファイルとパスワードは安全な場所に保管してください。",

        .reportTitle: "問題を報告",
        .reportSummary: "概要",
        .reportExpected: "期待される動作",
        .reportActual: "実際の動作",
        .reportSteps: "再現手順",
        .reportArea: "影響範囲",
        .reportRedactionNote: "機微なデータはローカルで除去されます。コピー前にレポートを確認します。",
        .reportCopyHint: "レポートは自動送信されません。自分でコピーします。",

        .exportReport: "レポートを書き出す",
        .pdfTitle: "財務概要",
        .pdfSubtitle: "個人の家計レポート",
        .pdfSummary: "ひと目で",
        .pdfGeneratedOn: "作成日",
        .pdfConfidential: "機密",
        .pdfPage: "ページ",
        .pdfTotal: "合計",
        .pdfColProgress: "進捗",
        .pdfUnencryptedNote: "レポートは読み取り可能な暗号化されていない PDF です。安全な場所に保管してください。",
        .pdfNoData: "まだ書き出すデータがありません。",
        .pdfDefaultHousehold: "わが家",

        .lockTitle: "ロック中",
        .lockWelcomeSetup: "Kontiva へようこそ",
        .lockWelcomeBack: "おかえりなさい",
        .lockSetupTitle: "パスワードを設定",
        .lockEnterPassphrase: "パスワードまたは PIN を入力",
        .lockWrongPassphrase: "パスワードが違います。もう一度お試しください。",
        .lockRecoveryWarning: "復元はできません。パスワードがないとデータにアクセスできません。",
        .lockRecoveryAcknowledge: "復元できないことを理解しました。",
        .securityNote: "データはローカルに暗号化して保存されます (AES-256-GCM)。クラウドなし、サーバーなし、パスワード復元なし。",

        .onboardingIntroBody: "Kontiva はスイスの家計を静かに見渡す手助けをします — すべてこのデバイス上で。",
        .onboardingStart: "始める",
        .onboardingProfileTitle: "プロフィールを作成",
        .onboardingProfileBody: "名前を付けて画像を選びましょう。どちらもこのデバイスにのみ残ります。",
        .onboardingSkip: "スキップ",
        .onboardingFeaturePrivate: "完全にローカル — クラウドなし、追跡なし",
        .onboardingFeatureSecure: "AES-256 で暗号化",
        .onboardingFeatureMoney: "サンチーム単位まで正確、丸め誤差なし",
        .onboardingConfirmPassphrase: "パスワードを確認",
        .onboardingPassphraseNote: "パスワードは安全な場所に書き留めてください — リセットできません。",
        .backupNudgeText: "暗号化バックアップを作成しましょう。これがないと、パスワードを忘れた場合にデータを失います。",
        .commonNext: "次へ",
        .navMore: "その他",
        .actionLock: "ロック",
    ]
}
