import Foundation

// Sinhala. Best-effort — flagged as a high priority for native-speaker review.
extension Localization {
    static let si: [L10nKey: String] = [
        .appName: "Kontiva",
        .appTagline: "ඔබේ ස්විස් අයවැය පිළිබඳ සන්සුන්, පෞද්ගලික දැක්මක්.",
        .notBetaNotice: "මුල් අදියර සංස්කරණයකි – බීටා නොවේ, V1 නොවේ.",

        .navOverview: "දළ විශ්ලේෂණය",
        .navPlanning: "මාසික සැලසුම",
        .navBills: "බිල්පත්",
        .navSettings: "සැකසීම්",
        .navReport: "ගැටලුවක් වාර්තා කරන්න",
        .navInsights: "විශ්ලේෂණ",
        .navSparen: "ඉතිරිකිරීම්",
        .sparenSubtitle: "නිතිපතා ඉතිරිකිරීමේ දායකත්ව – සහ දැනටමත් එකතු වූ මුදල.",
        .sparenEmpty: "තවම ඉතිරිකිරීමේ ඉලක්ක නැත. සෑම මසකම ඔබ කුමක් සඳහා ඉතිරි කරනවාද යන්න තීරණය කරන්න.",
        .sparenMonthlyTotal: "ඉතිරිකිරීම් / මස",
        .sparenAccumulatedTotal: "දැනටමත් ඉතිරි කළ",
        .sparenPerMonth: "/ මස",
        .sparenContributions: "දායකත්ව",
        .sparenSince: "සිට",
        .sparenOpenEnded: "ඉලක්ක මුදලක් නැත",
        .sparenGoalsLabel: "ඉලක්ක",
        .savingsCatCar: "මෝටර් රථය",
        .savingsCatVacation: "නිවාඩුව",
        .savingsCatHome: "නිවාස",
        .savingsCatRetirement: "කණුව 3a / විශ්‍රාම වැටුප",
        .savingsCatEmergency: "හදිසි අරමුදල",
        .savingsCatEducation: "අධ්‍යාපනය",
        .savingsCatOther: "වෙනත්",
        .savingsCatWedding: "විවාහ මංගල්‍යය",
        .savingsCatFamily: "පවුල සහ දරුවන්",
        .savingsCatRenovation: "අලුත්වැඩියාව සහ සැරසිලි",
        .savingsCatElectronics: "ඉලෙක්ට්‍රොනික උපකරණ",
        .savingsCatTaxes: "බදු සඳහා වෙන්කිරීම",
        .savingsCatInvestment: "ආයෝජන",
        .savingsCatHealth: "සෞඛ්‍යය",
        .savingsCatGift: "තෑගි",
        .overviewPlannedSavings: "මෙම මස ඉතිරිකිරීම්",
        .overviewShowCalculation: "ගණනය පෙන්වන්න",
        .overviewTrendTitle: "ප්‍රවණතාව · මාස 6",
        .overviewStatusGood: "සෞඛ්‍ය සම්පන්න අතිරික්තය",
        .overviewStatusTight: "තද",
        .overviewStatusNegative: "හිඟයෙහි",
        .overviewAllocationOf: "ශුද්ධ ආදායමෙන්",
        .formStartDate: "ඉතිරිකරන සිට",
        .formStartingBalance: "ආරම්භක ශේෂය (විකල්ප)",
        .insightsSubtitle: "ඔබේ අයවැය සඳහා මඟපෙන්වීම – ඔබේ මුදල කොහෙද සහ කොතැනින් ඉතිරි කළ හැකිද.",
        .insightOverspending: "ඔබ උපයනවාට වඩා වැය කරයි",
        .insightTightBudget: "මෙම මස ඉඩ අඩුයි",
        .insightHealthySurplus: "සෞඛ්‍ය සම්පන්න අතිරික්තය",
        .insightHighFixed: "ඉහළ ස්ථාවර වියදම්",
        .insightHighHousing: "ඉහළ නිවාස වියදම්",
        .insightLargestFixed: "ස්ථාවර වියදම්වල විශාලතම කොටස",
        .insightLargestVariable: "විශාලතම විචල්‍ය අයවැය",
        .insightOverdue: "කල් ඉකුත් වූ බිල්පත්",
        .insightNoSavings: "තවම ඉතිරිකිරීම් සැලසුම් කර නැත",
        .insightGoodSavings: "හොඳ ඉතිරිකිරීමේ අනුපාතය",
        .insightAllHealthy: "ඔබේ අයවැය සෞඛ්‍ය සම්පන්නව පෙනේ",
        .insightHousingHint: "මඟපෙන්වීම: ආදායමෙන් උපරිම තුනෙන් එකක්",
        .insightNoSavingsDetail: "ඔබට ඉඩ ඇත – ඉතිරිකිරීමේ ඉලක්කයක් උපකාරී විය හැක.",
        .insightAllHealthyDetail: "කිසිවක් කැපී පෙනෙන්නේ නැත. තියුණු විශ්ලේෂණ සඳහා වැඩි දත්ත එක් කරන්න.",
        .fragOfNetIncome: "ශුද්ධ ආදායමෙන්",
        .fragOfFixedCosts: "ස්ථාවර වියදම්වලින්",
        .fragShortfall: "හිඟය",

        .commonAdd: "එක් කරන්න",
        .commonEdit: "සංස්කරණය",
        .commonDelete: "මකන්න",
        .commonCancel: "අවලංගු කරන්න",
        .commandsAdd: "ඇතුළත්කිරීමක් එක් කරන්න",
        .billsAddCta: "ඔබේ පළමු බිල්පත එක් කරන්න",
        .sparenAddCta: "ඉතිරිකිරීමේ ඉලක්කයක් සාදන්න",
        .overviewAddCta: "ආදායම එක් කරන්න",
        .commonSave: "සුරකින්න",
        .commonSaved: "සුරැකිණි",
        .commonClose: "වසන්න",
        .commonDone: "අවසන්",
        .commonShowSampleData: "නියැදි දත්ත පෙන්වන්න",
        .commonHideSampleData: "නියැදි දත්ත සඟවන්න",
        .commonEmptyHint: "තවම දත්ත ඇතුළත් කර නැත.",
        .commonCopy: "පිටපත් කරන්න",
        .commonOptions: "විකල්ප",
        .commonMoveUp: "ඉහළට ගෙනයන්න",
        .commonMoveDown: "පහළට ගෙනයන්න",
        .monthToday: "අද",

        .formName: "නම",
        .formAmount: "මුදල (CHF)",
        .formStatus: "තත්ත්වය",
        .formNotes: "සටහන",
        .formInvalidAmount: "වලංගු මුදලක් ඇතුළත් කරන්න.",
        .formThirteenthAmount: "13වන මස වැටුප (මුදල)",
        .formThirteenthModel: "13වන මස වැටුප් ආකෘතිය",
        .thirteenthModelSeparate: "වෙන වෙනම පෙන්වන්න",
        .thirteenthModelAveraged: "මාස 12කට බෙදන්න",
        .formTarget: "ඉතිරිකිරීමේ ඉලක්කය (මුදල)",
        .formSaved: "දැනටමත් ඉතිරි කළ",
        .formMonthlyContribution: "මාසික දායකත්වය",
        .formCategory: "ප්‍රවර්ගය",
        .formLimitedDuration: "සීමිත කාල ස්ථාවර නියෝගය",
        .formLimitedDurationHint: "උදා: බදු වාරික 6ක් – එම මාසවල පමණක් ගණන් ගෙන පසුව ස්වයංක්‍රීයව ඉවත් වේ.",
        .formStartMonth: "පළමු වාරිකය",
        .formInstallments: "වාරික ගණන",
        .planningStandingOrder: "ස්ථාවර නියෝගය",
        .catRent: "කුලිය",
        .catSubscription: "දායකත්වය",
        .catLeasing: "බදු දීම",
        .catUtilities: "උපයෝගිතා (ජලය, විදුලිය)",
        .catTelecom: "විදුලි සංදේශ",
        .catGroceries: "සිල්ලර බඩු",
        .catFuel: "ඉන්ධන",
        .catTransport: "ප්‍රවාහනය",
        .catPersonal: "පෞද්ගලික",
        .catDining: "පිටත ආහාර",
        .catHousehold: "ගෘහස්ථ",

        .overviewTitle: "දළ විශ්ලේෂණය",
        .overviewAvailableThisMonth: "මෙම මස ලබා ගත හැකි",
        .overviewNetIncome: "මෙම මස ශුද්ධ ආදායම",
        .overviewThirteenthSeparate: "13වන මස වැටුප (වෙනම)",
        .overviewRecurringFixed: "ස්ථාවර වියදම්",
        .overviewPlannedVariable: "විචල්‍ය වියදම්",
        .overviewBillsDueThisMonth: "මෙම මස හිඟ බිල්පත්",
        .overviewOverdueBills: "කල් ඉකුත් වූ බිල්පත්",
        .overviewSavingsTarget: "ඉතිරිකිරීමේ ඉලක්කය",
        .overviewSecurityStatus: "ආරක්ෂක තත්ත්වය",
        .overviewFormulaExplainer: "ලබා ගත හැකි = ශුද්ධ ආදායම − ස්ථාවර වියදම් − විචල්‍ය අයවැය − මෙම මස හිඟ බිල්පත් − කල් ඉකුත් වූ බිල්පත්. ගෙවූ සහ අනාගත බිල්පත් මුදල අඩු නොකරයි.",
        .overviewEmpty: "ඔබේ දළ විශ්ලේෂණය බැලීමට මාසික සැලසුමෙහි ආදායම සහ වියදම් ඇතුළත් කරන්න.",
        .chartSpendingTitle: "මෙම මස බෙදා හැරීම",
        .chartByCategory: "ප්‍රවර්ගය අනුව",

        .planningTitle: "මාසික සැලසුම",
        .planningIncome: "ආදායම",
        .planningFixed: "ස්ථාවර වියදම්",
        .planningVariable: "විචල්‍ය වියදම්",
        .planningSavings: "ඉතිරිකිරීමේ ඉලක්කය",
        .planningFixedExplainer: "ස්ථාවර වියදම් සෑම මසකම පුනරාවර්තනය වේ: කුලිය, රක්ෂණ, දායකත්ව, බදු දීම.",
        .planningVariableExplainer: "විචල්‍ය අයවැය ඔබම සැලසුම් කරයි: සිල්ලර බඩු, ඉන්ධන, පෞද්ගලික වියදම්.",
        .planningOneOffHint: "එක්වරක් බිල්පත් „බිල්පත්” තුළ කළමනාකරණය වේ.",
        .planningEmpty: "ඔබේ ආදායමෙන් ආරම්භ කර, පසුව ස්ථාවර වියදම් සහ අයවැය එක් කරන්න.",
        .planningBalance: "සැලසුම් කළ ශේෂය",

        .billsTitle: "බිල්පත්",
        .billsStatusOpen: "හිඟ",
        .billsStatusPaid: "ගෙවා ඇත",
        .billsStateOverdue: "කල් ඉකුත්",
        .billsStateDueThisMonth: "මෙම මස ගෙවිය යුතු",
        .billsStateFuture: "අනාගත",
        .billsAffectsBalance: "ලබා ගත හැකි මුදල අඩු කරයි",
        .billsNoBalanceImpact: "මෙම මස බලපෑමක් නැත",
        .billsDueDate: "ගෙවිය යුතු දිනය",
        .billsProvider: "සපයන්නා",
        .billsEmpty: "තවම බිල්පත් නැත. ගෙවිය යුතු දිනයක් සහිත එක්වරක් බිල්පත් මෙහි පෙන්වයි.",
        .billsMarkPaid: "ගෙවූ ලෙස ලකුණු කරන්න",
        .billsMarkOpen: "හිඟ ලෙස ලකුණු කරන්න",
        .billsOpenTotal: "මුළු හිඟය",

        .navSchulden: "ණය",
        .schuldenSubtitle: "කල් ඉකුත් වූ බිල්පත් සහ බලහත්කාර අයකරගැනීම නිරීක්ෂණය කරන්න.",
        .schuldenEmpty: "වාර්තා කළ ණය නැත. කල් ඉකුත් වූ බිල්පත් මෙහි ස්වයංක්‍රීයව පෙන්වයි – තවද බලහත්කාර අයකරගැනීම (Betreibung) හෝ පාඩු සහතික සටහන් කළ හැක.",
        .schuldenAddCta: "ණයක් වාර්තා කරන්න",
        .schuldenTotal: "මුළු ණය",
        .schuldenOverdueBills: "කල් ඉකුත් වූ බිල්පත්",
        .schuldenRecorded: "වාර්තා කළ ණය",
        .schuldenManagedInBills: "කල් ඉකුත් වූ බිල්පත් „බිල්පත්” තුළ කළමනාකරණය කරන්න.",
        .debtTypeOpenClaim: "හිඟ ඉල්ලීම",
        .debtTypeBetreibung: "බලහත්කාර අයකරගැනීම",
        .debtTypePfaendung: "වැටුප්/දේපළ සීරුමාරුව",
        .debtTypeVerlustschein: "පාඩු සහතිකය",
        .debtTypeOther: "වෙනත් ණය",
        .debtCreditor: "ණයහිමියා",
        .debtReference: "යොමුව / නඩු අංකය",
        .debtDate: "දිනය",
        .debtType: "වර්ගය",
        .schuldenGuidanceTitle: "ණයෙන් මිදීමේ මඟ",
        .schuldenTipContactTitle: "කල් තබා සම්බන්ධ වන්න",
        .schuldenTipContactBody: "ණයහිමියන් සමඟ කල් තබා කතා කරන්න. ලිඛිත වාරික ගෙවීමේ සැලැස්මක් බොහෝ විට හැකි අතර විධිමත් ක්‍රියාමාර්ග වළක්වයි.",
        .schuldenTipBetreibungTitle: "අයකරගැනීම ආරම්භ වුවහොත්",
        .schuldenTipBetreibungBody: "ගෙවීමේ නියෝගයෙන් පසු ගෙවීමට දින 20ක් – හෝ ඉල්ලීම අසාධාරණ නම් විරෝධතාවක් (Rechtsvorschlag) ඉදිරිපත් කිරීමට දින 10ක් ඇත.",
        .schuldenTipExistenzminimumTitle: "ඔබේ අවම ජීවන වියදම ආරක්ෂිතයි",
        .schuldenTipExistenzminimumBody: "සීරුමාරුවකදී ඔබේ අවම ජීවන වියදම ස්පර්ශ නොවී පවතී – මූලික මුදල, කුලිය, සෞඛ්‍ය රක්ෂණය සහ සමාජ දායකත්ව.",
        .schuldenTipVerlustscheinTitle: "පාඩු සහතිකය",
        .schuldenTipVerlustscheinBody: "පාඩු සහතිකය වසර 20කට පසුව පමණක් කල් ඉකුත් වේ. නව වත්කම් ලැබූ විට පමණක් නැවත අයකරගත හැක.",
        .schuldenTipCounselingTitle: "නොමිලේ ණය උපදේශනය",
        .schuldenTipCounselingBody: "Schuldenberatung Schweiz, Caritas සහ අයවැය උපදේශනය නොමිලේ සහ රහසිගතව උපකාර කරයි. වඩාත් බරපතල ප්‍රතිවිපාක ඇති ණය මුලින් ගෙවන්න.",
        .schuldenDisclaimer: "සාමාන්‍ය තොරතුරු, නීති උපදෙස් නොවේ.",

        .catInsurance: "රක්ෂණය",
        .catOther: "වෙනත්",
        .catMortgage: "නිවාස ණය",
        .catHealthInsurance: "සෞඛ්‍ය රක්ෂණය",
        .catSerafe: "ගුවන්විදුලි/රූපවාහිනී (Serafe)",
        .catPublicTransport: "ගමන් බලපත්‍රය",
        .catChildcare: "ළමා රැකවරණය",
        .catMembership: "සාමාජික ගාස්තු",
        .catAlimony: "නඩත්තු දීමනා",
        .catTaxes: "බදු",
        .catClothing: "ඇඳුම්",
        .catHealth: "සෞඛ්‍යය",
        .catLeisure: "විවේකය සහ විනෝදාංශ",
        .catEntertainment: "විනෝදාස්වාදය",
        .catChildren: "දරුවන්",
        .catPets: "සුරතල් සතුන්",
        .catGifts: "තෑගි",
        .catTravel: "සංචාර",
        .catCharity: "පරිත්‍යාග",
        .catEducation: "අධ්‍යාපනය",

        .settingsTitle: "සැකසීම්",
        .settingsLanguage: "භාෂාව",
        .settingsTheme: "වර්ණ තේමාව",
        .themeSwissRed: "ස්විස් රතු",
        .themeOrange: "තැඹිලි",
        .themeSand: "වැලි",
        .themeGreen: "කොළ",
        .themeTeal: "නිල්-කොළ",
        .themeBlue: "නිල්",
        .themePurple: "දම්",
        .themePink: "රෝස",
        .settingsData: "දත්ත",
        .settingsHousehold: "ගෘහස්ථය",
        .settingsCanton: "කැන්ටනය",
        .settingsProfile: "පැතිකඩ",
        .profileName: "නම",
        .profileChoosePicture: "පැතිකඩ පින්තූරය තෝරන්න",
        .profileNoPicture: "පින්තූරයක් නැත",
        .profileLocalNote: "මෙම උපාංගයේ පමණක් දේශීයව සුරැකේ.",
        .settingsSecurity: "ආරක්ෂාව",
        .settingsAutoLock: "ස්වයංක්‍රීය අගුල",
        .settingsChangePassphrase: "මුරපදය/PIN වෙනස් කරන්න",
        .settingsBackup: "සංකේතාත්මක උපස්ථය",
        .settingsRestore: "ප්‍රතිස්ථාපනය",
        .settingsPrivacy: "පෞද්ගලිකත්වය",
        .settingsDangerZone: "අවදානම් කලාපය",
        .settingsDeleteAll: "සියලු දේශීය දත්ත මකන්න",
        .backupCreateTitle: "සංකේතාත්මක උපස්ථයක් සාදන්න",
        .backupPassphrase: "උපස්ථ මුරපදය",
        .backupHint: "උපස්ථය සඳහා වෙනම මුරපදයක් තෝරන්න. ප්‍රතිස්ථාපනය සඳහා එය අවශ්‍යයි – මුරපදය ප්‍රතිසාධනය කළ නොහැක.",
        .restorePreview: "පෙරදසුන",
        .restoreConfirm: "සියලු දේශීය දත්ත ප්‍රතිස්ථාපනය කරන්න",
        .restoreWarning: "මෙය සියලු දේශීය දත්ත ස්ථිරවම උඩින් ලියයි.",
        .backupInvalid: "වලංගු නොවන උපස්ථයක් හෝ වැරදි මුරපදය.",
        .backupSavedHint: "උපස්ථ ගොනුව සහ මුරපදය ආරක්ෂිත ස්ථානයක තබන්න.",

        .reportTitle: "ගැටලුවක් වාර්තා කරන්න",
        .reportSummary: "සාරාංශය",
        .reportExpected: "අපේක්ෂිත හැසිරීම",
        .reportActual: "සැබෑ හැසිරීම",
        .reportSteps: "නැවත ඇතිකිරීමේ පියවර",
        .reportArea: "බලපෑමට ලක් වූ ප්‍රදේශය",
        .reportRedactionNote: "සංවේදී දත්ත දේශීයව ඉවත් කෙරේ. පිටපත් කිරීමට පෙර ඔබ වාර්තාව සමාලෝචනය කරයි.",
        .reportCopyHint: "වාර්තාව ස්වයංක්‍රීයව නොයැවේ. ඔබම එය පිටපත් කරයි.",

        .exportReport: "වාර්තාව නිර්යාත කරන්න",
        .pdfTitle: "මූල්‍ය දළ විශ්ලේෂණය",
        .pdfSubtitle: "පෞද්ගලික ගෘහස්ථ වාර්තාව",
        .pdfSummary: "එක් බැල්මකින්",
        .pdfGeneratedOn: "ජනනය කළේ",
        .pdfConfidential: "රහස්‍ය",
        .pdfPage: "පිටුව",
        .pdfTotal: "එකතුව",
        .pdfColProgress: "ප්‍රගතිය",
        .pdfUnencryptedNote: "වාර්තාව කියවිය හැකි, සංකේතනය නොකළ PDF එකකි. එය ආරක්ෂිත ස්ථානයක තබන්න.",
        .pdfNoData: "තවම නිර්යාත කිරීමට දත්ත නැත.",
        .pdfDefaultHousehold: "මගේ ගෘහස්ථය",

        .lockTitle: "අගුළු දමා ඇත",
        .lockWelcomeSetup: "Kontiva වෙත සාදරයෙන් පිළිගනිමු",
        .lockWelcomeBack: "නැවත සාදරයෙන් පිළිගනිමු",
        .lockSetupTitle: "මුරපදය සකසන්න",
        .lockEnterPassphrase: "මුරපදය හෝ PIN ඇතුළත් කරන්න",
        .lockWrongPassphrase: "වැරදි මුරපදය. නැවත උත්සාහ කරන්න.",
        .lockRecoveryWarning: "ප්‍රතිසාධනයක් නැත. ඔබේ මුරපදය නොමැතිව ඔබේ දත්ත වෙත ප්‍රවේශ විය නොහැක.",
        .lockRecoveryAcknowledge: "ප්‍රතිසාධනයක් නොමැති බව මම තේරුම් ගනිමි.",
        .securityNote: "ඔබේ දත්ත දේශීයව සහ සංකේතනය කර සුරැකේ (AES-256-GCM). වලාකුළක් නැත, සේවාදායකයක් නැත, මුරපද ප්‍රතිසාධනයක් නැත.",

        .onboardingIntroBody: "Kontiva ඔබට ඔබේ ස්විස් ගෘහස්ථ අයවැය සන්සුන්ව බැලීමට උපකාර කරයි – සම්පූර්ණයෙන්ම මෙම උපාංගයේ.",
        .onboardingStart: "ආරම්භ කරන්න",
        .onboardingProfileTitle: "පැතිකඩක් සාදන්න",
        .onboardingProfileBody: "ඔබටම නමක් දී පින්තූරයක් තෝරන්න. දෙකම මෙම උපාංගයේ පමණක් රැඳේ.",
        .onboardingSkip: "මඟ හරින්න",
        .onboardingFeaturePrivate: "සම්පූර්ණයෙන්ම දේශීය – වලාකුළක් නැත, ලුහුබැඳීමක් නැත",
        .onboardingFeatureSecure: "AES-256 මඟින් සංකේතනය",
        .onboardingFeatureMoney: "සෙන්ටිම් දක්වා නිවැරදියි, වටකිරීමේ දෝෂ නැත",
        .onboardingConfirmPassphrase: "මුරපදය තහවුරු කරන්න",
        .onboardingPassphraseNote: "ඔබේ මුරපදය ආරක්ෂිත ස්ථානයක ලියන්න – එය යළි පිහිටුවිය නොහැක.",
        .backupNudgeText: "සංකේතාත්මක උපස්ථයක් සාදන්න. එය නොමැතිව, මුරපදය අමතක වුවහොත් ඔබේ දත්ත නැති වේ.",
        .commonNext: "ඊළඟ",
        .navMore: "තවත්",
        .actionLock: "අගුළු දමන්න",
        .pinSetTitle: "කේතය සකසන්න",
        .pinConfirmTitle: "කේතය තහවුරු කරන්න",
        .pinRequirementNote: "අවම අංක 6 · ප්‍රතිසාධනයක් නැත",
        .pinMismatch: "කේත නොගැලපේ",
    ]
}
