import Foundation

// Modern Standard Arabic (RTL). Swiss-specific terms (Serafe, Betreibung,
// Säule 3a) kept close to the source where no standard Arabic term exists.
extension Localization {
    static let ar: [L10nKey: String] = [
        .appName: "Kontiva",
        .appTagline: "نظرة هادئة وخاصة على ميزانيتك السويسرية.",
        .notBetaNotice: "إصدار تطوير مبكر – ليس بيتا، وليس V1.",

        .navOverview: "نظرة عامة",
        .navPlanning: "التخطيط",
        .navBills: "الفواتير",
        .navSettings: "الإعدادات",
        .navReport: "الإبلاغ عن مشكلة",
        .navInsights: "رؤى",
        .navSparen: "المدخرات",
        .sparenSubtitle: "مساهمات ادخار منتظمة – وما تم جمعه بالفعل.",
        .sparenEmpty: "لا توجد أهداف ادخار بعد. حدد ما تدّخر من أجله كل شهر.",
        .sparenMonthlyTotal: "ادخار / شهر",
        .sparenAccumulatedTotal: "تم ادخاره بالفعل",
        .sparenPerMonth: "/ شهر",
        .sparenContributions: "مساهمات",
        .sparenSince: "منذ",
        .sparenOpenEnded: "بدون مبلغ مستهدف",
        .sparenGoalsLabel: "الأهداف",
        .sparenSortBy: "ترتيب",
        .sparenSortStartMonth: "شهر البدء",
        .savingsCatCar: "سيارة",
        .savingsCatVacation: "إجازة",
        .savingsCatHome: "السكن",
        .savingsCatRetirement: "الركيزة 3a / التقاعد",
        .savingsCatEmergency: "صندوق الطوارئ",
        .savingsCatEducation: "التعليم",
        .savingsCatOther: "أخرى",
        .savingsCatWedding: "زفاف",
        .savingsCatFamily: "العائلة والأطفال",
        .savingsCatRenovation: "التجديد والتأثيث",
        .savingsCatElectronics: "إلكترونيات",
        .savingsCatTaxes: "احتياطي الضرائب",
        .savingsCatInvestment: "استثمارات",
        .savingsCatHealth: "الصحة",
        .savingsCatGift: "هدايا",
        .overviewPlannedSavings: "ادخار هذا الشهر",
        .overviewShowCalculation: "إظهار الحساب",
        .overviewTrendTitle: "الاتجاه · 6 أشهر",
        .overviewStatusGood: "فائض صحي",
        .overviewStatusTight: "ضيّق",
        .overviewStatusNegative: "في العجز",
        .overviewAllocationOf: "من صافي الدخل",
        .formStartDate: "يدّخر منذ",
        .formStartingBalance: "الرصيد الافتتاحي (اختياري)",
        .insightsSubtitle: "إرشادات حول ميزانيتك – أين أموالك وأين يمكنك التوفير.",
        .insightOverspending: "تنفق أكثر مما تكسب",
        .insightTightBudget: "مساحة قليلة هذا الشهر",
        .insightHealthySurplus: "فائض صحي",
        .insightHighFixed: "تكاليف ثابتة مرتفعة",
        .insightHighHousing: "تكاليف سكن مرتفعة",
        .insightLargestFixed: "أكبر بند في التكاليف الثابتة",
        .insightLargestVariable: "أكبر ميزانية متغيرة",
        .insightOverdue: "فواتير متأخرة",
        .insightNoSavings: "لا ادخار مخطط بعد",
        .insightGoodSavings: "معدل ادخار جيد",
        .insightAllHealthy: "تبدو ميزانيتك صحية",
        .insightHousingHint: "إرشاد: ثلث الدخل على الأكثر",
        .insightNoSavingsDetail: "لديك مساحة – قد يساعد هدف ادخار.",
        .insightAllHealthyDetail: "لا شيء يبرز. أضف مزيدًا من البيانات للحصول على رؤى أدق.",
        .insightExtraIncome: "دخل إضافي هذا الشهر",
        .insightGoalProgress: "هدف الادخار في متناول اليد",
        .insightBillsDueSoon: "متبقٍ للدفع هذا الشهر",
        .insightGettingStarted: "لنبدأ",
        .insightGettingStartedDetail: "أضف دخلك لعرض تحليلاتك الشخصية.",
        .schuldenEncourageTitle: "خطوة بخطوة",
        .schuldenEncourageBody: "أنت تتعامل معها. إليك خطوات تالية ملموسة.",
        .fragOfNetIncome: "من صافي الدخل",
        .fragOfFixedCosts: "من التكاليف الثابتة",
        .fragShortfall: "عجز",

        .commonAdd: "إضافة",
        .commonEdit: "تعديل",
        .commonActivate: "تفعيل",
        .commonDelete: "حذف",
        .commonCancel: "إلغاء",
        .commandsAdd: "إضافة إدخال",
        .billsAddCta: "أضف فاتورتك الأولى",
        .sparenAddCta: "أنشئ هدف ادخار",
        .overviewAddCta: "إضافة دخل",
        .commonSave: "حفظ",
        .commonSaved: "تم الحفظ",
        .commonClose: "إغلاق",
        .commonDone: "تم",
        .commonShowSampleData: "إظهار بيانات نموذجية",
        .commonHideSampleData: "إخفاء البيانات النموذجية",
        .commonEmptyHint: "لم تُدخل بيانات بعد.",
        .commonCopy: "نسخ",
        .commonOptions: "خيارات",
        .commonMoveUp: "تحريك لأعلى",
        .commonMoveDown: "تحريك لأسفل",
        .monthToday: "اليوم",

        .formName: "الاسم",
        .formAmount: "المبلغ (CHF)",
        .formStatus: "الحالة",
        .formNotes: "ملاحظة",
        .formInvalidAmount: "أدخل مبلغًا صالحًا.",
        .formThirteenthAmount: "الراتب الـ13 (المبلغ)",
        .formThirteenthModel: "نموذج الراتب الـ13",
        .incomeBonuses: "مدفوعات إضافية",
        .formMonth: "الشهر",
        .thirteenthModelSeparate: "إظهار منفصلًا",
        .thirteenthModelAveraged: "توزيع على 12 شهرًا",
        .formTarget: "هدف الادخار (المبلغ)",
        .formSaved: "تم ادخاره بالفعل",
        .formMonthlyContribution: "مساهمة شهرية",
        .formCategory: "الفئة",
        .formLimitedDuration: "أمر دائم محدود المدة",
        .formLimitedDurationHint: "مثلًا 6 أقساط ضريبية – تُحتسب في تلك الأشهر فقط ثم تُزال تلقائيًا.",
        .formStartMonth: "القسط الأول",
        .formInstallments: "عدد الأقساط",
        .planningStandingOrder: "أمر دائم",
        .catRent: "الإيجار",
        .catSubscription: "اشتراك",
        .catLeasing: "تأجير تمويلي",
        .catUtilities: "مرافق (ماء، كهرباء)",
        .catTelecom: "اتصالات",
        .catGroceries: "بقالة",
        .catFuel: "وقود",
        .catTransport: "النقل",
        .catPersonal: "شخصي",
        .catDining: "تناول الطعام بالخارج",
        .catHousehold: "المنزل",

        .overviewTitle: "نظرة عامة",
        .overviewAvailableThisMonth: "المتاح هذا الشهر",
        .overviewNetIncome: "صافي الدخل هذا الشهر",
        .overviewThirteenthSeparate: "الراتب الـ13 (منفصل)",
        .overviewRecurringFixed: "التكاليف الثابتة",
        .overviewPlannedVariable: "النفقات المتغيرة",
        .overviewBillsDueThisMonth: "فواتير هذا الشهر",
        .overviewOverdueBills: "فواتير متأخرة",
        .overviewSavingsTarget: "هدف الادخار",
        .overviewSecurityStatus: "حالة الأمان",
        .overviewFormulaExplainer: "المتاح = صافي الدخل − التكاليف الثابتة − الميزانيات المتغيرة − الفواتير المفتوحة هذا الشهر − الفواتير المتأخرة. الفواتير المدفوعة والمستقبلية لا تُنقص المبلغ.",
        .overviewEmpty: "أدخل الدخل والتكاليف في التخطيط الشهري لرؤية نظرتك العامة.",
        .chartSpendingTitle: "التوزيع هذا الشهر",
        .chartByCategory: "حسب الفئة",

        .planningTitle: "التخطيط الشهري",
        .planningIncome: "الدخل",
        .planningFixed: "التكاليف الثابتة",
        .planningVariable: "النفقات المتغيرة",
        .planningSavings: "هدف الادخار",
        .planningFixedExplainer: "تتكرر التكاليف الثابتة كل شهر: الإيجار، التأمينات، الاشتراكات، التأجير التمويلي.",
        .planningVariableExplainer: "تخطط الميزانيات المتغيرة بنفسك: البقالة، الوقود، النفقات الشخصية.",
        .planningOneOffHint: "تُدار الفواتير لمرة واحدة ضمن «الفواتير».",
        .planningEmpty: "ابدأ بدخلك، ثم أضف التكاليف الثابتة والميزانيات.",
        .planningBalance: "الرصيد المخطط",

        .billsTitle: "الفواتير",
        .billsStatusOpen: "مفتوحة",
        .billsStatusPaid: "مدفوعة",
        .billsStateOverdue: "متأخرة",
        .billsStateDueThisMonth: "تستحق هذا الشهر",
        .billsStateFuture: "مستقبلية",
        .billsAffectsBalance: "تُنقص المبلغ المتاح",
        .billsNoBalanceImpact: "لا تأثير هذا الشهر",
        .billsDueDate: "تاريخ الاستحقاق",
        .billsProvider: "المزوّد",
        .billsEmpty: "لا فواتير بعد. تظهر هنا الفواتير لمرة واحدة ذات تاريخ استحقاق.",
        .billsMarkPaid: "تعليم كمدفوعة",
        .billsMarkOpen: "تعليم كمفتوحة",
        .billsOpenTotal: "إجمالي المفتوح",

        .navSchulden: "الديون",
        .schuldenSubtitle: "تابع الفواتير المتأخرة وإجراءات التحصيل.",
        .schuldenEmpty: "لا ديون مسجلة. تظهر هنا الفواتير المتأخرة تلقائيًا – ويمكنك تدوين إجراء تحصيل (Betreibung) أو شهادات الخسارة.",
        .schuldenAddCta: "سجّل دينًا",
        .schuldenTotal: "إجمالي الدين",
        .schuldenOverdueBills: "فواتير متأخرة",
        .schuldenRecorded: "ديون مسجلة",
        .schuldenManagedInBills: "أدر الفواتير المتأخرة ضمن «الفواتير».",
        .debtTypeOpenClaim: "مطالبة مفتوحة",
        .debtTypeBetreibung: "إجراء تحصيل",
        .debtTypePfaendung: "حجز على الراتب/الممتلكات",
        .debtTypeVerlustschein: "شهادة خسارة",
        .debtTypeOther: "دين آخر",
        .debtCreditor: "الدائن",
        .debtReference: "مرجع / رقم الملف",
        .debtDate: "التاريخ",
        .debtType: "النوع",
        .schuldenGuidanceTitle: "طريق الخروج من الديون",
        .schuldenTipContactTitle: "تواصل مبكرًا",
        .schuldenTipContactBody: "تحدث مع الدائنين مبكرًا. غالبًا ما تكون خطة تقسيط مكتوبة ممكنة وتتجنب الإجراء الرسمي.",
        .schuldenTipBetreibungTitle: "إذا بدأ التحصيل",
        .schuldenTipBetreibungBody: "بعد أمر الدفع لديك 20 يومًا للسداد – أو 10 أيام لتقديم اعتراض (Rechtsvorschlag) إذا كانت المطالبة غير مبررة.",
        .schuldenTipExistenzminimumTitle: "حد الكفاف الخاص بك محمي",
        .schuldenTipExistenzminimumBody: "عند الحجز يبقى حد الكفاف الخاص بك دون مساس – المبلغ الأساسي، الإيجار، التأمين الصحي والمساهمات الاجتماعية.",
        .schuldenTipVerlustscheinTitle: "شهادة الخسارة",
        .schuldenTipVerlustscheinBody: "تسقط شهادة الخسارة بالتقادم بعد 20 عامًا فقط. يمكن ملاحقتك مجددًا فقط عند حصولك على أصول جديدة.",
        .schuldenTipCounselingTitle: "استشارة ديون مجانية",
        .schuldenTipCounselingBody: "تساعد Schuldenberatung Schweiz وCaritas واستشارة الميزانية مجانًا وبسرية. سدّد أولًا الديون ذات العواقب الأشد.",
        .schuldenDisclaimer: "معلومات عامة، وليست استشارة قانونية.",

        .catInsurance: "تأمين",
        .catOther: "أخرى",
        .catMortgage: "قرض عقاري",
        .catHealthInsurance: "تأمين صحي",
        .catSerafe: "راديو/تلفزيون (Serafe)",
        .catPublicTransport: "اشتراك مواصلات",
        .catChildcare: "رعاية الأطفال",
        .catMembership: "اشتراكات العضوية",
        .catAlimony: "نفقة",
        .catTaxes: "ضرائب",
        .catClothing: "ملابس",
        .catHealth: "الصحة",
        .catLeisure: "وقت الفراغ والهوايات",
        .catEntertainment: "ترفيه",
        .catChildren: "أطفال",
        .catPets: "حيوانات أليفة",
        .catGifts: "هدايا",
        .catTravel: "سفر",
        .catCharity: "تبرعات",
        .catEducation: "التعليم",

        .settingsTitle: "الإعدادات",
        .settingsLanguage: "اللغة",
        .settingsTheme: "سمة الألوان",
        .themeSwissRed: "أحمر سويسري",
        .themeOrange: "برتقالي",
        .themeSand: "رملي",
        .themeGreen: "أخضر",
        .themeTeal: "أزرق مخضر",
        .themeBlue: "أزرق",
        .themePurple: "بنفسجي",
        .themePink: "وردي",
        .settingsData: "البيانات",
        .settingsHousehold: "الأسرة المعيشية",
        .settingsCanton: "الكانتون",
        .settingsProfile: "الملف الشخصي",
        .profileName: "الاسم",
        .profileChoosePicture: "اختر صورة الملف الشخصي",
        .profileNoPicture: "بدون صورة",
        .profileLocalNote: "يُحفظ محليًا فقط على هذا الجهاز.",
        .settingsSecurity: "الأمان",
        .settingsAutoLock: "القفل التلقائي",
        .settingsBiometric: "الفتح بالمقاييس الحيوية",
        .settingsChangePassphrase: "تغيير كلمة المرور/PIN",
        .settingsBackup: "نسخة احتياطية مشفّرة",
        .settingsRestore: "استعادة",
        .settingsPrivacy: "الخصوصية",
        .settingsDangerZone: "منطقة الخطر",
        .settingsDeleteAll: "حذف جميع البيانات المحلية",
        .backupCreateTitle: "إنشاء نسخة احتياطية مشفّرة",
        .backupPassphrase: "كلمة مرور النسخة الاحتياطية",
        .backupHint: "اختر كلمة مرور منفصلة للنسخة الاحتياطية. وهي لازمة للاستعادة – لا يمكن استرداد كلمة المرور.",
        .restorePreview: "معاينة",
        .restoreConfirm: "استبدال جميع البيانات المحلية",
        .restoreWarning: "سيؤدي هذا إلى استبدال جميع البيانات المحلية نهائيًا.",
        .backupInvalid: "نسخة احتياطية غير صالحة أو كلمة مرور خاطئة.",
        .backupSavedHint: "احتفظ بملف النسخة الاحتياطية وكلمة المرور في مكان آمن.",

        .reportTitle: "الإبلاغ عن مشكلة",
        .reportSummary: "ملخص",
        .reportExpected: "السلوك المتوقع",
        .reportActual: "السلوك الفعلي",
        .reportSteps: "خطوات إعادة الإنتاج",
        .reportArea: "المنطقة المتأثرة",
        .reportRedactionNote: "تُزال البيانات الحساسة محليًا. تراجع التقرير قبل نسخه.",
        .reportCopyHint: "لا يُرسل التقرير تلقائيًا. تنسخه بنفسك.",

        .exportReport: "تصدير التقرير",
        .pdfTitle: "نظرة مالية عامة",
        .pdfSubtitle: "تقرير شخصي للأسرة المعيشية",
        .pdfSummary: "في لمحة",
        .pdfGeneratedOn: "أُنشئ في",
        .pdfConfidential: "سرّي",
        .pdfPage: "صفحة",
        .pdfTotal: "الإجمالي",
        .pdfColProgress: "التقدم",
        .pdfUnencryptedNote: "التقرير ملف PDF قابل للقراءة وغير مشفّر. احتفظ به في مكان آمن.",
        .pdfNoData: "لا بيانات للتصدير بعد.",
        .pdfDefaultHousehold: "أسرتي المعيشية",

        .lockTitle: "مقفل",
        .lockWelcomeSetup: "مرحبًا بك في Kontiva",
        .lockWelcomeBack: "مرحبًا بعودتك",
        .lockSetupTitle: "تعيين كلمة المرور",
        .lockEnterPassphrase: "أدخل كلمة المرور أو PIN",
        .lockWrongPassphrase: "كلمة مرور خاطئة. حاول مرة أخرى.",
        .lockRecoveryWarning: "لا توجد استعادة. بدون كلمة مرورك لا يمكن الوصول إلى بياناتك.",
        .lockRecoveryAcknowledge: "أفهم أنه لا توجد استعادة.",
        .securityNote: "تُحفظ بياناتك محليًا ومشفّرة (AES-256-GCM). لا سحابة، لا خادم، لا استعادة لكلمة المرور.",

        .onboardingIntroBody: "يساعدك Kontiva على الاحتفاظ بنظرة هادئة على ميزانية أسرتك المعيشية السويسرية – بالكامل على هذا الجهاز.",
        .onboardingStart: "ابدأ",
        .onboardingProfileTitle: "أنشئ ملفًا شخصيًا",
        .onboardingProfileBody: "اختر لنفسك اسمًا وصورة. كلاهما يبقى على هذا الجهاز فقط.",
        .onboardingSkip: "تخطٍّ",
        .onboardingFeaturePrivate: "محلي بالكامل – لا سحابة، لا تتبع",
        .onboardingFeatureSecure: "مشفّر بـ AES-256",
        .onboardingFeatureMoney: "دقيق حتى السنتيم، دون أخطاء تقريب",
        .onboardingConfirmPassphrase: "تأكيد كلمة المرور",
        .onboardingPassphraseNote: "اكتب كلمة مرورك في مكان آمن – لا يمكن إعادة تعيينها.",
        .backupNudgeText: "أنشئ نسخة احتياطية مشفّرة. بدونها تفقد بياناتك إذا نسيت كلمة المرور.",
        .commonNext: "التالي",
        .navMore: "المزيد",
        .actionLock: "قفل",
        .pinSetTitle: "تعيين الرمز",
        .pinConfirmTitle: "تأكيد الرمز",
        .pinRequirementNote: "6 أرقام على الأقل · لا استعادة",
        .pinMismatch: "الرمزان غير متطابقين",
    ]
}
