import Foundation

extension Localization {
    static let mk: [L10nKey: String] = [
        .appName: "Kontiva",
        .appTagline: "Смирен, приватен преглед на вашиот швајцарски буџет.",
        .notBetaNotice: "Рана развојна верзија – не е бета, не е V1.",

        .navOverview: "Преглед",
        .navPlanning: "План",
        .navBills: "Сметки",
        .navSettings: "Поставки",
        .navReport: "Пријави проблем",
        .navInsights: "Увиди",
        .navSparen: "Штедење",
        .sparenSubtitle: "Редовни придонеси за штедење – и она што е веќе собрано.",
        .sparenEmpty: "Сè уште нема цели за штедење. Одредете за што штедите секој месец.",
        .sparenMonthlyTotal: "Штедење / месец",
        .sparenAccumulatedTotal: "Веќе заштедено",
        .sparenPerMonth: "/ месец",
        .sparenContributions: "придонеси",
        .sparenSince: "од",
        .sparenOpenEnded: "Без целен износ",
        .sparenGoalsLabel: "Цели",
        .sparenSortBy: "Подреди",
        .sparenSortStartMonth: "Почетен месец",
        .savingsCatCar: "Автомобил",
        .savingsCatVacation: "Одмор",
        .savingsCatHome: "Домување",
        .savingsCatRetirement: "Столб 3a / Пензија",
        .savingsCatEmergency: "Фонд за итни случаи",
        .savingsCatEducation: "Образование",
        .savingsCatOther: "Друго",
        .savingsCatWedding: "Свадба",
        .savingsCatFamily: "Семејство и деца",
        .savingsCatRenovation: "Реновирање и опремување",
        .savingsCatElectronics: "Електроника",
        .savingsCatTaxes: "Резерва за даноци",
        .savingsCatInvestment: "Инвестиции",
        .savingsCatHealth: "Здравје",
        .savingsCatGift: "Подароци",
        .overviewPlannedSavings: "Штедење овој месец",
        .overviewShowCalculation: "Прикажи пресметка",
        .overviewTrendTitle: "Тренд · 6 месеци",
        .overviewStatusGood: "Здрав вишок",
        .overviewStatusTight: "Тесно",
        .overviewStatusNegative: "Во минус",
        .overviewAllocationOf: "од нето приходот",
        .formStartDate: "Штедам од",
        .formStartingBalance: "Почетно салдо (опционално)",
        .insightsSubtitle: "Насоки за вашиот буџет – каде се вашите пари и каде можете да заштедите.",
        .insightOverspending: "Трошите повеќе отколку што заработувате",
        .insightTightBudget: "Малку простор овој месец",
        .insightHealthySurplus: "Здрав вишок",
        .insightHighFixed: "Високи фиксни трошоци",
        .insightHighHousing: "Високи трошоци за домување",
        .insightLargestFixed: "Најголема ставка во фиксните трошоци",
        .insightLargestVariable: "Најголем променлив буџет",
        .insightOverdue: "Достасани сметки",
        .insightNoSavings: "Сè уште нема планирано штедење",
        .insightGoodSavings: "Добра стапка на штедење",
        .insightAllHealthy: "Вашиот буџет изгледа здраво",
        .insightHousingHint: "Препорака: најмногу една третина од приходот",
        .insightNoSavingsDetail: "Имате простор – цел за штедење би можела да помогне.",
        .insightAllHealthyDetail: "Ништо не се истакнува. Додадете повеќе податоци за попрецизни увиди.",
        .fragOfNetIncome: "од нето приходот",
        .fragOfFixedCosts: "од фиксните трошоци",
        .fragShortfall: "Недостиг",

        .commonAdd: "Додај",
        .commonEdit: "Уреди",
        .commonDelete: "Избриши",
        .commonCancel: "Откажи",
        .commandsAdd: "Додај запис",
        .billsAddCta: "Додај ја првата сметка",
        .sparenAddCta: "Создади цел за штедење",
        .overviewAddCta: "Додај приход",
        .commonSave: "Зачувај",
        .commonSaved: "Зачувано",
        .commonClose: "Затвори",
        .commonDone: "Готово",
        .commonShowSampleData: "Прикажи примери",
        .commonHideSampleData: "Скриј примери",
        .commonEmptyHint: "Сè уште нема внесени податоци.",
        .commonCopy: "Копирај",
        .commonOptions: "Опции",
        .commonMoveUp: "Помести нагоре",
        .commonMoveDown: "Помести надолу",
        .monthToday: "Денес",

        .formName: "Име",
        .formAmount: "Износ (CHF)",
        .formStatus: "Статус",
        .formNotes: "Белешка",
        .formInvalidAmount: "Внесете важечки износ.",
        .formThirteenthAmount: "13-та плата (износ)",
        .formThirteenthModel: "Модел на 13-та плата",
        .thirteenthModelSeparate: "Прикажи одделно",
        .thirteenthModelAveraged: "Распредели на 12 месеци",
        .formTarget: "Цел за штедење (износ)",
        .formSaved: "Веќе заштедено",
        .formMonthlyContribution: "Месечен придонес",
        .formCategory: "Категорија",
        .formLimitedDuration: "Ограничен траен налог",
        .formLimitedDurationHint: "На пр. 6 рати за данок – се бројат само во тие месеци и потоа автоматски се отстрануваат.",
        .formStartMonth: "Прва рата",
        .formInstallments: "Број на рати",
        .planningStandingOrder: "Траен налог",
        .catRent: "Кирија",
        .catSubscription: "Претплата",
        .catLeasing: "Лизинг",
        .catUtilities: "Режии",
        .catTelecom: "Телекомуникации",
        .catGroceries: "Намирници",
        .catFuel: "Гориво",
        .catTransport: "Превоз",
        .catPersonal: "Лично",
        .catDining: "Јадење надвор",
        .catHousehold: "Домаќинство",

        .overviewTitle: "Преглед",
        .overviewAvailableThisMonth: "Достапно овој месец",
        .overviewNetIncome: "Нето приход овој месец",
        .overviewThirteenthSeparate: "13-та плата (одделно)",
        .overviewRecurringFixed: "Фиксни трошоци",
        .overviewPlannedVariable: "Променливи трошоци",
        .overviewBillsDueThisMonth: "Сметки овој месец",
        .overviewOverdueBills: "Достасани сметки",
        .overviewSavingsTarget: "Цел за штедење",
        .overviewSecurityStatus: "Статус на безбедност",
        .overviewFormulaExplainer: "Достапно = нето приход − фиксни трошоци − променливи буџети − отворени сметки овој месец − достасани сметки. Платените и идните сметки не го намалуваат износот.",
        .overviewEmpty: "Внесете приходи и трошоци во Месечно планирање за да го видите прегледот.",
        .chartSpendingTitle: "Распределба овој месец",
        .chartByCategory: "По категорија",

        .planningTitle: "Месечно планирање",
        .planningIncome: "Приход",
        .planningFixed: "Фиксни трошоци",
        .planningVariable: "Променливи трошоци",
        .planningSavings: "Цел за штедење",
        .planningFixedExplainer: "Фиксните трошоци се повторуваат секој месец: кирија, осигурувања, претплати, лизинг.",
        .planningVariableExplainer: "Променливите буџети ги планирате сами: намирници, гориво, лични трошоци.",
        .planningOneOffHint: "Еднократните сметки се управуваат во „Сметки”.",
        .planningEmpty: "Започнете со вашиот приход, а потоа додадете фиксни трошоци и буџети.",
        .planningBalance: "Планирано салдо",

        .billsTitle: "Сметки",
        .billsStatusOpen: "Отворена",
        .billsStatusPaid: "Платена",
        .billsStateOverdue: "Достасана",
        .billsStateDueThisMonth: "Достасува овој месец",
        .billsStateFuture: "Идна",
        .billsAffectsBalance: "Го намалува достапниот износ",
        .billsNoBalanceImpact: "Без влијание овој месец",
        .billsDueDate: "Датум на достасување",
        .billsProvider: "Давател",
        .billsEmpty: "Сè уште нема сметки. Еднократните сметки со датум на достасување се прикажуваат тука.",
        .billsMarkPaid: "Означи како платена",
        .billsMarkOpen: "Означи како отворена",
        .billsOpenTotal: "Вкупно отворено",

        .navSchulden: "Долгови",
        .schuldenSubtitle: "Следете ги достасаните сметки и присилната наплата.",
        .schuldenEmpty: "Нема забележани долгови. Достасаните сметки се прикажуваат тука автоматски – а можете да забележите присилна наплата (Betreibung) или потврди за загуба.",
        .schuldenAddCta: "Забележи долг",
        .schuldenTotal: "Вкупен долг",
        .schuldenOverdueBills: "Достасани сметки",
        .schuldenRecorded: "Забележани долгови",
        .schuldenManagedInBills: "Управувајте со достасаните сметки во „Сметки”.",
        .debtTypeOpenClaim: "Отворено побарување",
        .debtTypeBetreibung: "Присилна наплата",
        .debtTypePfaendung: "Запленување на плата/имот",
        .debtTypeVerlustschein: "Потврда за загуба",
        .debtTypeOther: "Друг долг",
        .debtCreditor: "Доверител",
        .debtReference: "Референца / број на предмет",
        .debtDate: "Датум",
        .debtType: "Тип",
        .schuldenGuidanceTitle: "Како да излезете од долговите",
        .schuldenTipContactTitle: "Јавете се навреме",
        .schuldenTipContactBody: "Разговарајте со доверителите навреме. Писмен план за отплата на рати често е можен и ја избегнува формалната постапка.",
        .schuldenTipBetreibungTitle: "Ако започне наплатата",
        .schuldenTipBetreibungBody: "По налогот за плаќање имате 20 дена да платите – или 10 дена да поднесете приговор (Rechtsvorschlag) ако побарувањето е неосновано.",
        .schuldenTipExistenzminimumTitle: "Вашиот егзистенцијален минимум е заштитен",
        .schuldenTipExistenzminimumBody: "При запленување, вашиот егзистенцијален минимум останува недопрен – основен износ, кирија, здравствено осигурување и социјални придонеси.",
        .schuldenTipVerlustscheinTitle: "Потврда за загуба",
        .schuldenTipVerlustscheinBody: "Потврдата за загуба застарува дури по 20 години. Може повторно да бидете гонети само кога ќе се здобиете со нов имот.",
        .schuldenTipCounselingTitle: "Бесплатно советување за долгови",
        .schuldenTipCounselingBody: "Schuldenberatung Schweiz, Caritas и буџетското советување помагаат бесплатно и доверливо. Прво отплатете ги долговите со најтешки последици.",
        .schuldenDisclaimer: "Општи информации, не правен совет.",

        .catInsurance: "Осигурување",
        .catOther: "Друго",
        .catMortgage: "Хипотекарен кредит",
        .catHealthInsurance: "Здравствено осигурување",
        .catSerafe: "Радио/ТВ (Serafe)",
        .catPublicTransport: "Превозен билет",
        .catChildcare: "Чување деца",
        .catMembership: "Членарини",
        .catAlimony: "Издршка",
        .catTaxes: "Даноци",
        .catClothing: "Облека",
        .catHealth: "Здравје",
        .catLeisure: "Слободно време и хобија",
        .catEntertainment: "Забава",
        .catChildren: "Деца",
        .catPets: "Домашни миленици",
        .catGifts: "Подароци",
        .catTravel: "Патувања",
        .catCharity: "Донации",
        .catEducation: "Образование",

        .settingsTitle: "Поставки",
        .settingsLanguage: "Јазик",
        .settingsTheme: "Тема на бои",
        .themeSwissRed: "Швајцарска црвена",
        .themeOrange: "Портокалова",
        .themeSand: "Песочна",
        .themeGreen: "Зелена",
        .themeTeal: "Тиркизна",
        .themeBlue: "Сина",
        .themePurple: "Виолетова",
        .themePink: "Розова",
        .settingsData: "Податоци",
        .settingsHousehold: "Домаќинство",
        .settingsCanton: "Кантон",
        .settingsProfile: "Профил",
        .profileName: "Име",
        .profileChoosePicture: "Избери профилна слика",
        .profileNoPicture: "Без слика",
        .profileLocalNote: "Се чува само локално на овој уред.",
        .settingsSecurity: "Безбедност",
        .settingsAutoLock: "Автоматско заклучување",
        .settingsBiometric: "Биометриско отклучување",
        .settingsChangePassphrase: "Промени лозинка/PIN",
        .settingsBackup: "Шифрирана резервна копија",
        .settingsRestore: "Врати",
        .settingsPrivacy: "Приватност",
        .settingsDangerZone: "Опасна зона",
        .settingsDeleteAll: "Избриши ги сите локални податоци",
        .backupCreateTitle: "Создади шифрирана резервна копија",
        .backupPassphrase: "Лозинка за резервната копија",
        .backupHint: "Изберете одделна лозинка за резервната копија. Потребна е за враќање – лозинката не може да се поврати.",
        .restorePreview: "Преглед",
        .restoreConfirm: "Замени ги сите локални податоци",
        .restoreWarning: "Ова трајно ги препишува сите локални податоци.",
        .backupInvalid: "Неважечка резервна копија или погрешна лозинка.",
        .backupSavedHint: "Чувајте ја датотеката на резервната копија и лозинката на безбедно место.",

        .reportTitle: "Пријави проблем",
        .reportSummary: "Резиме",
        .reportExpected: "Очекувано однесување",
        .reportActual: "Вистинско однесување",
        .reportSteps: "Чекори за репродукција",
        .reportArea: "Засегната област",
        .reportRedactionNote: "Чувствителните податоци се отстрануваат локално. Го прегледувате извештајот пред да го копирате.",
        .reportCopyHint: "Извештајот не се испраќа автоматски. Сами го копирате.",

        .exportReport: "Извези извештај",
        .pdfTitle: "Финансиски преглед",
        .pdfSubtitle: "Личен извештај за домаќинството",
        .pdfSummary: "На прв поглед",
        .pdfGeneratedOn: "Создадено на",
        .pdfConfidential: "Доверливо",
        .pdfPage: "Страница",
        .pdfTotal: "Вкупно",
        .pdfColProgress: "Напредок",
        .pdfUnencryptedNote: "Извештајот е читлив, нешифриран PDF. Чувајте го на безбедно место.",
        .pdfNoData: "Сè уште нема податоци за извоз.",
        .pdfDefaultHousehold: "Моето домаќинство",

        .lockTitle: "Заклучено",
        .lockWelcomeSetup: "Добредојдовте во Kontiva",
        .lockWelcomeBack: "Добредојдовте назад",
        .lockSetupTitle: "Постави лозинка",
        .lockEnterPassphrase: "Внесете лозинка или PIN",
        .lockWrongPassphrase: "Погрешна лозинка. Обидете се повторно.",
        .lockRecoveryWarning: "Нема враќање. Без вашата лозинка, вашите податоци не може да се пристапат.",
        .lockRecoveryAcknowledge: "Разбирам дека нема враќање.",
        .securityNote: "Вашите податоци се чуваат локално и шифрирани (AES-256-GCM). Без облак, без сервер, без враќање на лозинка.",

        .onboardingIntroBody: "Kontiva ви помага да имате смирен преглед на буџетот на вашето швајцарско домаќинство – целосно на овој уред.",
        .onboardingStart: "Започни",
        .onboardingProfileTitle: "Создади профил",
        .onboardingProfileBody: "Дадете си име и изберете слика. Двете остануваат само на овој уред.",
        .onboardingSkip: "Прескокни",
        .onboardingFeaturePrivate: "Целосно локално – без облак, без следење",
        .onboardingFeatureSecure: "Шифрирано со AES-256",
        .onboardingFeatureMoney: "Точно до сантим, без грешки во заокружување",
        .onboardingConfirmPassphrase: "Потврди лозинка",
        .onboardingPassphraseNote: "Запишете ја лозинката на безбедно место – не може да се ресетира.",
        .backupNudgeText: "Создадете шифрирана резервна копија. Без неа ги губите податоците ако ја заборавите лозинката.",
        .commonNext: "Следно",
        .navMore: "Повеќе",
        .actionLock: "Заклучи",
        .pinSetTitle: "Постави код",
        .pinConfirmTitle: "Потврди код",
        .pinRequirementNote: "Мин. 6 цифри · без враќање",
        .pinMismatch: "Кодовите не се совпаѓаат",
    ]
}
