import Foundation

extension Localization {
    static let vi: [L10nKey: String] = [
        .appName: "Kontiva",
        .appTagline: "Một cái nhìn yên tĩnh, riêng tư về ngân sách Thụy Sĩ của bạn.",
        .notBetaNotice: "Phiên bản phát triển sớm – không phải beta, không phải V1.",

        .navOverview: "Tổng quan",
        .navPlanning: "Kế hoạch",
        .navBills: "Hóa đơn",
        .navSettings: "Cài đặt",
        .navReport: "Báo cáo sự cố",
        .navInsights: "Phân tích",
        .navSparen: "Tiết kiệm",
        .sparenSubtitle: "Các khoản đóng góp tiết kiệm định kỳ – và số đã tích lũy.",
        .sparenEmpty: "Chưa có mục tiêu tiết kiệm. Hãy xác định bạn tiết kiệm cho điều gì mỗi tháng.",
        .sparenMonthlyTotal: "Tiết kiệm / tháng",
        .sparenAccumulatedTotal: "Đã tiết kiệm",
        .sparenPerMonth: "/ tháng",
        .sparenContributions: "lần đóng góp",
        .sparenSince: "từ",
        .sparenOpenEnded: "Không có số mục tiêu",
        .sparenGoalReached: "Đã đạt mục tiêu",
        .sparenGoalReachedMessage: "Chúc mừng! Bạn đã đạt mục tiêu tiết kiệm. Bạn muốn tiếp tục thế nào?",
        .sparenGoalIncrease: "Tăng mục tiêu",
        .sparenGoalComplete: "Đánh dấu hoàn thành",
        .sparenGoalKeep: "Tiếp tục tiết kiệm",
        .sparenGoalCompleted: "Hoàn thành",
        .sparenGoalReopen: "Kích hoạt lại",
        .sparenGoalsLabel: "Mục tiêu",
        .sparenSortBy: "Sắp xếp",
        .sparenSortStartMonth: "Tháng bắt đầu",
        .savingsCatCar: "Xe hơi",
        .savingsCatVacation: "Kỳ nghỉ",
        .savingsCatHome: "Nhà ở",
        .savingsCatRetirement: "Trụ cột 3a / Lương hưu",
        .savingsCatEmergency: "Quỹ khẩn cấp",
        .savingsCatEducation: "Giáo dục",
        .savingsCatOther: "Khác",
        .savingsCatWedding: "Đám cưới",
        .savingsCatFamily: "Gia đình và con cái",
        .savingsCatRenovation: "Sửa chữa và nội thất",
        .savingsCatElectronics: "Đồ điện tử",
        .savingsCatTaxes: "Dự phòng thuế",
        .savingsCatInvestment: "Đầu tư",
        .savingsCatHealth: "Sức khỏe",
        .savingsCatGift: "Quà tặng",
        .overviewPlannedSavings: "Tiết kiệm tháng này",
        .overviewShowCalculation: "Hiện phép tính",
        .overviewTrendTitle: "Xu hướng · 6 tháng",
        .overviewStatusGood: "Thặng dư lành mạnh",
        .overviewStatusTight: "Eo hẹp",
        .overviewStatusNegative: "Âm",
        .overviewAllocationOf: "trên thu nhập ròng",
        .formStartDate: "Tiết kiệm từ",
        .formStartingBalance: "Số dư ban đầu (tùy chọn)",
        .insightsSubtitle: "Hướng dẫn về ngân sách của bạn – tiền của bạn ở đâu và có thể tiết kiệm ở đâu.",
        .insightOverspending: "Bạn đang chi nhiều hơn thu",
        .insightTightBudget: "Ít dư địa trong tháng này",
        .insightHealthySurplus: "Thặng dư lành mạnh",
        .insightHighFixed: "Chi phí cố định cao",
        .insightHighHousing: "Chi phí nhà ở cao",
        .insightLargestFixed: "Khoản lớn nhất trong chi phí cố định",
        .insightLargestVariable: "Ngân sách biến đổi lớn nhất",
        .insightOverdue: "Hóa đơn quá hạn",
        .insightNoSavings: "Chưa lập kế hoạch tiết kiệm",
        .insightGoodSavings: "Tỷ lệ tiết kiệm tốt",
        .insightAllHealthy: "Ngân sách của bạn trông lành mạnh",
        .insightHousingHint: "Khuyến nghị: tối đa một phần ba thu nhập",
        .insightNoSavingsDetail: "Bạn có dư địa – một mục tiêu tiết kiệm có thể hữu ích.",
        .insightAllHealthyDetail: "Không có gì nổi bật. Thêm dữ liệu để có phân tích sắc nét hơn.",
        .insightExtraIncome: "Thu nhập thêm tháng này",
        .insightGoalProgress: "Sắp đạt mục tiêu tiết kiệm",
        .insightBillsDueSoon: "Còn phải trả tháng này",
        .insightGettingStarted: "Bắt đầu nào",
        .insightGettingStartedDetail: "Thêm thu nhập để xem phân tích cá nhân.",
        .schuldenEncourageTitle: "Từng bước một",
        .schuldenEncourageBody: "Bạn đang đối mặt với nó. Đây là các bước tiếp theo.",
        .fragOfNetIncome: "trên thu nhập ròng",
        .fragOfFixedCosts: "trên chi phí cố định",
        .fragShortfall: "Thiếu hụt",

        .commonAdd: "Thêm",
        .commonEdit: "Sửa",
        .commonActivate: "Bật",
        .commonDelete: "Xóa",
        .commonCancel: "Hủy",
        .commandsAdd: "Thêm mục",
        .billsAddCta: "Thêm hóa đơn đầu tiên",
        .sparenAddCta: "Tạo mục tiêu tiết kiệm",
        .overviewAddCta: "Thêm thu nhập",
        .commonSave: "Lưu",
        .commonSaved: "Đã lưu",
        .commonClose: "Đóng",
        .commonDone: "Xong",
        .commonShowSampleData: "Hiện dữ liệu mẫu",
        .commonHideSampleData: "Ẩn dữ liệu mẫu",
        .commonEmptyHint: "Chưa nhập dữ liệu.",
        .commonCopy: "Sao chép",
        .commonOptions: "Tùy chọn",
        .commonMoveUp: "Di chuyển lên",
        .commonMoveDown: "Di chuyển xuống",
        .monthToday: "Hôm nay",

        .formName: "Tên",
        .formAmount: "Số tiền (CHF)",
        .formStatus: "Trạng thái",
        .formNotes: "Ghi chú",
        .formInvalidAmount: "Hãy nhập số tiền hợp lệ.",
        .formThirteenthAmount: "Lương tháng 13 (số tiền)",
        .formThirteenthModel: "Mô hình lương tháng 13",
        .incomeBonuses: "Khoản thanh toán thêm",
        .formMonth: "Tháng",
        .thirteenthModelSeparate: "Hiện riêng",
        .thirteenthModelAveraged: "Chia đều cho 12 tháng",
        .formTarget: "Mục tiêu tiết kiệm (số tiền)",
        .formSaved: "Đã tiết kiệm",
        .formMonthlyContribution: "Đóng góp hàng tháng",
        .formCategory: "Danh mục",
        .formLimitedDuration: "Lệnh chuyển khoản định kỳ có thời hạn",
        .formLimitedDurationHint: "Ví dụ 6 kỳ thuế – chỉ tính trong những tháng đó rồi tự động bị xóa.",
        .formStartMonth: "Kỳ đầu",
        .formInstallments: "Số kỳ",
        .planningStandingOrder: "Lệnh chuyển khoản định kỳ",
        .catRent: "Tiền thuê nhà",
        .catSubscription: "Thuê bao",
        .catLeasing: "Cho thuê tài chính",
        .catUtilities: "Tiện ích (điện, nước)",
        .catTelecom: "Viễn thông",
        .catGroceries: "Thực phẩm",
        .catFuel: "Nhiên liệu",
        .catTransport: "Giao thông",
        .catPersonal: "Cá nhân",
        .catDining: "Ăn ngoài",
        .catHousehold: "Gia đình",

        .overviewTitle: "Tổng quan",
        .overviewAvailableThisMonth: "Khả dụng tháng này",
        .overviewNetIncome: "Thu nhập ròng tháng này",
        .overviewThirteenthSeparate: "Lương tháng 13 (riêng)",
        .overviewRecurringFixed: "Chi phí cố định",
        .overviewPlannedVariable: "Chi tiêu biến đổi",
        .overviewBillsDueThisMonth: "Hóa đơn tháng này",
        .overviewOverdueBills: "Hóa đơn quá hạn",
        .overviewSavingsTarget: "Mục tiêu tiết kiệm",
        .overviewSecurityStatus: "Trạng thái bảo mật",
        .overviewFormulaExplainer: "Khả dụng = thu nhập ròng − chi phí cố định − ngân sách biến đổi − hóa đơn chưa trả tháng này − hóa đơn quá hạn. Hóa đơn đã trả và tương lai không làm giảm số tiền.",
        .overviewEmpty: "Nhập thu nhập và chi phí trong Kế hoạch hàng tháng để xem tổng quan.",
        .chartSpendingTitle: "Phân bổ tháng này",
        .chartByCategory: "Theo danh mục",

        .planningTitle: "Kế hoạch hàng tháng",
        .planningIncome: "Thu nhập",
        .planningFixed: "Chi phí cố định",
        .planningVariable: "Chi tiêu biến đổi",
        .planningSavings: "Mục tiêu tiết kiệm",
        .planningFixedExplainer: "Chi phí cố định lặp lại mỗi tháng: tiền thuê nhà, bảo hiểm, thuê bao, cho thuê tài chính.",
        .planningVariableExplainer: "Ngân sách biến đổi do bạn tự lập: thực phẩm, nhiên liệu, chi tiêu cá nhân.",
        .planningOneOffHint: "Hóa đơn một lần được quản lý trong „Hóa đơn”.",
        .planningEmpty: "Bắt đầu với thu nhập, rồi thêm chi phí cố định và ngân sách.",
        .planningBalance: "Số dư dự kiến",

        .billsTitle: "Hóa đơn",
        .billsStatusOpen: "Chưa trả",
        .billsStatusPaid: "Đã trả",
        .billsStateOverdue: "Quá hạn",
        .billsStateDueThisMonth: "Đến hạn tháng này",
        .billsStateFuture: "Tương lai",
        .billsAffectsBalance: "Làm giảm số tiền khả dụng",
        .billsNoBalanceImpact: "Không ảnh hưởng tháng này",
        .billsDueDate: "Ngày đến hạn",
        .billsProvider: "Nhà cung cấp",
        .billsEmpty: "Chưa có hóa đơn. Hóa đơn một lần có ngày đến hạn sẽ hiện ở đây.",
        .billsMarkPaid: "Đánh dấu đã trả",
        .billsMarkOpen: "Đánh dấu chưa trả",
        .billsOpenTotal: "Tổng chưa trả",

        .navSchulden: "Nợ",
        .schuldenSubtitle: "Theo dõi hóa đơn quá hạn và việc cưỡng chế thu nợ.",
        .schuldenEmpty: "Chưa ghi nhận khoản nợ nào. Hóa đơn quá hạn tự động hiện ở đây – và bạn có thể ghi chú việc cưỡng chế thu nợ (Betreibung) hoặc giấy chứng nhận thua lỗ.",
        .schuldenAddCta: "Ghi nhận một khoản nợ",
        .schuldenTotal: "Tổng nợ",
        .schuldenOverdueBills: "Hóa đơn quá hạn",
        .schuldenRecorded: "Nợ đã ghi nhận",
        .schuldenManagedInBills: "Quản lý hóa đơn quá hạn trong „Hóa đơn”.",
        .debtTypeOpenClaim: "Yêu cầu chưa thanh toán",
        .debtTypeBetreibung: "Cưỡng chế thu nợ",
        .debtTypePfaendung: "Tịch thu lương/tài sản",
        .debtTypeVerlustschein: "Giấy chứng nhận thua lỗ",
        .debtTypeOther: "Nợ khác",
        .debtCreditor: "Chủ nợ",
        .debtReference: "Tham chiếu / số hồ sơ",
        .debtDate: "Ngày",
        .debtType: "Loại",
        .schuldenGuidanceTitle: "Lối thoát khỏi nợ nần",
        .schuldenTipContactTitle: "Liên hệ sớm",
        .schuldenTipContactBody: "Hãy nói chuyện với chủ nợ sớm. Kế hoạch trả góp bằng văn bản thường khả thi và tránh thủ tục chính thức.",
        .schuldenTipBetreibungTitle: "Nếu việc thu nợ bắt đầu",
        .schuldenTipBetreibungBody: "Sau lệnh thanh toán, bạn có 20 ngày để trả – hoặc 10 ngày để khiếu nại (Rechtsvorschlag) nếu yêu cầu không hợp lý.",
        .schuldenTipExistenzminimumTitle: "Mức sống tối thiểu của bạn được bảo vệ",
        .schuldenTipExistenzminimumBody: "Khi bị tịch thu, mức sống tối thiểu của bạn vẫn nguyên vẹn – số tiền cơ bản, tiền thuê nhà, bảo hiểm y tế và các khoản đóng góp xã hội.",
        .schuldenTipVerlustscheinTitle: "Giấy chứng nhận thua lỗ",
        .schuldenTipVerlustscheinBody: "Giấy chứng nhận thua lỗ chỉ hết hiệu lực sau 20 năm. Bạn chỉ có thể bị truy đòi lại khi có tài sản mới.",
        .schuldenTipCounselingTitle: "Tư vấn nợ miễn phí",
        .schuldenTipCounselingBody: "Schuldenberatung Schweiz, Caritas và tư vấn ngân sách giúp đỡ miễn phí và bảo mật. Hãy trả trước những khoản nợ có hậu quả nặng nhất.",
        .schuldenDisclaimer: "Thông tin chung, không phải tư vấn pháp lý.",

        .catInsurance: "Bảo hiểm",
        .catOther: "Khác",
        .catMortgage: "Vay thế chấp",
        .catHealthInsurance: "Bảo hiểm y tế",
        .catSerafe: "Phát thanh/truyền hình (Serafe)",
        .catPublicTransport: "Vé giao thông",
        .catChildcare: "Chăm sóc trẻ",
        .catMembership: "Phí thành viên",
        .catAlimony: "Cấp dưỡng",
        .catTaxes: "Thuế",
        .catRatenzahlung: "Trả góp",
        .catStreaming: "Streaming",
        .catCreditCard: "Thẻ tín dụng",
        .catClothing: "Quần áo",
        .catHealth: "Sức khỏe",
        .catLeisure: "Giải trí và sở thích",
        .catEntertainment: "Vui chơi",
        .catChildren: "Con cái",
        .catPets: "Thú cưng",
        .catGifts: "Quà tặng",
        .catTravel: "Du lịch",
        .catCharity: "Từ thiện",
        .catEducation: "Giáo dục",

        .settingsTitle: "Cài đặt",
        .settingsLanguage: "Ngôn ngữ",
        .settingsTheme: "Chủ đề màu",
        .themeSwissRed: "Đỏ Thụy Sĩ",
        .themeOrange: "Cam",
        .themeSand: "Cát",
        .themeGreen: "Xanh lá",
        .themeTeal: "Xanh mòng két",
        .themeBlue: "Xanh dương",
        .themePurple: "Tím",
        .themePink: "Hồng",
        .settingsData: "Dữ liệu",
        .settingsHousehold: "Hộ gia đình",
        .settingsCanton: "Bang (canton)",
        .settingsProfile: "Hồ sơ",
        .profileName: "Tên",
        .profileChoosePicture: "Chọn ảnh hồ sơ",
        .profileNoPicture: "Không có ảnh",
        .profileLocalNote: "Chỉ lưu cục bộ trên thiết bị này.",
        .settingsSecurity: "Bảo mật",
        .settingsAutoLock: "Tự động khóa",
        .settingsBiometric: "Mở khóa sinh trắc học",
        .settingsChangePassphrase: "Đổi mật khẩu/PIN",
        .settingsBackup: "Sao lưu được mã hóa",
        .settingsRestore: "Khôi phục",
        .settingsPrivacy: "Quyền riêng tư",
        .settingsDangerZone: "Vùng nguy hiểm",
        .settingsDeleteAll: "Xóa tất cả dữ liệu cục bộ",
        .backupCreateTitle: "Tạo bản sao lưu được mã hóa",
        .backupPassphrase: "Mật khẩu sao lưu",
        .backupHint: "Hãy chọn một mật khẩu riêng cho bản sao lưu. Nó cần để khôi phục – mật khẩu không thể lấy lại.",
        .restorePreview: "Xem trước",
        .restoreConfirm: "Thay thế tất cả dữ liệu cục bộ",
        .restoreWarning: "Thao tác này ghi đè vĩnh viễn tất cả dữ liệu cục bộ.",
        .backupInvalid: "Bản sao lưu không hợp lệ hoặc sai mật khẩu.",
        .backupSavedHint: "Hãy giữ tệp sao lưu và mật khẩu ở nơi an toàn.",

        .reportTitle: "Báo cáo sự cố",
        .reportSummary: "Tóm tắt",
        .reportExpected: "Hành vi mong đợi",
        .reportActual: "Hành vi thực tế",
        .reportSteps: "Các bước tái hiện",
        .reportArea: "Khu vực ảnh hưởng",
        .reportRedactionNote: "Dữ liệu nhạy cảm được loại bỏ cục bộ. Bạn xem lại báo cáo trước khi sao chép.",
        .reportCopyHint: "Báo cáo không được gửi tự động. Bạn tự sao chép.",

        .exportReport: "Xuất báo cáo",
        .pdfTitle: "Tổng quan tài chính",
        .pdfSubtitle: "Báo cáo hộ gia đình cá nhân",
        .pdfSummary: "Nhìn nhanh",
        .pdfGeneratedOn: "Được tạo vào",
        .pdfConfidential: "Bảo mật",
        .pdfPage: "Trang",
        .pdfTotal: "Tổng",
        .pdfColProgress: "Tiến độ",
        .pdfUnencryptedNote: "Báo cáo là tệp PDF có thể đọc và không mã hóa. Hãy giữ ở nơi an toàn.",
        .pdfNoData: "Chưa có dữ liệu để xuất.",
        .pdfDefaultHousehold: "Hộ gia đình của tôi",

        .lockTitle: "Đã khóa",
        .lockWelcomeSetup: "Chào mừng đến với Kontiva",
        .lockWelcomeBack: "Chào mừng trở lại",
        .lockSetupTitle: "Đặt mật khẩu",
        .lockEnterPassphrase: "Nhập mật khẩu hoặc PIN",
        .lockWrongPassphrase: "Sai mật khẩu. Hãy thử lại.",
        .lockRecoveryWarning: "Không có khôi phục. Không có mật khẩu, dữ liệu của bạn không thể truy cập.",
        .lockRecoveryAcknowledge: "Tôi hiểu rằng không có khôi phục.",
        .securityNote: "Dữ liệu của bạn được lưu cục bộ và mã hóa (AES-256-GCM). Không đám mây, không máy chủ, không khôi phục mật khẩu.",

        .onboardingIntroBody: "Kontiva giúp bạn giữ một cái nhìn yên tĩnh về ngân sách hộ gia đình Thụy Sĩ – hoàn toàn trên thiết bị này.",
        .onboardingStart: "Bắt đầu",
        .onboardingProfileTitle: "Tạo hồ sơ",
        .onboardingProfileBody: "Đặt cho mình một cái tên và chọn ảnh. Cả hai chỉ ở lại trên thiết bị này.",
        .onboardingSkip: "Bỏ qua",
        .onboardingFeaturePrivate: "Hoàn toàn cục bộ – không đám mây, không theo dõi",
        .onboardingFeatureSecure: "Mã hóa bằng AES-256",
        .onboardingFeatureMoney: "Chính xác đến từng xu, không sai số làm tròn",
        .onboardingConfirmPassphrase: "Xác nhận mật khẩu",
        .onboardingPassphraseNote: "Hãy ghi mật khẩu ở nơi an toàn – không thể đặt lại.",
        .backupNudgeText: "Hãy tạo bản sao lưu được mã hóa. Không có nó, bạn sẽ mất dữ liệu nếu quên mật khẩu.",
        .commonNext: "Tiếp",
        .navMore: "Thêm",
        .actionLock: "Khóa",
        .pinSetTitle: "Đặt mã",
        .pinConfirmTitle: "Xác nhận mã",
        .pinRequirementNote: "Tối thiểu 6 chữ số · không khôi phục",
        .pinMismatch: "Mã không khớp",
    ]
}
