import Foundation

extension Localization {
    static let hr: [L10nKey: String] = [
        .appName: "Kontiva",
        .appTagline: "Smiren, privatan pregled vašeg švicarskog proračuna.",
        .notBetaNotice: "Rana razvojna verzija – nije beta, nije V1.",

        .navOverview: "Pregled",
        .navPlanning: "Mjesečno planiranje",
        .navBills: "Računi",
        .navSettings: "Postavke",
        .navReport: "Prijavi problem",
        .navInsights: "Uvidi",
        .navSparen: "Štednja",
        .sparenSubtitle: "Redoviti doprinosi štednji – i ono što je već prikupljeno.",
        .sparenEmpty: "Još nema ciljeva štednje. Odredite za što štedite svaki mjesec.",
        .sparenMonthlyTotal: "Štednja / mjesec",
        .sparenAccumulatedTotal: "Već ušteđeno",
        .sparenPerMonth: "/ mjesec",
        .sparenContributions: "doprinosa",
        .sparenSince: "od",
        .sparenOpenEnded: "Bez ciljnog iznosa",
        .sparenGoalsLabel: "Ciljevi",
        .sparenSortBy: "Razvrstaj",
        .sparenSortStartMonth: "Početni mjesec",
        .savingsCatCar: "Automobil",
        .savingsCatVacation: "Odmor",
        .savingsCatHome: "Stanovanje",
        .savingsCatRetirement: "Stup 3a / Mirovina",
        .savingsCatEmergency: "Fond za hitne slučajeve",
        .savingsCatEducation: "Obrazovanje",
        .savingsCatOther: "Ostalo",
        .savingsCatWedding: "Vjenčanje",
        .savingsCatFamily: "Obitelj i djeca",
        .savingsCatRenovation: "Renovacija i opremanje",
        .savingsCatElectronics: "Elektronika",
        .savingsCatTaxes: "Rezerva za poreze",
        .savingsCatInvestment: "Ulaganja",
        .savingsCatHealth: "Zdravlje",
        .savingsCatGift: "Pokloni",
        .overviewPlannedSavings: "Štednja ovaj mjesec",
        .overviewShowCalculation: "Prikaži izračun",
        .overviewTrendTitle: "Trend · 6 mjeseci",
        .overviewStatusGood: "Zdrav višak",
        .overviewStatusTight: "Tijesno",
        .overviewStatusNegative: "U minusu",
        .overviewAllocationOf: "neto prihoda",
        .formStartDate: "Štedim od",
        .formStartingBalance: "Početno stanje (neobavezno)",
        .insightsSubtitle: "Smjernice za vaš proračun – gdje je vaš novac i gdje možete uštedjeti.",
        .insightOverspending: "Trošite više nego što zarađujete",
        .insightTightBudget: "Malo prostora ovaj mjesec",
        .insightHealthySurplus: "Zdrav višak",
        .insightHighFixed: "Visoki fiksni troškovi",
        .insightHighHousing: "Visoki troškovi stanovanja",
        .insightLargestFixed: "Najveća stavka fiksnih troškova",
        .insightLargestVariable: "Najveći promjenjivi proračun",
        .insightOverdue: "Dospjeli računi",
        .insightNoSavings: "Štednja još nije planirana",
        .insightGoodSavings: "Dobra stopa štednje",
        .insightAllHealthy: "Vaš proračun izgleda zdravo",
        .insightHousingHint: "Smjernica: najviše trećina prihoda",
        .insightNoSavingsDetail: "Imate prostora – cilj štednje mogao bi pomoći.",
        .insightAllHealthyDetail: "Ništa se ne ističe. Dodajte više podataka za preciznije uvide.",
        .fragOfNetIncome: "neto prihoda",
        .fragOfFixedCosts: "fiksnih troškova",
        .fragShortfall: "Manjak",

        .commonAdd: "Dodaj",
        .commonEdit: "Uredi",
        .commonDelete: "Izbriši",
        .commonCancel: "Odustani",
        .commandsAdd: "Dodaj unos",
        .billsAddCta: "Dodaj svoj prvi račun",
        .sparenAddCta: "Stvori cilj štednje",
        .overviewAddCta: "Dodaj prihod",
        .commonSave: "Spremi",
        .commonSaved: "Spremljeno",
        .commonClose: "Zatvori",
        .commonDone: "Gotovo",
        .commonShowSampleData: "Prikaži primjere podataka",
        .commonHideSampleData: "Sakrij primjere podataka",
        .commonEmptyHint: "Još nema unesenih podataka.",
        .commonCopy: "Kopiraj",
        .commonOptions: "Opcije",
        .commonMoveUp: "Pomakni gore",
        .commonMoveDown: "Pomakni dolje",
        .monthToday: "Danas",

        .formName: "Naziv",
        .formAmount: "Iznos (CHF)",
        .formStatus: "Status",
        .formNotes: "Napomena",
        .formInvalidAmount: "Unesite valjani iznos.",
        .formThirteenthAmount: "13. plaća (iznos)",
        .formThirteenthModel: "Model 13. plaće",
        .thirteenthModelSeparate: "Prikaži zasebno",
        .thirteenthModelAveraged: "Rasporedi na 12 mjeseci",
        .formTarget: "Cilj štednje (iznos)",
        .formSaved: "Već ušteđeno",
        .formMonthlyContribution: "Mjesečni doprinos",
        .formCategory: "Kategorija",
        .formLimitedDuration: "Ograničeni trajni nalog",
        .formLimitedDurationHint: "Npr. 6 rata poreza – broje se samo u tim mjesecima i zatim se automatski uklanjaju.",
        .formStartMonth: "Prva rata",
        .formInstallments: "Broj rata",
        .planningStandingOrder: "Trajni nalog",
        .catRent: "Najamnina",
        .catSubscription: "Pretplata",
        .catLeasing: "Leasing",
        .catUtilities: "Režije",
        .catTelecom: "Telekomunikacije",
        .catGroceries: "Namirnice",
        .catFuel: "Gorivo",
        .catTransport: "Prijevoz",
        .catPersonal: "Osobno",
        .catDining: "Vanjska prehrana",
        .catHousehold: "Kućanstvo",

        .overviewTitle: "Pregled",
        .overviewAvailableThisMonth: "Dostupno ovaj mjesec",
        .overviewNetIncome: "Neto prihod ovaj mjesec",
        .overviewThirteenthSeparate: "13. plaća (zasebno)",
        .overviewRecurringFixed: "Fiksni troškovi",
        .overviewPlannedVariable: "Promjenjivi izdaci",
        .overviewBillsDueThisMonth: "Otvoreni računi ovaj mjesec",
        .overviewOverdueBills: "Dospjeli računi",
        .overviewSavingsTarget: "Cilj štednje",
        .overviewSecurityStatus: "Status sigurnosti",
        .overviewFormulaExplainer: "Dostupno = neto prihod − fiksni troškovi − promjenjivi proračuni − otvoreni računi ovaj mjesec − dospjeli računi. Plaćeni i budući računi ne smanjuju iznos.",
        .overviewEmpty: "Unesite prihode i troškove u Mjesečno planiranje da biste vidjeli pregled.",
        .chartSpendingTitle: "Raspodjela ovaj mjesec",
        .chartByCategory: "Po kategoriji",

        .planningTitle: "Mjesečno planiranje",
        .planningIncome: "Prihod",
        .planningFixed: "Fiksni troškovi",
        .planningVariable: "Promjenjivi izdaci",
        .planningSavings: "Cilj štednje",
        .planningFixedExplainer: "Fiksni troškovi ponavljaju se svaki mjesec: najamnina, osiguranja, pretplate, leasing.",
        .planningVariableExplainer: "Promjenjive proračune planirate sami: namirnice, gorivo, osobni izdaci.",
        .planningOneOffHint: "Jednokratnim računima upravljate u „Računi”.",
        .planningEmpty: "Počnite s prihodom, a zatim dodajte fiksne troškove i proračune.",
        .planningBalance: "Planirano stanje",

        .billsTitle: "Računi",
        .billsStatusOpen: "Otvoren",
        .billsStatusPaid: "Plaćen",
        .billsStateOverdue: "Dospio",
        .billsStateDueThisMonth: "Dospijeva ovaj mjesec",
        .billsStateFuture: "Budući",
        .billsAffectsBalance: "Smanjuje dostupni iznos",
        .billsNoBalanceImpact: "Bez učinka ovaj mjesec",
        .billsDueDate: "Datum dospijeća",
        .billsProvider: "Pružatelj",
        .billsEmpty: "Još nema računa. Jednokratni računi s datumom dospijeća prikazat će se ovdje.",
        .billsMarkPaid: "Označi kao plaćeno",
        .billsMarkOpen: "Označi kao otvoreno",
        .billsOpenTotal: "Ukupno otvoreno",

        .navSchulden: "Dugovi",
        .schuldenSubtitle: "Pratite dospjele račune i prisilnu naplatu.",
        .schuldenEmpty: "Nema zabilježenih dugova. Dospjeli računi prikazuju se ovdje automatski – a možete zabilježiti prisilnu naplatu (Betreibung) ili potvrde o gubitku.",
        .schuldenAddCta: "Zabilježi dug",
        .schuldenTotal: "Ukupni dug",
        .schuldenOverdueBills: "Dospjeli računi",
        .schuldenRecorded: "Zabilježeni dugovi",
        .schuldenManagedInBills: "Dospjelim računima upravljajte u „Računi”.",
        .debtTypeOpenClaim: "Otvoreno potraživanje",
        .debtTypeBetreibung: "Prisilna naplata",
        .debtTypePfaendung: "Ovrha na plaći/imovini",
        .debtTypeVerlustschein: "Potvrda o gubitku",
        .debtTypeOther: "Drugi dug",
        .debtCreditor: "Vjerovnik",
        .debtReference: "Referenca / broj predmeta",
        .debtDate: "Datum",
        .debtType: "Vrsta",
        .schuldenGuidanceTitle: "Kako izaći iz dugova",
        .schuldenTipContactTitle: "Javite se rano",
        .schuldenTipContactBody: "Razgovarajte s vjerovnicima rano. Pisani plan obročne otplate često je moguć i izbjegava formalni postupak.",
        .schuldenTipBetreibungTitle: "Ako počne naplata",
        .schuldenTipBetreibungBody: "Nakon platnog naloga imate 20 dana za plaćanje – ili 10 dana za podnošenje prigovora (Rechtsvorschlag) ako je potraživanje neopravdano.",
        .schuldenTipExistenzminimumTitle: "Vaš egzistencijalni minimum je zaštićen",
        .schuldenTipExistenzminimumBody: "Pri ovrsi vaš egzistencijalni minimum ostaje nedirnut – osnovni iznos, najamnina, zdravstveno osiguranje i socijalni doprinosi.",
        .schuldenTipVerlustscheinTitle: "Potvrda o gubitku",
        .schuldenTipVerlustscheinBody: "Potvrda o gubitku zastarijeva tek nakon 20 godina. Možete biti ponovno gonjeni samo kada steknete novu imovinu.",
        .schuldenTipCounselingTitle: "Besplatno savjetovanje o dugovima",
        .schuldenTipCounselingBody: "Schuldenberatung Schweiz, Caritas i proračunsko savjetovanje pomažu besplatno i povjerljivo. Prvo otplatite dugove s najgorim posljedicama.",
        .schuldenDisclaimer: "Opće informacije, nije pravni savjet.",

        .catInsurance: "Osiguranje",
        .catOther: "Ostalo",
        .catMortgage: "Hipotekarni kredit",
        .catHealthInsurance: "Zdravstveno osiguranje",
        .catSerafe: "Radio/TV (Serafe)",
        .catPublicTransport: "Prijevozna karta",
        .catChildcare: "Čuvanje djece",
        .catMembership: "Članarine",
        .catAlimony: "Uzdržavanje",
        .catTaxes: "Porezi",
        .catClothing: "Odjeća",
        .catHealth: "Zdravlje",
        .catLeisure: "Slobodno vrijeme i hobiji",
        .catEntertainment: "Zabava",
        .catChildren: "Djeca",
        .catPets: "Kućni ljubimci",
        .catGifts: "Pokloni",
        .catTravel: "Putovanja",
        .catCharity: "Donacije",
        .catEducation: "Obrazovanje",

        .settingsTitle: "Postavke",
        .settingsLanguage: "Jezik",
        .settingsTheme: "Tema boja",
        .themeSwissRed: "Švicarska crvena",
        .themeOrange: "Narančasta",
        .themeSand: "Pijesak",
        .themeGreen: "Zelena",
        .themeTeal: "Tirkizna",
        .themeBlue: "Plava",
        .themePurple: "Ljubičasta",
        .themePink: "Roza",
        .settingsData: "Podaci",
        .settingsHousehold: "Kućanstvo",
        .settingsCanton: "Kanton",
        .settingsProfile: "Profil",
        .profileName: "Ime",
        .profileChoosePicture: "Odaberi profilnu sliku",
        .profileNoPicture: "Bez slike",
        .profileLocalNote: "Pohranjeno samo lokalno na ovom uređaju.",
        .settingsSecurity: "Sigurnost",
        .settingsAutoLock: "Automatsko zaključavanje",
        .settingsBiometric: "Biometrijsko otključavanje",
        .settingsChangePassphrase: "Promijeni lozinku/PIN",
        .settingsBackup: "Šifrirana sigurnosna kopija",
        .settingsRestore: "Vrati",
        .settingsPrivacy: "Privatnost",
        .settingsDangerZone: "Opasna zona",
        .settingsDeleteAll: "Izbriši sve lokalne podatke",
        .backupCreateTitle: "Stvori šifriranu sigurnosnu kopiju",
        .backupPassphrase: "Lozinka sigurnosne kopije",
        .backupHint: "Odaberite zasebnu lozinku za sigurnosnu kopiju. Potrebna je za vraćanje – lozinku nije moguće oporaviti.",
        .restorePreview: "Pretpregled",
        .restoreConfirm: "Zamijeni sve lokalne podatke",
        .restoreWarning: "Ovo trajno prebrisuje sve lokalne podatke.",
        .backupInvalid: "Nevaljana sigurnosna kopija ili pogrešna lozinka.",
        .backupSavedHint: "Čuvajte datoteku sigurnosne kopije i lozinku na sigurnom mjestu.",

        .reportTitle: "Prijavi problem",
        .reportSummary: "Sažetak",
        .reportExpected: "Očekivano ponašanje",
        .reportActual: "Stvarno ponašanje",
        .reportSteps: "Koraci za reprodukciju",
        .reportArea: "Zahvaćeno područje",
        .reportRedactionNote: "Osjetljivi podaci uklanjaju se lokalno. Pregledavate izvješće prije kopiranja.",
        .reportCopyHint: "Izvješće se ne šalje automatski. Sami ga kopirate.",

        .exportReport: "Izvezi izvješće",
        .pdfTitle: "Financijski pregled",
        .pdfSubtitle: "Osobno izvješće kućanstva",
        .pdfSummary: "Na prvi pogled",
        .pdfGeneratedOn: "Izrađeno",
        .pdfConfidential: "Povjerljivo",
        .pdfPage: "Stranica",
        .pdfTotal: "Ukupno",
        .pdfColProgress: "Napredak",
        .pdfUnencryptedNote: "Izvješće je čitljiv, nešifrirani PDF. Čuvajte ga na sigurnom mjestu.",
        .pdfNoData: "Još nema podataka za izvoz.",
        .pdfDefaultHousehold: "Moje kućanstvo",

        .lockTitle: "Zaključano",
        .lockWelcomeSetup: "Dobrodošli u Kontivu",
        .lockWelcomeBack: "Dobrodošli natrag",
        .lockSetupTitle: "Postavi lozinku",
        .lockEnterPassphrase: "Unesite lozinku ili PIN",
        .lockWrongPassphrase: "Pogrešna lozinka. Pokušajte ponovno.",
        .lockRecoveryWarning: "Nema oporavka. Bez vaše lozinke vašim podacima nije moguće pristupiti.",
        .lockRecoveryAcknowledge: "Razumijem da nema oporavka.",
        .securityNote: "Vaši podaci pohranjeni su lokalno i šifrirani (AES-256-GCM). Bez oblaka, bez poslužitelja, bez oporavka lozinke.",

        .onboardingIntroBody: "Kontiva vam pomaže zadržati smiren pregled proračuna vašeg švicarskog kućanstva – u potpunosti na ovom uređaju.",
        .onboardingStart: "Započni",
        .onboardingProfileTitle: "Stvori profil",
        .onboardingProfileBody: "Dajte si ime i odaberite sliku. Oboje ostaje samo na ovom uređaju.",
        .onboardingSkip: "Preskoči",
        .onboardingFeaturePrivate: "Potpuno lokalno – bez oblaka, bez praćenja",
        .onboardingFeatureSecure: "Šifrirano s AES-256",
        .onboardingFeatureMoney: "Točno do centima, bez pogrešaka zaokruživanja",
        .onboardingConfirmPassphrase: "Potvrdi lozinku",
        .onboardingPassphraseNote: "Zapišite lozinku na sigurno mjesto – nije ju moguće poništiti.",
        .backupNudgeText: "Stvorite šifriranu sigurnosnu kopiju. Bez nje gubite podatke ako zaboravite lozinku.",
        .commonNext: "Dalje",
        .navMore: "Više",
        .actionLock: "Zaključaj",
        .pinSetTitle: "Postavi kod",
        .pinConfirmTitle: "Potvrdi kod",
        .pinRequirementNote: "Min. 6 znamenki · bez oporavka",
        .pinMismatch: "Kodovi se ne podudaraju",
    ]
}
