import Foundation

extension Localization {
    static let da: [L10nKey: String] = [
        .appName: "Kontiva",
        .appTagline: "Et roligt, privat overblik over dit schweiziske budget.",
        .notBetaNotice: "Tidlig udviklingsversion – ikke beta, ikke V1.",

        .navOverview: "Overblik",
        .navPlanning: "Plan",
        .navBills: "Regninger",
        .navSettings: "Indstillinger",
        .navReport: "Rapportér et problem",
        .navInsights: "Indsigt",
        .navSparen: "Opsparing",
        .sparenSubtitle: "Tilbagevendende opsparingsbidrag – og hvad der allerede er sparet op.",
        .sparenEmpty: "Ingen opsparingsmål endnu. Vælg, hvad du sparer op til hver måned.",
        .sparenMonthlyTotal: "Opsparing / måned",
        .sparenAccumulatedTotal: "Allerede sparet",
        .sparenPerMonth: "/ måned",
        .sparenContributions: "bidrag",
        .sparenSince: "siden",
        .sparenOpenEnded: "Intet målbeløb",
        .sparenGoalReached: "Mål nået",
        .sparenGoalReachedMessage: "Tillykke! Du har nået dit sparemål. Hvordan vil du fortsætte?",
        .sparenGoalIncrease: "Hæv målet",
        .sparenGoalComplete: "Marker som færdig",
        .sparenGoalKeep: "Fortsæt med at spare",
        .sparenGoalCompleted: "Færdig",
        .sparenGoalReopen: "Genaktivér",
        .sparenGoalsLabel: "Mål",
        .sparenSortBy: "Sortér",
        .sparenSortStartMonth: "Startmåned",
        .savingsCatCar: "Bil",
        .savingsCatVacation: "Ferie",
        .savingsCatHome: "Bolig",
        .savingsCatRetirement: "Søjle 3a / Pension",
        .savingsCatEmergency: "Nødopsparing",
        .savingsCatEducation: "Uddannelse",
        .savingsCatOther: "Andet",
        .savingsCatWedding: "Bryllup",
        .savingsCatFamily: "Familie og børn",
        .savingsCatRenovation: "Renovering og indretning",
        .savingsCatElectronics: "Elektronik",
        .savingsCatTaxes: "Skattereserve",
        .savingsCatInvestment: "Investeringer",
        .savingsCatHealth: "Sundhed",
        .savingsCatGift: "Gaver",
        .overviewPlannedSavings: "Opsparing denne måned",
        .overviewShowCalculation: "Vis beregning",
        .overviewTrendTitle: "Tendens · 6 måneder",
        .overviewStatusGood: "Sundt overskud",
        .overviewStatusTight: "Stramt",
        .overviewStatusNegative: "I minus",
        .overviewAllocationOf: "af nettoindkomsten",
        .formStartDate: "Sparer siden",
        .formStartingBalance: "Startsaldo (valgfri)",
        .insightsSubtitle: "Vejledning om dit budget – hvor dine penge er, og hvor du kan spare.",
        .insightOverspending: "Du bruger mere, end du tjener",
        .insightTightBudget: "Lidt plads denne måned",
        .insightHealthySurplus: "Sundt overskud",
        .insightHighFixed: "Høje faste udgifter",
        .insightHighHousing: "Høje boligudgifter",
        .insightLargestFixed: "Største post i faste udgifter",
        .insightLargestVariable: "Største variable budget",
        .insightOverdue: "Forfaldne regninger",
        .insightNoSavings: "Ingen opsparing planlagt endnu",
        .insightGoodSavings: "God opsparingsrate",
        .insightAllHealthy: "Dit budget ser sundt ud",
        .insightHousingHint: "Vejledning: højst en tredjedel af indkomsten",
        .insightNoSavingsDetail: "Du har plads – et opsparingsmål kunne hjælpe.",
        .insightAllHealthyDetail: "Intet skiller sig ud. Tilføj flere data for skarpere indsigt.",
        .insightExtraIncome: "Ekstra indkomst denne måned",
        .insightGoalProgress: "Sparemål inden for rækkevidde",
        .insightBillsDueSoon: "Stadig at betale denne måned",
        .insightGettingStarted: "Kom godt i gang",
        .insightGettingStartedDetail: "Tilføj din indkomst for at se dine personlige indsigter.",
        .schuldenEncourageTitle: "Et skridt ad gangen",
        .schuldenEncourageBody: "Du tager fat. Her er konkrete næste skridt.",
        .fragOfNetIncome: "af nettoindkomsten",
        .fragOfFixedCosts: "af de faste udgifter",
        .fragShortfall: "Underskud",

        .commonAdd: "Tilføj",
        .commonEdit: "Rediger",
        .commonActivate: "Aktivér",
        .commonDelete: "Slet",
        .commonCancel: "Annuller",
        .commandsAdd: "Tilføj post",
        .billsAddCta: "Tilføj din første regning",
        .sparenAddCta: "Opret et opsparingsmål",
        .overviewAddCta: "Tilføj indkomst",
        .commonSave: "Gem",
        .commonSaved: "Gemt",
        .commonClose: "Luk",
        .commonDone: "Færdig",
        .commonShowSampleData: "Vis eksempeldata",
        .commonHideSampleData: "Skjul eksempeldata",
        .commonEmptyHint: "Endnu ingen data indtastet.",
        .commonCopy: "Kopiér",
        .commonOptions: "Indstillinger",
        .commonMoveUp: "Flyt op",
        .commonMoveDown: "Flyt ned",
        .monthToday: "I dag",

        .formName: "Navn",
        .formAmount: "Beløb (CHF)",
        .formStatus: "Status",
        .formNotes: "Note",
        .formInvalidAmount: "Indtast et gyldigt beløb.",
        .formThirteenthAmount: "13. månedsløn (beløb)",
        .formThirteenthModel: "Model for 13. månedsløn",
        .incomeBonuses: "Ekstra udbetalinger",
        .formMonth: "Måned",
        .thirteenthModelSeparate: "Vis separat",
        .thirteenthModelAveraged: "Fordel over 12 måneder",
        .formTarget: "Opsparingsmål (beløb)",
        .formSaved: "Allerede sparet",
        .formMonthlyContribution: "Månedligt bidrag",
        .formCategory: "Kategori",
        .formLimitedDuration: "Tidsbegrænset fast overførsel",
        .formLimitedDurationHint: "F.eks. 6 skatterater – tælles kun i de måneder og fjernes derefter automatisk.",
        .formStartMonth: "Første rate",
        .formInstallments: "Antal rater",
        .planningStandingOrder: "Fast overførsel",
        .catRent: "Husleje",
        .catSubscription: "Abonnement",
        .catLeasing: "Leasing",
        .catUtilities: "Forsyning",
        .catTelecom: "Telekom",
        .catGroceries: "Dagligvarer",
        .catFuel: "Brændstof",
        .catTransport: "Transport",
        .catPersonal: "Personligt",
        .catDining: "Spise ude",
        .catHousehold: "Husholdning",

        .overviewTitle: "Overblik",
        .overviewAvailableThisMonth: "Til rådighed denne måned",
        .overviewNetIncome: "Nettoindkomst denne måned",
        .overviewThirteenthSeparate: "13. månedsløn (vist separat)",
        .overviewRecurringFixed: "Faste udgifter",
        .overviewPlannedVariable: "Variable udgifter",
        .overviewBillsDueThisMonth: "Regninger denne måned",
        .overviewOverdueBills: "Forfaldne regninger",
        .overviewSavingsTarget: "Opsparingsmål",
        .overviewSecurityStatus: "Sikkerhedsstatus",
        .overviewFormulaExplainer: "Til rådighed = nettoindkomst − faste udgifter − variable budgetter − åbne regninger denne måned − forfaldne regninger. Betalte og fremtidige regninger reducerer ikke beløbet.",
        .overviewEmpty: "Indtast indkomst og udgifter i Månedsplan for at se dit overblik.",
        .chartSpendingTitle: "Fordeling denne måned",
        .chartByCategory: "Efter kategori",

        .planningTitle: "Månedsplan",
        .planningIncome: "Indkomst",
        .planningFixed: "Faste udgifter",
        .planningVariable: "Variable udgifter",
        .planningSavings: "Opsparingsmål",
        .planningFixedExplainer: "Faste udgifter gentages hver måned: husleje, forsikringer, abonnementer, leasing.",
        .planningVariableExplainer: "Variable budgetter planlægger du selv: dagligvarer, brændstof, personlige udgifter.",
        .planningOneOffHint: "Engangsregninger administreres under “Regninger”.",
        .planningEmpty: "Begynd med din indkomst, og tilføj derefter faste udgifter og budgetter.",
        .planningBalance: "Planlagt saldo",

        .billsTitle: "Regninger",
        .billsStatusOpen: "Åben",
        .billsStatusPaid: "Betalt",
        .billsStateOverdue: "Forfalden",
        .billsStateDueThisMonth: "Forfalder denne måned",
        .billsStateFuture: "Fremtidig",
        .billsAffectsBalance: "Reducerer det tilgængelige beløb",
        .billsNoBalanceImpact: "Ingen effekt denne måned",
        .billsDueDate: "Forfaldsdato",
        .billsProvider: "Udbyder",
        .billsEmpty: "Endnu ingen regninger. Engangsregninger med forfaldsdato vises her.",
        .billsMarkPaid: "Markér som betalt",
        .billsMarkOpen: "Markér som åben",
        .billsOpenTotal: "Åbent i alt",

        .navSchulden: "Gæld",
        .schuldenSubtitle: "Hold øje med forfaldne regninger og inddrivelse.",
        .schuldenEmpty: "Ingen gæld registreret. Forfaldne regninger vises her automatisk – og du kan notere inddrivelse (Betreibung) eller tabsattester.",
        .schuldenAddCta: "Registrér en gæld",
        .schuldenTotal: "Samlet gæld",
        .schuldenOverdueBills: "Forfaldne regninger",
        .schuldenRecorded: "Registreret gæld",
        .schuldenManagedInBills: "Administrér forfaldne regninger under “Regninger”.",
        .debtTypeOpenClaim: "Åbent krav",
        .debtTypeBetreibung: "Inddrivelse",
        .debtTypePfaendung: "Løn-/aktivudlæg",
        .debtTypeVerlustschein: "Tabsattest",
        .debtTypeOther: "Anden gæld",
        .debtCreditor: "Kreditor",
        .debtReference: "Reference / sagsnr.",
        .debtDate: "Dato",
        .debtType: "Type",
        .schuldenGuidanceTitle: "Find vej ud af gælden",
        .schuldenTipContactTitle: "Tag kontakt tidligt",
        .schuldenTipContactBody: "Tal med kreditorerne tidligt. En skriftlig afdragsordning er ofte mulig og undgår formel inddrivelse.",
        .schuldenTipBetreibungTitle: "Hvis inddrivelsen begynder",
        .schuldenTipBetreibungBody: "Efter betalingspåkravet har du 20 dage til at betale – eller 10 dage til at gøre indsigelse (Rechtsvorschlag), hvis kravet er uberettiget.",
        .schuldenTipExistenzminimumTitle: "Dit eksistensminimum er beskyttet",
        .schuldenTipExistenzminimumBody: "Ved udlæg forbliver dit eksistensminimum urørligt – grundbeløb, husleje, sygesikring og sociale bidrag.",
        .schuldenTipVerlustscheinTitle: "Tabsattest",
        .schuldenTipVerlustscheinBody: "En tabsattest forældes først efter 20 år. Du kan kun forfølges igen, når du erhverver nye midler.",
        .schuldenTipCounselingTitle: "Gratis gældsrådgivning",
        .schuldenTipCounselingBody: "Schuldenberatung Schweiz, Caritas og budgetrådgivning hjælper gratis og fortroligt. Betal først den gæld med de værste konsekvenser.",
        .schuldenDisclaimer: "Generel information, ikke juridisk rådgivning.",

        .catInsurance: "Forsikring",
        .catOther: "Andet",
        .catMortgage: "Realkreditlån",
        .catHealthInsurance: "Sygesikring",
        .catSerafe: "Radio/tv (Serafe)",
        .catPublicTransport: "Pendlerkort",
        .catChildcare: "Børnepasning",
        .catMembership: "Medlemskaber",
        .catAlimony: "Underholdsbidrag",
        .catTaxes: "Skatter",
        .catRatenzahlung: "Afdrag",
        .catStreaming: "Streaming",
        .catCreditCard: "Kreditkort",
        .catClothing: "Tøj",
        .catHealth: "Sundhed",
        .catLeisure: "Fritid og hobbyer",
        .catEntertainment: "Underholdning",
        .catChildren: "Børn",
        .catPets: "Kæledyr",
        .catGifts: "Gaver",
        .catTravel: "Rejser",
        .catCharity: "Velgørenhed",
        .catEducation: "Uddannelse",

        .settingsTitle: "Indstillinger",
        .settingsLanguage: "Sprog",
        .settingsTheme: "Farvetema",
        .themeSwissRed: "Schweizerrød",
        .themeOrange: "Orange",
        .themeSand: "Sand",
        .themeGreen: "Grøn",
        .themeTeal: "Blågrøn",
        .themeBlue: "Blå",
        .themePurple: "Lilla",
        .themePink: "Pink",
        .settingsData: "Data",
        .settingsHousehold: "Husstand",
        .settingsCanton: "Kanton",
        .settingsProfile: "Profil",
        .profileName: "Navn",
        .profileChoosePicture: "Vælg profilbillede",
        .profileNoPicture: "Intet billede",
        .profileLocalNote: "Gemmes kun lokalt på denne enhed.",
        .settingsSecurity: "Sikkerhed",
        .settingsAutoLock: "Automatisk lås",
        .settingsBiometric: "Biometrisk oplåsning",
        .settingsChangePassphrase: "Skift adgangskode/PIN",
        .settingsBackup: "Krypteret sikkerhedskopi",
        .settingsRestore: "Gendan",
        .settingsPrivacy: "Privatliv",
        .settingsDangerZone: "Farezone",
        .settingsDeleteAll: "Slet alle lokale data",
        .backupCreateTitle: "Opret krypteret sikkerhedskopi",
        .backupPassphrase: "Adgangskode til sikkerhedskopi",
        .backupHint: "Vælg en separat adgangskode til sikkerhedskopien. Den er nødvendig for at gendanne – der er ingen måde at gendanne den på.",
        .restorePreview: "Forhåndsvisning",
        .restoreConfirm: "Erstat alle lokale data",
        .restoreWarning: "Dette overskriver permanent alle lokale data.",
        .backupInvalid: "Ugyldig sikkerhedskopi eller forkert adgangskode.",
        .backupSavedHint: "Opbevar sikkerhedskopifilen og adgangskoden et sikkert sted.",

        .reportTitle: "Rapportér et problem",
        .reportSummary: "Resumé",
        .reportExpected: "Forventet adfærd",
        .reportActual: "Faktisk adfærd",
        .reportSteps: "Trin til at gengive",
        .reportArea: "Berørt område",
        .reportRedactionNote: "Følsomme data fjernes lokalt. Du gennemgår rapporten, før du kopierer den.",
        .reportCopyHint: "Rapporten sendes ikke automatisk. Du kopierer den selv.",

        .exportReport: "Eksportér rapport",
        .pdfTitle: "Finansielt overblik",
        .pdfSubtitle: "Personlig husstandsrapport",
        .pdfSummary: "Overblik",
        .pdfGeneratedOn: "Genereret den",
        .pdfConfidential: "Fortroligt",
        .pdfPage: "Side",
        .pdfTotal: "I alt",
        .pdfColProgress: "Fremskridt",
        .pdfUnencryptedNote: "Rapporten er en læsbar, ukrypteret PDF. Opbevar den et sikkert sted.",
        .pdfNoData: "Endnu ingen data at eksportere.",
        .pdfDefaultHousehold: "Min husstand",

        .lockTitle: "Låst",
        .lockWelcomeSetup: "Velkommen til Kontiva",
        .lockWelcomeBack: "Velkommen tilbage",
        .lockSetupTitle: "Opret adgangskode",
        .lockEnterPassphrase: "Indtast adgangskode eller PIN",
        .lockWrongPassphrase: "Forkert adgangskode. Prøv igen.",
        .lockRecoveryWarning: "Der er ingen gendannelse. Uden din adgangskode kan dine data ikke tilgås.",
        .lockRecoveryAcknowledge: "Jeg forstår, at der ikke er nogen gendannelse.",
        .securityNote: "Dine data gemmes lokalt og krypteret (AES-256-GCM). Ingen sky, ingen server, ingen gendannelse af adgangskode.",

        .onboardingIntroBody: "Kontiva hjælper dig med at bevare et roligt overblik over dit schweiziske husstandsbudget – helt på denne enhed.",
        .onboardingStart: "Kom i gang",
        .onboardingProfileTitle: "Opret en profil",
        .onboardingProfileBody: "Giv dig selv et navn og vælg et billede. Begge forbliver kun på denne enhed.",
        .onboardingSkip: "Spring over",
        .onboardingFeaturePrivate: "Helt lokal – ingen sky, ingen sporing",
        .onboardingFeatureSecure: "Krypteret med AES-256",
        .onboardingFeatureMoney: "Præcis ned til centimen, ingen afrundingsfejl",
        .onboardingConfirmPassphrase: "Bekræft adgangskode",
        .onboardingPassphraseNote: "Skriv din adgangskode ned et sikkert sted – den kan ikke nulstilles.",
        .backupNudgeText: "Opret en krypteret sikkerhedskopi. Uden den mister du dine data, hvis du glemmer adgangskoden.",
        .commonNext: "Næste",
        .navMore: "Mere",
        .actionLock: "Lås",
        .pinSetTitle: "Vælg kode",
        .pinConfirmTitle: "Bekræft kode",
        .pinRequirementNote: "Min. 6 cifre · ingen gendannelse",
        .pinMismatch: "Koderne stemmer ikke overens",
    ]
}
