import Foundation

extension Localization {
    static let nb: [L10nKey: String] = [
        .appName: "Kontiva",
        .appTagline: "Et rolig, privat overblikk over det sveitsiske budsjettet ditt.",
        .notBetaNotice: "Tidlig utviklingsversjon – ikke beta, ikke V1.",

        .navOverview: "Oversikt",
        .navPlanning: "Plan",
        .navBills: "Regninger",
        .navSettings: "Innstillinger",
        .navReport: "Rapporter et problem",
        .navInsights: "Innsikt",
        .navSparen: "Sparing",
        .sparenSubtitle: "Faste sparebidrag – og det du allerede har spart opp.",
        .sparenEmpty: "Ingen sparemål ennå. Bestem hva du sparer til hver måned.",
        .sparenMonthlyTotal: "Sparing / måned",
        .sparenAccumulatedTotal: "Allerede spart",
        .sparenPerMonth: "/ måned",
        .sparenContributions: "bidrag",
        .sparenSince: "siden",
        .sparenOpenEnded: "Ingen målsum",
        .sparenGoalReached: "Mål nådd",
        .sparenGoalReachedMessage: "Gratulerer! Du har nådd sparemålet. Hvordan vil du fortsette?",
        .sparenGoalIncrease: "Øk målet",
        .sparenGoalComplete: "Merk som ferdig",
        .sparenGoalKeep: "Fortsett å spare",
        .sparenGoalCompleted: "Fullført",
        .sparenGoalReopen: "Reaktiver",
        .sparenGoalsLabel: "Mål",
        .sparenSortBy: "Sorter",
        .sparenSortStartMonth: "Startmåned",
        .savingsCatCar: "Bil",
        .savingsCatVacation: "Ferie",
        .savingsCatHome: "Bolig",
        .savingsCatRetirement: "Søyle 3a / Pensjon",
        .savingsCatEmergency: "Bufferkonto",
        .savingsCatEducation: "Utdanning",
        .savingsCatOther: "Annet",
        .savingsCatWedding: "Bryllup",
        .savingsCatFamily: "Familie og barn",
        .savingsCatRenovation: "Oppussing og innredning",
        .savingsCatElectronics: "Elektronikk",
        .savingsCatTaxes: "Skattereserve",
        .savingsCatInvestment: "Investeringer",
        .savingsCatHealth: "Helse",
        .savingsCatGift: "Gaver",
        .overviewPlannedSavings: "Sparing denne måneden",
        .overviewShowCalculation: "Vis beregning",
        .overviewTrendTitle: "Trend · 6 måneder",
        .overviewStatusGood: "Sunt overskudd",
        .overviewStatusTight: "Stramt",
        .overviewStatusNegative: "I minus",
        .overviewAllocationOf: "av nettoinntekten",
        .formStartDate: "Sparer siden",
        .formStartingBalance: "Startsaldo (valgfritt)",
        .insightsSubtitle: "Veiledning om budsjettet ditt – hvor pengene dine er, og hvor du kan spare.",
        .insightOverspending: "Du bruker mer enn du tjener",
        .insightTightBudget: "Lite rom denne måneden",
        .insightHealthySurplus: "Sunt overskudd",
        .insightHighFixed: "Høye faste utgifter",
        .insightHighHousing: "Høye boutgifter",
        .insightLargestFixed: "Største faste utgiftspost",
        .insightLargestVariable: "Største variable budsjett",
        .insightOverdue: "Forfalte regninger",
        .insightNoSavings: "Ingen sparing planlagt ennå",
        .insightGoodSavings: "God sparerate",
        .insightAllHealthy: "Budsjettet ditt ser sunt ut",
        .insightHousingHint: "Veiledende: høyst en tredjedel av inntekten",
        .insightNoSavingsDetail: "Du har rom – et sparemål kan hjelpe.",
        .insightAllHealthyDetail: "Ingenting skiller seg ut. Legg til mer data for skarpere innsikt.",
        .insightExtraIncome: "Ekstra inntekt denne måneden",
        .insightGoalProgress: "Sparemål innen rekkevidde",
        .insightBillsDueSoon: "Fortsatt å betale denne måneden",
        .insightGettingStarted: "Kom i gang",
        .insightGettingStartedDetail: "Legg til inntekten din for å se personlige innsikter.",
        .schuldenEncourageTitle: "Ett skritt om gangen",
        .schuldenEncourageBody: "Du tar tak i det. Her er konkrete neste steg.",
        .fragOfNetIncome: "av nettoinntekten",
        .fragOfFixedCosts: "av de faste utgiftene",
        .fragShortfall: "Underskudd",

        .commonAdd: "Legg til",
        .commonEdit: "Rediger",
        .commonActivate: "Aktiver",
        .commonDelete: "Slett",
        .commonCancel: "Avbryt",
        .commandsAdd: "Legg til oppføring",
        .billsAddCta: "Legg til din første regning",
        .sparenAddCta: "Opprett et sparemål",
        .overviewAddCta: "Legg til inntekt",
        .commonSave: "Lagre",
        .commonSaved: "Lagret",
        .commonClose: "Lukk",
        .commonDone: "Ferdig",
        .commonShowSampleData: "Vis eksempeldata",
        .commonHideSampleData: "Skjul eksempeldata",
        .commonEmptyHint: "Ingen data lagt inn ennå.",
        .commonCopy: "Kopier",
        .commonOptions: "Valg",
        .commonMoveUp: "Flytt opp",
        .commonMoveDown: "Flytt ned",
        .monthToday: "I dag",

        .formName: "Navn",
        .formAmount: "Beløp (CHF)",
        .formStatus: "Status",
        .formNotes: "Notat",
        .formInvalidAmount: "Skriv inn et gyldig beløp.",
        .formThirteenthAmount: "13. månedslønn (beløp)",
        .formThirteenthModel: "Modell for 13. månedslønn",
        .incomeBonuses: "Ekstra utbetalinger",
        .formMonth: "Måned",
        .thirteenthModelSeparate: "Vis separat",
        .thirteenthModelAveraged: "Fordel over 12 måneder",
        .formTarget: "Sparemål (beløp)",
        .formSaved: "Allerede spart",
        .formMonthlyContribution: "Månedlig bidrag",
        .formCategory: "Kategori",
        .formLimitedDuration: "Tidsbegrenset fast overføring",
        .formLimitedDurationHint: "F.eks. 6 skatterater – telles bare i de månedene og fjernes deretter automatisk.",
        .formStartMonth: "Første rate",
        .formInstallments: "Antall rater",
        .planningStandingOrder: "Fast overføring",
        .catRent: "Husleie",
        .catSubscription: "Abonnement",
        .catLeasing: "Leasing",
        .catUtilities: "Strøm og vann",
        .catTelecom: "Telekom",
        .catGroceries: "Dagligvarer",
        .catFuel: "Drivstoff",
        .catTransport: "Transport",
        .catPersonal: "Personlig",
        .catDining: "Spise ute",
        .catHousehold: "Husholdning",

        .overviewTitle: "Oversikt",
        .overviewAvailableThisMonth: "Tilgjengelig denne måneden",
        .overviewNetIncome: "Nettoinntekt denne måneden",
        .overviewThirteenthSeparate: "13. månedslønn (vist separat)",
        .overviewRecurringFixed: "Faste utgifter",
        .overviewPlannedVariable: "Variable utgifter",
        .overviewBillsDueThisMonth: "Regninger denne måneden",
        .overviewOverdueBills: "Forfalte regninger",
        .overviewSavingsTarget: "Sparemål",
        .overviewSecurityStatus: "Sikkerhetsstatus",
        .overviewFormulaExplainer: "Tilgjengelig = nettoinntekt − faste utgifter − variable budsjetter − åpne regninger denne måneden − forfalte regninger. Betalte og fremtidige regninger reduserer ikke beløpet.",
        .overviewEmpty: "Legg inn inntekt og utgifter i Månedsplan for å se oversikten din.",
        .chartSpendingTitle: "Fordeling denne måneden",
        .chartByCategory: "Etter kategori",

        .planningTitle: "Månedsplan",
        .planningIncome: "Inntekt",
        .planningFixed: "Faste utgifter",
        .planningVariable: "Variable utgifter",
        .planningSavings: "Sparemål",
        .planningFixedExplainer: "Faste utgifter gjentas hver måned: husleie, forsikringer, abonnementer, leasing.",
        .planningVariableExplainer: "Variable budsjetter planlegger du selv: dagligvarer, drivstoff, personlige utgifter.",
        .planningOneOffHint: "Engangsregninger administreres under «Regninger».",
        .planningEmpty: "Start med inntekten din, og legg deretter til faste utgifter og budsjetter.",
        .planningBalance: "Planlagt saldo",

        .billsTitle: "Regninger",
        .billsStatusOpen: "Åpen",
        .billsStatusPaid: "Betalt",
        .billsStateOverdue: "Forfalt",
        .billsStateDueThisMonth: "Forfaller denne måneden",
        .billsStateFuture: "Fremtidig",
        .billsAffectsBalance: "Reduserer tilgjengelig beløp",
        .billsNoBalanceImpact: "Ingen effekt denne måneden",
        .billsDueDate: "Forfallsdato",
        .billsProvider: "Leverandør",
        .billsEmpty: "Ingen regninger ennå. Engangsregninger med forfallsdato vises her.",
        .billsMarkPaid: "Merk som betalt",
        .billsMarkOpen: "Merk som åpen",
        .billsOpenTotal: "Åpent totalt",

        .navSchulden: "Gjeld",
        .schuldenSubtitle: "Hold øye med forfalte regninger og inndriving.",
        .schuldenEmpty: "Ingen gjeld registrert. Forfalte regninger vises her automatisk – og du kan notere inndriving (Betreibung) eller tapsattester.",
        .schuldenAddCta: "Registrer en gjeld",
        .schuldenTotal: "Samlet gjeld",
        .schuldenOverdueBills: "Forfalte regninger",
        .schuldenRecorded: "Registrert gjeld",
        .schuldenManagedInBills: "Administrer forfalte regninger under «Regninger».",
        .debtTypeOpenClaim: "Åpent krav",
        .debtTypeBetreibung: "Inndriving",
        .debtTypePfaendung: "Lønns-/utleggstrekk",
        .debtTypeVerlustschein: "Tapsattest",
        .debtTypeOther: "Annen gjeld",
        .debtCreditor: "Kreditor",
        .debtReference: "Referanse / saksnr.",
        .debtDate: "Dato",
        .debtType: "Type",
        .schuldenGuidanceTitle: "Finn veien ut av gjelden",
        .schuldenTipContactTitle: "Ta kontakt tidlig",
        .schuldenTipContactBody: "Snakk med kreditorene tidlig. En skriftlig nedbetalingsavtale er ofte mulig og unngår formell inndriving.",
        .schuldenTipBetreibungTitle: "Hvis inndrivingen starter",
        .schuldenTipBetreibungBody: "Etter betalingskravet har du 20 dager på å betale – eller 10 dager på å fremme innsigelse (Rechtsvorschlag) hvis kravet er uberettiget.",
        .schuldenTipExistenzminimumTitle: "Eksistensminimumet ditt er beskyttet",
        .schuldenTipExistenzminimumBody: "Ved utlegg forblir eksistensminimumet ditt urørlig – grunnbeløp, husleie, helseforsikring og sosiale avgifter.",
        .schuldenTipVerlustscheinTitle: "Tapsattest",
        .schuldenTipVerlustscheinBody: "En tapsattest foreldes først etter 20 år. Du kan bare forfølges igjen når du får nye midler.",
        .schuldenTipCounselingTitle: "Gratis gjeldsrådgivning",
        .schuldenTipCounselingBody: "Schuldenberatung Schweiz, Caritas og budsjettrådgivning hjelper gratis og fortrolig. Betal først ned gjelden med de verste konsekvensene.",
        .schuldenDisclaimer: "Generell informasjon, ikke juridisk rådgivning.",

        .catInsurance: "Forsikring",
        .catOther: "Annet",
        .catMortgage: "Boliglån",
        .catHealthInsurance: "Helseforsikring",
        .catSerafe: "Radio/TV (Serafe)",
        .catPublicTransport: "Kollektivkort",
        .catChildcare: "Barnepass",
        .catMembership: "Medlemskap",
        .catAlimony: "Bidrag og underhold",
        .catTaxes: "Skatter",
        .catRatenzahlung: "Avdrag",
        .catStreaming: "Strømming",
        .catCreditCard: "Kredittkort",
        .catClothing: "Klær",
        .catHealth: "Helse",
        .catLeisure: "Fritid og hobbyer",
        .catEntertainment: "Underholdning",
        .catChildren: "Barn",
        .catPets: "Kjæledyr",
        .catGifts: "Gaver",
        .catTravel: "Reiser",
        .catCharity: "Veldedighet",
        .catEducation: "Utdanning",

        .settingsTitle: "Innstillinger",
        .settingsLanguage: "Språk",
        .settingsTheme: "Fargetema",
        .themeSwissRed: "Sveitsisk rød",
        .themeOrange: "Oransje",
        .themeSand: "Sand",
        .themeGreen: "Grønn",
        .themeTeal: "Blågrønn",
        .themeBlue: "Blå",
        .themePurple: "Lilla",
        .themePink: "Rosa",
        .settingsData: "Data",
        .settingsHousehold: "Husholdning",
        .settingsCanton: "Kanton",
        .settingsProfile: "Profil",
        .profileName: "Navn",
        .profileChoosePicture: "Velg profilbilde",
        .profileNoPicture: "Uten bilde",
        .profileLocalNote: "Lagres kun lokalt på denne enheten.",
        .settingsSecurity: "Sikkerhet",
        .settingsAutoLock: "Automatisk lås",
        .settingsBiometric: "Biometrisk opplåsing",
        .settingsChangePassphrase: "Endre passord/PIN",
        .settingsBackup: "Kryptert sikkerhetskopi",
        .settingsRestore: "Gjenopprett",
        .settingsPrivacy: "Personvern",
        .settingsDangerZone: "Faresone",
        .settingsDeleteAll: "Slett alle lokale data",
        .backupCreateTitle: "Opprett kryptert sikkerhetskopi",
        .backupPassphrase: "Passord for sikkerhetskopi",
        .backupHint: "Velg et eget passord for sikkerhetskopien. Det kreves for å gjenopprette – passordet kan ikke gjenopprettes.",
        .restorePreview: "Forhåndsvisning",
        .restoreConfirm: "Erstatt alle lokale data",
        .restoreWarning: "Dette overskriver alle lokale data permanent.",
        .backupInvalid: "Ugyldig sikkerhetskopi eller feil passord.",
        .backupSavedHint: "Oppbevar sikkerhetskopifilen og passordet på et trygt sted.",

        .reportTitle: "Rapporter et problem",
        .reportSummary: "Sammendrag",
        .reportExpected: "Forventet atferd",
        .reportActual: "Faktisk atferd",
        .reportSteps: "Trinn for å gjenskape",
        .reportArea: "Berørt område",
        .reportRedactionNote: "Sensitive data fjernes lokalt. Du gjennomgår rapporten før du kopierer den.",
        .reportCopyHint: "Rapporten sendes ikke automatisk. Du kopierer den selv.",

        .exportReport: "Eksporter rapport",
        .pdfTitle: "Finansiell oversikt",
        .pdfSubtitle: "Personlig husholdningsrapport",
        .pdfSummary: "Med ett blikk",
        .pdfGeneratedOn: "Generert",
        .pdfConfidential: "Konfidensielt",
        .pdfPage: "Side",
        .pdfTotal: "Totalt",
        .pdfColProgress: "Fremdrift",
        .pdfUnencryptedNote: "Rapporten er en lesbar, ukryptert PDF. Oppbevar den på et trygt sted.",
        .pdfNoData: "Ingen data å eksportere ennå.",
        .pdfDefaultHousehold: "Min husholdning",

        .lockTitle: "Låst",
        .lockWelcomeSetup: "Velkommen til Kontiva",
        .lockWelcomeBack: "Velkommen tilbake",
        .lockSetupTitle: "Opprett passord",
        .lockEnterPassphrase: "Skriv inn passord eller PIN",
        .lockWrongPassphrase: "Feil passord. Prøv igjen.",
        .lockRecoveryWarning: "Det finnes ingen gjenoppretting. Uten passordet ditt kan ikke dataene dine nås.",
        .lockRecoveryAcknowledge: "Jeg forstår at det ikke finnes gjenoppretting.",
        .securityNote: "Dataene dine lagres lokalt og kryptert (AES-256-GCM). Ingen sky, ingen server, ingen gjenoppretting av passord.",

        .onboardingIntroBody: "Kontiva hjelper deg med å beholde et rolig overblikk over det sveitsiske husholdningsbudsjettet ditt – helt på denne enheten.",
        .onboardingStart: "Kom i gang",
        .onboardingProfileTitle: "Opprett en profil",
        .onboardingProfileBody: "Gi deg selv et navn og velg et bilde. Begge forblir kun på denne enheten.",
        .onboardingSkip: "Hopp over",
        .onboardingFeaturePrivate: "Helt lokal – ingen sky, ingen sporing",
        .onboardingFeatureSecure: "Kryptert med AES-256",
        .onboardingFeatureMoney: "Nøyaktig ned til centimen, uten avrundingsfeil",
        .onboardingConfirmPassphrase: "Bekreft passord",
        .onboardingPassphraseNote: "Skriv ned passordet ditt på et trygt sted – det kan ikke tilbakestilles.",
        .backupNudgeText: "Opprett en kryptert sikkerhetskopi. Uten den mister du dataene dine hvis du glemmer passordet.",
        .commonNext: "Neste",
        .navMore: "Mer",
        .actionLock: "Lås",
        .pinSetTitle: "Velg kode",
        .pinConfirmTitle: "Bekreft kode",
        .pinRequirementNote: "Min. 6 sifre · ingen gjenoppretting",
        .pinMismatch: "Kodene stemmer ikke overens",
    ]
}
