import Foundation

// Thai. Flagged for native-speaker review (no inter-word spacing; tone of
// formal financial terms benefits from a native pass).
extension Localization {
    static let th: [L10nKey: String] = [
        .appName: "Kontiva",
        .appTagline: "มุมมองที่สงบและเป็นส่วนตัวต่องบประมาณสวิสของคุณ",
        .notBetaNotice: "เวอร์ชันพัฒนาช่วงต้น – ไม่ใช่เบต้า ไม่ใช่ V1",

        .navOverview: "ภาพรวม",
        .navPlanning: "วางแผน",
        .navBills: "ใบแจ้งหนี้",
        .navSettings: "การตั้งค่า",
        .navReport: "รายงานปัญหา",
        .navInsights: "การวิเคราะห์",
        .navSparen: "การออม",
        .sparenSubtitle: "เงินออมสมทบเป็นประจำ – และยอดที่สะสมไว้แล้ว",
        .sparenEmpty: "ยังไม่มีเป้าหมายการออม กำหนดว่าคุณออมเพื่ออะไรในแต่ละเดือน",
        .sparenMonthlyTotal: "ออม / เดือน",
        .sparenAccumulatedTotal: "ออมไว้แล้ว",
        .sparenPerMonth: "/ เดือน",
        .sparenContributions: "ครั้งที่สมทบ",
        .sparenSince: "ตั้งแต่",
        .sparenOpenEnded: "ไม่มียอดเป้าหมาย",
        .sparenGoalsLabel: "เป้าหมาย",
        .sparenSortBy: "เรียงลำดับ",
        .sparenSortStartMonth: "เดือนเริ่มต้น",
        .savingsCatCar: "รถยนต์",
        .savingsCatVacation: "วันหยุดพักผ่อน",
        .savingsCatHome: "ที่อยู่อาศัย",
        .savingsCatRetirement: "เสาหลัก 3a / เงินบำนาญ",
        .savingsCatEmergency: "กองทุนฉุกเฉิน",
        .savingsCatEducation: "การศึกษา",
        .savingsCatOther: "อื่น ๆ",
        .savingsCatWedding: "งานแต่งงาน",
        .savingsCatFamily: "ครอบครัวและบุตร",
        .savingsCatRenovation: "ปรับปรุงและตกแต่ง",
        .savingsCatElectronics: "อุปกรณ์อิเล็กทรอนิกส์",
        .savingsCatTaxes: "สำรองภาษี",
        .savingsCatInvestment: "การลงทุน",
        .savingsCatHealth: "สุขภาพ",
        .savingsCatGift: "ของขวัญ",
        .overviewPlannedSavings: "การออมเดือนนี้",
        .overviewShowCalculation: "แสดงการคำนวณ",
        .overviewTrendTitle: "แนวโน้ม · 6 เดือน",
        .overviewStatusGood: "เงินเหลือที่ดี",
        .overviewStatusTight: "ตึงตัว",
        .overviewStatusNegative: "ติดลบ",
        .overviewAllocationOf: "ของรายได้สุทธิ",
        .formStartDate: "ออมตั้งแต่",
        .formStartingBalance: "ยอดเริ่มต้น (ไม่บังคับ)",
        .insightsSubtitle: "คำแนะนำเกี่ยวกับงบประมาณของคุณ – เงินของคุณอยู่ที่ไหนและประหยัดได้ตรงไหน",
        .insightOverspending: "คุณใช้จ่ายมากกว่าที่หาได้",
        .insightTightBudget: "เดือนนี้มีพื้นที่เหลือน้อย",
        .insightHealthySurplus: "เงินเหลือที่ดี",
        .insightHighFixed: "ค่าใช้จ่ายคงที่สูง",
        .insightHighHousing: "ค่าที่อยู่อาศัยสูง",
        .insightLargestFixed: "รายการค่าใช้จ่ายคงที่ที่ใหญ่ที่สุด",
        .insightLargestVariable: "งบประมาณผันแปรที่ใหญ่ที่สุด",
        .insightOverdue: "ใบแจ้งหนี้ที่เกินกำหนด",
        .insightNoSavings: "ยังไม่ได้วางแผนการออม",
        .insightGoodSavings: "อัตราการออมที่ดี",
        .insightAllHealthy: "งบประมาณของคุณดูแข็งแรง",
        .insightHousingHint: "แนวทาง: ไม่เกินหนึ่งในสามของรายได้",
        .insightNoSavingsDetail: "คุณมีพื้นที่เหลือ – เป้าหมายการออมอาจช่วยได้",
        .insightAllHealthyDetail: "ไม่มีอะไรโดดเด่น เพิ่มข้อมูลเพื่อการวิเคราะห์ที่คมชัดขึ้น",
        .fragOfNetIncome: "ของรายได้สุทธิ",
        .fragOfFixedCosts: "ของค่าใช้จ่ายคงที่",
        .fragShortfall: "ส่วนที่ขาด",

        .commonAdd: "เพิ่ม",
        .commonEdit: "แก้ไข",
        .commonActivate: "เปิดใช้งาน",
        .commonDelete: "ลบ",
        .commonCancel: "ยกเลิก",
        .commandsAdd: "เพิ่มรายการ",
        .billsAddCta: "เพิ่มใบแจ้งหนี้แรกของคุณ",
        .sparenAddCta: "สร้างเป้าหมายการออม",
        .overviewAddCta: "เพิ่มรายได้",
        .commonSave: "บันทึก",
        .commonSaved: "บันทึกแล้ว",
        .commonClose: "ปิด",
        .commonDone: "เสร็จ",
        .commonShowSampleData: "แสดงข้อมูลตัวอย่าง",
        .commonHideSampleData: "ซ่อนข้อมูลตัวอย่าง",
        .commonEmptyHint: "ยังไม่มีการป้อนข้อมูล",
        .commonCopy: "คัดลอก",
        .commonOptions: "ตัวเลือก",
        .commonMoveUp: "เลื่อนขึ้น",
        .commonMoveDown: "เลื่อนลง",
        .monthToday: "วันนี้",

        .formName: "ชื่อ",
        .formAmount: "จำนวนเงิน (CHF)",
        .formStatus: "สถานะ",
        .formNotes: "บันทึก",
        .formInvalidAmount: "กรุณาป้อนจำนวนเงินที่ถูกต้อง",
        .formThirteenthAmount: "เงินเดือนที่ 13 (จำนวน)",
        .formThirteenthModel: "รูปแบบเงินเดือนที่ 13",
        .incomeBonuses: "การจ่ายเงินพิเศษ",
        .formMonth: "เดือน",
        .thirteenthModelSeparate: "แสดงแยก",
        .thirteenthModelAveraged: "เฉลี่ยใน 12 เดือน",
        .formTarget: "เป้าหมายการออม (จำนวน)",
        .formSaved: "ออมไว้แล้ว",
        .formMonthlyContribution: "เงินสมทบรายเดือน",
        .formCategory: "หมวดหมู่",
        .formLimitedDuration: "คำสั่งโอนประจำแบบมีกำหนด",
        .formLimitedDurationHint: "เช่น ภาษี 6 งวด – นับเฉพาะเดือนเหล่านั้นแล้วลบออกอัตโนมัติ",
        .formStartMonth: "งวดแรก",
        .formInstallments: "จำนวนงวด",
        .planningStandingOrder: "คำสั่งโอนประจำ",
        .catRent: "ค่าเช่า",
        .catSubscription: "การสมัครสมาชิก",
        .catLeasing: "ลีสซิ่ง",
        .catUtilities: "ค่าสาธารณูปโภค",
        .catTelecom: "โทรคมนาคม",
        .catGroceries: "ของชำ",
        .catFuel: "เชื้อเพลิง",
        .catTransport: "การเดินทาง",
        .catPersonal: "ส่วนตัว",
        .catDining: "รับประทานนอกบ้าน",
        .catHousehold: "ของใช้ในบ้าน",

        .overviewTitle: "ภาพรวม",
        .overviewAvailableThisMonth: "ใช้ได้เดือนนี้",
        .overviewNetIncome: "รายได้สุทธิเดือนนี้",
        .overviewThirteenthSeparate: "เงินเดือนที่ 13 (แยก)",
        .overviewRecurringFixed: "ค่าใช้จ่ายคงที่",
        .overviewPlannedVariable: "ค่าใช้จ่ายผันแปร",
        .overviewBillsDueThisMonth: "บิลเดือนนี้",
        .overviewOverdueBills: "ใบแจ้งหนี้ที่เกินกำหนด",
        .overviewSavingsTarget: "เป้าหมายการออม",
        .overviewSecurityStatus: "สถานะความปลอดภัย",
        .overviewFormulaExplainer: "ใช้ได้ = รายได้สุทธิ − ค่าใช้จ่ายคงที่ − งบประมาณผันแปร − ใบแจ้งหนี้ที่ยังไม่ชำระเดือนนี้ − ใบแจ้งหนี้ที่เกินกำหนด ใบแจ้งหนี้ที่ชำระแล้วและในอนาคตจะไม่ลดจำนวนเงิน",
        .overviewEmpty: "ป้อนรายได้และค่าใช้จ่ายในการวางแผนรายเดือนเพื่อดูภาพรวมของคุณ",
        .chartSpendingTitle: "การกระจายเดือนนี้",
        .chartByCategory: "ตามหมวดหมู่",

        .planningTitle: "การวางแผนรายเดือน",
        .planningIncome: "รายได้",
        .planningFixed: "ค่าใช้จ่ายคงที่",
        .planningVariable: "ค่าใช้จ่ายผันแปร",
        .planningSavings: "เป้าหมายการออม",
        .planningFixedExplainer: "ค่าใช้จ่ายคงที่เกิดซ้ำทุกเดือน: ค่าเช่า ประกัน การสมัครสมาชิก ลีสซิ่ง",
        .planningVariableExplainer: "งบประมาณผันแปรคุณวางแผนเอง: ของชำ เชื้อเพลิง ค่าใช้จ่ายส่วนตัว",
        .planningOneOffHint: "ใบแจ้งหนี้ครั้งเดียวจัดการได้ใน „ใบแจ้งหนี้”",
        .planningEmpty: "เริ่มจากรายได้ของคุณ จากนั้นเพิ่มค่าใช้จ่ายคงที่และงบประมาณ",
        .planningBalance: "ยอดคงเหลือตามแผน",

        .billsTitle: "ใบแจ้งหนี้",
        .billsStatusOpen: "ยังไม่ชำระ",
        .billsStatusPaid: "ชำระแล้ว",
        .billsStateOverdue: "เกินกำหนด",
        .billsStateDueThisMonth: "ครบกำหนดเดือนนี้",
        .billsStateFuture: "อนาคต",
        .billsAffectsBalance: "ลดจำนวนเงินที่ใช้ได้",
        .billsNoBalanceImpact: "ไม่มีผลเดือนนี้",
        .billsDueDate: "วันครบกำหนด",
        .billsProvider: "ผู้ให้บริการ",
        .billsEmpty: "ยังไม่มีใบแจ้งหนี้ ใบแจ้งหนี้ครั้งเดียวที่มีวันครบกำหนดจะแสดงที่นี่",
        .billsMarkPaid: "ทำเครื่องหมายว่าชำระแล้ว",
        .billsMarkOpen: "ทำเครื่องหมายว่ายังไม่ชำระ",
        .billsOpenTotal: "ยอดที่ยังไม่ชำระทั้งหมด",

        .navSchulden: "หนี้สิน",
        .schuldenSubtitle: "ติดตามใบแจ้งหนี้ที่เกินกำหนดและการบังคับชำระหนี้",
        .schuldenEmpty: "ยังไม่มีหนี้ที่บันทึกไว้ ใบแจ้งหนี้ที่เกินกำหนดจะแสดงที่นี่อัตโนมัติ – และคุณบันทึกการบังคับชำระหนี้ (Betreibung) หรือใบรับรองการสูญเสียได้",
        .schuldenAddCta: "บันทึกหนี้",
        .schuldenTotal: "หนี้รวม",
        .schuldenOverdueBills: "ใบแจ้งหนี้ที่เกินกำหนด",
        .schuldenRecorded: "หนี้ที่บันทึกไว้",
        .schuldenManagedInBills: "จัดการใบแจ้งหนี้ที่เกินกำหนดใน „ใบแจ้งหนี้”",
        .debtTypeOpenClaim: "สิทธิเรียกร้องที่ค้างอยู่",
        .debtTypeBetreibung: "การบังคับชำระหนี้",
        .debtTypePfaendung: "การอายัดเงินเดือน/ทรัพย์สิน",
        .debtTypeVerlustschein: "ใบรับรองการสูญเสีย",
        .debtTypeOther: "หนี้อื่น ๆ",
        .debtCreditor: "เจ้าหนี้",
        .debtReference: "อ้างอิง / เลขที่คดี",
        .debtDate: "วันที่",
        .debtType: "ประเภท",
        .schuldenGuidanceTitle: "ทางออกจากหนี้",
        .schuldenTipContactTitle: "ติดต่อแต่เนิ่น ๆ",
        .schuldenTipContactBody: "พูดคุยกับเจ้าหนี้แต่เนิ่น ๆ แผนผ่อนชำระเป็นลายลักษณ์อักษรมักเป็นไปได้และหลีกเลี่ยงกระบวนการทางการ",
        .schuldenTipBetreibungTitle: "หากการบังคับชำระหนี้เริ่มขึ้น",
        .schuldenTipBetreibungBody: "หลังคำสั่งให้ชำระ คุณมี 20 วันในการชำระ – หรือ 10 วันในการคัดค้าน (Rechtsvorschlag) หากการเรียกร้องไม่ชอบธรรม",
        .schuldenTipExistenzminimumTitle: "ค่าครองชีพขั้นต่ำของคุณได้รับการคุ้มครอง",
        .schuldenTipExistenzminimumBody: "เมื่อมีการอายัด ค่าครองชีพขั้นต่ำของคุณจะไม่ถูกแตะต้อง – จำนวนเงินพื้นฐาน ค่าเช่า ประกันสุขภาพ และเงินสมทบสังคม",
        .schuldenTipVerlustscheinTitle: "ใบรับรองการสูญเสีย",
        .schuldenTipVerlustscheinBody: "ใบรับรองการสูญเสียจะหมดอายุความหลังจาก 20 ปีเท่านั้น คุณจะถูกทวงถามอีกได้ก็ต่อเมื่อมีทรัพย์สินใหม่",
        .schuldenTipCounselingTitle: "คำปรึกษาหนี้ฟรี",
        .schuldenTipCounselingBody: "Schuldenberatung Schweiz, Caritas และคำปรึกษาด้านงบประมาณช่วยเหลือฟรีและเป็นความลับ ชำระหนี้ที่มีผลร้ายแรงที่สุดก่อน",
        .schuldenDisclaimer: "ข้อมูลทั่วไป ไม่ใช่คำแนะนำทางกฎหมาย",

        .catInsurance: "ประกัน",
        .catOther: "อื่น ๆ",
        .catMortgage: "สินเชื่อบ้าน",
        .catHealthInsurance: "ประกันสุขภาพ",
        .catSerafe: "วิทยุ/โทรทัศน์ (Serafe)",
        .catPublicTransport: "ตั๋วเดินทาง",
        .catChildcare: "การดูแลเด็ก",
        .catMembership: "ค่าสมาชิก",
        .catAlimony: "ค่าเลี้ยงดู",
        .catTaxes: "ภาษี",
        .catClothing: "เสื้อผ้า",
        .catHealth: "สุขภาพ",
        .catLeisure: "เวลาว่างและงานอดิเรก",
        .catEntertainment: "ความบันเทิง",
        .catChildren: "บุตร",
        .catPets: "สัตว์เลี้ยง",
        .catGifts: "ของขวัญ",
        .catTravel: "การท่องเที่ยว",
        .catCharity: "การบริจาค",
        .catEducation: "การศึกษา",

        .settingsTitle: "การตั้งค่า",
        .settingsLanguage: "ภาษา",
        .settingsTheme: "ธีมสี",
        .themeSwissRed: "แดงสวิส",
        .themeOrange: "ส้ม",
        .themeSand: "สีทราย",
        .themeGreen: "เขียว",
        .themeTeal: "เขียวอมฟ้า",
        .themeBlue: "น้ำเงิน",
        .themePurple: "ม่วง",
        .themePink: "ชมพู",
        .settingsData: "ข้อมูล",
        .settingsHousehold: "ครัวเรือน",
        .settingsCanton: "รัฐ (แคนทอน)",
        .settingsProfile: "โปรไฟล์",
        .profileName: "ชื่อ",
        .profileChoosePicture: "เลือกรูปโปรไฟล์",
        .profileNoPicture: "ไม่มีรูป",
        .profileLocalNote: "จัดเก็บไว้ในเครื่องนี้เท่านั้น",
        .settingsSecurity: "ความปลอดภัย",
        .settingsAutoLock: "ล็อกอัตโนมัติ",
        .settingsBiometric: "ปลดล็อกด้วยไบโอเมตริก",
        .settingsChangePassphrase: "เปลี่ยนรหัสผ่าน/PIN",
        .settingsBackup: "การสำรองข้อมูลที่เข้ารหัส",
        .settingsRestore: "กู้คืน",
        .settingsPrivacy: "ความเป็นส่วนตัว",
        .settingsDangerZone: "โซนอันตราย",
        .settingsDeleteAll: "ลบข้อมูลในเครื่องทั้งหมด",
        .backupCreateTitle: "สร้างการสำรองข้อมูลที่เข้ารหัส",
        .backupPassphrase: "รหัสผ่านสำรองข้อมูล",
        .backupHint: "เลือกรหัสผ่านแยกต่างหากสำหรับการสำรองข้อมูล จำเป็นต้องใช้เพื่อกู้คืน – ไม่สามารถกู้รหัสผ่านได้",
        .restorePreview: "ตัวอย่าง",
        .restoreConfirm: "แทนที่ข้อมูลในเครื่องทั้งหมด",
        .restoreWarning: "การดำเนินการนี้จะเขียนทับข้อมูลในเครื่องทั้งหมดอย่างถาวร",
        .backupInvalid: "การสำรองข้อมูลไม่ถูกต้องหรือรหัสผ่านผิด",
        .backupSavedHint: "เก็บไฟล์สำรองข้อมูลและรหัสผ่านไว้ในที่ปลอดภัย",

        .reportTitle: "รายงานปัญหา",
        .reportSummary: "สรุป",
        .reportExpected: "พฤติกรรมที่คาดหวัง",
        .reportActual: "พฤติกรรมจริง",
        .reportSteps: "ขั้นตอนการทำซ้ำ",
        .reportArea: "ส่วนที่ได้รับผลกระทบ",
        .reportRedactionNote: "ข้อมูลที่ละเอียดอ่อนจะถูกลบในเครื่อง คุณตรวจสอบรายงานก่อนคัดลอก",
        .reportCopyHint: "รายงานจะไม่ถูกส่งโดยอัตโนมัติ คุณคัดลอกเอง",

        .exportReport: "ส่งออกรายงาน",
        .pdfTitle: "ภาพรวมทางการเงิน",
        .pdfSubtitle: "รายงานครัวเรือนส่วนบุคคล",
        .pdfSummary: "โดยสรุป",
        .pdfGeneratedOn: "สร้างเมื่อ",
        .pdfConfidential: "เป็นความลับ",
        .pdfPage: "หน้า",
        .pdfTotal: "รวม",
        .pdfColProgress: "ความคืบหน้า",
        .pdfUnencryptedNote: "รายงานเป็นไฟล์ PDF ที่อ่านได้และไม่เข้ารหัส เก็บไว้ในที่ปลอดภัย",
        .pdfNoData: "ยังไม่มีข้อมูลให้ส่งออก",
        .pdfDefaultHousehold: "ครัวเรือนของฉัน",

        .lockTitle: "ล็อกอยู่",
        .lockWelcomeSetup: "ยินดีต้อนรับสู่ Kontiva",
        .lockWelcomeBack: "ยินดีต้อนรับกลับ",
        .lockSetupTitle: "ตั้งรหัสผ่าน",
        .lockEnterPassphrase: "ป้อนรหัสผ่านหรือ PIN",
        .lockWrongPassphrase: "รหัสผ่านผิด ลองอีกครั้ง",
        .lockRecoveryWarning: "ไม่มีการกู้คืน หากไม่มีรหัสผ่านของคุณ จะไม่สามารถเข้าถึงข้อมูลของคุณได้",
        .lockRecoveryAcknowledge: "ฉันเข้าใจว่าไม่มีการกู้คืน",
        .securityNote: "ข้อมูลของคุณจัดเก็บในเครื่องและเข้ารหัส (AES-256-GCM) ไม่มีคลาวด์ ไม่มีเซิร์ฟเวอร์ ไม่มีการกู้รหัสผ่าน",

        .onboardingIntroBody: "Kontiva ช่วยให้คุณมองงบประมาณครัวเรือนสวิสได้อย่างสงบ – ทั้งหมดบนเครื่องนี้",
        .onboardingStart: "เริ่มต้น",
        .onboardingProfileTitle: "สร้างโปรไฟล์",
        .onboardingProfileBody: "ตั้งชื่อให้ตัวเองและเลือกรูป ทั้งสองอย่างจะอยู่บนเครื่องนี้เท่านั้น",
        .onboardingSkip: "ข้าม",
        .onboardingFeaturePrivate: "อยู่ในเครื่องทั้งหมด – ไม่มีคลาวด์ ไม่มีการติดตาม",
        .onboardingFeatureSecure: "เข้ารหัสด้วย AES-256",
        .onboardingFeatureMoney: "แม่นยำถึงระดับซองตีม ไม่มีข้อผิดพลาดจากการปัดเศษ",
        .onboardingConfirmPassphrase: "ยืนยันรหัสผ่าน",
        .onboardingPassphraseNote: "จดรหัสผ่านไว้ในที่ปลอดภัย – ไม่สามารถรีเซ็ตได้",
        .backupNudgeText: "สร้างการสำรองข้อมูลที่เข้ารหัส หากไม่มี คุณจะสูญเสียข้อมูลเมื่อลืมรหัสผ่าน",
        .commonNext: "ถัดไป",
        .navMore: "เพิ่มเติม",
        .actionLock: "ล็อก",
        .pinSetTitle: "ตั้งรหัส",
        .pinConfirmTitle: "ยืนยันรหัส",
        .pinRequirementNote: "อย่างน้อย 6 หลัก · กู้คืนไม่ได้",
        .pinMismatch: "รหัสไม่ตรงกัน",
    ]
}
