import Foundation

extension Localization {
    static let ptPT: [L10nKey: String] = [
        .appName: "Kontiva",
        .appTagline: "Uma visão serena e privada do seu orçamento suíço.",
        .notBetaNotice: "Versão em desenvolvimento inicial — não é beta, não é V1.",

        .navOverview: "Resumo",
        .navPlanning: "Planeamento mensal",
        .navBills: "Faturas",
        .navSettings: "Definições",
        .navReport: "Comunicar um problema",
        .navInsights: "Análises",
        .navSparen: "Poupança",
        .sparenSubtitle: "Contribuições de poupança recorrentes — e o que já juntou.",
        .sparenEmpty: "Ainda não há objetivos de poupança. Defina para que poupa todos os meses.",
        .sparenMonthlyTotal: "Poupança / mês",
        .sparenAccumulatedTotal: "Já poupado",
        .sparenPerMonth: "/ mês",
        .sparenContributions: "contribuições",
        .sparenSince: "desde",
        .sparenOpenEnded: "Sem valor-alvo",
        .sparenGoalsLabel: "Objetivos",
        .savingsCatCar: "Carro",
        .savingsCatVacation: "Férias",
        .savingsCatHome: "Casa",
        .savingsCatRetirement: "Pilar 3a / Reforma",
        .savingsCatEmergency: "Fundo de emergência",
        .savingsCatEducation: "Educação",
        .savingsCatOther: "Outro",
        .savingsCatWedding: "Casamento",
        .savingsCatFamily: "Família e filhos",
        .savingsCatRenovation: "Renovação e mobiliário",
        .savingsCatElectronics: "Eletrónica",
        .savingsCatTaxes: "Reserva para impostos",
        .savingsCatInvestment: "Investimentos",
        .savingsCatHealth: "Saúde",
        .savingsCatGift: "Presentes",
        .overviewPlannedSavings: "Poupança este mês",
        .overviewShowCalculation: "Mostrar cálculo",
        .overviewTrendTitle: "Tendência · 6 meses",
        .overviewStatusGood: "Excedente saudável",
        .overviewStatusTight: "Apertado",
        .overviewStatusNegative: "No vermelho",
        .overviewAllocationOf: "do rendimento líquido",
        .formStartDate: "A poupar desde",
        .formStartingBalance: "Saldo inicial (opcional)",
        .insightsSubtitle: "Orientação sobre o seu orçamento — onde está o seu dinheiro e onde pode poupar.",
        .insightOverspending: "Gasta mais do que recebe",
        .insightTightBudget: "Pouca margem este mês",
        .insightHealthySurplus: "Excedente saudável",
        .insightHighFixed: "Carga elevada de custos fixos",
        .insightHighHousing: "Custos de habitação elevados",
        .insightLargestFixed: "Maior bloco de custos fixos",
        .insightLargestVariable: "Maior orçamento variável",
        .insightOverdue: "Faturas em atraso",
        .insightNoSavings: "Ainda sem poupança planeada",
        .insightGoodSavings: "Boa taxa de poupança",
        .insightAllHealthy: "O seu orçamento parece saudável",
        .insightHousingHint: "Orientação: no máximo um terço do rendimento",
        .insightNoSavingsDetail: "Tem margem — um objetivo de poupança pode ajudar.",
        .insightAllHealthyDetail: "Nada se destaca. Adicione mais dados para análises mais precisas.",
        .fragOfNetIncome: "do rendimento líquido",
        .fragOfFixedCosts: "dos custos fixos",
        .fragShortfall: "Défice",

        .commonAdd: "Adicionar",
        .commonEdit: "Editar",
        .commonDelete: "Eliminar",
        .commonCancel: "Cancelar",
        .commandsAdd: "Adicionar entrada",
        .billsAddCta: "Adicione a sua primeira fatura",
        .sparenAddCta: "Criar um objetivo de poupança",
        .overviewAddCta: "Adicionar rendimento",
        .commonSave: "Guardar",
        .commonSaved: "Guardado",
        .commonClose: "Fechar",
        .commonDone: "Concluído",
        .commonShowSampleData: "Mostrar dados de exemplo",
        .commonHideSampleData: "Ocultar dados de exemplo",
        .commonEmptyHint: "Ainda não foram introduzidos dados.",
        .commonCopy: "Copiar",
        .commonOptions: "Opções",
        .commonMoveUp: "Mover para cima",
        .commonMoveDown: "Mover para baixo",
        .monthToday: "Hoje",

        .formName: "Nome",
        .formAmount: "Valor (CHF)",
        .formStatus: "Estado",
        .formNotes: "Nota",
        .formInvalidAmount: "Introduza um valor válido.",
        .formThirteenthAmount: "13.º salário (valor)",
        .formThirteenthModel: "Modelo do 13.º salário",
        .thirteenthModelSeparate: "Mostrar em separado",
        .thirteenthModelAveraged: "Distribuir por 12 meses",
        .formTarget: "Objetivo de poupança (valor)",
        .formSaved: "Já poupado",
        .formMonthlyContribution: "Contribuição mensal",
        .formCategory: "Categoria",
        .formLimitedDuration: "Ordem permanente limitada",
        .formLimitedDurationHint: "P. ex. 6 prestações de impostos — contadas apenas nesses meses e depois removidas automaticamente.",
        .formStartMonth: "Primeira prestação",
        .formInstallments: "Número de prestações",
        .planningStandingOrder: "Ordem permanente",
        .catRent: "Renda",
        .catSubscription: "Subscrição",
        .catLeasing: "Leasing",
        .catUtilities: "Serviços (água, luz)",
        .catTelecom: "Telecomunicações",
        .catGroceries: "Mercearia",
        .catFuel: "Combustível",
        .catTransport: "Transporte",
        .catPersonal: "Pessoal",
        .catDining: "Refeições fora",
        .catHousehold: "Casa",

        .overviewTitle: "Resumo",
        .overviewAvailableThisMonth: "Disponível este mês",
        .overviewNetIncome: "Rendimento líquido este mês",
        .overviewThirteenthSeparate: "13.º salário (em separado)",
        .overviewRecurringFixed: "Custos fixos",
        .overviewPlannedVariable: "Despesas variáveis",
        .overviewBillsDueThisMonth: "Faturas a vencer este mês",
        .overviewOverdueBills: "Faturas em atraso",
        .overviewSavingsTarget: "Objetivo de poupança",
        .overviewSecurityStatus: "Estado de segurança",
        .overviewFormulaExplainer: "Disponível = rendimento líquido − custos fixos − orçamentos variáveis − faturas a vencer este mês − faturas em atraso. As faturas pagas e futuras não reduzem o valor.",
        .overviewEmpty: "Introduza rendimentos e custos no Planeamento mensal para ver o seu resumo.",
        .chartSpendingTitle: "Repartição deste mês",
        .chartByCategory: "Por categoria",

        .planningTitle: "Planeamento mensal",
        .planningIncome: "Rendimento",
        .planningFixed: "Custos fixos",
        .planningVariable: "Despesas variáveis",
        .planningSavings: "Objetivo de poupança",
        .planningFixedExplainer: "Os custos fixos repetem-se todos os meses: renda, seguros, subscrições, leasing.",
        .planningVariableExplainer: "Os orçamentos variáveis planeia-os você: mercearia, combustível, despesas pessoais.",
        .planningOneOffHint: "As faturas pontuais são geridas em «Faturas».",
        .planningEmpty: "Comece pelo rendimento e depois adicione custos fixos e orçamentos.",
        .planningBalance: "Saldo planeado",

        .billsTitle: "Faturas",
        .billsStatusOpen: "Em aberto",
        .billsStatusPaid: "Paga",
        .billsStateOverdue: "Em atraso",
        .billsStateDueThisMonth: "Vence este mês",
        .billsStateFuture: "Futura",
        .billsAffectsBalance: "Reduz o valor disponível",
        .billsNoBalanceImpact: "Sem efeito este mês",
        .billsDueDate: "Data de vencimento",
        .billsProvider: "Fornecedor",
        .billsEmpty: "Ainda não há faturas. As faturas pontuais com data de vencimento aparecem aqui.",
        .billsMarkPaid: "Marcar como paga",
        .billsMarkOpen: "Marcar como em aberto",
        .billsOpenTotal: "Total em aberto",

        .navSchulden: "Dívidas",
        .schuldenSubtitle: "Acompanhe as faturas em atraso e os processos de cobrança.",
        .schuldenEmpty: "Sem dívidas registadas. As faturas em atraso aparecem aqui automaticamente — e pode registar processos de cobrança (Betreibung) ou certidões de incobrabilidade.",
        .schuldenAddCta: "Registar uma dívida",
        .schuldenTotal: "Dívida total",
        .schuldenOverdueBills: "Faturas em atraso",
        .schuldenRecorded: "Dívidas registadas",
        .schuldenManagedInBills: "Faça a gestão das faturas em atraso em «Faturas».",
        .debtTypeOpenClaim: "Reclamação em aberto",
        .debtTypeBetreibung: "Processo de cobrança",
        .debtTypePfaendung: "Penhora de salário/bens",
        .debtTypeVerlustschein: "Certidão de incobrabilidade",
        .debtTypeOther: "Outra dívida",
        .debtCreditor: "Credor",
        .debtReference: "Referência / n.º de processo",
        .debtDate: "Data",
        .debtType: "Tipo",
        .schuldenGuidanceTitle: "Encontrar a saída das dívidas",
        .schuldenTipContactTitle: "Contacte cedo",
        .schuldenTipContactBody: "Fale com os credores o quanto antes. Um plano de pagamento a prestações por escrito é muitas vezes possível e evita o processo formal.",
        .schuldenTipBetreibungTitle: "Se o processo começar",
        .schuldenTipBetreibungBody: "Após a ordem de pagamento tem 20 dias para pagar — ou 10 dias para apresentar oposição (Rechtsvorschlag) se a reclamação for injustificada.",
        .schuldenTipExistenzminimumTitle: "O seu mínimo de subsistência está protegido",
        .schuldenTipExistenzminimumBody: "Numa penhora, o seu mínimo de subsistência permanece intocável — valor base, renda, seguro de saúde e contribuições sociais.",
        .schuldenTipVerlustscheinTitle: "Certidão de incobrabilidade",
        .schuldenTipVerlustscheinBody: "Uma certidão de incobrabilidade prescreve apenas ao fim de 20 anos. Só pode ser cobrado novamente quando adquirir novos bens.",
        .schuldenTipCounselingTitle: "Aconselhamento de dívidas gratuito",
        .schuldenTipCounselingBody: "A Schuldenberatung Schweiz, a Caritas e os serviços de aconselhamento orçamental ajudam de forma gratuita e confidencial. Pague primeiro as dívidas com piores consequências.",
        .schuldenDisclaimer: "Informação geral, não é aconselhamento jurídico.",

        .catInsurance: "Seguros",
        .catOther: "Outro",
        .catMortgage: "Hipoteca",
        .catHealthInsurance: "Seguro de saúde",
        .catSerafe: "Rádio/TV (Serafe)",
        .catPublicTransport: "Passe de transporte",
        .catChildcare: "Creche / amas",
        .catMembership: "Quotas e adesões",
        .catAlimony: "Pensões e alimentos",
        .catTaxes: "Impostos",
        .catClothing: "Vestuário",
        .catHealth: "Saúde",
        .catLeisure: "Lazer e passatempos",
        .catEntertainment: "Entretenimento",
        .catChildren: "Crianças",
        .catPets: "Animais",
        .catGifts: "Presentes",
        .catTravel: "Viagens",
        .catCharity: "Donativos",
        .catEducation: "Educação",

        .settingsTitle: "Definições",
        .settingsLanguage: "Idioma",
        .settingsTheme: "Tema de cor",
        .themeSwissRed: "Vermelho suíço",
        .themeOrange: "Laranja",
        .themeSand: "Areia",
        .themeGreen: "Verde",
        .themeTeal: "Azul-petróleo",
        .themeBlue: "Azul",
        .themePurple: "Roxo",
        .themePink: "Rosa",
        .settingsData: "Dados",
        .settingsHousehold: "Agregado familiar",
        .settingsCanton: "Cantão",
        .settingsProfile: "Perfil",
        .profileName: "Nome",
        .profileChoosePicture: "Escolher foto de perfil",
        .profileNoPicture: "Sem foto",
        .profileLocalNote: "Guardado apenas localmente neste dispositivo.",
        .settingsSecurity: "Segurança",
        .settingsAutoLock: "Bloqueio automático",
        .settingsChangePassphrase: "Alterar palavra-passe/PIN",
        .settingsBackup: "Cópia de segurança cifrada",
        .settingsRestore: "Restaurar",
        .settingsPrivacy: "Privacidade",
        .settingsDangerZone: "Zona de perigo",
        .settingsDeleteAll: "Eliminar todos os dados locais",
        .backupCreateTitle: "Criar cópia de segurança cifrada",
        .backupPassphrase: "Palavra-passe da cópia",
        .backupHint: "Escolha uma palavra-passe separada para a cópia. É necessária para restaurar — não há forma de a recuperar.",
        .restorePreview: "Pré-visualização",
        .restoreConfirm: "Substituir todos os dados locais",
        .restoreWarning: "Isto substitui permanentemente todos os dados locais.",
        .backupInvalid: "Cópia inválida ou palavra-passe incorreta.",
        .backupSavedHint: "Guarde o ficheiro da cópia e a respetiva palavra-passe num local seguro.",

        .reportTitle: "Comunicar um problema",
        .reportSummary: "Resumo",
        .reportExpected: "Comportamento esperado",
        .reportActual: "Comportamento real",
        .reportSteps: "Passos para reproduzir",
        .reportArea: "Área afetada",
        .reportRedactionNote: "Os dados sensíveis são removidos localmente. Reveja o relatório antes de copiar.",
        .reportCopyHint: "O relatório não é enviado automaticamente. É você que o copia.",

        .exportReport: "Exportar relatório",
        .pdfTitle: "Resumo financeiro",
        .pdfSubtitle: "Relatório pessoal do agregado",
        .pdfSummary: "Num relance",
        .pdfGeneratedOn: "Gerado a",
        .pdfConfidential: "Confidencial",
        .pdfPage: "Página",
        .pdfTotal: "Total",
        .pdfColProgress: "Progresso",
        .pdfUnencryptedNote: "O relatório é um PDF legível e não cifrado. Guarde-o num local seguro.",
        .pdfNoData: "Ainda não há dados para exportar.",
        .pdfDefaultHousehold: "O meu agregado",

        .lockTitle: "Bloqueado",
        .lockWelcomeSetup: "Bem-vindo ao Kontiva",
        .lockWelcomeBack: "Bem-vindo de volta",
        .lockSetupTitle: "Definir palavra-passe",
        .lockEnterPassphrase: "Introduza a palavra-passe ou o PIN",
        .lockWrongPassphrase: "Palavra-passe incorreta. Tente novamente.",
        .lockRecoveryWarning: "Não há recuperação. Sem a sua palavra-passe, não é possível aceder aos seus dados.",
        .lockRecoveryAcknowledge: "Compreendo que não há recuperação.",
        .securityNote: "Os seus dados são guardados localmente e cifrados (AES-256-GCM). Sem nuvem, sem servidor, sem recuperação da palavra-passe.",

        .onboardingIntroBody: "O Kontiva ajuda-o a manter uma visão serena do orçamento do seu agregado suíço — inteiramente neste dispositivo.",
        .onboardingStart: "Começar",
        .onboardingProfileTitle: "Crie um perfil",
        .onboardingProfileBody: "Dê-se um nome e escolha uma imagem. Ambos ficam apenas neste dispositivo.",
        .onboardingSkip: "Ignorar",
        .onboardingFeaturePrivate: "Totalmente local — sem nuvem, sem rastreio",
        .onboardingFeatureSecure: "Cifrado com AES-256",
        .onboardingFeatureMoney: "Preciso ao cêntimo, sem erros de arredondamento",
        .onboardingConfirmPassphrase: "Confirmar palavra-passe",
        .onboardingPassphraseNote: "Anote a sua palavra-passe num local seguro — não pode ser reposta.",
        .backupNudgeText: "Crie uma cópia de segurança cifrada. Sem ela, perde os seus dados se esquecer a palavra-passe.",
        .commonNext: "Seguinte",
        .navMore: "Mais",
        .actionLock: "Bloquear",
    ]
}
