import Foundation

extension Localization {
    static let frCH: [L10nKey: String] = [
        .appName: "Kontiva",
        .appTagline: "Une vue calme et privée de votre budget suisse.",
        .notBetaNotice: "Version de développement précoce – pas prête pour la bêta, pas V1.",

        .navOverview: "Aperçu",
        .navPlanning: "Plan",
        .navBills: "Factures",
        .navSettings: "Réglages",
        .navReport: "Signaler un problème",
        .navInsights: "Analyses",
        .navSparen: "Épargne",
        .sparenSubtitle: "Versements d’épargne récurrents – et ce qui s’est déjà accumulé.",
        .sparenEmpty: "Aucun objectif d’épargne. Définissez pour quoi vous épargnez chaque mois.",
        .sparenMonthlyTotal: "Épargne / mois",
        .sparenAccumulatedTotal: "Déjà épargné",
        .sparenPerMonth: "/ mois",
        .sparenContributions: "versements",
        .sparenSince: "depuis",
        .sparenOpenEnded: "Sans montant cible",
        .sparenGoalReached: "Objectif atteint",
        .sparenGoalReachedMessage: "Félicitations ! Tu as atteint ton objectif d'épargne. Comment veux-tu continuer ?",
        .sparenGoalIncrease: "Augmenter l'objectif",
        .sparenGoalComplete: "Marquer comme terminé",
        .sparenGoalKeep: "Continuer d'épargner",
        .sparenGoalCompleted: "Terminé",
        .sparenGoalReopen: "Réactiver",
        .sparenGoalsLabel: "Objectifs",
        .sparenSortBy: "Trier",
        .sparenSortStartMonth: "Mois de début",
        .savingsCatCar: "Voiture",
        .savingsCatVacation: "Vacances",
        .savingsCatHome: "Logement",
        .savingsCatRetirement: "Pilier 3a / Prévoyance",
        .savingsCatEmergency: "Réserve d’urgence",
        .savingsCatEducation: "Formation",
        .savingsCatOther: "Autre",
        .savingsCatWedding: "Mariage",
        .savingsCatFamily: "Famille & enfants",
        .savingsCatRenovation: "Rénovation & aménagement",
        .savingsCatElectronics: "Électronique",
        .savingsCatTaxes: "Réserve d'impôts",
        .savingsCatInvestment: "Investissements",
        .savingsCatHealth: "Santé",
        .savingsCatGift: "Cadeaux",
        .overviewPlannedSavings: "Épargne ce mois",
        .overviewShowCalculation: "Afficher le calcul",
        .overviewTrendTitle: "Tendance · 6 mois",
        .overviewStatusGood: "Excédent sain",
        .overviewStatusTight: "Juste",
        .overviewStatusNegative: "En négatif",
        .overviewAllocationOf: "du revenu net",
        .formStartDate: "Épargne depuis",
        .formStartingBalance: "Solde initial (facultatif)",
        .insightsSubtitle: "Des indications sur votre budget – où va votre argent et où économiser.",
        .insightOverspending: "Vous dépensez plus que vos revenus",
        .insightTightBudget: "Peu de marge ce mois",
        .insightHealthySurplus: "Excédent sain",
        .insightHighFixed: "Charges fixes élevées",
        .insightHighHousing: "Coûts de logement élevés",
        .insightLargestFixed: "Plus grand poste de charges fixes",
        .insightLargestVariable: "Plus grand budget variable",
        .insightOverdue: "Factures en retard",
        .insightNoSavings: "Aucune épargne planifiée",
        .insightGoodSavings: "Bonne épargne",
        .insightAllHealthy: "Votre budget semble sain",
        .insightHousingHint: "Référence : au plus un tiers du revenu",
        .insightNoSavingsDetail: "Vous avez de la marge – un objectif d’épargne pourrait aider.",
        .insightAllHealthyDetail: "Rien à signaler. Saisissez plus de données pour des indications précises.",
        .insightExtraIncome: "Revenu supplémentaire ce mois",
        .insightGoalProgress: "Objectif d'épargne à portée",
        .insightBillsDueSoon: "Encore à payer ce mois",
        .insightGettingStarted: "C'est parti",
        .insightGettingStartedDetail: "Ajoute ton revenu pour voir tes analyses personnelles.",
        .schuldenEncourageTitle: "Pas à pas",
        .schuldenEncourageBody: "Tu t'y attaques. Voici des prochaines étapes concrètes.",
        .fragOfNetIncome: "du revenu net",
        .fragOfFixedCosts: "des charges fixes",
        .fragShortfall: "Déficit",

        .commonAdd: "Ajouter",
        .commonEdit: "Modifier",
        .commonActivate: "Activer",
        .commonDelete: "Supprimer",
        .commonCancel: "Annuler",
        .commandsAdd: "Ajouter une entrée",
        .billsAddCta: "Ajouter la première facture",
        .sparenAddCta: "Créer un objectif d’épargne",
        .overviewAddCta: "Saisir un revenu",
        .commonSave: "Enregistrer",
        .commonSaved: "Enregistré",
        .commonClose: "Fermer",
        .commonDone: "Terminé",
        .commonShowSampleData: "Afficher les données d’exemple",
        .commonHideSampleData: "Masquer les données d’exemple",
        .commonEmptyHint: "Aucune donnée saisie pour l’instant.",
        .commonCopy: "Copier",
        .commonOptions: "Options",
        .commonMoveUp: "Monter",
        .commonMoveDown: "Descendre",
        .monthToday: "Aujourd’hui",

        .formName: "Désignation",
        .formAmount: "Montant (CHF)",
        .formStatus: "Statut",
        .formNotes: "Note",
        .formInvalidAmount: "Veuillez saisir un montant valide.",
        .formThirteenthAmount: "13e salaire (montant)",
        .formThirteenthModel: "Modèle 13e salaire",
        .incomeBonuses: "Paiements spéciaux",
        .formMonth: "Mois",
        .thirteenthModelSeparate: "Indiquer séparément",
        .thirteenthModelAveraged: "Répartir sur 12 mois",
        .formTarget: "Objectif d’épargne (montant)",
        .formSaved: "Déjà épargné",
        .formMonthlyContribution: "Contribution mensuelle",
        .formCategory: "Catégorie",
        .formLimitedDuration: "Ordre permanent limité",
        .formLimitedDurationHint: "P. ex. 6 acomptes d’impôt – comptés uniquement ces mois-là, puis retirés automatiquement.",
        .formStartMonth: "Premier versement",
        .formInstallments: "Nombre de versements",
        .planningStandingOrder: "Ordre permanent",
        .catRent: "Loyer",
        .catSubscription: "Abonnement",
        .catLeasing: "Leasing",
        .catUtilities: "Charges",
        .catTelecom: "Télécom",
        .catGroceries: "Alimentation",
        .catFuel: "Carburant",
        .catTransport: "Transport",
        .catPersonal: "Dépenses personnelles",
        .catDining: "Restaurant",
        .catHousehold: "Ménage",

        .overviewTitle: "Aperçu",
        .overviewAvailableThisMonth: "Disponible ce mois",
        .overviewNetIncome: "Revenu net ce mois",
        .overviewThirteenthSeparate: "13e salaire (indiqué séparément)",
        .overviewRecurringFixed: "Charges fixes",
        .overviewPlannedVariable: "Dépenses variables",
        .overviewBillsDueThisMonth: "Factures ce mois",
        .overviewOverdueBills: "Factures en retard",
        .overviewSavingsTarget: "Objectif d’épargne",
        .overviewSecurityStatus: "État de sécurité",
        .overviewFormulaExplainer: "Disponible = revenu net − charges fixes − budgets variables − factures ouvertes ce mois − factures en retard. Les factures payées et futures ne réduisent pas le montant.",
        .overviewEmpty: "Saisissez vos revenus et charges dans la planification mensuelle pour voir votre aperçu.",
        .chartSpendingTitle: "Répartition ce mois",
        .chartByCategory: "Par catégorie",

        .planningTitle: "Planification mensuelle",
        .planningIncome: "Revenu",
        .planningFixed: "Charges fixes",
        .planningVariable: "Dépenses variables",
        .planningSavings: "Objectif d’épargne",
        .planningFixedExplainer: "Les charges fixes reviennent chaque mois : loyer, assurances, abonnements, leasing.",
        .planningVariableExplainer: "Vous planifiez vous-même les budgets variables : alimentation, carburant, dépenses personnelles.",
        .planningOneOffHint: "Les factures uniques se gèrent sous « Factures ».",
        .planningEmpty: "Commencez par votre revenu, puis ajoutez les charges fixes et les budgets.",
        .planningBalance: "Solde planifié",

        .billsTitle: "Factures",
        .billsStatusOpen: "Ouverte",
        .billsStatusPaid: "Payée",
        .billsStateOverdue: "En retard",
        .billsStateDueThisMonth: "Échéance ce mois",
        .billsStateFuture: "Future",
        .billsAffectsBalance: "Réduit le montant disponible",
        .billsNoBalanceImpact: "Sans effet sur ce mois",
        .billsDueDate: "Date d’échéance",
        .billsProvider: "Fournisseur",
        .billsEmpty: "Aucune facture saisie. Les factures uniques avec échéance apparaîtront ici.",
        .billsMarkPaid: "Marquer comme payée",
        .billsMarkOpen: "Marquer comme ouverte",
        .billsOpenTotal: "Total ouvert",

        .navSchulden: "Dettes",
        .schuldenSubtitle: "Gardez un œil sur les factures en retard et les poursuites.",
        .schuldenEmpty: "Aucune dette enregistrée. Les factures en retard apparaissent ici automatiquement – et vous pouvez noter poursuites ou actes de défaut de biens.",
        .schuldenAddCta: "Saisir une dette",
        .schuldenTotal: "Total des dettes",
        .schuldenOverdueBills: "Factures en retard",
        .schuldenRecorded: "Dettes enregistrées",
        .schuldenManagedInBills: "Gérez les factures en retard sous « Factures ».",
        .debtTypeOpenClaim: "Créance ouverte",
        .debtTypeBetreibung: "Poursuite",
        .debtTypePfaendung: "Saisie",
        .debtTypeVerlustschein: "Acte de défaut de biens",
        .debtTypeOther: "Autre dette",
        .debtCreditor: "Créancier",
        .debtReference: "Référence / dossier",
        .debtDate: "Date",
        .debtType: "Type",
        .schuldenGuidanceTitle: "Sortir de l'endettement",
        .schuldenTipContactTitle: "Prenez contact tôt",
        .schuldenTipContactBody: "Contactez vos créanciers rapidement. Un paiement échelonné par écrit est souvent possible et évite une poursuite.",
        .schuldenTipBetreibungTitle: "En cas de poursuite",
        .schuldenTipBetreibungBody: "Après le commandement de payer, vous avez 20 jours pour payer – ou 10 jours pour faire opposition si la créance est injustifiée.",
        .schuldenTipExistenzminimumTitle: "Le minimum vital est protégé",
        .schuldenTipExistenzminimumBody: "En cas de saisie, votre minimum vital reste intouchable – montant de base, loyer, assurance maladie et cotisations sociales.",
        .schuldenTipVerlustscheinTitle: "Acte de défaut de biens",
        .schuldenTipVerlustscheinBody: "Un acte de défaut de biens se prescrit après 20 ans. Vous ne pouvez toutefois être poursuivi à nouveau qu'en cas de retour à meilleure fortune.",
        .schuldenTipCounselingTitle: "Conseil en désendettement gratuit",
        .schuldenTipCounselingBody: "Dettes Conseils Suisse, Caritas et les conseils budgétaires aident gratuitement et confidentiellement. Remboursez d'abord les dettes aux conséquences les plus graves.",
        .schuldenDisclaimer: "Informations générales, pas de conseil juridique.",
        .schuldenAsFixed: "Comme charge fixe",
        .schuldenAsBill: "Comme facture",
        .schuldenAsVariable: "Comme budget variable",

        .catInsurance: "Assurance",
        .catOther: "Autre",
        .catMortgage: "Hypothèque",
        .catHealthInsurance: "Assurance maladie",
        .catSerafe: "Radio/TV (Serafe)",
        .catPublicTransport: "Abonnement de transports",
        .catChildcare: "Garde d'enfants",
        .catMembership: "Cotisations",
        .catAlimony: "Pension alimentaire",
        .catTaxes: "Impôts",
        .catRatenzahlung: "Paiement échelonné",
        .catStreaming: "Streaming",
        .catCreditCard: "Carte de crédit",
        .catClothing: "Vêtements",
        .catHealth: "Santé",
        .catLeisure: "Loisirs & hobbies",
        .catEntertainment: "Divertissement",
        .catChildren: "Enfants",
        .catPets: "Animaux",
        .catGifts: "Cadeaux",
        .catTravel: "Voyages",
        .catCharity: "Dons",
        .catEducation: "Formation",

        .settingsTitle: "Réglages",
        .settingsLanguage: "Langue",
        .settingsTheme: "Thème de couleur",
        .themeCustom: "Thème personnalisé",
        .themeSwissRed: "Rouge suisse",
        .themeOrange: "Orange",
        .themeSand: "Sable",
        .themeGreen: "Vert",
        .themeTeal: "Turquoise",
        .themeBlue: "Bleu",
        .themePurple: "Violet",
        .themePink: "Rose",
        .settingsData: "Données",
        .settingsHousehold: "Ménage",
        .settingsCanton: "Canton",
        .settingsProfile: "Profil",
        .profileName: "Nom",
        .profileChoosePicture: "Choisir une photo de profil",
        .profileNoPicture: "Aucune image",
        .profileLocalNote: "Enregistré uniquement en local sur cet appareil.",
        .settingsSecurity: "Sécurité",
        .settingsAutoLock: "Verrouillage automatique",
        .settingsBiometric: "Déverrouillage biométrique",
        .settingsChangePassphrase: "Modifier la phrase secrète/le NIP",
        .settingsBackup: "Sauvegarde chiffrée",
        .settingsRestore: "Restaurer",
        .settingsPrivacy: "Confidentialité",
        .settingsDangerZone: "Zone sensible",
        .settingsDeleteAll: "Supprimer toutes les données locales",
        .backupCreateTitle: "Créer une sauvegarde chiffrée",
        .backupPassphrase: "Phrase secrète de sauvegarde",
        .backupHint: "Choisissez une phrase secrète de sauvegarde distincte. Elle est requise pour restaurer – aucune récupération de cette phrase n’est possible.",
        .restorePreview: "Aperçu",
        .restoreConfirm: "Remplacer toutes les données locales",
        .restoreWarning: "Cette opération écrase définitivement toutes les données locales.",
        .backupInvalid: "Sauvegarde invalide ou phrase secrète incorrecte.",
        .backupSavedHint: "Conservez le fichier de sauvegarde et la phrase secrète en lieu sûr.",

        .reportTitle: "Signaler un problème",
        .reportSummary: "Résumé",
        .reportExpected: "Comportement attendu",
        .reportActual: "Comportement constaté",
        .reportSteps: "Étapes de reproduction",
        .reportArea: "Zone concernée",
        .reportRedactionNote: "Les données sensibles sont supprimées localement. Vous vérifiez le rapport avant de le copier.",
        .reportCopyHint: "Le rapport n’est pas envoyé automatiquement. Vous le copiez vous-même.",

        .exportReport: "Exporter le rapport",
        .pdfTitle: "Aperçu financier",
        .pdfSubtitle: "Rapport de ménage personnel",
        .pdfSummary: "En un coup d’œil",
        .pdfGeneratedOn: "Généré le",
        .pdfConfidential: "Confidentiel",
        .pdfPage: "Page",
        .pdfTotal: "Total",
        .pdfColProgress: "Progression",
        .pdfUnencryptedNote: "Le rapport est un PDF non chiffré et lisible. Conservez-le en lieu sûr.",
        .pdfNoData: "Aucune donnée à exporter pour l’instant.",
        .pdfDefaultHousehold: "Mon ménage",

        .lockTitle: "Verrouillé",
        .lockWelcomeSetup: "Bienvenue sur Kontiva",
        .lockWelcomeBack: "Bon retour",
        .lockSetupTitle: "Configurer la phrase secrète",
        .lockEnterPassphrase: "Saisir la phrase secrète ou le NIP",
        .lockWrongPassphrase: "Phrase secrète incorrecte. Veuillez réessayer.",
        .lockRecoveryWarning: "Aucune récupération n’est possible. Sans la phrase secrète, vos données sont inaccessibles.",
        .lockRecoveryAcknowledge: "Je comprends qu’aucune récupération n’est possible.",
        .securityNote: "Vos données sont stockées localement et chiffrées (AES-256-GCM). Pas de cloud, pas de serveur, aucune récupération de la phrase secrète.",

        .onboardingIntroBody: "Kontiva vous aide à garder une vue sereine sur votre budget familial suisse – entièrement sur cet appareil.",
        .onboardingStart: "C'est parti",
        .onboardingProfileTitle: "Créer un profil",
        .onboardingProfileBody: "Choisissez un nom et une image. Les deux restent uniquement sur cet appareil.",
        .onboardingSkip: "Passer",
        .onboardingFeaturePrivate: "Entièrement local – pas de cloud, pas de suivi",
        .onboardingFeatureSecure: "Chiffré avec AES-256",
        .onboardingFeatureMoney: "Au centime près, sans erreur d'arrondi",
        .onboardingConfirmPassphrase: "Confirmer la phrase secrète",
        .onboardingPassphraseNote: "Notez votre phrase secrète en lieu sûr – elle ne peut pas être réinitialisée.",
        .backupNudgeText: "Créez une sauvegarde chiffrée. Sans elle, vos données sont perdues si vous oubliez la phrase secrète.",
        .commonNext: "Suivant",
        .navMore: "Plus",
        .actionLock: "Verrouiller",
        .pinSetTitle: "Définir le code",
        .pinConfirmTitle: "Confirmer le code",
        .pinRequirementNote: "Min. 6 chiffres · aucune récupération",
        .pinMismatch: "Les codes ne correspondent pas",
    ]
}
