import Foundation

extension Localization {
    static let ro: [L10nKey: String] = [
        .appName: "Kontiva",
        .appTagline: "O privire calmă și privată asupra bugetului tău elvețian.",
        .notBetaNotice: "Versiune timpurie de dezvoltare – nu este beta, nu este V1.",

        .navOverview: "Prezentare generală",
        .navPlanning: "Plan",
        .navBills: "Facturi",
        .navSettings: "Setări",
        .navReport: "Raportează o problemă",
        .navInsights: "Analize",
        .navSparen: "Economii",
        .sparenSubtitle: "Contribuții de economii recurente – și ce s-a strâns deja.",
        .sparenEmpty: "Încă nu există obiective de economisire. Stabilește pentru ce economisești în fiecare lună.",
        .sparenMonthlyTotal: "Economii / lună",
        .sparenAccumulatedTotal: "Deja economisit",
        .sparenPerMonth: "/ lună",
        .sparenContributions: "contribuții",
        .sparenSince: "din",
        .sparenOpenEnded: "Fără sumă-țintă",
        .sparenGoalsLabel: "Obiective",
        .sparenSortBy: "Sortează",
        .sparenSortStartMonth: "Luna de început",
        .savingsCatCar: "Mașină",
        .savingsCatVacation: "Vacanță",
        .savingsCatHome: "Locuință",
        .savingsCatRetirement: "Pilonul 3a / Pensie",
        .savingsCatEmergency: "Fond de urgență",
        .savingsCatEducation: "Educație",
        .savingsCatOther: "Altele",
        .savingsCatWedding: "Nuntă",
        .savingsCatFamily: "Familie și copii",
        .savingsCatRenovation: "Renovare și mobilare",
        .savingsCatElectronics: "Electronice",
        .savingsCatTaxes: "Rezervă pentru impozite",
        .savingsCatInvestment: "Investiții",
        .savingsCatHealth: "Sănătate",
        .savingsCatGift: "Cadouri",
        .overviewPlannedSavings: "Economii în această lună",
        .overviewShowCalculation: "Afișează calculul",
        .overviewTrendTitle: "Tendință · 6 luni",
        .overviewStatusGood: "Surplus sănătos",
        .overviewStatusTight: "Strâmt",
        .overviewStatusNegative: "Pe minus",
        .overviewAllocationOf: "din venitul net",
        .formStartDate: "Economisesc din",
        .formStartingBalance: "Sold inițial (opțional)",
        .insightsSubtitle: "Îndrumare privind bugetul tău – unde îți stau banii și unde poți economisi.",
        .insightOverspending: "Cheltui mai mult decât câștigi",
        .insightTightBudget: "Puțin loc de manevră luna aceasta",
        .insightHealthySurplus: "Surplus sănătos",
        .insightHighFixed: "Costuri fixe ridicate",
        .insightHighHousing: "Costuri ridicate cu locuința",
        .insightLargestFixed: "Cel mai mare bloc de costuri fixe",
        .insightLargestVariable: "Cel mai mare buget variabil",
        .insightOverdue: "Facturi restante",
        .insightNoSavings: "Încă fără economii planificate",
        .insightGoodSavings: "Rată bună de economisire",
        .insightAllHealthy: "Bugetul tău pare sănătos",
        .insightHousingHint: "Recomandare: cel mult o treime din venit",
        .insightNoSavingsDetail: "Ai loc – un obiectiv de economisire ar putea ajuta.",
        .insightAllHealthyDetail: "Nimic nu iese în evidență. Adaugă mai multe date pentru analize mai precise.",
        .fragOfNetIncome: "din venitul net",
        .fragOfFixedCosts: "din costurile fixe",
        .fragShortfall: "Deficit",

        .commonAdd: "Adaugă",
        .commonEdit: "Editează",
        .commonDelete: "Șterge",
        .commonCancel: "Anulează",
        .commandsAdd: "Adaugă intrare",
        .billsAddCta: "Adaugă prima ta factură",
        .sparenAddCta: "Creează un obiectiv de economisire",
        .overviewAddCta: "Adaugă venit",
        .commonSave: "Salvează",
        .commonSaved: "Salvat",
        .commonClose: "Închide",
        .commonDone: "Gata",
        .commonShowSampleData: "Afișează date exemplu",
        .commonHideSampleData: "Ascunde date exemplu",
        .commonEmptyHint: "Încă nu au fost introduse date.",
        .commonCopy: "Copiază",
        .commonOptions: "Opțiuni",
        .commonMoveUp: "Mută în sus",
        .commonMoveDown: "Mută în jos",
        .monthToday: "Azi",

        .formName: "Nume",
        .formAmount: "Sumă (CHF)",
        .formStatus: "Stare",
        .formNotes: "Notă",
        .formInvalidAmount: "Introdu o sumă validă.",
        .formThirteenthAmount: "Al 13-lea salariu (sumă)",
        .formThirteenthModel: "Model al 13-lea salariu",
        .thirteenthModelSeparate: "Afișează separat",
        .thirteenthModelAveraged: "Distribuie pe 12 luni",
        .formTarget: "Obiectiv de economisire (sumă)",
        .formSaved: "Deja economisit",
        .formMonthlyContribution: "Contribuție lunară",
        .formCategory: "Categorie",
        .formLimitedDuration: "Ordin permanent limitat",
        .formLimitedDurationHint: "Ex.: 6 rate de impozit – numărate doar în acele luni și apoi eliminate automat.",
        .formStartMonth: "Prima rată",
        .formInstallments: "Număr de rate",
        .planningStandingOrder: "Ordin permanent",
        .catRent: "Chirie",
        .catSubscription: "Abonament",
        .catLeasing: "Leasing",
        .catUtilities: "Utilități",
        .catTelecom: "Telecomunicații",
        .catGroceries: "Alimente",
        .catFuel: "Combustibil",
        .catTransport: "Transport",
        .catPersonal: "Personal",
        .catDining: "Masa în oraș",
        .catHousehold: "Gospodărie",

        .overviewTitle: "Prezentare generală",
        .overviewAvailableThisMonth: "Disponibil luna aceasta",
        .overviewNetIncome: "Venit net luna aceasta",
        .overviewThirteenthSeparate: "Al 13-lea salariu (separat)",
        .overviewRecurringFixed: "Costuri fixe",
        .overviewPlannedVariable: "Cheltuieli variabile",
        .overviewBillsDueThisMonth: "Facturi luna aceasta",
        .overviewOverdueBills: "Facturi restante",
        .overviewSavingsTarget: "Obiectiv de economisire",
        .overviewSecurityStatus: "Stare de securitate",
        .overviewFormulaExplainer: "Disponibil = venit net − costuri fixe − bugete variabile − facturi de plată luna aceasta − facturi restante. Facturile plătite și viitoare nu reduc suma.",
        .overviewEmpty: "Introdu venituri și costuri în Planificare lunară pentru a vedea prezentarea generală.",
        .chartSpendingTitle: "Repartizare luna aceasta",
        .chartByCategory: "Pe categorii",

        .planningTitle: "Planificare lunară",
        .planningIncome: "Venit",
        .planningFixed: "Costuri fixe",
        .planningVariable: "Cheltuieli variabile",
        .planningSavings: "Obiectiv de economisire",
        .planningFixedExplainer: "Costurile fixe se repetă în fiecare lună: chirie, asigurări, abonamente, leasing.",
        .planningVariableExplainer: "Bugetele variabile le planifici singur: alimente, combustibil, cheltuieli personale.",
        .planningOneOffHint: "Facturile unice se gestionează în „Facturi”.",
        .planningEmpty: "Începe cu venitul tău, apoi adaugă costuri fixe și bugete.",
        .planningBalance: "Sold planificat",

        .billsTitle: "Facturi",
        .billsStatusOpen: "Deschisă",
        .billsStatusPaid: "Plătită",
        .billsStateOverdue: "Restantă",
        .billsStateDueThisMonth: "Scadentă luna aceasta",
        .billsStateFuture: "Viitoare",
        .billsAffectsBalance: "Reduce suma disponibilă",
        .billsNoBalanceImpact: "Fără efect luna aceasta",
        .billsDueDate: "Data scadenței",
        .billsProvider: "Furnizor",
        .billsEmpty: "Încă nu există facturi. Facturile unice cu dată scadentă apar aici.",
        .billsMarkPaid: "Marchează ca plătită",
        .billsMarkOpen: "Marchează ca deschisă",
        .billsOpenTotal: "Total deschise",

        .navSchulden: "Datorii",
        .schuldenSubtitle: "Ține sub observație facturile restante și executarea silită.",
        .schuldenEmpty: "Nicio datorie înregistrată. Facturile restante apar aici automat – și poți nota executarea silită (Betreibung) sau certificatele de insolvabilitate.",
        .schuldenAddCta: "Înregistrează o datorie",
        .schuldenTotal: "Datorie totală",
        .schuldenOverdueBills: "Facturi restante",
        .schuldenRecorded: "Datorii înregistrate",
        .schuldenManagedInBills: "Gestionează facturile restante în „Facturi”.",
        .debtTypeOpenClaim: "Pretenție deschisă",
        .debtTypeBetreibung: "Executare silită",
        .debtTypePfaendung: "Poprire salariu/bunuri",
        .debtTypeVerlustschein: "Certificat de insolvabilitate",
        .debtTypeOther: "Altă datorie",
        .debtCreditor: "Creditor",
        .debtReference: "Referință / nr. dosar",
        .debtDate: "Dată",
        .debtType: "Tip",
        .schuldenGuidanceTitle: "Cum ieși din datorii",
        .schuldenTipContactTitle: "Ia legătura din timp",
        .schuldenTipContactBody: "Vorbește din timp cu creditorii. Un plan de plată în rate, în scris, este adesea posibil și evită procedura formală.",
        .schuldenTipBetreibungTitle: "Dacă începe executarea",
        .schuldenTipBetreibungBody: "După somația de plată ai 20 de zile să plătești – sau 10 zile să depui o opoziție (Rechtsvorschlag), dacă pretenția este nejustificată.",
        .schuldenTipExistenzminimumTitle: "Minimul tău de existență este protejat",
        .schuldenTipExistenzminimumBody: "La o poprire, minimul tău de existență rămâne neatins – suma de bază, chiria, asigurarea de sănătate și contribuțiile sociale.",
        .schuldenTipVerlustscheinTitle: "Certificat de insolvabilitate",
        .schuldenTipVerlustscheinBody: "Un certificat de insolvabilitate se prescrie abia după 20 de ani. Poți fi urmărit din nou doar când dobândești bunuri noi.",
        .schuldenTipCounselingTitle: "Consiliere gratuită pentru datorii",
        .schuldenTipCounselingBody: "Schuldenberatung Schweiz, Caritas și consilierea bugetară ajută gratuit și confidențial. Plătește mai întâi datoriile cu cele mai grave consecințe.",
        .schuldenDisclaimer: "Informații generale, nu consultanță juridică.",

        .catInsurance: "Asigurare",
        .catOther: "Altele",
        .catMortgage: "Credit ipotecar",
        .catHealthInsurance: "Asigurare de sănătate",
        .catSerafe: "Radio/TV (Serafe)",
        .catPublicTransport: "Abonament de transport",
        .catChildcare: "Îngrijirea copiilor",
        .catMembership: "Cotizații",
        .catAlimony: "Pensii alimentare",
        .catTaxes: "Impozite",
        .catClothing: "Îmbrăcăminte",
        .catHealth: "Sănătate",
        .catLeisure: "Timp liber și hobby-uri",
        .catEntertainment: "Divertisment",
        .catChildren: "Copii",
        .catPets: "Animale de companie",
        .catGifts: "Cadouri",
        .catTravel: "Călătorii",
        .catCharity: "Donații",
        .catEducation: "Educație",

        .settingsTitle: "Setări",
        .settingsLanguage: "Limbă",
        .settingsTheme: "Temă de culoare",
        .themeSwissRed: "Roșu elvețian",
        .themeOrange: "Portocaliu",
        .themeSand: "Nisip",
        .themeGreen: "Verde",
        .themeTeal: "Verde-albastru",
        .themeBlue: "Albastru",
        .themePurple: "Mov",
        .themePink: "Roz",
        .settingsData: "Date",
        .settingsHousehold: "Gospodărie",
        .settingsCanton: "Canton",
        .settingsProfile: "Profil",
        .profileName: "Nume",
        .profileChoosePicture: "Alege poza de profil",
        .profileNoPicture: "Fără poză",
        .profileLocalNote: "Stocat doar local pe acest dispozitiv.",
        .settingsSecurity: "Securitate",
        .settingsAutoLock: "Blocare automată",
        .settingsBiometric: "Deblocare biometrică",
        .settingsChangePassphrase: "Schimbă parola/PIN-ul",
        .settingsBackup: "Copie de rezervă criptată",
        .settingsRestore: "Restaurează",
        .settingsPrivacy: "Confidențialitate",
        .settingsDangerZone: "Zonă periculoasă",
        .settingsDeleteAll: "Șterge toate datele locale",
        .backupCreateTitle: "Creează o copie de rezervă criptată",
        .backupPassphrase: "Parola copiei de rezervă",
        .backupHint: "Alege o parolă separată pentru copia de rezervă. Este necesară pentru restaurare – parola nu poate fi recuperată.",
        .restorePreview: "Previzualizare",
        .restoreConfirm: "Înlocuiește toate datele locale",
        .restoreWarning: "Aceasta suprascrie permanent toate datele locale.",
        .backupInvalid: "Copie de rezervă invalidă sau parolă greșită.",
        .backupSavedHint: "Păstrează fișierul copiei de rezervă și parola într-un loc sigur.",

        .reportTitle: "Raportează o problemă",
        .reportSummary: "Rezumat",
        .reportExpected: "Comportament așteptat",
        .reportActual: "Comportament real",
        .reportSteps: "Pași de reproducere",
        .reportArea: "Zona afectată",
        .reportRedactionNote: "Datele sensibile sunt eliminate local. Verifici raportul înainte de a-l copia.",
        .reportCopyHint: "Raportul nu este trimis automat. Îl copiezi tu.",

        .exportReport: "Exportă raportul",
        .pdfTitle: "Prezentare financiară",
        .pdfSubtitle: "Raport personal al gospodăriei",
        .pdfSummary: "Pe scurt",
        .pdfGeneratedOn: "Generat la",
        .pdfConfidential: "Confidențial",
        .pdfPage: "Pagina",
        .pdfTotal: "Total",
        .pdfColProgress: "Progres",
        .pdfUnencryptedNote: "Raportul este un PDF lizibil, necriptat. Păstrează-l într-un loc sigur.",
        .pdfNoData: "Încă nu există date de exportat.",
        .pdfDefaultHousehold: "Gospodăria mea",

        .lockTitle: "Blocat",
        .lockWelcomeSetup: "Bun venit la Kontiva",
        .lockWelcomeBack: "Bine ai revenit",
        .lockSetupTitle: "Setează parola",
        .lockEnterPassphrase: "Introdu parola sau PIN-ul",
        .lockWrongPassphrase: "Parolă greșită. Încearcă din nou.",
        .lockRecoveryWarning: "Nu există recuperare. Fără parola ta, datele nu pot fi accesate.",
        .lockRecoveryAcknowledge: "Înțeleg că nu există recuperare.",
        .securityNote: "Datele tale sunt stocate local și criptate (AES-256-GCM). Fără cloud, fără server, fără recuperarea parolei.",

        .onboardingIntroBody: "Kontiva te ajută să ai o privire calmă asupra bugetului gospodăriei tale elvețiene – complet pe acest dispozitiv.",
        .onboardingStart: "Începe",
        .onboardingProfileTitle: "Creează un profil",
        .onboardingProfileBody: "Dă-ți un nume și alege o imagine. Ambele rămân doar pe acest dispozitiv.",
        .onboardingSkip: "Omite",
        .onboardingFeaturePrivate: "Complet local – fără cloud, fără urmărire",
        .onboardingFeatureSecure: "Criptat cu AES-256",
        .onboardingFeatureMoney: "Precis până la centimă, fără erori de rotunjire",
        .onboardingConfirmPassphrase: "Confirmă parola",
        .onboardingPassphraseNote: "Notează-ți parola într-un loc sigur – nu poate fi resetată.",
        .backupNudgeText: "Creează o copie de rezervă criptată. Fără ea, îți pierzi datele dacă uiți parola.",
        .commonNext: "Înainte",
        .navMore: "Mai multe",
        .actionLock: "Blochează",
        .pinSetTitle: "Setează codul",
        .pinConfirmTitle: "Confirmă codul",
        .pinRequirementNote: "Min. 6 cifre · fără recuperare",
        .pinMismatch: "Codurile nu se potrivesc",
    ]
}
