import Foundation

extension Localization {
    static let ptBR: [L10nKey: String] = [
        .appName: "Kontiva",
        .appTagline: "Uma visão tranquila e privada do seu orçamento suíço.",
        .notBetaNotice: "Versão em desenvolvimento inicial — não é beta, não é V1.",

        .navOverview: "Visão geral",
        .navPlanning: "Plano",
        .navBills: "Contas",
        .navSettings: "Configurações",
        .navReport: "Relatar um problema",
        .navInsights: "Análises",
        .navSparen: "Poupança",
        .sparenSubtitle: "Contribuições de poupança recorrentes — e o que você já juntou.",
        .sparenEmpty: "Ainda não há metas de poupança. Defina para que você economiza todo mês.",
        .sparenMonthlyTotal: "Poupança / mês",
        .sparenAccumulatedTotal: "Já poupado",
        .sparenPerMonth: "/ mês",
        .sparenContributions: "contribuições",
        .sparenSince: "desde",
        .sparenOpenEnded: "Sem valor-alvo",
        .sparenGoalsLabel: "Metas",
        .sparenSortBy: "Ordenar",
        .sparenSortStartMonth: "Mês de início",
        .savingsCatCar: "Carro",
        .savingsCatVacation: "Férias",
        .savingsCatHome: "Casa",
        .savingsCatRetirement: "Pilar 3a / Aposentadoria",
        .savingsCatEmergency: "Fundo de emergência",
        .savingsCatEducation: "Educação",
        .savingsCatOther: "Outro",
        .savingsCatWedding: "Casamento",
        .savingsCatFamily: "Família e filhos",
        .savingsCatRenovation: "Reforma e mobília",
        .savingsCatElectronics: "Eletrônicos",
        .savingsCatTaxes: "Reserva para impostos",
        .savingsCatInvestment: "Investimentos",
        .savingsCatHealth: "Saúde",
        .savingsCatGift: "Presentes",
        .overviewPlannedSavings: "Poupança neste mês",
        .overviewShowCalculation: "Mostrar cálculo",
        .overviewTrendTitle: "Tendência · 6 meses",
        .overviewStatusGood: "Sobra saudável",
        .overviewStatusTight: "Apertado",
        .overviewStatusNegative: "No vermelho",
        .overviewAllocationOf: "da renda líquida",
        .formStartDate: "Poupando desde",
        .formStartingBalance: "Saldo inicial (opcional)",
        .insightsSubtitle: "Orientação sobre seu orçamento — onde está seu dinheiro e onde você pode economizar.",
        .insightOverspending: "Você gasta mais do que ganha",
        .insightTightBudget: "Pouca margem neste mês",
        .insightHealthySurplus: "Sobra saudável",
        .insightHighFixed: "Alta carga de custos fixos",
        .insightHighHousing: "Custos de moradia elevados",
        .insightLargestFixed: "Maior bloco de custos fixos",
        .insightLargestVariable: "Maior orçamento variável",
        .insightOverdue: "Contas em atraso",
        .insightNoSavings: "Ainda sem poupança planejada",
        .insightGoodSavings: "Boa taxa de poupança",
        .insightAllHealthy: "Seu orçamento parece saudável",
        .insightHousingHint: "Recomendação: no máximo um terço da renda",
        .insightNoSavingsDetail: "Você tem margem — uma meta de poupança pode ajudar.",
        .insightAllHealthyDetail: "Nada se destaca. Adicione mais dados para análises mais precisas.",
        .fragOfNetIncome: "da renda líquida",
        .fragOfFixedCosts: "dos custos fixos",
        .fragShortfall: "Déficit",

        .commonAdd: "Adicionar",
        .commonEdit: "Editar",
        .commonActivate: "Ativar",
        .commonDelete: "Excluir",
        .commonCancel: "Cancelar",
        .commandsAdd: "Adicionar item",
        .billsAddCta: "Adicione sua primeira conta",
        .sparenAddCta: "Criar uma meta de poupança",
        .overviewAddCta: "Adicionar renda",
        .commonSave: "Salvar",
        .commonSaved: "Salvo",
        .commonClose: "Fechar",
        .commonDone: "Concluído",
        .commonShowSampleData: "Mostrar dados de exemplo",
        .commonHideSampleData: "Ocultar dados de exemplo",
        .commonEmptyHint: "Nenhum dado inserido ainda.",
        .commonCopy: "Copiar",
        .commonOptions: "Opções",
        .commonMoveUp: "Mover para cima",
        .commonMoveDown: "Mover para baixo",
        .monthToday: "Hoje",

        .formName: "Nome",
        .formAmount: "Valor (CHF)",
        .formStatus: "Status",
        .formNotes: "Observação",
        .formInvalidAmount: "Insira um valor válido.",
        .formThirteenthAmount: "13.º salário (valor)",
        .formThirteenthModel: "Modelo do 13.º salário",
        .thirteenthModelSeparate: "Mostrar separadamente",
        .thirteenthModelAveraged: "Distribuir em 12 meses",
        .formTarget: "Meta de poupança (valor)",
        .formSaved: "Já poupado",
        .formMonthlyContribution: "Contribuição mensal",
        .formCategory: "Categoria",
        .formLimitedDuration: "Ordem permanente limitada",
        .formLimitedDurationHint: "Ex.: 6 parcelas de impostos — contadas apenas nesses meses e depois removidas automaticamente.",
        .formStartMonth: "Primeira parcela",
        .formInstallments: "Número de parcelas",
        .planningStandingOrder: "Ordem permanente",
        .catRent: "Aluguel",
        .catSubscription: "Assinatura",
        .catLeasing: "Leasing",
        .catUtilities: "Serviços (água, luz)",
        .catTelecom: "Telecom",
        .catGroceries: "Supermercado",
        .catFuel: "Combustível",
        .catTransport: "Transporte",
        .catPersonal: "Pessoal",
        .catDining: "Comer fora",
        .catHousehold: "Casa",

        .overviewTitle: "Visão geral",
        .overviewAvailableThisMonth: "Disponível neste mês",
        .overviewNetIncome: "Renda líquida neste mês",
        .overviewThirteenthSeparate: "13.º salário (separadamente)",
        .overviewRecurringFixed: "Custos fixos",
        .overviewPlannedVariable: "Gastos variáveis",
        .overviewBillsDueThisMonth: "Contas deste mês",
        .overviewOverdueBills: "Contas em atraso",
        .overviewSavingsTarget: "Meta de poupança",
        .overviewSecurityStatus: "Status de segurança",
        .overviewFormulaExplainer: "Disponível = renda líquida − custos fixos − orçamentos variáveis − contas a vencer neste mês − contas em atraso. Contas pagas e futuras não reduzem o valor.",
        .overviewEmpty: "Insira renda e custos no Planejamento mensal para ver sua visão geral.",
        .chartSpendingTitle: "Distribuição deste mês",
        .chartByCategory: "Por categoria",

        .planningTitle: "Planejamento mensal",
        .planningIncome: "Renda",
        .planningFixed: "Custos fixos",
        .planningVariable: "Gastos variáveis",
        .planningSavings: "Meta de poupança",
        .planningFixedExplainer: "Os custos fixos se repetem todo mês: aluguel, seguros, assinaturas, leasing.",
        .planningVariableExplainer: "Os orçamentos variáveis você planeja: supermercado, combustível, gastos pessoais.",
        .planningOneOffHint: "As contas avulsas são gerenciadas em «Contas».",
        .planningEmpty: "Comece pela sua renda e depois adicione custos fixos e orçamentos.",
        .planningBalance: "Saldo planejado",

        .billsTitle: "Contas",
        .billsStatusOpen: "Em aberto",
        .billsStatusPaid: "Paga",
        .billsStateOverdue: "Em atraso",
        .billsStateDueThisMonth: "Vence neste mês",
        .billsStateFuture: "Futura",
        .billsAffectsBalance: "Reduz o valor disponível",
        .billsNoBalanceImpact: "Sem efeito neste mês",
        .billsDueDate: "Vencimento",
        .billsProvider: "Fornecedor",
        .billsEmpty: "Nenhuma conta inserida ainda. Contas avulsas com data de vencimento aparecem aqui.",
        .billsMarkPaid: "Marcar como paga",
        .billsMarkOpen: "Marcar como em aberto",
        .billsOpenTotal: "Total em aberto",

        .navSchulden: "Dívidas",
        .schuldenSubtitle: "Fique de olho nas contas em atraso e nos processos de cobrança.",
        .schuldenEmpty: "Nenhuma dívida registrada. As contas em atraso aparecem aqui automaticamente — e você pode registrar processos de cobrança (Betreibung) ou certidões de incobrabilidade.",
        .schuldenAddCta: "Registrar uma dívida",
        .schuldenTotal: "Dívida total",
        .schuldenOverdueBills: "Contas em atraso",
        .schuldenRecorded: "Dívidas registradas",
        .schuldenManagedInBills: "Gerencie as contas em atraso em «Contas».",
        .debtTypeOpenClaim: "Cobrança em aberto",
        .debtTypeBetreibung: "Processo de cobrança",
        .debtTypePfaendung: "Penhora de salário/bens",
        .debtTypeVerlustschein: "Certidão de incobrabilidade",
        .debtTypeOther: "Outra dívida",
        .debtCreditor: "Credor",
        .debtReference: "Referência / n.º do processo",
        .debtDate: "Data",
        .debtType: "Tipo",
        .schuldenGuidanceTitle: "Encontrando a saída das dívidas",
        .schuldenTipContactTitle: "Entre em contato cedo",
        .schuldenTipContactBody: "Converse com os credores o quanto antes. Um plano de parcelamento por escrito costuma ser possível e evita o processo formal.",
        .schuldenTipBetreibungTitle: "Se o processo começar",
        .schuldenTipBetreibungBody: "Após a ordem de pagamento você tem 20 dias para pagar — ou 10 dias para apresentar objeção (Rechtsvorschlag) se a cobrança for injustificada.",
        .schuldenTipExistenzminimumTitle: "Seu mínimo de subsistência é protegido",
        .schuldenTipExistenzminimumBody: "Em uma penhora, seu mínimo de subsistência permanece intocável — valor base, aluguel, plano de saúde e contribuições sociais.",
        .schuldenTipVerlustscheinTitle: "Certidão de incobrabilidade",
        .schuldenTipVerlustscheinBody: "Uma certidão de incobrabilidade prescreve apenas após 20 anos. Você só pode ser cobrado de novo quando adquirir novos bens.",
        .schuldenTipCounselingTitle: "Aconselhamento de dívidas gratuito",
        .schuldenTipCounselingBody: "A Schuldenberatung Schweiz, a Caritas e os serviços de orientação orçamentária ajudam de forma gratuita e sigilosa. Pague primeiro as dívidas com piores consequências.",
        .schuldenDisclaimer: "Informação geral, não é aconselhamento jurídico.",

        .catInsurance: "Seguros",
        .catOther: "Outro",
        .catMortgage: "Financiamento imobiliário",
        .catHealthInsurance: "Plano de saúde",
        .catSerafe: "Rádio/TV (Serafe)",
        .catPublicTransport: "Passe de transporte",
        .catChildcare: "Creche / babá",
        .catMembership: "Mensalidades e associações",
        .catAlimony: "Pensão e alimentos",
        .catTaxes: "Impostos",
        .catClothing: "Vestuário",
        .catHealth: "Saúde",
        .catLeisure: "Lazer e hobbies",
        .catEntertainment: "Entretenimento",
        .catChildren: "Crianças",
        .catPets: "Animais",
        .catGifts: "Presentes",
        .catTravel: "Viagens",
        .catCharity: "Doações",
        .catEducation: "Educação",

        .settingsTitle: "Configurações",
        .settingsLanguage: "Idioma",
        .settingsTheme: "Tema de cor",
        .themeSwissRed: "Vermelho suíço",
        .themeOrange: "Laranja",
        .themeSand: "Areia",
        .themeGreen: "Verde",
        .themeTeal: "Verde-azulado",
        .themeBlue: "Azul",
        .themePurple: "Roxo",
        .themePink: "Rosa",
        .settingsData: "Dados",
        .settingsHousehold: "Domicílio",
        .settingsCanton: "Cantão",
        .settingsProfile: "Perfil",
        .profileName: "Nome",
        .profileChoosePicture: "Escolher foto de perfil",
        .profileNoPicture: "Sem foto",
        .profileLocalNote: "Salvo apenas localmente neste dispositivo.",
        .settingsSecurity: "Segurança",
        .settingsAutoLock: "Bloqueio automático",
        .settingsBiometric: "Desbloqueio biométrico",
        .settingsChangePassphrase: "Alterar senha/PIN",
        .settingsBackup: "Backup criptografado",
        .settingsRestore: "Restaurar",
        .settingsPrivacy: "Privacidade",
        .settingsDangerZone: "Zona de perigo",
        .settingsDeleteAll: "Excluir todos os dados locais",
        .backupCreateTitle: "Criar backup criptografado",
        .backupPassphrase: "Senha do backup",
        .backupHint: "Escolha uma senha separada para o backup. Ela é necessária para restaurar — não há como recuperá-la.",
        .restorePreview: "Pré-visualização",
        .restoreConfirm: "Substituir todos os dados locais",
        .restoreWarning: "Isto substitui permanentemente todos os dados locais.",
        .backupInvalid: "Backup inválido ou senha incorreta.",
        .backupSavedHint: "Guarde o arquivo de backup e a senha em um lugar seguro.",

        .reportTitle: "Relatar um problema",
        .reportSummary: "Resumo",
        .reportExpected: "Comportamento esperado",
        .reportActual: "Comportamento real",
        .reportSteps: "Passos para reproduzir",
        .reportArea: "Área afetada",
        .reportRedactionNote: "Dados sensíveis são removidos localmente. Revise o relatório antes de copiar.",
        .reportCopyHint: "O relatório não é enviado automaticamente. Você mesmo o copia.",

        .exportReport: "Exportar relatório",
        .pdfTitle: "Visão financeira",
        .pdfSubtitle: "Relatório pessoal do domicílio",
        .pdfSummary: "Num relance",
        .pdfGeneratedOn: "Gerado em",
        .pdfConfidential: "Confidencial",
        .pdfPage: "Página",
        .pdfTotal: "Total",
        .pdfColProgress: "Progresso",
        .pdfUnencryptedNote: "O relatório é um PDF legível e não criptografado. Guarde-o em um lugar seguro.",
        .pdfNoData: "Ainda não há dados para exportar.",
        .pdfDefaultHousehold: "Meu domicílio",

        .lockTitle: "Bloqueado",
        .lockWelcomeSetup: "Bem-vindo ao Kontiva",
        .lockWelcomeBack: "Bem-vindo de volta",
        .lockSetupTitle: "Definir senha",
        .lockEnterPassphrase: "Digite a senha ou o PIN",
        .lockWrongPassphrase: "Senha incorreta. Tente novamente.",
        .lockRecoveryWarning: "Não há recuperação. Sem sua senha, não é possível acessar seus dados.",
        .lockRecoveryAcknowledge: "Entendo que não há recuperação.",
        .securityNote: "Seus dados são salvos localmente e criptografados (AES-256-GCM). Sem nuvem, sem servidor, sem recuperação de senha.",

        .onboardingIntroBody: "O Kontiva ajuda você a manter uma visão tranquila do orçamento do seu domicílio suíço — totalmente neste dispositivo.",
        .onboardingStart: "Começar",
        .onboardingProfileTitle: "Crie um perfil",
        .onboardingProfileBody: "Escolha um nome e uma imagem. Ambos ficam apenas neste dispositivo.",
        .onboardingSkip: "Pular",
        .onboardingFeaturePrivate: "Totalmente local — sem nuvem, sem rastreamento",
        .onboardingFeatureSecure: "Criptografado com AES-256",
        .onboardingFeatureMoney: "Preciso até o centavo, sem erros de arredondamento",
        .onboardingConfirmPassphrase: "Confirmar senha",
        .onboardingPassphraseNote: "Anote sua senha em um lugar seguro — ela não pode ser redefinida.",
        .backupNudgeText: "Crie um backup criptografado. Sem ele, você perde seus dados se esquecer a senha.",
        .commonNext: "Avançar",
        .navMore: "Mais",
        .actionLock: "Bloquear",
        .pinSetTitle: "Definir código",
        .pinConfirmTitle: "Confirmar código",
        .pinRequirementNote: "Mín. 6 dígitos · sem recuperação",
        .pinMismatch: "Os códigos não coincidem",
    ]
}
