import Foundation

extension Localization {
    static let hu: [L10nKey: String] = [
        .appName: "Kontiva",
        .appTagline: "Nyugodt, privát rálátás a svájci költségvetésedre.",
        .notBetaNotice: "Korai fejlesztői verzió – nem béta, nem V1.",

        .navOverview: "Áttekintés",
        .navPlanning: "Havi tervezés",
        .navBills: "Számlák",
        .navSettings: "Beállítások",
        .navReport: "Probléma jelentése",
        .navInsights: "Elemzések",
        .navSparen: "Megtakarítás",
        .sparenSubtitle: "Rendszeres megtakarítási befizetések – és ami már összegyűlt.",
        .sparenEmpty: "Még nincsenek megtakarítási célok. Határozd meg, mire spórolsz havonta.",
        .sparenMonthlyTotal: "Megtakarítás / hó",
        .sparenAccumulatedTotal: "Eddig megtakarítva",
        .sparenPerMonth: "/ hó",
        .sparenContributions: "befizetés",
        .sparenSince: "óta",
        .sparenOpenEnded: "Nincs célösszeg",
        .sparenGoalsLabel: "Célok",
        .savingsCatCar: "Autó",
        .savingsCatVacation: "Nyaralás",
        .savingsCatHome: "Lakhatás",
        .savingsCatRetirement: "3a pillér / Nyugdíj",
        .savingsCatEmergency: "Vésztartalék",
        .savingsCatEducation: "Oktatás",
        .savingsCatOther: "Egyéb",
        .savingsCatWedding: "Esküvő",
        .savingsCatFamily: "Család és gyerekek",
        .savingsCatRenovation: "Felújítás és berendezés",
        .savingsCatElectronics: "Elektronika",
        .savingsCatTaxes: "Adótartalék",
        .savingsCatInvestment: "Befektetések",
        .savingsCatHealth: "Egészség",
        .savingsCatGift: "Ajándékok",
        .overviewPlannedSavings: "Megtakarítás ebben a hónapban",
        .overviewShowCalculation: "Számítás megjelenítése",
        .overviewTrendTitle: "Trend · 6 hónap",
        .overviewStatusGood: "Egészséges többlet",
        .overviewStatusTight: "Szűkös",
        .overviewStatusNegative: "Mínuszban",
        .overviewAllocationOf: "a nettó jövedelemből",
        .formStartDate: "Megtakarítás kezdete",
        .formStartingBalance: "Kezdő egyenleg (opcionális)",
        .insightsSubtitle: "Útmutatás a költségvetésedhez – hol van a pénzed és hol takaríthatsz meg.",
        .insightOverspending: "Többet költesz, mint amennyit keresel",
        .insightTightBudget: "Kevés a mozgástér ebben a hónapban",
        .insightHealthySurplus: "Egészséges többlet",
        .insightHighFixed: "Magas állandó költségek",
        .insightHighHousing: "Magas lakhatási költségek",
        .insightLargestFixed: "Legnagyobb állandó költségtétel",
        .insightLargestVariable: "Legnagyobb változó keret",
        .insightOverdue: "Lejárt számlák",
        .insightNoSavings: "Még nincs megtervezett megtakarítás",
        .insightGoodSavings: "Jó megtakarítási arány",
        .insightAllHealthy: "A költségvetésed egészségesnek tűnik",
        .insightHousingHint: "Irányelv: legfeljebb a jövedelem harmada",
        .insightNoSavingsDetail: "Van mozgástered – egy megtakarítási cél segíthet.",
        .insightAllHealthyDetail: "Semmi sem tűnik ki. Adj meg több adatot a pontosabb elemzésekhez.",
        .fragOfNetIncome: "a nettó jövedelemből",
        .fragOfFixedCosts: "az állandó költségekből",
        .fragShortfall: "Hiány",

        .commonAdd: "Hozzáadás",
        .commonEdit: "Szerkesztés",
        .commonDelete: "Törlés",
        .commonCancel: "Mégse",
        .commandsAdd: "Bejegyzés hozzáadása",
        .billsAddCta: "Add hozzá az első számládat",
        .sparenAddCta: "Megtakarítási cél létrehozása",
        .overviewAddCta: "Jövedelem hozzáadása",
        .commonSave: "Mentés",
        .commonSaved: "Mentve",
        .commonClose: "Bezárás",
        .commonDone: "Kész",
        .commonShowSampleData: "Mintaadatok megjelenítése",
        .commonHideSampleData: "Mintaadatok elrejtése",
        .commonEmptyHint: "Még nincs adat megadva.",
        .commonCopy: "Másolás",
        .commonOptions: "Beállítások",
        .commonMoveUp: "Mozgatás fel",
        .commonMoveDown: "Mozgatás le",
        .monthToday: "Ma",

        .formName: "Név",
        .formAmount: "Összeg (CHF)",
        .formStatus: "Állapot",
        .formNotes: "Megjegyzés",
        .formInvalidAmount: "Adj meg érvényes összeget.",
        .formThirteenthAmount: "13. havi fizetés (összeg)",
        .formThirteenthModel: "13. havi fizetés modellje",
        .thirteenthModelSeparate: "Külön megjelenítés",
        .thirteenthModelAveraged: "Elosztás 12 hónapra",
        .formTarget: "Megtakarítási cél (összeg)",
        .formSaved: "Eddig megtakarítva",
        .formMonthlyContribution: "Havi befizetés",
        .formCategory: "Kategória",
        .formLimitedDuration: "Határozott idejű állandó megbízás",
        .formLimitedDurationHint: "Pl. 6 adórészlet – csak azokban a hónapokban számít, majd automatikusan megszűnik.",
        .formStartMonth: "Első részlet",
        .formInstallments: "Részletek száma",
        .planningStandingOrder: "Állandó megbízás",
        .catRent: "Bérleti díj",
        .catSubscription: "Előfizetés",
        .catLeasing: "Lízing",
        .catUtilities: "Közüzemi díjak",
        .catTelecom: "Telekommunikáció",
        .catGroceries: "Élelmiszer",
        .catFuel: "Üzemanyag",
        .catTransport: "Közlekedés",
        .catPersonal: "Személyes",
        .catDining: "Étkezés házon kívül",
        .catHousehold: "Háztartás",

        .overviewTitle: "Áttekintés",
        .overviewAvailableThisMonth: "Elérhető ebben a hónapban",
        .overviewNetIncome: "Nettó jövedelem ebben a hónapban",
        .overviewThirteenthSeparate: "13. havi fizetés (külön)",
        .overviewRecurringFixed: "Állandó költségek",
        .overviewPlannedVariable: "Változó kiadások",
        .overviewBillsDueThisMonth: "Nyitott számlák ebben a hónapban",
        .overviewOverdueBills: "Lejárt számlák",
        .overviewSavingsTarget: "Megtakarítási cél",
        .overviewSecurityStatus: "Biztonsági állapot",
        .overviewFormulaExplainer: "Elérhető = nettó jövedelem − állandó költségek − változó keretek − ebben a hónapban nyitott számlák − lejárt számlák. A kifizetett és jövőbeli számlák nem csökkentik az összeget.",
        .overviewEmpty: "Adj meg jövedelmet és költségeket a Havi tervezésben az áttekintés megtekintéséhez.",
        .chartSpendingTitle: "Megoszlás ebben a hónapban",
        .chartByCategory: "Kategóriánként",

        .planningTitle: "Havi tervezés",
        .planningIncome: "Jövedelem",
        .planningFixed: "Állandó költségek",
        .planningVariable: "Változó kiadások",
        .planningSavings: "Megtakarítási cél",
        .planningFixedExplainer: "Az állandó költségek minden hónapban ismétlődnek: bérleti díj, biztosítások, előfizetések, lízing.",
        .planningVariableExplainer: "A változó kereteket te tervezed: élelmiszer, üzemanyag, személyes kiadások.",
        .planningOneOffHint: "Az egyszeri számlákat a „Számlák” részben kezeled.",
        .planningEmpty: "Kezdd a jövedelmeddel, majd add hozzá az állandó költségeket és a kereteket.",
        .planningBalance: "Tervezett egyenleg",

        .billsTitle: "Számlák",
        .billsStatusOpen: "Nyitott",
        .billsStatusPaid: "Kifizetve",
        .billsStateOverdue: "Lejárt",
        .billsStateDueThisMonth: "Ebben a hónapban esedékes",
        .billsStateFuture: "Jövőbeli",
        .billsAffectsBalance: "Csökkenti az elérhető összeget",
        .billsNoBalanceImpact: "Nincs hatása ebben a hónapban",
        .billsDueDate: "Esedékesség",
        .billsProvider: "Szolgáltató",
        .billsEmpty: "Még nincsenek számlák. Az esedékességi dátummal rendelkező egyszeri számlák itt jelennek meg.",
        .billsMarkPaid: "Megjelölés kifizetettként",
        .billsMarkOpen: "Megjelölés nyitottként",
        .billsOpenTotal: "Nyitott összesen",

        .navSchulden: "Adósságok",
        .schuldenSubtitle: "Tartsd szemmel a lejárt számlákat és a behajtást.",
        .schuldenEmpty: "Nincs rögzített adósság. A lejárt számlák itt automatikusan megjelennek – és feljegyezhetsz behajtást (Betreibung) vagy veszteségbizonylatot.",
        .schuldenAddCta: "Adósság rögzítése",
        .schuldenTotal: "Teljes adósság",
        .schuldenOverdueBills: "Lejárt számlák",
        .schuldenRecorded: "Rögzített adósságok",
        .schuldenManagedInBills: "A lejárt számlákat a „Számlák” részben kezeld.",
        .debtTypeOpenClaim: "Nyitott követelés",
        .debtTypeBetreibung: "Behajtási eljárás",
        .debtTypePfaendung: "Bér-/vagyonletiltás",
        .debtTypeVerlustschein: "Veszteségbizonylat",
        .debtTypeOther: "Egyéb adósság",
        .debtCreditor: "Hitelező",
        .debtReference: "Hivatkozás / ügyszám",
        .debtDate: "Dátum",
        .debtType: "Típus",
        .schuldenGuidanceTitle: "Kiút az adósságból",
        .schuldenTipContactTitle: "Vedd fel időben a kapcsolatot",
        .schuldenTipContactBody: "Beszélj korán a hitelezőkkel. Írásos részletfizetési megállapodás gyakran lehetséges, és elkerülhető a hivatalos eljárás.",
        .schuldenTipBetreibungTitle: "Ha elindul az eljárás",
        .schuldenTipBetreibungBody: "A fizetési meghagyás után 20 napod van fizetni – vagy 10 napod kifogást (Rechtsvorschlag) emelni, ha a követelés jogtalan.",
        .schuldenTipExistenzminimumTitle: "A létminimumod védett",
        .schuldenTipExistenzminimumBody: "Letiltáskor a létminimumod érinthetetlen marad – alapösszeg, bérleti díj, egészségbiztosítás és társadalombiztosítási járulékok.",
        .schuldenTipVerlustscheinTitle: "Veszteségbizonylat",
        .schuldenTipVerlustscheinBody: "A veszteségbizonylat csak 20 év után évül el. Csak akkor indulhat újra eljárás, ha új vagyonra teszel szert.",
        .schuldenTipCounselingTitle: "Ingyenes adósságtanácsadás",
        .schuldenTipCounselingBody: "A Schuldenberatung Schweiz, a Caritas és a költségvetési tanácsadás ingyen és bizalmasan segít. Először a legsúlyosabb következményekkel járó adósságokat fizesd ki.",
        .schuldenDisclaimer: "Általános tájékoztatás, nem jogi tanácsadás.",

        .catInsurance: "Biztosítás",
        .catOther: "Egyéb",
        .catMortgage: "Jelzáloghitel",
        .catHealthInsurance: "Egészségbiztosítás",
        .catSerafe: "Rádió/TV (Serafe)",
        .catPublicTransport: "Bérlet",
        .catChildcare: "Gyermekfelügyelet",
        .catMembership: "Tagdíjak",
        .catAlimony: "Tartásdíj",
        .catTaxes: "Adók",
        .catClothing: "Ruházat",
        .catHealth: "Egészség",
        .catLeisure: "Szabadidő és hobbi",
        .catEntertainment: "Szórakozás",
        .catChildren: "Gyerekek",
        .catPets: "Háziállatok",
        .catGifts: "Ajándékok",
        .catTravel: "Utazás",
        .catCharity: "Adományok",
        .catEducation: "Oktatás",

        .settingsTitle: "Beállítások",
        .settingsLanguage: "Nyelv",
        .settingsTheme: "Színtéma",
        .themeSwissRed: "Svájci vörös",
        .themeOrange: "Narancs",
        .themeSand: "Homok",
        .themeGreen: "Zöld",
        .themeTeal: "Türkiz",
        .themeBlue: "Kék",
        .themePurple: "Lila",
        .themePink: "Rózsaszín",
        .settingsData: "Adatok",
        .settingsHousehold: "Háztartás",
        .settingsCanton: "Kanton",
        .settingsProfile: "Profil",
        .profileName: "Név",
        .profileChoosePicture: "Profilkép kiválasztása",
        .profileNoPicture: "Nincs kép",
        .profileLocalNote: "Csak helyben, ezen az eszközön tárolva.",
        .settingsSecurity: "Biztonság",
        .settingsAutoLock: "Automatikus zárolás",
        .settingsBiometric: "Biometrikus feloldás",
        .settingsChangePassphrase: "Jelszó/PIN módosítása",
        .settingsBackup: "Titkosított biztonsági mentés",
        .settingsRestore: "Visszaállítás",
        .settingsPrivacy: "Adatvédelem",
        .settingsDangerZone: "Veszélyzóna",
        .settingsDeleteAll: "Összes helyi adat törlése",
        .backupCreateTitle: "Titkosított biztonsági mentés létrehozása",
        .backupPassphrase: "Mentés jelszava",
        .backupHint: "Válassz külön jelszót a mentéshez. A visszaállításhoz szükséges – a jelszó nem állítható vissza.",
        .restorePreview: "Előnézet",
        .restoreConfirm: "Összes helyi adat cseréje",
        .restoreWarning: "Ez véglegesen felülír minden helyi adatot.",
        .backupInvalid: "Érvénytelen mentés vagy hibás jelszó.",
        .backupSavedHint: "A mentési fájlt és a jelszót biztonságos helyen őrizd.",

        .reportTitle: "Probléma jelentése",
        .reportSummary: "Összegzés",
        .reportExpected: "Várt viselkedés",
        .reportActual: "Tényleges viselkedés",
        .reportSteps: "Reprodukálás lépései",
        .reportArea: "Érintett terület",
        .reportRedactionNote: "Az érzékeny adatok helyben eltávolításra kerülnek. Másolás előtt átnézed a jelentést.",
        .reportCopyHint: "A jelentés nem küldődik el automatikusan. Te magad másolod.",

        .exportReport: "Jelentés exportálása",
        .pdfTitle: "Pénzügyi áttekintés",
        .pdfSubtitle: "Személyes háztartási jelentés",
        .pdfSummary: "Egy pillantásra",
        .pdfGeneratedOn: "Létrehozva",
        .pdfConfidential: "Bizalmas",
        .pdfPage: "Oldal",
        .pdfTotal: "Összesen",
        .pdfColProgress: "Haladás",
        .pdfUnencryptedNote: "A jelentés olvasható, titkosítatlan PDF. Tartsd biztonságos helyen.",
        .pdfNoData: "Még nincs exportálható adat.",
        .pdfDefaultHousehold: "Háztartásom",

        .lockTitle: "Zárolva",
        .lockWelcomeSetup: "Üdvözöl a Kontiva",
        .lockWelcomeBack: "Üdv újra",
        .lockSetupTitle: "Jelszó beállítása",
        .lockEnterPassphrase: "Add meg a jelszót vagy PIN-t",
        .lockWrongPassphrase: "Hibás jelszó. Próbáld újra.",
        .lockRecoveryWarning: "Nincs helyreállítás. A jelszavad nélkül az adataid nem érhetők el.",
        .lockRecoveryAcknowledge: "Megértettem, hogy nincs helyreállítás.",
        .securityNote: "Az adataid helyben, titkosítva tárolódnak (AES-256-GCM). Nincs felhő, nincs szerver, nincs jelszó-helyreállítás.",

        .onboardingIntroBody: "A Kontiva segít, hogy nyugodt rálátásod legyen a svájci háztartásod költségvetésére – teljesen ezen az eszközön.",
        .onboardingStart: "Kezdés",
        .onboardingProfileTitle: "Hozz létre profilt",
        .onboardingProfileBody: "Adj magadnak nevet és válassz képet. Mindkettő csak ezen az eszközön marad.",
        .onboardingSkip: "Kihagyás",
        .onboardingFeaturePrivate: "Teljesen helyi – nincs felhő, nincs követés",
        .onboardingFeatureSecure: "AES-256 titkosítással",
        .onboardingFeatureMoney: "Centime-pontos, kerekítési hibák nélkül",
        .onboardingConfirmPassphrase: "Jelszó megerősítése",
        .onboardingPassphraseNote: "Írd le a jelszavad egy biztonságos helyre – nem lehet visszaállítani.",
        .backupNudgeText: "Hozz létre titkosított biztonsági mentést. Nélküle elveszíted az adataidat, ha elfelejted a jelszót.",
        .commonNext: "Tovább",
        .navMore: "Továbbiak",
        .actionLock: "Zárolás",
        .pinSetTitle: "Kód beállítása",
        .pinConfirmTitle: "Kód megerősítése",
        .pinRequirementNote: "Min. 6 számjegy · nincs helyreállítás",
        .pinMismatch: "A kódok nem egyeznek",
    ]
}
