import Foundation

// Pashto (RTL). Best-effort — flagged alongside Romansh as the highest
// priority for native-speaker review.
extension Localization {
    static let ps: [L10nKey: String] = [
        .appName: "Kontiva",
        .appTagline: "ستاسو په سویس بودیجه یوه ارامه، شخصي کتنه.",
        .notBetaNotice: "د پراختیا لومړنۍ نسخه – بیټا نه ده، V1 نه ده.",

        .navOverview: "لنډه کتنه",
        .navPlanning: "میاشتنی پلان",
        .navBills: "بلونه",
        .navSettings: "امستنې",
        .navReport: "ستونزه راپور کړئ",
        .navInsights: "شننه",
        .navSparen: "سپما",
        .sparenSubtitle: "منظمې سپما ونډې – او هغه څه چې لا دمخه راټول شوي.",
        .sparenEmpty: "تر اوسه د سپما هیڅ موخه نشته. وټاکئ چې هره میاشت د څه لپاره سپما کوئ.",
        .sparenMonthlyTotal: "سپما / میاشت",
        .sparenAccumulatedTotal: "لا دمخه سپما شوې",
        .sparenPerMonth: "/ میاشت",
        .sparenContributions: "ونډې",
        .sparenSince: "له",
        .sparenOpenEnded: "د موخې مبلغ نشته",
        .sparenGoalsLabel: "موخې",
        .sparenSortBy: "ترتیب",
        .sparenSortStartMonth: "د پیل میاشت",
        .savingsCatCar: "موټر",
        .savingsCatVacation: "رخصتي",
        .savingsCatHome: "استوګنه",
        .savingsCatRetirement: "ستن 3a / تقاعد",
        .savingsCatEmergency: "بیړنی صندوق",
        .savingsCatEducation: "زده‌کړه",
        .savingsCatOther: "نور",
        .savingsCatWedding: "واده",
        .savingsCatFamily: "کورنۍ او ماشومان",
        .savingsCatRenovation: "نوي‌کول او سینگار",
        .savingsCatElectronics: "بریښنایي وسایل",
        .savingsCatTaxes: "د مالیې لپاره ذخیره",
        .savingsCatInvestment: "پانګونه",
        .savingsCatHealth: "روغتیا",
        .savingsCatGift: "ډالۍ",
        .overviewPlannedSavings: "د دې میاشتې سپما",
        .overviewShowCalculation: "محاسبه وښایاست",
        .overviewTrendTitle: "رجحان · ۶ میاشتې",
        .overviewStatusGood: "روغ اضافه",
        .overviewStatusTight: "تنگ",
        .overviewStatusNegative: "په تاوان کې",
        .overviewAllocationOf: "د خالص عاید له",
        .formStartDate: "سپما له",
        .formStartingBalance: "پیل بیلانس (اختیاري)",
        .insightsSubtitle: "ستاسو د بودیجې لپاره لارښوونه – ستاسو پیسې چیرته دي او چیرته سپما کولای شئ.",
        .insightOverspending: "تاسو له ګټې زیات لګښت کوئ",
        .insightTightBudget: "دا میاشت لږ ځای شته",
        .insightHealthySurplus: "روغ اضافه",
        .insightHighFixed: "لوړ ثابت لګښتونه",
        .insightHighHousing: "لوړ د استوګنې لګښتونه",
        .insightLargestFixed: "په ثابتو لګښتونو کې ترټولو لویه برخه",
        .insightLargestVariable: "ترټولو لویه متغیره بودیجه",
        .insightOverdue: "ناوخته بلونه",
        .insightNoSavings: "تر اوسه سپما پلان شوې نه ده",
        .insightGoodSavings: "ښه د سپما کچه",
        .insightAllHealthy: "ستاسو بودیجه روغه ښکاري",
        .insightHousingHint: "لارښوونه: د عاید تر ټولو ډیر یو پر دریمه برخه",
        .insightNoSavingsDetail: "تاسو ځای لرئ – د سپما موخه مرسته کولای شي.",
        .insightAllHealthyDetail: "هیڅ شی نه ځلیږي. د دقیقې شننې لپاره نور معلومات ورزیات کړئ.",
        .fragOfNetIncome: "د خالص عاید له",
        .fragOfFixedCosts: "د ثابتو لګښتونو له",
        .fragShortfall: "کمښت",

        .commonAdd: "ورزیات کړئ",
        .commonEdit: "سمون",
        .commonDelete: "ړنګول",
        .commonCancel: "لغوه",
        .commandsAdd: "ننوتنه ورزیاته کړئ",
        .billsAddCta: "خپل لومړی بل ورزیات کړئ",
        .sparenAddCta: "د سپما موخه جوړه کړئ",
        .overviewAddCta: "عاید ورزیات کړئ",
        .commonSave: "خوندي کړئ",
        .commonSaved: "خوندي شو",
        .commonClose: "بند کړئ",
        .commonDone: "بشپړ شو",
        .commonShowSampleData: "نمونه معلومات وښایاست",
        .commonHideSampleData: "نمونه معلومات پټ کړئ",
        .commonEmptyHint: "تر اوسه هیڅ معلومات نه دي ننوتل شوي.",
        .commonCopy: "کاپي",
        .commonOptions: "اختیارونه",
        .commonMoveUp: "پورته کول",
        .commonMoveDown: "ښکته کول",
        .monthToday: "نن",

        .formName: "نوم",
        .formAmount: "مبلغ (CHF)",
        .formStatus: "حالت",
        .formNotes: "یادونه",
        .formInvalidAmount: "یو سم مبلغ ولیکئ.",
        .formThirteenthAmount: "۱۳مه میاشتنۍ معاش (مبلغ)",
        .formThirteenthModel: "د ۱۳مې معاش ماډل",
        .thirteenthModelSeparate: "جلا وښایاست",
        .thirteenthModelAveraged: "په ۱۲ میاشتو ووېشئ",
        .formTarget: "د سپما موخه (مبلغ)",
        .formSaved: "لا دمخه سپما شوې",
        .formMonthlyContribution: "میاشتنۍ ونډه",
        .formCategory: "کټګوري",
        .formLimitedDuration: "د محدودې مودې دایمي امر",
        .formLimitedDurationHint: "د بیلګې په توګه ۶ د مالیې قسطونه – یوازې په هغو میاشتو کې شمیرل کیږي او بیا په اتومات ډول لرې کیږي.",
        .formStartMonth: "لومړی قسط",
        .formInstallments: "د قسطونو شمیر",
        .planningStandingOrder: "دایمي امر",
        .catRent: "کرایه",
        .catSubscription: "ګډون",
        .catLeasing: "لیزنگ",
        .catUtilities: "خدمتونه (اوبه، بریښنا)",
        .catTelecom: "مخابرات",
        .catGroceries: "خوراکي توکي",
        .catFuel: "تیل",
        .catTransport: "ترانسپورت",
        .catPersonal: "شخصي",
        .catDining: "بهر خوراک",
        .catHousehold: "کورنۍ",

        .overviewTitle: "لنډه کتنه",
        .overviewAvailableThisMonth: "دا میاشت شته",
        .overviewNetIncome: "دا میاشت خالص عاید",
        .overviewThirteenthSeparate: "۱۳مه میاشتنۍ معاش (جلا)",
        .overviewRecurringFixed: "ثابت لګښتونه",
        .overviewPlannedVariable: "متغیر لګښتونه",
        .overviewBillsDueThisMonth: "د دې میاشتې پرانیستي بلونه",
        .overviewOverdueBills: "ناوخته بلونه",
        .overviewSavingsTarget: "د سپما موخه",
        .overviewSecurityStatus: "د خوندیتوب حالت",
        .overviewFormulaExplainer: "شته = خالص عاید − ثابت لګښتونه − متغیره بودیجه − د دې میاشتې پرانیستي بلونه − ناوخته بلونه. تادیه شوي او راتلونکي بلونه مبلغ نه کموي.",
        .overviewEmpty: "خپله کتنه لیدلو لپاره په میاشتني پلان کې عاید او لګښتونه ولیکئ.",
        .chartSpendingTitle: "د دې میاشتې ویش",
        .chartByCategory: "د کټګورۍ له مخې",

        .planningTitle: "میاشتنی پلان",
        .planningIncome: "عاید",
        .planningFixed: "ثابت لګښتونه",
        .planningVariable: "متغیر لګښتونه",
        .planningSavings: "د سپما موخه",
        .planningFixedExplainer: "ثابت لګښتونه هره میاشت تکراریږي: کرایه، بیمې، ګډونونه، لیزنگ.",
        .planningVariableExplainer: "متغیره بودیجه تاسو پخپله پلان کوئ: خوراکي توکي، تیل، شخصي لګښتونه.",
        .planningOneOffHint: "یو ځلي بلونه په „بلونه” کې اداره کیږي.",
        .planningEmpty: "د خپل عاید سره پیل وکړئ، بیا ثابت لګښتونه او بودیجه ورزیاته کړئ.",
        .planningBalance: "پلان شوی بیلانس",

        .billsTitle: "بلونه",
        .billsStatusOpen: "پرانیستی",
        .billsStatusPaid: "تادیه شوی",
        .billsStateOverdue: "ناوخته",
        .billsStateDueThisMonth: "دا میاشت د تادیې وړ",
        .billsStateFuture: "راتلونکی",
        .billsAffectsBalance: "شته مبلغ کموي",
        .billsNoBalanceImpact: "دا میاشت هیڅ اغیز نلري",
        .billsDueDate: "د تادیې نیټه",
        .billsProvider: "چمتو کوونکی",
        .billsEmpty: "تر اوسه هیڅ بل نشته. د تادیې نیټې سره یو ځلي بلونه دلته ښکاري.",
        .billsMarkPaid: "د تادیه شوي په توګه نښه کړئ",
        .billsMarkOpen: "د پرانیستي په توګه نښه کړئ",
        .billsOpenTotal: "ټول پرانیستي",

        .navSchulden: "پورونه",
        .schuldenSubtitle: "ناوخته بلونه او اجباري راټولونه وڅارئ.",
        .schuldenEmpty: "هیڅ پور نه دی ثبت شوی. ناوخته بلونه دلته په اتومات ډول ښکاري – او تاسو اجباري راټولونه (Betreibung) یا د زیان سندونه ثبتولای شئ.",
        .schuldenAddCta: "یو پور ثبت کړئ",
        .schuldenTotal: "ټول پور",
        .schuldenOverdueBills: "ناوخته بلونه",
        .schuldenRecorded: "ثبت شوي پورونه",
        .schuldenManagedInBills: "ناوخته بلونه په „بلونه” کې اداره کړئ.",
        .debtTypeOpenClaim: "پرانیستی ادعا",
        .debtTypeBetreibung: "اجباري راټولونه",
        .debtTypePfaendung: "د معاش/شتمنۍ ضبط",
        .debtTypeVerlustschein: "د زیان سند",
        .debtTypeOther: "بل پور",
        .debtCreditor: "پوروړی",
        .debtReference: "حواله / د دوسیې شمیره",
        .debtDate: "نیټه",
        .debtType: "ډول",
        .schuldenGuidanceTitle: "له پور څخه د وتلو لار",
        .schuldenTipContactTitle: "وختي اړیکه ونیسئ",
        .schuldenTipContactBody: "له پوروړو سره وختي خبرې وکړئ. لیکلی د قسطونو پلان ډیری وخت ممکن وي او رسمي بهیر مخنیوی کوي.",
        .schuldenTipBetreibungTitle: "که راټولونه پیل شي",
        .schuldenTipBetreibungBody: "د تادیې له امر وروسته تاسو د تادیې لپاره ۲۰ ورځې لرئ – یا که ادعا ناسمه وي د اعتراض (Rechtsvorschlag) لپاره ۱۰ ورځې.",
        .schuldenTipExistenzminimumTitle: "ستاسو لږ تر لږه د ژوند لګښت خوندي دی",
        .schuldenTipExistenzminimumBody: "د ضبط پر مهال ستاسو لږ تر لږه د ژوند لګښت نه لاسوهل کیږي – بنسټیز مبلغ، کرایه، روغتیایي بیمه او ټولنیزې ونډې.",
        .schuldenTipVerlustscheinTitle: "د زیان سند",
        .schuldenTipVerlustscheinBody: "د زیان سند یوازې له ۲۰ کلونو وروسته منسوخیږي. یوازې هغه وخت بیا تعقیب کیدای شئ کله چې نوې شتمني ترلاسه کړئ.",
        .schuldenTipCounselingTitle: "وړیا د پور مشوره",
        .schuldenTipCounselingBody: "Schuldenberatung Schweiz، Caritas او د بودیجې مشوره وړیا او محرمانه مرسته کوي. لومړی هغه پورونه ورکړئ چې ترټولو سخت پایلې لري.",
        .schuldenDisclaimer: "عمومي معلومات، حقوقي مشوره نه ده.",

        .catInsurance: "بیمه",
        .catOther: "نور",
        .catMortgage: "د کور پور",
        .catHealthInsurance: "روغتیایي بیمه",
        .catSerafe: "راډیو/تلویزیون (Serafe)",
        .catPublicTransport: "د سفر کارت",
        .catChildcare: "د ماشومانو پاملرنه",
        .catMembership: "د غړیتوب فیس",
        .catAlimony: "نفقه",
        .catTaxes: "مالیات",
        .catClothing: "جامې",
        .catHealth: "روغتیا",
        .catLeisure: "فراغت او مشغولتیاوې",
        .catEntertainment: "تفریح",
        .catChildren: "ماشومان",
        .catPets: "کورني څاروي",
        .catGifts: "ډالۍ",
        .catTravel: "سفر",
        .catCharity: "بسپنې",
        .catEducation: "زده‌کړه",

        .settingsTitle: "امستنې",
        .settingsLanguage: "ژبه",
        .settingsTheme: "د رنګ موضوع",
        .themeSwissRed: "سویسي سور",
        .themeOrange: "نارنجي",
        .themeSand: "شګلن",
        .themeGreen: "شین",
        .themeTeal: "شین-آبي",
        .themeBlue: "آبي",
        .themePurple: "ارغواني",
        .themePink: "ګلابي",
        .settingsData: "معلومات",
        .settingsHousehold: "کورنۍ",
        .settingsCanton: "کانتون",
        .settingsProfile: "پروفایل",
        .profileName: "نوم",
        .profileChoosePicture: "د پروفایل انځور وټاکئ",
        .profileNoPicture: "هیڅ انځور نشته",
        .profileLocalNote: "یوازې پدې وسیله کې محلي ډول خوندي کیږي.",
        .settingsSecurity: "خوندیتوب",
        .settingsAutoLock: "اتومات کلپ",
        .settingsBiometric: "بايومتريک خلاصول",
        .settingsChangePassphrase: "پټنوم/PIN بدل کړئ",
        .settingsBackup: "کوډ شوی بیک اپ",
        .settingsRestore: "بیا راوستل",
        .settingsPrivacy: "محرمیت",
        .settingsDangerZone: "خطرناکه سیمه",
        .settingsDeleteAll: "ټول محلي معلومات ړنګ کړئ",
        .backupCreateTitle: "کوډ شوی بیک اپ جوړ کړئ",
        .backupPassphrase: "د بیک اپ پټنوم",
        .backupHint: "د بیک اپ لپاره جلا پټنوم وټاکئ. د بیا راوستلو لپاره اړین دی – پټنوم بیرته ترلاسه کیدای نشي.",
        .restorePreview: "مخکتنه",
        .restoreConfirm: "ټول محلي معلومات بدل کړئ",
        .restoreWarning: "دا ټول محلي معلومات د تل لپاره بدلوي.",
        .backupInvalid: "ناسم بیک اپ یا ناسم پټنوم.",
        .backupSavedHint: "د بیک اپ دوتنه او پټنوم په خوندي ځای کې وساتئ.",

        .reportTitle: "ستونزه راپور کړئ",
        .reportSummary: "لنډیز",
        .reportExpected: "تمه شوې چلند",
        .reportActual: "اصلي چلند",
        .reportSteps: "د بیا تکرار ګامونه",
        .reportArea: "اغیزمنه سیمه",
        .reportRedactionNote: "حساس معلومات محلي ډول لرې کیږي. تاسو د کاپي کولو دمخه راپور بیاکتنه کوئ.",
        .reportCopyHint: "راپور په اتومات ډول نه لیږل کیږي. تاسو پخپله یې کاپي کوئ.",

        .exportReport: "راپور صادر کړئ",
        .pdfTitle: "مالي کتنه",
        .pdfSubtitle: "شخصي کورنۍ راپور",
        .pdfSummary: "په یوه کتنه",
        .pdfGeneratedOn: "جوړ شو په",
        .pdfConfidential: "محرم",
        .pdfPage: "مخ",
        .pdfTotal: "ټول",
        .pdfColProgress: "پرمختګ",
        .pdfUnencryptedNote: "راپور یو لوستلو وړ، ناکوډ شوی PDF دی. په خوندي ځای کې یې وساتئ.",
        .pdfNoData: "تر اوسه د صادرولو لپاره هیڅ معلومات نشته.",
        .pdfDefaultHousehold: "زما کورنۍ",

        .lockTitle: "تړل شوی",
        .lockWelcomeSetup: "Kontiva ته ښه راغلاست",
        .lockWelcomeBack: "بیرته ښه راغلاست",
        .lockSetupTitle: "پټنوم وټاکئ",
        .lockEnterPassphrase: "پټنوم یا PIN ولیکئ",
        .lockWrongPassphrase: "ناسم پټنوم. بیا هڅه وکړئ.",
        .lockRecoveryWarning: "هیڅ بیا راوستل نشته. ستاسو د پټنوم پرته ستاسو معلوماتو ته لاسرسی نشته.",
        .lockRecoveryAcknowledge: "زه پوهیږم چې هیڅ بیا راوستل نشته.",
        .securityNote: "ستاسو معلومات محلي ډول او کوډ شوي خوندي کیږي (AES-256-GCM). هیڅ کلاوډ نشته، هیڅ سرور نشته، د پټنوم بیا راوستل نشته.",

        .onboardingIntroBody: "Kontiva تاسو سره مرسته کوي چې د خپلې سویس کورنۍ بودیجه ته ارامه کتنه وکړئ – بشپړ دې وسیلې کې.",
        .onboardingStart: "پیل وکړئ",
        .onboardingProfileTitle: "یو پروفایل جوړ کړئ",
        .onboardingProfileBody: "ځان ته یو نوم ورکړئ او یو انځور وټاکئ. دواړه یوازې پدې وسیله کې پاتې کیږي.",
        .onboardingSkip: "تیر شئ",
        .onboardingFeaturePrivate: "بشپړ محلي – هیڅ کلاوډ نشته، هیڅ څارنه نشته",
        .onboardingFeatureSecure: "د AES-256 سره کوډ شوی",
        .onboardingFeatureMoney: "تر سانتیم پورې دقیق، د ګردولو تېروتنې پرته",
        .onboardingConfirmPassphrase: "پټنوم تایید کړئ",
        .onboardingPassphraseNote: "خپل پټنوم په خوندي ځای کې ولیکئ – بیا تنظیمیدای نشي.",
        .backupNudgeText: "یو کوډ شوی بیک اپ جوړ کړئ. د هغې پرته، که پټنوم هیر کړئ خپل معلومات له لاسه ورکوئ.",
        .commonNext: "بل",
        .navMore: "نور",
        .actionLock: "بندول",
        .pinSetTitle: "کوډ وټاکئ",
        .pinConfirmTitle: "کوډ تایید کړئ",
        .pinRequirementNote: "لږ تر لږه ۶ عددونه · بیا راوستل نشته",
        .pinMismatch: "کوډونه سره سمون نه خوري",
    ]
}
