import Foundation

extension Localization {
    static let sv: [L10nKey: String] = [
        .appName: "Kontiva",
        .appTagline: "En lugn, privat överblick över din schweiziska budget.",
        .notBetaNotice: "Tidig utvecklingsversion – inte beta, inte V1.",

        .navOverview: "Översikt",
        .navPlanning: "Månadsplanering",
        .navBills: "Räkningar",
        .navSettings: "Inställningar",
        .navReport: "Rapportera ett problem",
        .navInsights: "Insikter",
        .navSparen: "Sparande",
        .sparenSubtitle: "Återkommande sparbidrag – och vad du redan har sparat ihop.",
        .sparenEmpty: "Inga sparmål ännu. Bestäm vad du sparar till varje månad.",
        .sparenMonthlyTotal: "Sparande / månad",
        .sparenAccumulatedTotal: "Redan sparat",
        .sparenPerMonth: "/ månad",
        .sparenContributions: "bidrag",
        .sparenSince: "sedan",
        .sparenOpenEnded: "Inget målbelopp",
        .sparenGoalsLabel: "Mål",
        .sparenSortBy: "Sortera",
        .sparenSortStartMonth: "Startmånad",
        .savingsCatCar: "Bil",
        .savingsCatVacation: "Semester",
        .savingsCatHome: "Bostad",
        .savingsCatRetirement: "Pelare 3a / Pension",
        .savingsCatEmergency: "Buffert",
        .savingsCatEducation: "Utbildning",
        .savingsCatOther: "Övrigt",
        .savingsCatWedding: "Bröllop",
        .savingsCatFamily: "Familj och barn",
        .savingsCatRenovation: "Renovering och inredning",
        .savingsCatElectronics: "Elektronik",
        .savingsCatTaxes: "Skattereserv",
        .savingsCatInvestment: "Investeringar",
        .savingsCatHealth: "Hälsa",
        .savingsCatGift: "Presenter",
        .overviewPlannedSavings: "Sparande denna månad",
        .overviewShowCalculation: "Visa beräkning",
        .overviewTrendTitle: "Trend · 6 månader",
        .overviewStatusGood: "Sunt överskott",
        .overviewStatusTight: "Snävt",
        .overviewStatusNegative: "På minus",
        .overviewAllocationOf: "av nettoinkomsten",
        .formStartDate: "Sparar sedan",
        .formStartingBalance: "Ingående saldo (valfritt)",
        .insightsSubtitle: "Vägledning om din budget – var dina pengar finns och var du kan spara.",
        .insightOverspending: "Du spenderar mer än du tjänar",
        .insightTightBudget: "Lite utrymme denna månad",
        .insightHealthySurplus: "Sunt överskott",
        .insightHighFixed: "Höga fasta kostnader",
        .insightHighHousing: "Höga boendekostnader",
        .insightLargestFixed: "Största fasta kostnadsposten",
        .insightLargestVariable: "Största rörliga budgeten",
        .insightOverdue: "Förfallna räkningar",
        .insightNoSavings: "Inget sparande planerat ännu",
        .insightGoodSavings: "Bra sparkvot",
        .insightAllHealthy: "Din budget ser sund ut",
        .insightHousingHint: "Riktlinje: högst en tredjedel av inkomsten",
        .insightNoSavingsDetail: "Du har utrymme – ett sparmål kan hjälpa.",
        .insightAllHealthyDetail: "Inget sticker ut. Lägg till mer data för skarpare insikter.",
        .fragOfNetIncome: "av nettoinkomsten",
        .fragOfFixedCosts: "av de fasta kostnaderna",
        .fragShortfall: "Underskott",

        .commonAdd: "Lägg till",
        .commonEdit: "Redigera",
        .commonDelete: "Radera",
        .commonCancel: "Avbryt",
        .commandsAdd: "Lägg till post",
        .billsAddCta: "Lägg till din första räkning",
        .sparenAddCta: "Skapa ett sparmål",
        .overviewAddCta: "Lägg till inkomst",
        .commonSave: "Spara",
        .commonSaved: "Sparat",
        .commonClose: "Stäng",
        .commonDone: "Klar",
        .commonShowSampleData: "Visa exempeldata",
        .commonHideSampleData: "Dölj exempeldata",
        .commonEmptyHint: "Inga data inmatade ännu.",
        .commonCopy: "Kopiera",
        .commonOptions: "Alternativ",
        .commonMoveUp: "Flytta upp",
        .commonMoveDown: "Flytta ner",
        .monthToday: "Idag",

        .formName: "Namn",
        .formAmount: "Belopp (CHF)",
        .formStatus: "Status",
        .formNotes: "Anteckning",
        .formInvalidAmount: "Ange ett giltigt belopp.",
        .formThirteenthAmount: "13:e månadslönen (belopp)",
        .formThirteenthModel: "Modell för 13:e månadslönen",
        .thirteenthModelSeparate: "Visa separat",
        .thirteenthModelAveraged: "Fördela över 12 månader",
        .formTarget: "Sparmål (belopp)",
        .formSaved: "Redan sparat",
        .formMonthlyContribution: "Månatligt bidrag",
        .formCategory: "Kategori",
        .formLimitedDuration: "Tidsbegränsad stående överföring",
        .formLimitedDurationHint: "T.ex. 6 skatterater – räknas bara de månaderna och tas sedan bort automatiskt.",
        .formStartMonth: "Första raten",
        .formInstallments: "Antal rater",
        .planningStandingOrder: "Stående överföring",
        .catRent: "Hyra",
        .catSubscription: "Prenumeration",
        .catLeasing: "Leasing",
        .catUtilities: "El och vatten",
        .catTelecom: "Telekom",
        .catGroceries: "Mat och dryck",
        .catFuel: "Bränsle",
        .catTransport: "Transport",
        .catPersonal: "Personligt",
        .catDining: "Äta ute",
        .catHousehold: "Hushåll",

        .overviewTitle: "Översikt",
        .overviewAvailableThisMonth: "Tillgängligt denna månad",
        .overviewNetIncome: "Nettoinkomst denna månad",
        .overviewThirteenthSeparate: "13:e månadslönen (visad separat)",
        .overviewRecurringFixed: "Fasta kostnader",
        .overviewPlannedVariable: "Rörliga utgifter",
        .overviewBillsDueThisMonth: "Räkningar denna månad",
        .overviewOverdueBills: "Förfallna räkningar",
        .overviewSavingsTarget: "Sparmål",
        .overviewSecurityStatus: "Säkerhetsstatus",
        .overviewFormulaExplainer: "Tillgängligt = nettoinkomst − fasta kostnader − rörliga budgetar − öppna räkningar denna månad − förfallna räkningar. Betalda och framtida räkningar minskar inte beloppet.",
        .overviewEmpty: "Ange inkomst och kostnader i Månadsplanering för att se din översikt.",
        .chartSpendingTitle: "Fördelning denna månad",
        .chartByCategory: "Per kategori",

        .planningTitle: "Månadsplanering",
        .planningIncome: "Inkomst",
        .planningFixed: "Fasta kostnader",
        .planningVariable: "Rörliga utgifter",
        .planningSavings: "Sparmål",
        .planningFixedExplainer: "Fasta kostnader återkommer varje månad: hyra, försäkringar, prenumerationer, leasing.",
        .planningVariableExplainer: "Rörliga budgetar planerar du själv: mat, bränsle, personliga utgifter.",
        .planningOneOffHint: "Engångsräkningar hanteras under ”Räkningar”.",
        .planningEmpty: "Börja med din inkomst och lägg sedan till fasta kostnader och budgetar.",
        .planningBalance: "Planerat saldo",

        .billsTitle: "Räkningar",
        .billsStatusOpen: "Öppen",
        .billsStatusPaid: "Betald",
        .billsStateOverdue: "Förfallen",
        .billsStateDueThisMonth: "Förfaller denna månad",
        .billsStateFuture: "Framtida",
        .billsAffectsBalance: "Minskar tillgängligt belopp",
        .billsNoBalanceImpact: "Ingen effekt denna månad",
        .billsDueDate: "Förfallodatum",
        .billsProvider: "Leverantör",
        .billsEmpty: "Inga räkningar ännu. Engångsräkningar med förfallodatum visas här.",
        .billsMarkPaid: "Markera som betald",
        .billsMarkOpen: "Markera som öppen",
        .billsOpenTotal: "Öppet totalt",

        .navSchulden: "Skulder",
        .schuldenSubtitle: "Håll koll på förfallna räkningar och indrivning.",
        .schuldenEmpty: "Inga skulder registrerade. Förfallna räkningar visas här automatiskt – och du kan notera indrivning (Betreibung) eller förlustbevis.",
        .schuldenAddCta: "Registrera en skuld",
        .schuldenTotal: "Total skuld",
        .schuldenOverdueBills: "Förfallna räkningar",
        .schuldenRecorded: "Registrerade skulder",
        .schuldenManagedInBills: "Hantera förfallna räkningar under ”Räkningar”.",
        .debtTypeOpenClaim: "Öppet krav",
        .debtTypeBetreibung: "Indrivning",
        .debtTypePfaendung: "Löne-/egendomsutmätning",
        .debtTypeVerlustschein: "Förlustbevis",
        .debtTypeOther: "Annan skuld",
        .debtCreditor: "Borgenär",
        .debtReference: "Referens / ärendenr.",
        .debtDate: "Datum",
        .debtType: "Typ",
        .schuldenGuidanceTitle: "Hitta vägen ut ur skulderna",
        .schuldenTipContactTitle: "Ta kontakt tidigt",
        .schuldenTipContactBody: "Prata med borgenärerna tidigt. En skriftlig avbetalningsplan är ofta möjlig och undviker formell indrivning.",
        .schuldenTipBetreibungTitle: "Om indrivningen börjar",
        .schuldenTipBetreibungBody: "Efter betalningsföreläggandet har du 20 dagar på dig att betala – eller 10 dagar att göra invändning (Rechtsvorschlag) om kravet är obefogat.",
        .schuldenTipExistenzminimumTitle: "Ditt existensminimum är skyddat",
        .schuldenTipExistenzminimumBody: "Vid utmätning förblir ditt existensminimum orört – grundbelopp, hyra, sjukförsäkring och sociala avgifter.",
        .schuldenTipVerlustscheinTitle: "Förlustbevis",
        .schuldenTipVerlustscheinBody: "Ett förlustbevis preskriberas först efter 20 år. Du kan bara förföljas igen när du får nya tillgångar.",
        .schuldenTipCounselingTitle: "Gratis skuldrådgivning",
        .schuldenTipCounselingBody: "Schuldenberatung Schweiz, Caritas och budgetrådgivning hjälper gratis och konfidentiellt. Betala först av de skulder som har värst konsekvenser.",
        .schuldenDisclaimer: "Allmän information, inte juridisk rådgivning.",

        .catInsurance: "Försäkring",
        .catOther: "Övrigt",
        .catMortgage: "Bolån",
        .catHealthInsurance: "Sjukförsäkring",
        .catSerafe: "Radio/TV (Serafe)",
        .catPublicTransport: "Resekort",
        .catChildcare: "Barnomsorg",
        .catMembership: "Medlemskap",
        .catAlimony: "Underhåll och bidrag",
        .catTaxes: "Skatter",
        .catClothing: "Kläder",
        .catHealth: "Hälsa",
        .catLeisure: "Fritid och hobbyer",
        .catEntertainment: "Underhållning",
        .catChildren: "Barn",
        .catPets: "Husdjur",
        .catGifts: "Presenter",
        .catTravel: "Resor",
        .catCharity: "Välgörenhet",
        .catEducation: "Utbildning",

        .settingsTitle: "Inställningar",
        .settingsLanguage: "Språk",
        .settingsTheme: "Färgtema",
        .themeSwissRed: "Schweizisk röd",
        .themeOrange: "Orange",
        .themeSand: "Sand",
        .themeGreen: "Grön",
        .themeTeal: "Blågrön",
        .themeBlue: "Blå",
        .themePurple: "Lila",
        .themePink: "Rosa",
        .settingsData: "Data",
        .settingsHousehold: "Hushåll",
        .settingsCanton: "Kanton",
        .settingsProfile: "Profil",
        .profileName: "Namn",
        .profileChoosePicture: "Välj profilbild",
        .profileNoPicture: "Ingen bild",
        .profileLocalNote: "Lagras endast lokalt på den här enheten.",
        .settingsSecurity: "Säkerhet",
        .settingsAutoLock: "Automatiskt lås",
        .settingsBiometric: "Biometrisk upplåsning",
        .settingsChangePassphrase: "Ändra lösenord/PIN",
        .settingsBackup: "Krypterad säkerhetskopia",
        .settingsRestore: "Återställ",
        .settingsPrivacy: "Integritet",
        .settingsDangerZone: "Farozon",
        .settingsDeleteAll: "Radera alla lokala data",
        .backupCreateTitle: "Skapa krypterad säkerhetskopia",
        .backupPassphrase: "Lösenord för säkerhetskopia",
        .backupHint: "Välj ett separat lösenord för säkerhetskopian. Det krävs för att återställa – lösenordet kan inte återställas.",
        .restorePreview: "Förhandsvisning",
        .restoreConfirm: "Ersätt alla lokala data",
        .restoreWarning: "Detta skriver över alla lokala data permanent.",
        .backupInvalid: "Ogiltig säkerhetskopia eller fel lösenord.",
        .backupSavedHint: "Förvara säkerhetskopian och lösenordet på en säker plats.",

        .reportTitle: "Rapportera ett problem",
        .reportSummary: "Sammanfattning",
        .reportExpected: "Förväntat beteende",
        .reportActual: "Faktiskt beteende",
        .reportSteps: "Steg för att återskapa",
        .reportArea: "Berört område",
        .reportRedactionNote: "Känsliga uppgifter tas bort lokalt. Du granskar rapporten innan du kopierar den.",
        .reportCopyHint: "Rapporten skickas inte automatiskt. Du kopierar den själv.",

        .exportReport: "Exportera rapport",
        .pdfTitle: "Ekonomisk översikt",
        .pdfSubtitle: "Personlig hushållsrapport",
        .pdfSummary: "I korthet",
        .pdfGeneratedOn: "Genererad",
        .pdfConfidential: "Konfidentiellt",
        .pdfPage: "Sida",
        .pdfTotal: "Totalt",
        .pdfColProgress: "Framsteg",
        .pdfUnencryptedNote: "Rapporten är en läsbar, okrypterad PDF. Förvara den på en säker plats.",
        .pdfNoData: "Inga data att exportera ännu.",
        .pdfDefaultHousehold: "Mitt hushåll",

        .lockTitle: "Låst",
        .lockWelcomeSetup: "Välkommen till Kontiva",
        .lockWelcomeBack: "Välkommen tillbaka",
        .lockSetupTitle: "Ange lösenord",
        .lockEnterPassphrase: "Ange lösenord eller PIN",
        .lockWrongPassphrase: "Fel lösenord. Försök igen.",
        .lockRecoveryWarning: "Det finns ingen återställning. Utan ditt lösenord går dina data inte att komma åt.",
        .lockRecoveryAcknowledge: "Jag förstår att det inte finns någon återställning.",
        .securityNote: "Dina data lagras lokalt och krypterat (AES-256-GCM). Inget moln, ingen server, ingen lösenordsåterställning.",

        .onboardingIntroBody: "Kontiva hjälper dig att behålla en lugn överblick över din schweiziska hushållsbudget – helt på den här enheten.",
        .onboardingStart: "Kom igång",
        .onboardingProfileTitle: "Skapa en profil",
        .onboardingProfileBody: "Ge dig själv ett namn och välj en bild. Båda stannar bara på den här enheten.",
        .onboardingSkip: "Hoppa över",
        .onboardingFeaturePrivate: "Helt lokalt – inget moln, ingen spårning",
        .onboardingFeatureSecure: "Krypterat med AES-256",
        .onboardingFeatureMoney: "Exakt ner till centimen, utan avrundningsfel",
        .onboardingConfirmPassphrase: "Bekräfta lösenord",
        .onboardingPassphraseNote: "Skriv ner ditt lösenord på en säker plats – det kan inte återställas.",
        .backupNudgeText: "Skapa en krypterad säkerhetskopia. Utan den förlorar du dina data om du glömmer lösenordet.",
        .commonNext: "Nästa",
        .navMore: "Mer",
        .actionLock: "Lås",
        .pinSetTitle: "Ange kod",
        .pinConfirmTitle: "Bekräfta kod",
        .pinRequirementNote: "Minst 6 siffror · ingen återställning",
        .pinMismatch: "Koderna stämmer inte överens",
    ]
}
