import Foundation

// Hindi (Devanagari). Flagged for native-speaker review.
extension Localization {
    static let hi: [L10nKey: String] = [
        .appName: "Kontiva",
        .appTagline: "आपके स्विस बजट पर एक शांत, निजी नज़र।",
        .notBetaNotice: "प्रारंभिक विकास संस्करण – बीटा नहीं, V1 नहीं।",

        .navOverview: "अवलोकन",
        .navPlanning: "योजना",
        .navBills: "बिल",
        .navSettings: "सेटिंग्स",
        .navReport: "समस्या की रिपोर्ट करें",
        .navInsights: "विश्लेषण",
        .navSparen: "बचत",
        .sparenSubtitle: "नियमित बचत योगदान – और जो पहले ही जमा हो चुका है।",
        .sparenEmpty: "अभी तक कोई बचत लक्ष्य नहीं। तय करें कि आप हर महीने किसके लिए बचत करते हैं।",
        .sparenMonthlyTotal: "बचत / माह",
        .sparenAccumulatedTotal: "पहले से बचाया गया",
        .sparenPerMonth: "/ माह",
        .sparenContributions: "योगदान",
        .sparenSince: "से",
        .sparenOpenEnded: "कोई लक्ष्य राशि नहीं",
        .sparenGoalsLabel: "लक्ष्य",
        .sparenSortBy: "क्रमबद्ध करें",
        .sparenSortStartMonth: "आरंभ माह",
        .savingsCatCar: "कार",
        .savingsCatVacation: "छुट्टी",
        .savingsCatHome: "आवास",
        .savingsCatRetirement: "स्तंभ 3a / पेंशन",
        .savingsCatEmergency: "आपातकालीन कोष",
        .savingsCatEducation: "शिक्षा",
        .savingsCatOther: "अन्य",
        .savingsCatWedding: "शादी",
        .savingsCatFamily: "परिवार और बच्चे",
        .savingsCatRenovation: "नवीनीकरण और साज-सज्जा",
        .savingsCatElectronics: "इलेक्ट्रॉनिक्स",
        .savingsCatTaxes: "कर के लिए आरक्षित",
        .savingsCatInvestment: "निवेश",
        .savingsCatHealth: "स्वास्थ्य",
        .savingsCatGift: "उपहार",
        .overviewPlannedSavings: "इस माह की बचत",
        .overviewShowCalculation: "गणना दिखाएँ",
        .overviewTrendTitle: "रुझान · 6 माह",
        .overviewStatusGood: "स्वस्थ अधिशेष",
        .overviewStatusTight: "तंग",
        .overviewStatusNegative: "घाटे में",
        .overviewAllocationOf: "शुद्ध आय का",
        .formStartDate: "बचत आरंभ",
        .formStartingBalance: "आरंभिक शेष (वैकल्पिक)",
        .insightsSubtitle: "आपके बजट के लिए मार्गदर्शन – आपका पैसा कहाँ है और कहाँ बचत कर सकते हैं।",
        .insightOverspending: "आप कमाई से अधिक खर्च कर रहे हैं",
        .insightTightBudget: "इस माह कम गुंजाइश",
        .insightHealthySurplus: "स्वस्थ अधिशेष",
        .insightHighFixed: "उच्च स्थिर लागत",
        .insightHighHousing: "उच्च आवास लागत",
        .insightLargestFixed: "स्थिर लागत में सबसे बड़ा मद",
        .insightLargestVariable: "सबसे बड़ा परिवर्तनीय बजट",
        .insightOverdue: "अतिदेय बिल",
        .insightNoSavings: "अभी तक कोई बचत नियोजित नहीं",
        .insightGoodSavings: "अच्छी बचत दर",
        .insightAllHealthy: "आपका बजट स्वस्थ दिखता है",
        .insightHousingHint: "मार्गदर्शन: आय का अधिकतम एक-तिहाई",
        .insightNoSavingsDetail: "आपके पास गुंजाइश है – एक बचत लक्ष्य मदद कर सकता है।",
        .insightAllHealthyDetail: "कुछ भी विशेष नहीं उभरता। अधिक सटीक विश्लेषण के लिए और डेटा जोड़ें।",
        .fragOfNetIncome: "शुद्ध आय का",
        .fragOfFixedCosts: "स्थिर लागत का",
        .fragShortfall: "कमी",

        .commonAdd: "जोड़ें",
        .commonEdit: "संपादित करें",
        .commonActivate: "सक्षम करें",
        .commonDelete: "हटाएँ",
        .commonCancel: "रद्द करें",
        .commandsAdd: "प्रविष्टि जोड़ें",
        .billsAddCta: "अपना पहला बिल जोड़ें",
        .sparenAddCta: "एक बचत लक्ष्य बनाएँ",
        .overviewAddCta: "आय जोड़ें",
        .commonSave: "सहेजें",
        .commonSaved: "सहेजा गया",
        .commonClose: "बंद करें",
        .commonDone: "हो गया",
        .commonShowSampleData: "नमूना डेटा दिखाएँ",
        .commonHideSampleData: "नमूना डेटा छिपाएँ",
        .commonEmptyHint: "अभी तक कोई डेटा दर्ज नहीं किया गया।",
        .commonCopy: "कॉपी करें",
        .commonOptions: "विकल्प",
        .commonMoveUp: "ऊपर ले जाएँ",
        .commonMoveDown: "नीचे ले जाएँ",
        .monthToday: "आज",

        .formName: "नाम",
        .formAmount: "राशि (CHF)",
        .formStatus: "स्थिति",
        .formNotes: "टिप्पणी",
        .formInvalidAmount: "एक मान्य राशि दर्ज करें।",
        .formThirteenthAmount: "13वाँ वेतन (राशि)",
        .formThirteenthModel: "13वें वेतन का मॉडल",
        .incomeBonuses: "अतिरिक्त भुगतान",
        .formMonth: "महीना",
        .thirteenthModelSeparate: "अलग दिखाएँ",
        .thirteenthModelAveraged: "12 माह में बाँटें",
        .formTarget: "बचत लक्ष्य (राशि)",
        .formSaved: "पहले से बचाया गया",
        .formMonthlyContribution: "मासिक योगदान",
        .formCategory: "श्रेणी",
        .formLimitedDuration: "सीमित अवधि का स्थायी अनुदेश",
        .formLimitedDurationHint: "जैसे 6 कर किस्तें – केवल उन्हीं महीनों में गिनी जाती हैं और फिर स्वतः हटा दी जाती हैं।",
        .formStartMonth: "पहली किस्त",
        .formInstallments: "किस्तों की संख्या",
        .planningStandingOrder: "स्थायी अनुदेश",
        .catRent: "किराया",
        .catSubscription: "सदस्यता",
        .catLeasing: "लीज़िंग",
        .catUtilities: "उपयोगिताएँ (बिजली, पानी)",
        .catTelecom: "दूरसंचार",
        .catGroceries: "किराना",
        .catFuel: "ईंधन",
        .catTransport: "परिवहन",
        .catPersonal: "व्यक्तिगत",
        .catDining: "बाहर भोजन",
        .catHousehold: "घर-गृहस्थी",

        .overviewTitle: "अवलोकन",
        .overviewAvailableThisMonth: "इस माह उपलब्ध",
        .overviewNetIncome: "इस माह शुद्ध आय",
        .overviewThirteenthSeparate: "13वाँ वेतन (अलग)",
        .overviewRecurringFixed: "स्थिर लागत",
        .overviewPlannedVariable: "परिवर्तनीय व्यय",
        .overviewBillsDueThisMonth: "इस माह के बिल",
        .overviewOverdueBills: "अतिदेय बिल",
        .overviewSavingsTarget: "बचत लक्ष्य",
        .overviewSecurityStatus: "सुरक्षा स्थिति",
        .overviewFormulaExplainer: "उपलब्ध = शुद्ध आय − स्थिर लागत − परिवर्तनीय बजट − इस माह बकाया बिल − अतिदेय बिल। भुगतान किए गए और भावी बिल राशि कम नहीं करते।",
        .overviewEmpty: "अपना अवलोकन देखने के लिए मासिक योजना में आय और व्यय दर्ज करें।",
        .chartSpendingTitle: "इस माह वितरण",
        .chartByCategory: "श्रेणी अनुसार",

        .planningTitle: "मासिक योजना",
        .planningIncome: "आय",
        .planningFixed: "स्थिर लागत",
        .planningVariable: "परिवर्तनीय व्यय",
        .planningSavings: "बचत लक्ष्य",
        .planningFixedExplainer: "स्थिर लागत हर माह दोहराई जाती है: किराया, बीमा, सदस्यता, लीज़िंग।",
        .planningVariableExplainer: "परिवर्तनीय बजट आप स्वयं नियोजित करते हैं: किराना, ईंधन, व्यक्तिगत व्यय।",
        .planningOneOffHint: "एकमुश्त बिल „बिल” में प्रबंधित होते हैं।",
        .planningEmpty: "अपनी आय से शुरू करें, फिर स्थिर लागत और बजट जोड़ें।",
        .planningBalance: "नियोजित शेष",

        .billsTitle: "बिल",
        .billsStatusOpen: "बकाया",
        .billsStatusPaid: "भुगतान किया",
        .billsStateOverdue: "अतिदेय",
        .billsStateDueThisMonth: "इस माह देय",
        .billsStateFuture: "भावी",
        .billsAffectsBalance: "उपलब्ध राशि घटाता है",
        .billsNoBalanceImpact: "इस माह कोई प्रभाव नहीं",
        .billsDueDate: "देय तिथि",
        .billsProvider: "प्रदाता",
        .billsEmpty: "अभी तक कोई बिल नहीं। देय तिथि वाले एकमुश्त बिल यहाँ दिखेंगे।",
        .billsMarkPaid: "भुगतान किया चिह्नित करें",
        .billsMarkOpen: "बकाया चिह्नित करें",
        .billsOpenTotal: "कुल बकाया",

        .navSchulden: "ऋण",
        .schuldenSubtitle: "अतिदेय बिलों और वसूली पर नज़र रखें।",
        .schuldenEmpty: "कोई ऋण दर्ज नहीं। अतिदेय बिल यहाँ स्वतः दिखते हैं – और आप वसूली (Betreibung) या हानि प्रमाणपत्र दर्ज कर सकते हैं।",
        .schuldenAddCta: "एक ऋण दर्ज करें",
        .schuldenTotal: "कुल ऋण",
        .schuldenOverdueBills: "अतिदेय बिल",
        .schuldenRecorded: "दर्ज ऋण",
        .schuldenManagedInBills: "अतिदेय बिल „बिल” में प्रबंधित करें।",
        .debtTypeOpenClaim: "बकाया दावा",
        .debtTypeBetreibung: "वसूली कार्यवाही",
        .debtTypePfaendung: "वेतन/संपत्ति कुर्की",
        .debtTypeVerlustschein: "हानि प्रमाणपत्र",
        .debtTypeOther: "अन्य ऋण",
        .debtCreditor: "लेनदार",
        .debtReference: "संदर्भ / मामला संख्या",
        .debtDate: "तिथि",
        .debtType: "प्रकार",
        .schuldenGuidanceTitle: "ऋण से बाहर निकलने का रास्ता",
        .schuldenTipContactTitle: "जल्दी संपर्क करें",
        .schuldenTipContactBody: "लेनदारों से जल्दी बात करें। लिखित किस्त योजना अक्सर संभव होती है और औपचारिक कार्यवाही से बचाती है।",
        .schuldenTipBetreibungTitle: "यदि वसूली शुरू हो",
        .schuldenTipBetreibungBody: "भुगतान आदेश के बाद आपके पास भुगतान के लिए 20 दिन – या दावा अनुचित होने पर आपत्ति (Rechtsvorschlag) के लिए 10 दिन हैं।",
        .schuldenTipExistenzminimumTitle: "आपका निर्वाह न्यूनतम सुरक्षित है",
        .schuldenTipExistenzminimumBody: "कुर्की में आपका निर्वाह न्यूनतम अछूता रहता है – मूल राशि, किराया, स्वास्थ्य बीमा और सामाजिक अंशदान।",
        .schuldenTipVerlustscheinTitle: "हानि प्रमाणपत्र",
        .schuldenTipVerlustscheinBody: "हानि प्रमाणपत्र 20 वर्ष बाद ही समाप्त होता है। नई संपत्ति प्राप्त करने पर ही आपसे पुनः वसूली हो सकती है।",
        .schuldenTipCounselingTitle: "निःशुल्क ऋण परामर्श",
        .schuldenTipCounselingBody: "Schuldenberatung Schweiz, Caritas और बजट परामर्श निःशुल्क और गोपनीय रूप से सहायता करते हैं। पहले सबसे गंभीर परिणाम वाले ऋण चुकाएँ।",
        .schuldenDisclaimer: "सामान्य जानकारी, कानूनी सलाह नहीं।",

        .catInsurance: "बीमा",
        .catOther: "अन्य",
        .catMortgage: "गृह ऋण",
        .catHealthInsurance: "स्वास्थ्य बीमा",
        .catSerafe: "रेडियो/टीवी (Serafe)",
        .catPublicTransport: "यात्रा पास",
        .catChildcare: "बाल देखभाल",
        .catMembership: "सदस्यता शुल्क",
        .catAlimony: "गुजारा भत्ता",
        .catTaxes: "कर",
        .catClothing: "वस्त्र",
        .catHealth: "स्वास्थ्य",
        .catLeisure: "अवकाश और शौक",
        .catEntertainment: "मनोरंजन",
        .catChildren: "बच्चे",
        .catPets: "पालतू पशु",
        .catGifts: "उपहार",
        .catTravel: "यात्रा",
        .catCharity: "दान",
        .catEducation: "शिक्षा",

        .settingsTitle: "सेटिंग्स",
        .settingsLanguage: "भाषा",
        .settingsTheme: "रंग थीम",
        .themeSwissRed: "स्विस लाल",
        .themeOrange: "नारंगी",
        .themeSand: "रेत",
        .themeGreen: "हरा",
        .themeTeal: "टील",
        .themeBlue: "नीला",
        .themePurple: "बैंगनी",
        .themePink: "गुलाबी",
        .settingsData: "डेटा",
        .settingsHousehold: "परिवार",
        .settingsCanton: "कैंटन",
        .settingsProfile: "प्रोफ़ाइल",
        .profileName: "नाम",
        .profileChoosePicture: "प्रोफ़ाइल चित्र चुनें",
        .profileNoPicture: "कोई चित्र नहीं",
        .profileLocalNote: "केवल इस डिवाइस पर स्थानीय रूप से सहेजा गया।",
        .settingsSecurity: "सुरक्षा",
        .settingsAutoLock: "स्वतः लॉक",
        .settingsBiometric: "बायोमेट्रिक अनलॉक",
        .settingsChangePassphrase: "पासवर्ड/PIN बदलें",
        .settingsBackup: "एन्क्रिप्टेड बैकअप",
        .settingsRestore: "पुनर्स्थापित करें",
        .settingsPrivacy: "गोपनीयता",
        .settingsDangerZone: "खतरनाक क्षेत्र",
        .settingsDeleteAll: "सभी स्थानीय डेटा हटाएँ",
        .backupCreateTitle: "एन्क्रिप्टेड बैकअप बनाएँ",
        .backupPassphrase: "बैकअप पासवर्ड",
        .backupHint: "बैकअप के लिए एक अलग पासवर्ड चुनें। पुनर्स्थापना के लिए यह आवश्यक है – पासवर्ड पुनर्प्राप्त नहीं हो सकता।",
        .restorePreview: "पूर्वावलोकन",
        .restoreConfirm: "सभी स्थानीय डेटा बदलें",
        .restoreWarning: "यह सभी स्थानीय डेटा को स्थायी रूप से अधिलेखित कर देता है।",
        .backupInvalid: "अमान्य बैकअप या गलत पासवर्ड।",
        .backupSavedHint: "बैकअप फ़ाइल और पासवर्ड सुरक्षित स्थान पर रखें।",

        .reportTitle: "समस्या की रिपोर्ट करें",
        .reportSummary: "सारांश",
        .reportExpected: "अपेक्षित व्यवहार",
        .reportActual: "वास्तविक व्यवहार",
        .reportSteps: "पुनरुत्पादन के चरण",
        .reportArea: "प्रभावित क्षेत्र",
        .reportRedactionNote: "संवेदनशील डेटा स्थानीय रूप से हटा दिया जाता है। आप कॉपी करने से पहले रिपोर्ट की समीक्षा करते हैं।",
        .reportCopyHint: "रिपोर्ट स्वतः नहीं भेजी जाती। आप स्वयं इसे कॉपी करते हैं।",

        .exportReport: "रिपोर्ट निर्यात करें",
        .pdfTitle: "वित्तीय अवलोकन",
        .pdfSubtitle: "व्यक्तिगत परिवार रिपोर्ट",
        .pdfSummary: "एक नज़र में",
        .pdfGeneratedOn: "बनाया गया",
        .pdfConfidential: "गोपनीय",
        .pdfPage: "पृष्ठ",
        .pdfTotal: "कुल",
        .pdfColProgress: "प्रगति",
        .pdfUnencryptedNote: "रिपोर्ट एक पठनीय, गैर-एन्क्रिप्टेड PDF है। इसे सुरक्षित स्थान पर रखें।",
        .pdfNoData: "अभी तक निर्यात के लिए कोई डेटा नहीं।",
        .pdfDefaultHousehold: "मेरा परिवार",

        .lockTitle: "लॉक है",
        .lockWelcomeSetup: "Kontiva में आपका स्वागत है",
        .lockWelcomeBack: "वापसी पर स्वागत है",
        .lockSetupTitle: "पासवर्ड सेट करें",
        .lockEnterPassphrase: "पासवर्ड या PIN दर्ज करें",
        .lockWrongPassphrase: "गलत पासवर्ड। फिर से प्रयास करें।",
        .lockRecoveryWarning: "कोई पुनर्प्राप्ति नहीं। आपके पासवर्ड के बिना आपके डेटा तक नहीं पहुँचा जा सकता।",
        .lockRecoveryAcknowledge: "मैं समझता हूँ कि कोई पुनर्प्राप्ति नहीं है।",
        .securityNote: "आपका डेटा स्थानीय रूप से और एन्क्रिप्टेड (AES-256-GCM) सहेजा जाता है। कोई क्लाउड नहीं, कोई सर्वर नहीं, कोई पासवर्ड पुनर्प्राप्ति नहीं।",

        .onboardingIntroBody: "Kontiva आपको अपने स्विस परिवार के बजट पर शांत नज़र रखने में मदद करता है – पूरी तरह इस डिवाइस पर।",
        .onboardingStart: "शुरू करें",
        .onboardingProfileTitle: "एक प्रोफ़ाइल बनाएँ",
        .onboardingProfileBody: "अपने आप को एक नाम दें और एक चित्र चुनें। दोनों केवल इस डिवाइस पर रहते हैं।",
        .onboardingSkip: "छोड़ें",
        .onboardingFeaturePrivate: "पूरी तरह स्थानीय – कोई क्लाउड नहीं, कोई ट्रैकिंग नहीं",
        .onboardingFeatureSecure: "AES-256 से एन्क्रिप्टेड",
        .onboardingFeatureMoney: "सेंटीम तक सटीक, कोई पूर्णांकन त्रुटि नहीं",
        .onboardingConfirmPassphrase: "पासवर्ड की पुष्टि करें",
        .onboardingPassphraseNote: "अपना पासवर्ड किसी सुरक्षित स्थान पर लिखें – इसे रीसेट नहीं किया जा सकता।",
        .backupNudgeText: "एक एन्क्रिप्टेड बैकअप बनाएँ। इसके बिना, पासवर्ड भूलने पर आप अपना डेटा खो देंगे।",
        .commonNext: "आगे",
        .navMore: "अधिक",
        .actionLock: "लॉक करें",
        .pinSetTitle: "कोड सेट करें",
        .pinConfirmTitle: "कोड की पुष्टि करें",
        .pinRequirementNote: "न्यूनतम 6 अंक · कोई पुनर्प्राप्ति नहीं",
        .pinMismatch: "कोड मेल नहीं खाते",
    ]
}
