import Foundation

extension Localization {
    static let fi: [L10nKey: String] = [
        .appName: "Kontiva",
        .appTagline: "Rauhallinen, yksityinen näkymä sveitsiläiseen budjettiisi.",
        .notBetaNotice: "Varhainen kehitysversio – ei beta, ei V1.",

        .navOverview: "Yleiskatsaus",
        .navPlanning: "Budjetti",
        .navBills: "Laskut",
        .navSettings: "Asetukset",
        .navReport: "Ilmoita ongelmasta",
        .navInsights: "Havainnot",
        .navSparen: "Säästöt",
        .sparenSubtitle: "Toistuvat säästöerät – ja se, mitä on jo kertynyt.",
        .sparenEmpty: "Ei vielä säästötavoitteita. Päätä, mihin säästät joka kuukausi.",
        .sparenMonthlyTotal: "Säästöt / kk",
        .sparenAccumulatedTotal: "Jo säästetty",
        .sparenPerMonth: "/ kk",
        .sparenContributions: "erää",
        .sparenSince: "alkaen",
        .sparenOpenEnded: "Ei tavoitesummaa",
        .sparenGoalReached: "Tavoite saavutettu",
        .sparenGoalReachedMessage: "Onnittelut! Saavutit säästötavoitteesi. Miten haluat jatkaa?",
        .sparenGoalIncrease: "Nosta tavoitetta",
        .sparenGoalComplete: "Merkitse valmiiksi",
        .sparenGoalKeep: "Jatka säästämistä",
        .sparenGoalCompleted: "Valmis",
        .sparenGoalReopen: "Aktivoi uudelleen",
        .sparenGoalsLabel: "Tavoitteet",
        .sparenSortBy: "Lajittele",
        .sparenSortStartMonth: "Aloituskuukausi",
        .savingsCatCar: "Auto",
        .savingsCatVacation: "Loma",
        .savingsCatHome: "Asunto",
        .savingsCatRetirement: "Pilari 3a / Eläke",
        .savingsCatEmergency: "Hätävara",
        .savingsCatEducation: "Koulutus",
        .savingsCatOther: "Muu",
        .savingsCatWedding: "Häät",
        .savingsCatFamily: "Perhe ja lapset",
        .savingsCatRenovation: "Remontti ja sisustus",
        .savingsCatElectronics: "Elektroniikka",
        .savingsCatTaxes: "Verovaraus",
        .savingsCatInvestment: "Sijoitukset",
        .savingsCatHealth: "Terveys",
        .savingsCatGift: "Lahjat",
        .overviewPlannedSavings: "Säästöt tässä kuussa",
        .overviewShowCalculation: "Näytä laskelma",
        .overviewTrendTitle: "Kehitys · 6 kuukautta",
        .overviewStatusGood: "Terve ylijäämä",
        .overviewStatusTight: "Tiukkaa",
        .overviewStatusNegative: "Miinuksella",
        .overviewAllocationOf: "nettotuloista",
        .formStartDate: "Säästetty alkaen",
        .formStartingBalance: "Alkusaldo (valinnainen)",
        .insightsSubtitle: "Ohjeita budjettiisi – missä rahasi ovat ja mistä voit säästää.",
        .insightOverspending: "Kulutat enemmän kuin tienaat",
        .insightTightBudget: "Vähän liikkumavaraa tässä kuussa",
        .insightHealthySurplus: "Terve ylijäämä",
        .insightHighFixed: "Korkeat kiinteät kulut",
        .insightHighHousing: "Korkeat asumiskulut",
        .insightLargestFixed: "Suurin kiinteä kuluerä",
        .insightLargestVariable: "Suurin muuttuva budjetti",
        .insightOverdue: "Erääntyneet laskut",
        .insightNoSavings: "Säästöjä ei vielä suunniteltu",
        .insightGoodSavings: "Hyvä säästöaste",
        .insightAllHealthy: "Budjettisi näyttää terveeltä",
        .insightHousingHint: "Suositus: enintään kolmasosa tuloista",
        .insightNoSavingsDetail: "Sinulla on liikkumavaraa – säästötavoite voisi auttaa.",
        .insightAllHealthyDetail: "Mikään ei erotu. Lisää tietoja saadaksesi tarkempia havaintoja.",
        .insightExtraIncome: "Lisätuloa tässä kuussa",
        .insightGoalProgress: "Säästötavoite lähellä",
        .insightBillsDueSoon: "Vielä maksettavaa tässä kuussa",
        .insightGettingStarted: "Aloitetaan",
        .insightGettingStartedDetail: "Lisää tulosi nähdäksesi henkilökohtaiset oivallukset.",
        .schuldenEncourageTitle: "Askel kerrallaan",
        .schuldenEncourageBody: "Tartut toimeen. Tässä konkreettiset seuraavat askeleet.",
        .fragOfNetIncome: "nettotuloista",
        .fragOfFixedCosts: "kiinteistä kuluista",
        .fragShortfall: "Vajaus",

        .commonAdd: "Lisää",
        .commonEdit: "Muokkaa",
        .commonActivate: "Ota käyttöön",
        .commonDelete: "Poista",
        .commonCancel: "Peruuta",
        .commandsAdd: "Lisää merkintä",
        .billsAddCta: "Lisää ensimmäinen laskusi",
        .sparenAddCta: "Luo säästötavoite",
        .overviewAddCta: "Lisää tulo",
        .commonSave: "Tallenna",
        .commonSaved: "Tallennettu",
        .commonClose: "Sulje",
        .commonDone: "Valmis",
        .commonShowSampleData: "Näytä esimerkkitiedot",
        .commonHideSampleData: "Piilota esimerkkitiedot",
        .commonEmptyHint: "Tietoja ei ole vielä syötetty.",
        .commonCopy: "Kopioi",
        .commonOptions: "Asetukset",
        .commonMoveUp: "Siirrä ylös",
        .commonMoveDown: "Siirrä alas",
        .monthToday: "Tänään",

        .formName: "Nimi",
        .formAmount: "Summa (CHF)",
        .formStatus: "Tila",
        .formNotes: "Muistiinpano",
        .formInvalidAmount: "Anna kelvollinen summa.",
        .formThirteenthAmount: "13. kuukausipalkka (summa)",
        .formThirteenthModel: "13. kuukausipalkan malli",
        .incomeBonuses: "Lisämaksut",
        .formMonth: "Kuukausi",
        .thirteenthModelSeparate: "Näytä erikseen",
        .thirteenthModelAveraged: "Jaa 12 kuukaudelle",
        .formTarget: "Säästötavoite (summa)",
        .formSaved: "Jo säästetty",
        .formMonthlyContribution: "Kuukausierä",
        .formCategory: "Luokka",
        .formLimitedDuration: "Määräaikainen toistuvaismaksu",
        .formLimitedDurationHint: "Esim. 6 veroerää – lasketaan vain niinä kuukausina ja poistetaan sitten automaattisesti.",
        .formStartMonth: "Ensimmäinen erä",
        .formInstallments: "Erien määrä",
        .planningStandingOrder: "Toistuvaismaksu",
        .catRent: "Vuokra",
        .catSubscription: "Tilaus",
        .catLeasing: "Leasing",
        .catUtilities: "Sähkö ja vesi",
        .catTelecom: "Tietoliikenne",
        .catGroceries: "Ruokaostokset",
        .catFuel: "Polttoaine",
        .catTransport: "Liikenne",
        .catPersonal: "Henkilökohtainen",
        .catDining: "Ulkona syöminen",
        .catHousehold: "Kotitalous",

        .overviewTitle: "Yleiskatsaus",
        .overviewAvailableThisMonth: "Käytettävissä tässä kuussa",
        .overviewNetIncome: "Nettotulo tässä kuussa",
        .overviewThirteenthSeparate: "13. kuukausipalkka (erikseen)",
        .overviewRecurringFixed: "Kiinteät kulut",
        .overviewPlannedVariable: "Muuttuvat menot",
        .overviewBillsDueThisMonth: "Tämän kuun laskut",
        .overviewOverdueBills: "Erääntyneet laskut",
        .overviewSavingsTarget: "Säästötavoite",
        .overviewSecurityStatus: "Suojaustila",
        .overviewFormulaExplainer: "Käytettävissä = nettotulo − kiinteät kulut − muuttuvat budjetit − tässä kuussa avoimet laskut − erääntyneet laskut. Maksetut ja tulevat laskut eivät vähennä summaa.",
        .overviewEmpty: "Syötä tulot ja kulut Kuukausisuunnitteluun nähdäksesi yleiskatsauksen.",
        .chartSpendingTitle: "Jakauma tässä kuussa",
        .chartByCategory: "Luokittain",

        .planningTitle: "Kuukausisuunnittelu",
        .planningIncome: "Tulot",
        .planningFixed: "Kiinteät kulut",
        .planningVariable: "Muuttuvat menot",
        .planningSavings: "Säästötavoite",
        .planningFixedExplainer: "Kiinteät kulut toistuvat joka kuukausi: vuokra, vakuutukset, tilaukset, leasing.",
        .planningVariableExplainer: "Muuttuvat budjetit suunnittelet itse: ruokaostokset, polttoaine, henkilökohtaiset menot.",
        .planningOneOffHint: "Kertaluonteisia laskuja hallitaan kohdassa ”Laskut”.",
        .planningEmpty: "Aloita tuloistasi ja lisää sitten kiinteät kulut ja budjetit.",
        .planningBalance: "Suunniteltu saldo",

        .billsTitle: "Laskut",
        .billsStatusOpen: "Avoin",
        .billsStatusPaid: "Maksettu",
        .billsStateOverdue: "Erääntynyt",
        .billsStateDueThisMonth: "Erääntyy tässä kuussa",
        .billsStateFuture: "Tuleva",
        .billsAffectsBalance: "Vähentää käytettävissä olevaa summaa",
        .billsNoBalanceImpact: "Ei vaikutusta tässä kuussa",
        .billsDueDate: "Eräpäivä",
        .billsProvider: "Toimittaja",
        .billsEmpty: "Ei vielä laskuja. Kertaluonteiset laskut, joilla on eräpäivä, näkyvät tässä.",
        .billsMarkPaid: "Merkitse maksetuksi",
        .billsMarkOpen: "Merkitse avoimeksi",
        .billsOpenTotal: "Avoinna yhteensä",

        .navSchulden: "Velat",
        .schuldenSubtitle: "Pidä silmällä erääntyneitä laskuja ja perintää.",
        .schuldenEmpty: "Ei kirjattuja velkoja. Erääntyneet laskut näkyvät tässä automaattisesti – ja voit merkitä muistiin perinnän (Betreibung) tai tappiotodistukset.",
        .schuldenAddCta: "Kirjaa velka",
        .schuldenTotal: "Velka yhteensä",
        .schuldenOverdueBills: "Erääntyneet laskut",
        .schuldenRecorded: "Kirjatut velat",
        .schuldenManagedInBills: "Hallitse erääntyneitä laskuja kohdassa ”Laskut”.",
        .debtTypeOpenClaim: "Avoin saatava",
        .debtTypeBetreibung: "Perintä",
        .debtTypePfaendung: "Palkan/omaisuuden ulosmittaus",
        .debtTypeVerlustschein: "Tappiotodistus",
        .debtTypeOther: "Muu velka",
        .debtCreditor: "Velkoja",
        .debtReference: "Viite / asianro",
        .debtDate: "Päivämäärä",
        .debtType: "Tyyppi",
        .schuldenGuidanceTitle: "Tie ulos veloista",
        .schuldenTipContactTitle: "Ota yhteyttä ajoissa",
        .schuldenTipContactBody: "Keskustele velkojien kanssa ajoissa. Kirjallinen maksusuunnitelma on usein mahdollinen ja välttää muodollisen perinnän.",
        .schuldenTipBetreibungTitle: "Jos perintä alkaa",
        .schuldenTipBetreibungBody: "Maksumääräyksen jälkeen sinulla on 20 päivää aikaa maksaa – tai 10 päivää tehdä vastalause (Rechtsvorschlag), jos saatava on perusteeton.",
        .schuldenTipExistenzminimumTitle: "Toimeentulominimisi on suojattu",
        .schuldenTipExistenzminimumBody: "Ulosmittauksessa toimeentulominimisi pysyy koskemattomana – perusmäärä, vuokra, sairausvakuutus ja sosiaalimaksut.",
        .schuldenTipVerlustscheinTitle: "Tappiotodistus",
        .schuldenTipVerlustscheinBody: "Tappiotodistus vanhenee vasta 20 vuoden kuluttua. Sinua voidaan periä uudelleen vain, kun saat uutta varallisuutta.",
        .schuldenTipCounselingTitle: "Maksuton velkaneuvonta",
        .schuldenTipCounselingBody: "Schuldenberatung Schweiz, Caritas ja budjettineuvonta auttavat maksutta ja luottamuksellisesti. Maksa ensin pois velat, joilla on pahimmat seuraukset.",
        .schuldenDisclaimer: "Yleistä tietoa, ei oikeudellista neuvontaa.",
        .schuldenAsFixed: "Kiinteänä kuluna",
        .schuldenAsBill: "Laskuna",
        .schuldenAsVariable: "Muuttuvana budjettina",

        .catInsurance: "Vakuutus",
        .catOther: "Muu",
        .catMortgage: "Asuntolaina",
        .catHealthInsurance: "Sairausvakuutus",
        .catSerafe: "Radio/TV (Serafe)",
        .catPublicTransport: "Matkalippu",
        .catChildcare: "Lastenhoito",
        .catMembership: "Jäsenyydet",
        .catAlimony: "Elatusmaksut",
        .catTaxes: "Verot",
        .catRatenzahlung: "Osamaksu",
        .catStreaming: "Suoratoisto",
        .catCreditCard: "Luottokortti",
        .catClothing: "Vaatteet",
        .catHealth: "Terveys",
        .catLeisure: "Vapaa-aika ja harrastukset",
        .catEntertainment: "Viihde",
        .catChildren: "Lapset",
        .catPets: "Lemmikit",
        .catGifts: "Lahjat",
        .catTravel: "Matkailu",
        .catCharity: "Hyväntekeväisyys",
        .catEducation: "Koulutus",

        .settingsTitle: "Asetukset",
        .settingsLanguage: "Kieli",
        .settingsTheme: "Väriteema",
        .themeCustom: "Oma teema",
        .themeSwissRed: "Sveitsinpunainen",
        .themeOrange: "Oranssi",
        .themeSand: "Hiekka",
        .themeGreen: "Vihreä",
        .themeTeal: "Sinivihreä",
        .themeBlue: "Sininen",
        .themePurple: "Violetti",
        .themePink: "Pinkki",
        .settingsData: "Tiedot",
        .settingsHousehold: "Kotitalous",
        .settingsCanton: "Kantoni",
        .settingsProfile: "Profiili",
        .profileName: "Nimi",
        .profileChoosePicture: "Valitse profiilikuva",
        .profileNoPicture: "Ei kuvaa",
        .profileLocalNote: "Tallennetaan vain paikallisesti tähän laitteeseen.",
        .settingsSecurity: "Suojaus",
        .settingsAutoLock: "Automaattinen lukitus",
        .settingsBiometric: "Biometrinen avaus",
        .settingsChangePassphrase: "Vaihda salasana/PIN",
        .settingsBackup: "Salattu varmuuskopio",
        .settingsRestore: "Palauta",
        .settingsPrivacy: "Yksityisyys",
        .settingsDangerZone: "Vaaravyöhyke",
        .settingsDeleteAll: "Poista kaikki paikalliset tiedot",
        .backupCreateTitle: "Luo salattu varmuuskopio",
        .backupPassphrase: "Varmuuskopion salasana",
        .backupHint: "Valitse erillinen salasana varmuuskopiolle. Sitä tarvitaan palautukseen – salasanaa ei voi palauttaa.",
        .restorePreview: "Esikatselu",
        .restoreConfirm: "Korvaa kaikki paikalliset tiedot",
        .restoreWarning: "Tämä korvaa pysyvästi kaikki paikalliset tiedot.",
        .backupInvalid: "Virheellinen varmuuskopio tai väärä salasana.",
        .backupSavedHint: "Säilytä varmuuskopiotiedosto ja salasana turvallisessa paikassa.",

        .reportTitle: "Ilmoita ongelmasta",
        .reportSummary: "Yhteenveto",
        .reportExpected: "Odotettu toiminta",
        .reportActual: "Todellinen toiminta",
        .reportSteps: "Toistamisen vaiheet",
        .reportArea: "Koskettu alue",
        .reportRedactionNote: "Arkaluonteiset tiedot poistetaan paikallisesti. Tarkistat raportin ennen kopiointia.",
        .reportCopyHint: "Raporttia ei lähetetä automaattisesti. Kopioit sen itse.",

        .exportReport: "Vie raportti",
        .pdfTitle: "Talouskatsaus",
        .pdfSubtitle: "Henkilökohtainen kotitalousraportti",
        .pdfSummary: "Yhdellä silmäyksellä",
        .pdfGeneratedOn: "Luotu",
        .pdfConfidential: "Luottamuksellinen",
        .pdfPage: "Sivu",
        .pdfTotal: "Yhteensä",
        .pdfColProgress: "Edistyminen",
        .pdfUnencryptedNote: "Raportti on luettava, salaamaton PDF. Säilytä se turvallisessa paikassa.",
        .pdfNoData: "Ei vielä vietäviä tietoja.",
        .pdfDefaultHousehold: "Kotitalouteni",

        .lockTitle: "Lukittu",
        .lockWelcomeSetup: "Tervetuloa Kontivaan",
        .lockWelcomeBack: "Tervetuloa takaisin",
        .lockSetupTitle: "Aseta salasana",
        .lockEnterPassphrase: "Anna salasana tai PIN",
        .lockWrongPassphrase: "Väärä salasana. Yritä uudelleen.",
        .lockRecoveryWarning: "Palautusta ei ole. Ilman salasanaasi tietoihisi ei pääse käsiksi.",
        .lockRecoveryAcknowledge: "Ymmärrän, ettei palautusta ole.",
        .securityNote: "Tietosi tallennetaan paikallisesti ja salattuna (AES-256-GCM). Ei pilveä, ei palvelinta, ei salasanan palautusta.",

        .onboardingIntroBody: "Kontiva auttaa sinua pitämään rauhallisen näkymän sveitsiläisen kotitaloutesi budjettiin – kokonaan tällä laitteella.",
        .onboardingStart: "Aloita",
        .onboardingProfileTitle: "Luo profiili",
        .onboardingProfileBody: "Anna itsellesi nimi ja valitse kuva. Molemmat pysyvät vain tällä laitteella.",
        .onboardingSkip: "Ohita",
        .onboardingFeaturePrivate: "Täysin paikallinen – ei pilveä, ei seurantaa",
        .onboardingFeatureSecure: "Salattu AES-256:lla",
        .onboardingFeatureMoney: "Tarkka senttiin asti, ei pyöristysvirheitä",
        .onboardingConfirmPassphrase: "Vahvista salasana",
        .onboardingPassphraseNote: "Kirjoita salasanasi muistiin turvalliseen paikkaan – sitä ei voi nollata.",
        .backupNudgeText: "Luo salattu varmuuskopio. Ilman sitä menetät tietosi, jos unohdat salasanan.",
        .commonNext: "Seuraava",
        .navMore: "Lisää",
        .actionLock: "Lukitse",
        .pinSetTitle: "Aseta koodi",
        .pinConfirmTitle: "Vahvista koodi",
        .pinRequirementNote: "Väh. 6 numeroa · ei palautusta",
        .pinMismatch: "Koodit eivät täsmää",
    ]
}
