import Foundation

extension Localization {
    static let sr: [L10nKey: String] = [
        .appName: "Kontiva",
        .appTagline: "Smiren, privatan pregled vašeg švajcarskog budžeta.",
        .notBetaNotice: "Rana razvojna verzija – nije beta, nije V1.",

        .navOverview: "Pregled",
        .navPlanning: "Mesečno planiranje",
        .navBills: "Računi",
        .navSettings: "Podešavanja",
        .navReport: "Prijavi problem",
        .navInsights: "Uvidi",
        .navSparen: "Štednja",
        .sparenSubtitle: "Redovni doprinosi štednji – i ono što je već prikupljeno.",
        .sparenEmpty: "Još nema ciljeva štednje. Odredite za šta štedite svakog meseca.",
        .sparenMonthlyTotal: "Štednja / mesec",
        .sparenAccumulatedTotal: "Već ušteđeno",
        .sparenPerMonth: "/ mesec",
        .sparenContributions: "doprinosa",
        .sparenSince: "od",
        .sparenOpenEnded: "Bez ciljnog iznosa",
        .sparenGoalsLabel: "Ciljevi",
        .sparenSortBy: "Сортирај",
        .sparenSortStartMonth: "Почетни месец",
        .savingsCatCar: "Automobil",
        .savingsCatVacation: "Odmor",
        .savingsCatHome: "Stanovanje",
        .savingsCatRetirement: "Stub 3a / Penzija",
        .savingsCatEmergency: "Fond za hitne slučajeve",
        .savingsCatEducation: "Obrazovanje",
        .savingsCatOther: "Ostalo",
        .savingsCatWedding: "Venčanje",
        .savingsCatFamily: "Porodica i deca",
        .savingsCatRenovation: "Renoviranje i opremanje",
        .savingsCatElectronics: "Elektronika",
        .savingsCatTaxes: "Rezerva za poreze",
        .savingsCatInvestment: "Ulaganja",
        .savingsCatHealth: "Zdravlje",
        .savingsCatGift: "Pokloni",
        .overviewPlannedSavings: "Štednja ovog meseca",
        .overviewShowCalculation: "Prikaži izračun",
        .overviewTrendTitle: "Trend · 6 meseci",
        .overviewStatusGood: "Zdrav višak",
        .overviewStatusTight: "Tesno",
        .overviewStatusNegative: "U minusu",
        .overviewAllocationOf: "neto prihoda",
        .formStartDate: "Štedim od",
        .formStartingBalance: "Početno stanje (opciono)",
        .insightsSubtitle: "Smernice za vaš budžet – gde je vaš novac i gde možete uštedeti.",
        .insightOverspending: "Trošite više nego što zarađujete",
        .insightTightBudget: "Malo prostora ovog meseca",
        .insightHealthySurplus: "Zdrav višak",
        .insightHighFixed: "Visoki fiksni troškovi",
        .insightHighHousing: "Visoki troškovi stanovanja",
        .insightLargestFixed: "Najveća stavka fiksnih troškova",
        .insightLargestVariable: "Najveći promenljivi budžet",
        .insightOverdue: "Dospeli računi",
        .insightNoSavings: "Štednja još nije planirana",
        .insightGoodSavings: "Dobra stopa štednje",
        .insightAllHealthy: "Vaš budžet izgleda zdravo",
        .insightHousingHint: "Smernica: najviše trećina prihoda",
        .insightNoSavingsDetail: "Imate prostora – cilj štednje mogao bi pomoći.",
        .insightAllHealthyDetail: "Ništa se ne ističe. Dodajte više podataka za preciznije uvide.",
        .fragOfNetIncome: "neto prihoda",
        .fragOfFixedCosts: "fiksnih troškova",
        .fragShortfall: "Manjak",

        .commonAdd: "Dodaj",
        .commonEdit: "Izmeni",
        .commonDelete: "Obriši",
        .commonCancel: "Otkaži",
        .commandsAdd: "Dodaj unos",
        .billsAddCta: "Dodaj svoj prvi račun",
        .sparenAddCta: "Napravi cilj štednje",
        .overviewAddCta: "Dodaj prihod",
        .commonSave: "Sačuvaj",
        .commonSaved: "Sačuvano",
        .commonClose: "Zatvori",
        .commonDone: "Gotovo",
        .commonShowSampleData: "Prikaži primere podataka",
        .commonHideSampleData: "Sakrij primere podataka",
        .commonEmptyHint: "Još nema unetih podataka.",
        .commonCopy: "Kopiraj",
        .commonOptions: "Opcije",
        .commonMoveUp: "Pomeri gore",
        .commonMoveDown: "Pomeri dole",
        .monthToday: "Danas",

        .formName: "Naziv",
        .formAmount: "Iznos (CHF)",
        .formStatus: "Status",
        .formNotes: "Napomena",
        .formInvalidAmount: "Unesite važeći iznos.",
        .formThirteenthAmount: "13. plata (iznos)",
        .formThirteenthModel: "Model 13. plate",
        .thirteenthModelSeparate: "Prikaži zasebno",
        .thirteenthModelAveraged: "Rasporedi na 12 meseci",
        .formTarget: "Cilj štednje (iznos)",
        .formSaved: "Već ušteđeno",
        .formMonthlyContribution: "Mesečni doprinos",
        .formCategory: "Kategorija",
        .formLimitedDuration: "Ograničeni trajni nalog",
        .formLimitedDurationHint: "Npr. 6 rata poreza – broje se samo u tim mesecima i zatim se automatski uklanjaju.",
        .formStartMonth: "Prva rata",
        .formInstallments: "Broj rata",
        .planningStandingOrder: "Trajni nalog",
        .catRent: "Kirija",
        .catSubscription: "Pretplata",
        .catLeasing: "Lizing",
        .catUtilities: "Režije",
        .catTelecom: "Telekomunikacije",
        .catGroceries: "Namirnice",
        .catFuel: "Gorivo",
        .catTransport: "Prevoz",
        .catPersonal: "Lično",
        .catDining: "Obroci van kuće",
        .catHousehold: "Domaćinstvo",

        .overviewTitle: "Pregled",
        .overviewAvailableThisMonth: "Dostupno ovog meseca",
        .overviewNetIncome: "Neto prihod ovog meseca",
        .overviewThirteenthSeparate: "13. plata (zasebno)",
        .overviewRecurringFixed: "Fiksni troškovi",
        .overviewPlannedVariable: "Promenljivi izdaci",
        .overviewBillsDueThisMonth: "Otvoreni računi ovog meseca",
        .overviewOverdueBills: "Dospeli računi",
        .overviewSavingsTarget: "Cilj štednje",
        .overviewSecurityStatus: "Status bezbednosti",
        .overviewFormulaExplainer: "Dostupno = neto prihod − fiksni troškovi − promenljivi budžeti − otvoreni računi ovog meseca − dospeli računi. Plaćeni i budući računi ne smanjuju iznos.",
        .overviewEmpty: "Unesite prihode i troškove u Mesečno planiranje da biste videli pregled.",
        .chartSpendingTitle: "Raspodela ovog meseca",
        .chartByCategory: "Po kategoriji",

        .planningTitle: "Mesečno planiranje",
        .planningIncome: "Prihod",
        .planningFixed: "Fiksni troškovi",
        .planningVariable: "Promenljivi izdaci",
        .planningSavings: "Cilj štednje",
        .planningFixedExplainer: "Fiksni troškovi ponavljaju se svakog meseca: kirija, osiguranja, pretplate, lizing.",
        .planningVariableExplainer: "Promenljive budžete planirate sami: namirnice, gorivo, lični izdaci.",
        .planningOneOffHint: "Jednokratnim računima upravljate u „Računi”.",
        .planningEmpty: "Počnite s prihodom, a zatim dodajte fiksne troškove i budžete.",
        .planningBalance: "Planirano stanje",

        .billsTitle: "Računi",
        .billsStatusOpen: "Otvoren",
        .billsStatusPaid: "Plaćen",
        .billsStateOverdue: "Dospeo",
        .billsStateDueThisMonth: "Dospeva ovog meseca",
        .billsStateFuture: "Budući",
        .billsAffectsBalance: "Smanjuje dostupni iznos",
        .billsNoBalanceImpact: "Bez uticaja ovog meseca",
        .billsDueDate: "Datum dospeća",
        .billsProvider: "Pružalac",
        .billsEmpty: "Još nema računa. Jednokratni računi s datumom dospeća prikazaće se ovde.",
        .billsMarkPaid: "Označi kao plaćeno",
        .billsMarkOpen: "Označi kao otvoreno",
        .billsOpenTotal: "Ukupno otvoreno",

        .navSchulden: "Dugovi",
        .schuldenSubtitle: "Pratite dospele račune i prinudnu naplatu.",
        .schuldenEmpty: "Nema zabeleženih dugova. Dospeli računi prikazuju se ovde automatski – a možete zabeležiti prinudnu naplatu (Betreibung) ili potvrde o gubitku.",
        .schuldenAddCta: "Zabeleži dug",
        .schuldenTotal: "Ukupni dug",
        .schuldenOverdueBills: "Dospeli računi",
        .schuldenRecorded: "Zabeleženi dugovi",
        .schuldenManagedInBills: "Dospelim računima upravljajte u „Računi”.",
        .debtTypeOpenClaim: "Otvoreno potraživanje",
        .debtTypeBetreibung: "Prinudna naplata",
        .debtTypePfaendung: "Plenidba plate/imovine",
        .debtTypeVerlustschein: "Potvrda o gubitku",
        .debtTypeOther: "Drugi dug",
        .debtCreditor: "Poverilac",
        .debtReference: "Referenca / broj predmeta",
        .debtDate: "Datum",
        .debtType: "Vrsta",
        .schuldenGuidanceTitle: "Kako izaći iz dugova",
        .schuldenTipContactTitle: "Javite se rano",
        .schuldenTipContactBody: "Razgovarajte s poveriocima rano. Pisani plan otplate na rate često je moguć i izbegava formalni postupak.",
        .schuldenTipBetreibungTitle: "Ako počne naplata",
        .schuldenTipBetreibungBody: "Nakon platnog naloga imate 20 dana za plaćanje – ili 10 dana za podnošenje prigovora (Rechtsvorschlag) ako je potraživanje neosnovano.",
        .schuldenTipExistenzminimumTitle: "Vaš egzistencijalni minimum je zaštićen",
        .schuldenTipExistenzminimumBody: "Pri plenidbi vaš egzistencijalni minimum ostaje netaknut – osnovni iznos, kirija, zdravstveno osiguranje i socijalni doprinosi.",
        .schuldenTipVerlustscheinTitle: "Potvrda o gubitku",
        .schuldenTipVerlustscheinBody: "Potvrda o gubitku zastareva tek nakon 20 godina. Možete biti ponovo gonjeni samo kada steknete novu imovinu.",
        .schuldenTipCounselingTitle: "Besplatno savetovanje o dugovima",
        .schuldenTipCounselingBody: "Schuldenberatung Schweiz, Caritas i budžetsko savetovanje pomažu besplatno i poverljivo. Prvo otplatite dugove s najgorim posledicama.",
        .schuldenDisclaimer: "Opšte informacije, nije pravni savet.",

        .catInsurance: "Osiguranje",
        .catOther: "Ostalo",
        .catMortgage: "Hipotekarni kredit",
        .catHealthInsurance: "Zdravstveno osiguranje",
        .catSerafe: "Radio/TV (Serafe)",
        .catPublicTransport: "Prevozna karta",
        .catChildcare: "Čuvanje dece",
        .catMembership: "Članarine",
        .catAlimony: "Izdržavanje",
        .catTaxes: "Porezi",
        .catClothing: "Odeća",
        .catHealth: "Zdravlje",
        .catLeisure: "Slobodno vreme i hobiji",
        .catEntertainment: "Zabava",
        .catChildren: "Deca",
        .catPets: "Kućni ljubimci",
        .catGifts: "Pokloni",
        .catTravel: "Putovanja",
        .catCharity: "Donacije",
        .catEducation: "Obrazovanje",

        .settingsTitle: "Podešavanja",
        .settingsLanguage: "Jezik",
        .settingsTheme: "Tema boja",
        .themeSwissRed: "Švajcarska crvena",
        .themeOrange: "Narandžasta",
        .themeSand: "Pesak",
        .themeGreen: "Zelena",
        .themeTeal: "Tirkizna",
        .themeBlue: "Plava",
        .themePurple: "Ljubičasta",
        .themePink: "Roze",
        .settingsData: "Podaci",
        .settingsHousehold: "Domaćinstvo",
        .settingsCanton: "Kanton",
        .settingsProfile: "Profil",
        .profileName: "Ime",
        .profileChoosePicture: "Izaberi profilnu sliku",
        .profileNoPicture: "Bez slike",
        .profileLocalNote: "Sačuvano samo lokalno na ovom uređaju.",
        .settingsSecurity: "Bezbednost",
        .settingsAutoLock: "Automatsko zaključavanje",
        .settingsBiometric: "Биометријско откључавање",
        .settingsChangePassphrase: "Promeni lozinku/PIN",
        .settingsBackup: "Šifrovana rezervna kopija",
        .settingsRestore: "Vrati",
        .settingsPrivacy: "Privatnost",
        .settingsDangerZone: "Opasna zona",
        .settingsDeleteAll: "Obriši sve lokalne podatke",
        .backupCreateTitle: "Napravi šifrovanu rezervnu kopiju",
        .backupPassphrase: "Lozinka rezervne kopije",
        .backupHint: "Izaberite zasebnu lozinku za rezervnu kopiju. Potrebna je za vraćanje – lozinku nije moguće povratiti.",
        .restorePreview: "Pregled",
        .restoreConfirm: "Zameni sve lokalne podatke",
        .restoreWarning: "Ovo trajno prepisuje sve lokalne podatke.",
        .backupInvalid: "Nevažeća rezervna kopija ili pogrešna lozinka.",
        .backupSavedHint: "Čuvajte datoteku rezervne kopije i lozinku na bezbednom mestu.",

        .reportTitle: "Prijavi problem",
        .reportSummary: "Sažetak",
        .reportExpected: "Očekivano ponašanje",
        .reportActual: "Stvarno ponašanje",
        .reportSteps: "Koraci za reprodukciju",
        .reportArea: "Zahvaćena oblast",
        .reportRedactionNote: "Osetljivi podaci uklanjaju se lokalno. Pregledate izveštaj pre kopiranja.",
        .reportCopyHint: "Izveštaj se ne šalje automatski. Sami ga kopirate.",

        .exportReport: "Izvezi izveštaj",
        .pdfTitle: "Finansijski pregled",
        .pdfSubtitle: "Lični izveštaj domaćinstva",
        .pdfSummary: "Na prvi pogled",
        .pdfGeneratedOn: "Napravljeno",
        .pdfConfidential: "Poverljivo",
        .pdfPage: "Stranica",
        .pdfTotal: "Ukupno",
        .pdfColProgress: "Napredak",
        .pdfUnencryptedNote: "Izveštaj je čitljiv, nešifrovan PDF. Čuvajte ga na bezbednom mestu.",
        .pdfNoData: "Još nema podataka za izvoz.",
        .pdfDefaultHousehold: "Moje domaćinstvo",

        .lockTitle: "Zaključano",
        .lockWelcomeSetup: "Dobro došli u Kontivu",
        .lockWelcomeBack: "Dobro došli nazad",
        .lockSetupTitle: "Postavi lozinku",
        .lockEnterPassphrase: "Unesite lozinku ili PIN",
        .lockWrongPassphrase: "Pogrešna lozinka. Pokušajte ponovo.",
        .lockRecoveryWarning: "Nema oporavka. Bez vaše lozinke vašim podacima nije moguće pristupiti.",
        .lockRecoveryAcknowledge: "Razumem da nema oporavka.",
        .securityNote: "Vaši podaci čuvaju se lokalno i šifrovani (AES-256-GCM). Bez oblaka, bez servera, bez oporavka lozinke.",

        .onboardingIntroBody: "Kontiva vam pomaže da imate smiren pregled budžeta vašeg švajcarskog domaćinstva – u potpunosti na ovom uređaju.",
        .onboardingStart: "Započni",
        .onboardingProfileTitle: "Napravi profil",
        .onboardingProfileBody: "Dajte sebi ime i izaberite sliku. Oboje ostaje samo na ovom uređaju.",
        .onboardingSkip: "Preskoči",
        .onboardingFeaturePrivate: "Potpuno lokalno – bez oblaka, bez praćenja",
        .onboardingFeatureSecure: "Šifrovano sa AES-256",
        .onboardingFeatureMoney: "Tačno do centima, bez grešaka zaokruživanja",
        .onboardingConfirmPassphrase: "Potvrdi lozinku",
        .onboardingPassphraseNote: "Zapišite lozinku na bezbedno mesto – nije ju moguće poništiti.",
        .backupNudgeText: "Napravite šifrovanu rezervnu kopiju. Bez nje gubite podatke ako zaboravite lozinku.",
        .commonNext: "Dalje",
        .navMore: "Više",
        .actionLock: "Zaključaj",
        .pinSetTitle: "Postavi kod",
        .pinConfirmTitle: "Potvrdi kod",
        .pinRequirementNote: "Min. 6 cifara · bez oporavka",
        .pinMismatch: "Kodovi se ne podudaraju",
    ]
}
