import Foundation

extension Localization {
    static let uk: [L10nKey: String] = [
        .appName: "Kontiva",
        .appTagline: "Спокійний, приватний огляд вашого швейцарського бюджету.",
        .notBetaNotice: "Рання версія розробки – не бета, не V1.",

        .navOverview: "Огляд",
        .navPlanning: "План",
        .navBills: "Рахунки",
        .navSettings: "Налаштування",
        .navReport: "Повідомити про проблему",
        .navInsights: "Аналітика",
        .navSparen: "Заощадження",
        .sparenSubtitle: "Регулярні внески на заощадження – і те, що вже накопичено.",
        .sparenEmpty: "Цілей заощадження ще немає. Визначте, на що відкладаєте щомісяця.",
        .sparenMonthlyTotal: "Заощадження / міс.",
        .sparenAccumulatedTotal: "Уже накопичено",
        .sparenPerMonth: "/ міс.",
        .sparenContributions: "внесків",
        .sparenSince: "з",
        .sparenOpenEnded: "Без цільової суми",
        .sparenGoalsLabel: "Цілі",
        .sparenSortBy: "Сортувати",
        .sparenSortStartMonth: "Місяць початку",
        .savingsCatCar: "Автомобіль",
        .savingsCatVacation: "Відпустка",
        .savingsCatHome: "Житло",
        .savingsCatRetirement: "Стовп 3a / Пенсія",
        .savingsCatEmergency: "Резервний фонд",
        .savingsCatEducation: "Освіта",
        .savingsCatOther: "Інше",
        .savingsCatWedding: "Весілля",
        .savingsCatFamily: "Сім'я та діти",
        .savingsCatRenovation: "Ремонт і облаштування",
        .savingsCatElectronics: "Електроніка",
        .savingsCatTaxes: "Резерв на податки",
        .savingsCatInvestment: "Інвестиції",
        .savingsCatHealth: "Здоров'я",
        .savingsCatGift: "Подарунки",
        .overviewPlannedSavings: "Заощадження цього місяця",
        .overviewShowCalculation: "Показати розрахунок",
        .overviewTrendTitle: "Тренд · 6 місяців",
        .overviewStatusGood: "Здоровий профіцит",
        .overviewStatusTight: "Впритул",
        .overviewStatusNegative: "У мінусі",
        .overviewAllocationOf: "від чистого доходу",
        .formStartDate: "Відкладає з",
        .formStartingBalance: "Початковий баланс (необов'язково)",
        .insightsSubtitle: "Підказки щодо вашого бюджету – де ваші гроші і де можна заощадити.",
        .insightOverspending: "Ви витрачаєте більше, ніж заробляєте",
        .insightTightBudget: "Мало простору цього місяця",
        .insightHealthySurplus: "Здоровий профіцит",
        .insightHighFixed: "Високі постійні витрати",
        .insightHighHousing: "Високі витрати на житло",
        .insightLargestFixed: "Найбільша стаття постійних витрат",
        .insightLargestVariable: "Найбільший змінний бюджет",
        .insightOverdue: "Прострочені рахунки",
        .insightNoSavings: "Заощадження ще не заплановані",
        .insightGoodSavings: "Хороша норма заощаджень",
        .insightAllHealthy: "Ваш бюджет виглядає здоровим",
        .insightHousingHint: "Орієнтир: не більше третини доходу",
        .insightNoSavingsDetail: "У вас є запас – ціль заощадження могла б допомогти.",
        .insightAllHealthyDetail: "Нічого не вирізняється. Додайте більше даних для точнішої аналітики.",
        .fragOfNetIncome: "від чистого доходу",
        .fragOfFixedCosts: "від постійних витрат",
        .fragShortfall: "Дефіцит",

        .commonAdd: "Додати",
        .commonEdit: "Змінити",
        .commonActivate: "Увімкнути",
        .commonDelete: "Видалити",
        .commonCancel: "Скасувати",
        .commandsAdd: "Додати запис",
        .billsAddCta: "Додайте перший рахунок",
        .sparenAddCta: "Створіть ціль заощадження",
        .overviewAddCta: "Додати дохід",
        .commonSave: "Зберегти",
        .commonSaved: "Збережено",
        .commonClose: "Закрити",
        .commonDone: "Готово",
        .commonShowSampleData: "Показати приклади даних",
        .commonHideSampleData: "Сховати приклади даних",
        .commonEmptyHint: "Дані ще не введені.",
        .commonCopy: "Копіювати",
        .commonOptions: "Параметри",
        .commonMoveUp: "Перемістити вгору",
        .commonMoveDown: "Перемістити вниз",
        .monthToday: "Сьогодні",

        .formName: "Назва",
        .formAmount: "Сума (CHF)",
        .formStatus: "Статус",
        .formNotes: "Примітка",
        .formInvalidAmount: "Введіть коректну суму.",
        .formThirteenthAmount: "13-та зарплата (сума)",
        .formThirteenthModel: "Модель 13-ї зарплати",
        .incomeBonuses: "Додаткові виплати",
        .formMonth: "Місяць",
        .thirteenthModelSeparate: "Показувати окремо",
        .thirteenthModelAveraged: "Розподілити на 12 місяців",
        .formTarget: "Ціль заощадження (сума)",
        .formSaved: "Уже накопичено",
        .formMonthlyContribution: "Щомісячний внесок",
        .formCategory: "Категорія",
        .formLimitedDuration: "Обмежене постійне доручення",
        .formLimitedDurationHint: "Напр. 6 податкових платежів – враховуються лише в ці місяці й потім видаляються автоматично.",
        .formStartMonth: "Перший платіж",
        .formInstallments: "Кількість платежів",
        .planningStandingOrder: "Постійне доручення",
        .catRent: "Оренда",
        .catSubscription: "Підписка",
        .catLeasing: "Лізинг",
        .catUtilities: "Комунальні послуги",
        .catTelecom: "Зв'язок",
        .catGroceries: "Продукти",
        .catFuel: "Пальне",
        .catTransport: "Транспорт",
        .catPersonal: "Особисте",
        .catDining: "Харчування поза домом",
        .catHousehold: "Господарство",

        .overviewTitle: "Огляд",
        .overviewAvailableThisMonth: "Доступно цього місяця",
        .overviewNetIncome: "Чистий дохід цього місяця",
        .overviewThirteenthSeparate: "13-та зарплата (окремо)",
        .overviewRecurringFixed: "Постійні витрати",
        .overviewPlannedVariable: "Змінні витрати",
        .overviewBillsDueThisMonth: "Рахунки цього місяця",
        .overviewOverdueBills: "Прострочені рахунки",
        .overviewSavingsTarget: "Ціль заощадження",
        .overviewSecurityStatus: "Стан безпеки",
        .overviewFormulaExplainer: "Доступно = чистий дохід − постійні витрати − змінні бюджети − відкриті рахунки цього місяця − прострочені рахунки. Оплачені та майбутні рахунки суму не зменшують.",
        .overviewEmpty: "Введіть доходи й витрати в «Планування на місяць», щоб побачити огляд.",
        .chartSpendingTitle: "Розподіл цього місяця",
        .chartByCategory: "За категоріями",

        .planningTitle: "Планування на місяць",
        .planningIncome: "Дохід",
        .planningFixed: "Постійні витрати",
        .planningVariable: "Змінні витрати",
        .planningSavings: "Ціль заощадження",
        .planningFixedExplainer: "Постійні витрати повторюються щомісяця: оренда, страхування, підписки, лізинг.",
        .planningVariableExplainer: "Змінні бюджети ви плануєте самі: продукти, пальне, особисті витрати.",
        .planningOneOffHint: "Разові рахунки керуються в розділі «Рахунки».",
        .planningEmpty: "Почніть із доходу, потім додайте постійні витрати й бюджети.",
        .planningBalance: "Плановий баланс",

        .billsTitle: "Рахунки",
        .billsStatusOpen: "Відкритий",
        .billsStatusPaid: "Оплачений",
        .billsStateOverdue: "Прострочений",
        .billsStateDueThisMonth: "Термін цього місяця",
        .billsStateFuture: "Майбутній",
        .billsAffectsBalance: "Зменшує доступну суму",
        .billsNoBalanceImpact: "Без впливу цього місяця",
        .billsDueDate: "Термін оплати",
        .billsProvider: "Постачальник",
        .billsEmpty: "Рахунків ще немає. Разові рахунки з терміном оплати з'являться тут.",
        .billsMarkPaid: "Позначити оплаченим",
        .billsMarkOpen: "Позначити відкритим",
        .billsOpenTotal: "Усього відкрито",

        .navSchulden: "Борги",
        .schuldenSubtitle: "Стежте за простроченими рахунками та стягненням.",
        .schuldenEmpty: "Боргів не записано. Прострочені рахунки з'являються тут автоматично – і ви можете позначити стягнення (Betreibung) або акти про неможливість стягнення.",
        .schuldenAddCta: "Записати борг",
        .schuldenTotal: "Загальний борг",
        .schuldenOverdueBills: "Прострочені рахунки",
        .schuldenRecorded: "Записані борги",
        .schuldenManagedInBills: "Керуйте простроченими рахунками в розділі «Рахунки».",
        .debtTypeOpenClaim: "Відкрита вимога",
        .debtTypeBetreibung: "Стягнення",
        .debtTypePfaendung: "Арешт зарплати/майна",
        .debtTypeVerlustschein: "Акт про неможливість стягнення",
        .debtTypeOther: "Інший борг",
        .debtCreditor: "Кредитор",
        .debtReference: "Посилання / номер справи",
        .debtDate: "Дата",
        .debtType: "Тип",
        .schuldenGuidanceTitle: "Шлях із боргів",
        .schuldenTipContactTitle: "Зверніться завчасно",
        .schuldenTipContactBody: "Поговоріть із кредиторами завчасно. Письмовий план розстрочки часто можливий і дозволяє уникнути формальної процедури.",
        .schuldenTipBetreibungTitle: "Якщо починається стягнення",
        .schuldenTipBetreibungBody: "Після платіжної вимоги у вас 20 днів на оплату – або 10 днів на заперечення (Rechtsvorschlag), якщо вимога безпідставна.",
        .schuldenTipExistenzminimumTitle: "Ваш прожитковий мінімум захищений",
        .schuldenTipExistenzminimumBody: "При арешті ваш прожитковий мінімум залишається недоторканним – базова сума, оренда, медичне страхування та соціальні внески.",
        .schuldenTipVerlustscheinTitle: "Акт про неможливість стягнення",
        .schuldenTipVerlustscheinBody: "Такий акт спливає лише через 20 років. Переслідування може відновитися тільки коли у вас з'явиться нове майно.",
        .schuldenTipCounselingTitle: "Безкоштовна консультація щодо боргів",
        .schuldenTipCounselingBody: "Schuldenberatung Schweiz, Caritas і бюджетні консультації допомагають безкоштовно й конфіденційно. Спершу погасіть борги з найважчими наслідками.",
        .schuldenDisclaimer: "Загальна інформація, не юридична консультація.",

        .catInsurance: "Страхування",
        .catOther: "Інше",
        .catMortgage: "Іпотека",
        .catHealthInsurance: "Медичне страхування",
        .catSerafe: "Радіо/ТБ (Serafe)",
        .catPublicTransport: "Проїзний",
        .catChildcare: "Догляд за дітьми",
        .catMembership: "Членські внески",
        .catAlimony: "Аліменти",
        .catTaxes: "Податки",
        .catClothing: "Одяг",
        .catHealth: "Здоров'я",
        .catLeisure: "Дозвілля та хобі",
        .catEntertainment: "Розваги",
        .catChildren: "Діти",
        .catPets: "Домашні улюбленці",
        .catGifts: "Подарунки",
        .catTravel: "Подорожі",
        .catCharity: "Благодійність",
        .catEducation: "Освіта",

        .settingsTitle: "Налаштування",
        .settingsLanguage: "Мова",
        .settingsTheme: "Кольорова тема",
        .themeSwissRed: "Швейцарський червоний",
        .themeOrange: "Помаранчевий",
        .themeSand: "Пісочний",
        .themeGreen: "Зелений",
        .themeTeal: "Бірюзовий",
        .themeBlue: "Синій",
        .themePurple: "Фіолетовий",
        .themePink: "Рожевий",
        .settingsData: "Дані",
        .settingsHousehold: "Господарство",
        .settingsCanton: "Кантон",
        .settingsProfile: "Профіль",
        .profileName: "Ім'я",
        .profileChoosePicture: "Вибрати фото профілю",
        .profileNoPicture: "Без фото",
        .profileLocalNote: "Зберігається лише локально на цьому пристрої.",
        .settingsSecurity: "Безпека",
        .settingsAutoLock: "Автоблокування",
        .settingsBiometric: "Біометричне розблокування",
        .settingsChangePassphrase: "Змінити пароль/PIN",
        .settingsBackup: "Зашифрована резервна копія",
        .settingsRestore: "Відновити",
        .settingsPrivacy: "Конфіденційність",
        .settingsDangerZone: "Небезпечна зона",
        .settingsDeleteAll: "Видалити всі локальні дані",
        .backupCreateTitle: "Створити зашифровану резервну копію",
        .backupPassphrase: "Пароль резервної копії",
        .backupHint: "Виберіть окремий пароль для резервної копії. Він потрібен для відновлення – відновити пароль неможливо.",
        .restorePreview: "Попередній перегляд",
        .restoreConfirm: "Замінити всі локальні дані",
        .restoreWarning: "Це безповоротно перезапише всі локальні дані.",
        .backupInvalid: "Недійсна резервна копія або неправильний пароль.",
        .backupSavedHint: "Зберігайте файл резервної копії й пароль у надійному місці.",

        .reportTitle: "Повідомити про проблему",
        .reportSummary: "Підсумок",
        .reportExpected: "Очікувана поведінка",
        .reportActual: "Фактична поведінка",
        .reportSteps: "Кроки відтворення",
        .reportArea: "Уражена область",
        .reportRedactionNote: "Конфіденційні дані видаляються локально. Ви переглядаєте звіт перед копіюванням.",
        .reportCopyHint: "Звіт не надсилається автоматично. Ви копіюєте його самі.",

        .exportReport: "Експортувати звіт",
        .pdfTitle: "Фінансовий огляд",
        .pdfSubtitle: "Особистий звіт по домогосподарству",
        .pdfSummary: "З першого погляду",
        .pdfGeneratedOn: "Створено",
        .pdfConfidential: "Конфіденційно",
        .pdfPage: "Сторінка",
        .pdfTotal: "Разом",
        .pdfColProgress: "Прогрес",
        .pdfUnencryptedNote: "Звіт – читабельний, незашифрований PDF. Зберігайте його в надійному місці.",
        .pdfNoData: "Даних для експорту ще немає.",
        .pdfDefaultHousehold: "Моє домогосподарство",

        .lockTitle: "Заблоковано",
        .lockWelcomeSetup: "Ласкаво просимо до Kontiva",
        .lockWelcomeBack: "З поверненням",
        .lockSetupTitle: "Задати пароль",
        .lockEnterPassphrase: "Введіть пароль або PIN",
        .lockWrongPassphrase: "Неправильний пароль. Спробуйте ще раз.",
        .lockRecoveryWarning: "Відновлення немає. Без вашого пароля доступ до даних неможливий.",
        .lockRecoveryAcknowledge: "Я розумію, що відновлення немає.",
        .securityNote: "Ваші дані зберігаються локально й у зашифрованому вигляді (AES-256-GCM). Без хмари, без сервера, без відновлення пароля.",

        .onboardingIntroBody: "Kontiva допомагає спокійно стежити за бюджетом вашого швейцарського домогосподарства – повністю на цьому пристрої.",
        .onboardingStart: "Почати",
        .onboardingProfileTitle: "Створіть профіль",
        .onboardingProfileBody: "Дайте собі ім'я та виберіть зображення. Обидва залишаються лише на цьому пристрої.",
        .onboardingSkip: "Пропустити",
        .onboardingFeaturePrivate: "Повністю локально – без хмари, без стеження",
        .onboardingFeatureSecure: "Зашифровано з AES-256",
        .onboardingFeatureMoney: "Точно до сантима, без помилок округлення",
        .onboardingConfirmPassphrase: "Підтвердьте пароль",
        .onboardingPassphraseNote: "Запишіть пароль у надійному місці – скинути його неможливо.",
        .backupNudgeText: "Створіть зашифровану резервну копію. Без неї ви втратите дані, якщо забудете пароль.",
        .commonNext: "Далі",
        .navMore: "Більше",
        .actionLock: "Заблокувати",
        .pinSetTitle: "Задати код",
        .pinConfirmTitle: "Підтвердьте код",
        .pinRequirementNote: "Мін. 6 цифр · без відновлення",
        .pinMismatch: "Коди не збігаються",
    ]
}
