import Foundation

// Urdu (RTL). Flagged for native-speaker review.
extension Localization {
    static let ur: [L10nKey: String] = [
        .appName: "Kontiva",
        .appTagline: "آپ کے سوئس بجٹ پر ایک پُرسکون، نجی نظر۔",
        .notBetaNotice: "ابتدائی ترقیاتی نسخہ – بیٹا نہیں، V1 نہیں۔",

        .navOverview: "جائزہ",
        .navPlanning: "ماہانہ منصوبہ بندی",
        .navBills: "بل",
        .navSettings: "ترتیبات",
        .navReport: "مسئلہ رپورٹ کریں",
        .navInsights: "تجزیہ",
        .navSparen: "بچت",
        .sparenSubtitle: "باقاعدہ بچت کی ادائیگیاں – اور جو پہلے ہی جمع ہو چکا ہے۔",
        .sparenEmpty: "ابھی تک کوئی بچت کا ہدف نہیں۔ طے کریں کہ آپ ہر ماہ کس لیے بچت کرتے ہیں۔",
        .sparenMonthlyTotal: "بچت / ماہ",
        .sparenAccumulatedTotal: "پہلے ہی بچایا گیا",
        .sparenPerMonth: "/ ماہ",
        .sparenContributions: "ادائیگیاں",
        .sparenSince: "سے",
        .sparenOpenEnded: "کوئی ہدف رقم نہیں",
        .sparenGoalsLabel: "اہداف",
        .savingsCatCar: "گاڑی",
        .savingsCatVacation: "تعطیلات",
        .savingsCatHome: "رہائش",
        .savingsCatRetirement: "ستون 3a / پنشن",
        .savingsCatEmergency: "ہنگامی فنڈ",
        .savingsCatEducation: "تعلیم",
        .savingsCatOther: "دیگر",
        .savingsCatWedding: "شادی",
        .savingsCatFamily: "خاندان اور بچے",
        .savingsCatRenovation: "تزئین و آرائش",
        .savingsCatElectronics: "برقی آلات",
        .savingsCatTaxes: "ٹیکس کے لیے ذخیرہ",
        .savingsCatInvestment: "سرمایہ کاری",
        .savingsCatHealth: "صحت",
        .savingsCatGift: "تحائف",
        .overviewPlannedSavings: "اس ماہ کی بچت",
        .overviewShowCalculation: "حساب دکھائیں",
        .overviewTrendTitle: "رجحان · 6 ماہ",
        .overviewStatusGood: "صحت مند فاضل",
        .overviewStatusTight: "تنگ",
        .overviewStatusNegative: "خسارے میں",
        .overviewAllocationOf: "خالص آمدنی کا",
        .formStartDate: "بچت بمطابق",
        .formStartingBalance: "ابتدائی بیلنس (اختیاری)",
        .insightsSubtitle: "آپ کے بجٹ کے لیے رہنمائی – آپ کا پیسہ کہاں ہے اور کہاں بچت ممکن ہے۔",
        .insightOverspending: "آپ کمائی سے زیادہ خرچ کر رہے ہیں",
        .insightTightBudget: "اس ماہ گنجائش کم ہے",
        .insightHealthySurplus: "صحت مند فاضل",
        .insightHighFixed: "زیادہ مقررہ اخراجات",
        .insightHighHousing: "زیادہ رہائشی اخراجات",
        .insightLargestFixed: "مقررہ اخراجات میں سب سے بڑا حصہ",
        .insightLargestVariable: "سب سے بڑا متغیر بجٹ",
        .insightOverdue: "واجب الادا بل",
        .insightNoSavings: "ابھی تک کوئی بچت منصوبہ بند نہیں",
        .insightGoodSavings: "اچھی بچت کی شرح",
        .insightAllHealthy: "آپ کا بجٹ صحت مند لگتا ہے",
        .insightHousingHint: "رہنمائی: آمدنی کا زیادہ سے زیادہ ایک تہائی",
        .insightNoSavingsDetail: "آپ کے پاس گنجائش ہے – ایک بچت کا ہدف مدد دے سکتا ہے۔",
        .insightAllHealthyDetail: "کچھ بھی نمایاں نہیں۔ تیز تر تجزیے کے لیے مزید ڈیٹا شامل کریں۔",
        .fragOfNetIncome: "خالص آمدنی کا",
        .fragOfFixedCosts: "مقررہ اخراجات کا",
        .fragShortfall: "کمی",

        .commonAdd: "شامل کریں",
        .commonEdit: "ترمیم",
        .commonDelete: "حذف کریں",
        .commonCancel: "منسوخ",
        .commandsAdd: "اندراج شامل کریں",
        .billsAddCta: "اپنا پہلا بل شامل کریں",
        .sparenAddCta: "ایک بچت کا ہدف بنائیں",
        .overviewAddCta: "آمدنی شامل کریں",
        .commonSave: "محفوظ کریں",
        .commonSaved: "محفوظ ہو گیا",
        .commonClose: "بند کریں",
        .commonDone: "ہو گیا",
        .commonShowSampleData: "نمونہ ڈیٹا دکھائیں",
        .commonHideSampleData: "نمونہ ڈیٹا چھپائیں",
        .commonEmptyHint: "ابھی تک کوئی ڈیٹا درج نہیں۔",
        .commonCopy: "نقل کریں",
        .commonOptions: "اختیارات",
        .commonMoveUp: "اوپر لے جائیں",
        .commonMoveDown: "نیچے لے جائیں",
        .monthToday: "آج",

        .formName: "نام",
        .formAmount: "رقم (CHF)",
        .formStatus: "حالت",
        .formNotes: "نوٹ",
        .formInvalidAmount: "ایک درست رقم درج کریں۔",
        .formThirteenthAmount: "13واں ماہانہ تنخواہ (رقم)",
        .formThirteenthModel: "13ویں تنخواہ کا ماڈل",
        .thirteenthModelSeparate: "علیحدہ دکھائیں",
        .thirteenthModelAveraged: "12 ماہ پر تقسیم کریں",
        .formTarget: "بچت کا ہدف (رقم)",
        .formSaved: "پہلے ہی بچایا گیا",
        .formMonthlyContribution: "ماہانہ ادائیگی",
        .formCategory: "زمرہ",
        .formLimitedDuration: "محدود مدت کا مستقل حکم",
        .formLimitedDurationHint: "مثلاً 6 ٹیکس اقساط – صرف ان مہینوں میں شمار ہوتی ہیں اور پھر خود بخود ہٹا دی جاتی ہیں۔",
        .formStartMonth: "پہلی قسط",
        .formInstallments: "اقساط کی تعداد",
        .planningStandingOrder: "مستقل حکم",
        .catRent: "کرایہ",
        .catSubscription: "سبسکرپشن",
        .catLeasing: "لیزنگ",
        .catUtilities: "یوٹیلیٹیز (بجلی، پانی)",
        .catTelecom: "ٹیلی کام",
        .catGroceries: "اشیائے خوردونوش",
        .catFuel: "ایندھن",
        .catTransport: "نقل و حمل",
        .catPersonal: "ذاتی",
        .catDining: "باہر کھانا",
        .catHousehold: "گھریلو",

        .overviewTitle: "جائزہ",
        .overviewAvailableThisMonth: "اس ماہ دستیاب",
        .overviewNetIncome: "اس ماہ خالص آمدنی",
        .overviewThirteenthSeparate: "13واں ماہانہ تنخواہ (علیحدہ)",
        .overviewRecurringFixed: "مقررہ اخراجات",
        .overviewPlannedVariable: "متغیر اخراجات",
        .overviewBillsDueThisMonth: "اس ماہ کے کھلے بل",
        .overviewOverdueBills: "واجب الادا بل",
        .overviewSavingsTarget: "بچت کا ہدف",
        .overviewSecurityStatus: "سیکیورٹی کی حالت",
        .overviewFormulaExplainer: "دستیاب = خالص آمدنی − مقررہ اخراجات − متغیر بجٹ − اس ماہ کے کھلے بل − واجب الادا بل۔ ادا شدہ اور مستقبل کے بل رقم کم نہیں کرتے۔",
        .overviewEmpty: "اپنا جائزہ دیکھنے کے لیے ماہانہ منصوبہ بندی میں آمدنی اور اخراجات درج کریں۔",
        .chartSpendingTitle: "اس ماہ کی تقسیم",
        .chartByCategory: "زمرے کے لحاظ سے",

        .planningTitle: "ماہانہ منصوبہ بندی",
        .planningIncome: "آمدنی",
        .planningFixed: "مقررہ اخراجات",
        .planningVariable: "متغیر اخراجات",
        .planningSavings: "بچت کا ہدف",
        .planningFixedExplainer: "مقررہ اخراجات ہر ماہ دہراتے ہیں: کرایہ، بیمہ، سبسکرپشن، لیزنگ۔",
        .planningVariableExplainer: "متغیر بجٹ آپ خود منصوبہ بناتے ہیں: اشیائے خوردونوش، ایندھن، ذاتی اخراجات۔",
        .planningOneOffHint: "یک بار بل „بل” میں منظم ہوتے ہیں۔",
        .planningEmpty: "اپنی آمدنی سے شروع کریں، پھر مقررہ اخراجات اور بجٹ شامل کریں۔",
        .planningBalance: "منصوبہ بند بیلنس",

        .billsTitle: "بل",
        .billsStatusOpen: "کھلا",
        .billsStatusPaid: "ادا شدہ",
        .billsStateOverdue: "واجب الادا",
        .billsStateDueThisMonth: "اس ماہ واجب",
        .billsStateFuture: "مستقبل",
        .billsAffectsBalance: "دستیاب رقم کم کرتا ہے",
        .billsNoBalanceImpact: "اس ماہ کوئی اثر نہیں",
        .billsDueDate: "واجب الادا تاریخ",
        .billsProvider: "فراہم کنندہ",
        .billsEmpty: "ابھی تک کوئی بل نہیں۔ واجب الادا تاریخ والے یک بار بل یہاں ظاہر ہوتے ہیں۔",
        .billsMarkPaid: "ادا شدہ نشان زد کریں",
        .billsMarkOpen: "کھلا نشان زد کریں",
        .billsOpenTotal: "کل کھلا",

        .navSchulden: "قرض",
        .schuldenSubtitle: "واجب الادا بلوں اور وصولی کی کارروائی پر نظر رکھیں۔",
        .schuldenEmpty: "کوئی قرض درج نہیں۔ واجب الادا بل یہاں خود بخود ظاہر ہوتے ہیں – اور آپ وصولی کی کارروائی (Betreibung) یا نقصان کے سرٹیفکیٹ درج کر سکتے ہیں۔",
        .schuldenAddCta: "ایک قرض درج کریں",
        .schuldenTotal: "کل قرض",
        .schuldenOverdueBills: "واجب الادا بل",
        .schuldenRecorded: "درج شدہ قرض",
        .schuldenManagedInBills: "واجب الادا بل „بل” میں منظم کریں۔",
        .debtTypeOpenClaim: "کھلا دعویٰ",
        .debtTypeBetreibung: "وصولی کی کارروائی",
        .debtTypePfaendung: "تنخواہ/جائیداد کی ضبطی",
        .debtTypeVerlustschein: "نقصان کا سرٹیفکیٹ",
        .debtTypeOther: "دیگر قرض",
        .debtCreditor: "قرض خواہ",
        .debtReference: "حوالہ / کیس نمبر",
        .debtDate: "تاریخ",
        .debtType: "قسم",
        .schuldenGuidanceTitle: "قرض سے نکلنے کا راستہ",
        .schuldenTipContactTitle: "جلد رابطہ کریں",
        .schuldenTipContactBody: "قرض خواہوں سے جلد بات کریں۔ تحریری قسط وار ادائیگی کا منصوبہ اکثر ممکن ہوتا ہے اور رسمی کارروائی سے بچاتا ہے۔",
        .schuldenTipBetreibungTitle: "اگر وصولی شروع ہو جائے",
        .schuldenTipBetreibungBody: "ادائیگی کے حکم کے بعد آپ کے پاس ادائیگی کے لیے 20 دن – یا اگر دعویٰ ناجائز ہو تو اعتراض (Rechtsvorschlag) کے لیے 10 دن ہیں۔",
        .schuldenTipExistenzminimumTitle: "آپ کا کم از کم گزارہ محفوظ ہے",
        .schuldenTipExistenzminimumBody: "ضبطی کے دوران آپ کا کم از کم گزارہ بے دست و خورد رہتا ہے – بنیادی رقم، کرایہ، صحت بیمہ اور سماجی شراکتیں۔",
        .schuldenTipVerlustscheinTitle: "نقصان کا سرٹیفکیٹ",
        .schuldenTipVerlustscheinBody: "نقصان کا سرٹیفکیٹ 20 سال بعد ہی ختم ہوتا ہے۔ نئی جائیداد حاصل کرنے پر ہی آپ سے دوبارہ وصولی ہو سکتی ہے۔",
        .schuldenTipCounselingTitle: "مفت قرض مشاورت",
        .schuldenTipCounselingBody: "Schuldenberatung Schweiz، Caritas اور بجٹ مشاورت مفت اور رازداری سے مدد کرتے ہیں۔ پہلے سب سے سنگین نتائج والے قرض ادا کریں۔",
        .schuldenDisclaimer: "عمومی معلومات، قانونی مشورہ نہیں۔",

        .catInsurance: "بیمہ",
        .catOther: "دیگر",
        .catMortgage: "رہن قرض",
        .catHealthInsurance: "صحت بیمہ",
        .catSerafe: "ریڈیو/ٹی وی (Serafe)",
        .catPublicTransport: "سفری پاس",
        .catChildcare: "بچوں کی دیکھ بھال",
        .catMembership: "رکنیت فیس",
        .catAlimony: "نان نفقہ",
        .catTaxes: "ٹیکس",
        .catClothing: "لباس",
        .catHealth: "صحت",
        .catLeisure: "فرصت اور مشاغل",
        .catEntertainment: "تفریح",
        .catChildren: "بچے",
        .catPets: "پالتو جانور",
        .catGifts: "تحائف",
        .catTravel: "سفر",
        .catCharity: "عطیات",
        .catEducation: "تعلیم",

        .settingsTitle: "ترتیبات",
        .settingsLanguage: "زبان",
        .settingsTheme: "رنگ تھیم",
        .themeSwissRed: "سوئس سرخ",
        .themeOrange: "نارنجی",
        .themeSand: "ریتی",
        .themeGreen: "سبز",
        .themeTeal: "نیلگوں سبز",
        .themeBlue: "نیلا",
        .themePurple: "جامنی",
        .themePink: "گلابی",
        .settingsData: "ڈیٹا",
        .settingsHousehold: "گھرانہ",
        .settingsCanton: "کینٹن",
        .settingsProfile: "پروفائل",
        .profileName: "نام",
        .profileChoosePicture: "پروفائل تصویر منتخب کریں",
        .profileNoPicture: "کوئی تصویر نہیں",
        .profileLocalNote: "صرف اس آلے پر مقامی طور پر محفوظ۔",
        .settingsSecurity: "سیکیورٹی",
        .settingsAutoLock: "خودکار قفل",
        .settingsChangePassphrase: "پاس ورڈ/PIN تبدیل کریں",
        .settingsBackup: "خفیہ کردہ بیک اپ",
        .settingsRestore: "بحال کریں",
        .settingsPrivacy: "رازداری",
        .settingsDangerZone: "خطرناک زون",
        .settingsDeleteAll: "تمام مقامی ڈیٹا حذف کریں",
        .backupCreateTitle: "خفیہ کردہ بیک اپ بنائیں",
        .backupPassphrase: "بیک اپ پاس ورڈ",
        .backupHint: "بیک اپ کے لیے ایک علیحدہ پاس ورڈ منتخب کریں۔ بحالی کے لیے یہ ضروری ہے – پاس ورڈ بازیافت نہیں ہو سکتا۔",
        .restorePreview: "پیش نظارہ",
        .restoreConfirm: "تمام مقامی ڈیٹا تبدیل کریں",
        .restoreWarning: "یہ تمام مقامی ڈیٹا کو مستقل طور پر اوور رائٹ کر دیتا ہے۔",
        .backupInvalid: "غلط بیک اپ یا غلط پاس ورڈ۔",
        .backupSavedHint: "بیک اپ فائل اور پاس ورڈ محفوظ جگہ پر رکھیں۔",

        .reportTitle: "مسئلہ رپورٹ کریں",
        .reportSummary: "خلاصہ",
        .reportExpected: "متوقع رویہ",
        .reportActual: "اصل رویہ",
        .reportSteps: "دوبارہ پیدا کرنے کے مراحل",
        .reportArea: "متاثرہ علاقہ",
        .reportRedactionNote: "حساس ڈیٹا مقامی طور پر ہٹا دیا جاتا ہے۔ آپ نقل کرنے سے پہلے رپورٹ کا جائزہ لیتے ہیں۔",
        .reportCopyHint: "رپورٹ خود بخود نہیں بھیجی جاتی۔ آپ خود اسے نقل کرتے ہیں۔",

        .exportReport: "رپورٹ برآمد کریں",
        .pdfTitle: "مالی جائزہ",
        .pdfSubtitle: "ذاتی گھرانہ رپورٹ",
        .pdfSummary: "ایک نظر میں",
        .pdfGeneratedOn: "تیار کردہ",
        .pdfConfidential: "خفیہ",
        .pdfPage: "صفحہ",
        .pdfTotal: "کل",
        .pdfColProgress: "پیش رفت",
        .pdfUnencryptedNote: "رپورٹ ایک پڑھنے کے قابل، غیر خفیہ PDF ہے۔ اسے محفوظ جگہ پر رکھیں۔",
        .pdfNoData: "ابھی تک برآمد کرنے کے لیے کوئی ڈیٹا نہیں۔",
        .pdfDefaultHousehold: "میرا گھرانہ",

        .lockTitle: "مقفل",
        .lockWelcomeSetup: "Kontiva میں خوش آمدید",
        .lockWelcomeBack: "واپسی پر خوش آمدید",
        .lockSetupTitle: "پاس ورڈ مقرر کریں",
        .lockEnterPassphrase: "پاس ورڈ یا PIN درج کریں",
        .lockWrongPassphrase: "غلط پاس ورڈ۔ دوبارہ کوشش کریں۔",
        .lockRecoveryWarning: "کوئی بحالی نہیں۔ آپ کے پاس ورڈ کے بغیر آپ کے ڈیٹا تک رسائی ممکن نہیں۔",
        .lockRecoveryAcknowledge: "میں سمجھتا ہوں کہ کوئی بحالی نہیں ہے۔",
        .securityNote: "آپ کا ڈیٹا مقامی طور پر اور خفیہ کر کے محفوظ ہوتا ہے (AES-256-GCM)۔ کوئی کلاؤڈ نہیں، کوئی سرور نہیں، کوئی پاس ورڈ بحالی نہیں۔",

        .onboardingIntroBody: "Kontiva آپ کو اپنے سوئس گھرانے کے بجٹ پر پُرسکون نظر رکھنے میں مدد دیتا ہے – مکمل طور پر اس آلے پر۔",
        .onboardingStart: "شروع کریں",
        .onboardingProfileTitle: "ایک پروفائل بنائیں",
        .onboardingProfileBody: "اپنے آپ کو ایک نام دیں اور ایک تصویر منتخب کریں۔ دونوں صرف اس آلے پر رہتے ہیں۔",
        .onboardingSkip: "چھوڑ دیں",
        .onboardingFeaturePrivate: "مکمل طور پر مقامی – کوئی کلاؤڈ نہیں، کوئی ٹریکنگ نہیں",
        .onboardingFeatureSecure: "AES-256 سے خفیہ کردہ",
        .onboardingFeatureMoney: "سنٹیم تک درست، گول کرنے کی غلطی کے بغیر",
        .onboardingConfirmPassphrase: "پاس ورڈ کی تصدیق کریں",
        .onboardingPassphraseNote: "اپنا پاس ورڈ کسی محفوظ جگہ لکھ لیں – اسے ری سیٹ نہیں کیا جا سکتا۔",
        .backupNudgeText: "ایک خفیہ کردہ بیک اپ بنائیں۔ اس کے بغیر، پاس ورڈ بھولنے پر آپ اپنا ڈیٹا کھو دیں گے۔",
        .commonNext: "اگلا",
    ]
}
