import Foundation

extension Localization {
    static let ru: [L10nKey: String] = [
        .appName: "Kontiva",
        .appTagline: "Спокойный, приватный обзор вашего швейцарского бюджета.",
        .notBetaNotice: "Ранняя версия разработки – не бета, не V1.",

        .navOverview: "Обзор",
        .navPlanning: "План",
        .navBills: "Счета",
        .navSettings: "Настройки",
        .navReport: "Сообщить о проблеме",
        .navInsights: "Аналитика",
        .navSparen: "Накопления",
        .sparenSubtitle: "Регулярные взносы на накопления – и то, что уже накоплено.",
        .sparenEmpty: "Целей накопления пока нет. Решите, на что копите каждый месяц.",
        .sparenMonthlyTotal: "Накопления / мес.",
        .sparenAccumulatedTotal: "Уже накоплено",
        .sparenPerMonth: "/ мес.",
        .sparenContributions: "взносов",
        .sparenSince: "с",
        .sparenOpenEnded: "Без целевой суммы",
        .sparenGoalsLabel: "Цели",
        .sparenSortBy: "Сортировка",
        .sparenSortStartMonth: "Месяц начала",
        .savingsCatCar: "Автомобиль",
        .savingsCatVacation: "Отпуск",
        .savingsCatHome: "Жильё",
        .savingsCatRetirement: "Столп 3a / Пенсия",
        .savingsCatEmergency: "Резервный фонд",
        .savingsCatEducation: "Образование",
        .savingsCatOther: "Другое",
        .savingsCatWedding: "Свадьба",
        .savingsCatFamily: "Семья и дети",
        .savingsCatRenovation: "Ремонт и обустройство",
        .savingsCatElectronics: "Электроника",
        .savingsCatTaxes: "Резерв на налоги",
        .savingsCatInvestment: "Инвестиции",
        .savingsCatHealth: "Здоровье",
        .savingsCatGift: "Подарки",
        .overviewPlannedSavings: "Накопления в этом месяце",
        .overviewShowCalculation: "Показать расчёт",
        .overviewTrendTitle: "Тренд · 6 месяцев",
        .overviewStatusGood: "Здоровый профицит",
        .overviewStatusTight: "Впритык",
        .overviewStatusNegative: "В минусе",
        .overviewAllocationOf: "от чистого дохода",
        .formStartDate: "Копит с",
        .formStartingBalance: "Начальный баланс (необязательно)",
        .insightsSubtitle: "Подсказки по вашему бюджету – где ваши деньги и где можно сэкономить.",
        .insightOverspending: "Вы тратите больше, чем зарабатываете",
        .insightTightBudget: "Мало пространства в этом месяце",
        .insightHealthySurplus: "Здоровый профицит",
        .insightHighFixed: "Высокие постоянные расходы",
        .insightHighHousing: "Высокие расходы на жильё",
        .insightLargestFixed: "Крупнейшая статья постоянных расходов",
        .insightLargestVariable: "Крупнейший переменный бюджет",
        .insightOverdue: "Просроченные счета",
        .insightNoSavings: "Накопления ещё не запланированы",
        .insightGoodSavings: "Хорошая норма накоплений",
        .insightAllHealthy: "Ваш бюджет выглядит здоровым",
        .insightHousingHint: "Ориентир: не более трети дохода",
        .insightNoSavingsDetail: "У вас есть запас – цель накопления могла бы помочь.",
        .insightAllHealthyDetail: "Ничего не выделяется. Добавьте больше данных для более точной аналитики.",
        .fragOfNetIncome: "от чистого дохода",
        .fragOfFixedCosts: "от постоянных расходов",
        .fragShortfall: "Дефицит",

        .commonAdd: "Добавить",
        .commonEdit: "Изменить",
        .commonActivate: "Включить",
        .commonDelete: "Удалить",
        .commonCancel: "Отмена",
        .commandsAdd: "Добавить запись",
        .billsAddCta: "Добавьте первый счёт",
        .sparenAddCta: "Создайте цель накопления",
        .overviewAddCta: "Добавить доход",
        .commonSave: "Сохранить",
        .commonSaved: "Сохранено",
        .commonClose: "Закрыть",
        .commonDone: "Готово",
        .commonShowSampleData: "Показать примеры данных",
        .commonHideSampleData: "Скрыть примеры данных",
        .commonEmptyHint: "Данные ещё не введены.",
        .commonCopy: "Копировать",
        .commonOptions: "Параметры",
        .commonMoveUp: "Переместить вверх",
        .commonMoveDown: "Переместить вниз",
        .monthToday: "Сегодня",

        .formName: "Название",
        .formAmount: "Сумма (CHF)",
        .formStatus: "Статус",
        .formNotes: "Заметка",
        .formInvalidAmount: "Введите корректную сумму.",
        .formThirteenthAmount: "13-я зарплата (сумма)",
        .formThirteenthModel: "Модель 13-й зарплаты",
        .incomeBonuses: "Дополнительные выплаты",
        .formMonth: "Месяц",
        .thirteenthModelSeparate: "Показывать отдельно",
        .thirteenthModelAveraged: "Распределить на 12 месяцев",
        .formTarget: "Цель накопления (сумма)",
        .formSaved: "Уже накоплено",
        .formMonthlyContribution: "Ежемесячный взнос",
        .formCategory: "Категория",
        .formLimitedDuration: "Ограниченное постоянное поручение",
        .formLimitedDurationHint: "Напр. 6 налоговых платежей – учитываются только в эти месяцы и затем удаляются автоматически.",
        .formStartMonth: "Первый платёж",
        .formInstallments: "Число платежей",
        .planningStandingOrder: "Постоянное поручение",
        .catRent: "Аренда",
        .catSubscription: "Подписка",
        .catLeasing: "Лизинг",
        .catUtilities: "Коммунальные услуги",
        .catTelecom: "Связь",
        .catGroceries: "Продукты",
        .catFuel: "Топливо",
        .catTransport: "Транспорт",
        .catPersonal: "Личное",
        .catDining: "Питание вне дома",
        .catHousehold: "Хозяйство",

        .overviewTitle: "Обзор",
        .overviewAvailableThisMonth: "Доступно в этом месяце",
        .overviewNetIncome: "Чистый доход в этом месяце",
        .overviewThirteenthSeparate: "13-я зарплата (отдельно)",
        .overviewRecurringFixed: "Постоянные расходы",
        .overviewPlannedVariable: "Переменные расходы",
        .overviewBillsDueThisMonth: "Счета за этот месяц",
        .overviewOverdueBills: "Просроченные счета",
        .overviewSavingsTarget: "Цель накопления",
        .overviewSecurityStatus: "Состояние безопасности",
        .overviewFormulaExplainer: "Доступно = чистый доход − постоянные расходы − переменные бюджеты − открытые счета в этом месяце − просроченные счета. Оплаченные и будущие счета сумму не уменьшают.",
        .overviewEmpty: "Введите доходы и расходы в «Планирование на месяц», чтобы увидеть обзор.",
        .chartSpendingTitle: "Распределение в этом месяце",
        .chartByCategory: "По категориям",

        .planningTitle: "Планирование на месяц",
        .planningIncome: "Доход",
        .planningFixed: "Постоянные расходы",
        .planningVariable: "Переменные расходы",
        .planningSavings: "Цель накопления",
        .planningFixedExplainer: "Постоянные расходы повторяются каждый месяц: аренда, страховки, подписки, лизинг.",
        .planningVariableExplainer: "Переменные бюджеты вы планируете сами: продукты, топливо, личные расходы.",
        .planningOneOffHint: "Разовые счета управляются в разделе «Счета».",
        .planningEmpty: "Начните с дохода, затем добавьте постоянные расходы и бюджеты.",
        .planningBalance: "Плановый баланс",

        .billsTitle: "Счета",
        .billsStatusOpen: "Открыт",
        .billsStatusPaid: "Оплачен",
        .billsStateOverdue: "Просрочен",
        .billsStateDueThisMonth: "Срок в этом месяце",
        .billsStateFuture: "Будущий",
        .billsAffectsBalance: "Уменьшает доступную сумму",
        .billsNoBalanceImpact: "Без влияния в этом месяце",
        .billsDueDate: "Срок оплаты",
        .billsProvider: "Поставщик",
        .billsEmpty: "Счетов пока нет. Разовые счета со сроком оплаты появятся здесь.",
        .billsMarkPaid: "Отметить оплаченным",
        .billsMarkOpen: "Отметить открытым",
        .billsOpenTotal: "Всего открыто",

        .navSchulden: "Долги",
        .schuldenSubtitle: "Следите за просроченными счетами и взысканием.",
        .schuldenEmpty: "Долги не записаны. Просроченные счета появляются здесь автоматически – и вы можете отметить взыскание (Betreibung) или акты о невозможности взыскания.",
        .schuldenAddCta: "Записать долг",
        .schuldenTotal: "Общий долг",
        .schuldenOverdueBills: "Просроченные счета",
        .schuldenRecorded: "Записанные долги",
        .schuldenManagedInBills: "Управляйте просроченными счетами в разделе «Счета».",
        .debtTypeOpenClaim: "Открытое требование",
        .debtTypeBetreibung: "Взыскание",
        .debtTypePfaendung: "Арест зарплаты/имущества",
        .debtTypeVerlustschein: "Акт о невозможности взыскания",
        .debtTypeOther: "Другой долг",
        .debtCreditor: "Кредитор",
        .debtReference: "Ссылка / номер дела",
        .debtDate: "Дата",
        .debtType: "Тип",
        .schuldenGuidanceTitle: "Путь из долгов",
        .schuldenTipContactTitle: "Свяжитесь заранее",
        .schuldenTipContactBody: "Поговорите с кредиторами заранее. Письменный план рассрочки часто возможен и избавляет от формальной процедуры.",
        .schuldenTipBetreibungTitle: "Если начинается взыскание",
        .schuldenTipBetreibungBody: "После платёжного требования у вас 20 дней на оплату – или 10 дней на возражение (Rechtsvorschlag), если требование необоснованно.",
        .schuldenTipExistenzminimumTitle: "Ваш прожиточный минимум защищён",
        .schuldenTipExistenzminimumBody: "При аресте ваш прожиточный минимум остаётся неприкосновенным – базовая сумма, аренда, медицинская страховка и социальные взносы.",
        .schuldenTipVerlustscheinTitle: "Акт о невозможности взыскания",
        .schuldenTipVerlustscheinBody: "Такой акт истекает только через 20 лет. Преследование может возобновиться лишь когда у вас появится новое имущество.",
        .schuldenTipCounselingTitle: "Бесплатная консультация по долгам",
        .schuldenTipCounselingBody: "Schuldenberatung Schweiz, Caritas и бюджетные консультации помогают бесплатно и конфиденциально. Сначала погасите долги с самыми тяжёлыми последствиями.",
        .schuldenDisclaimer: "Общая информация, не юридическая консультация.",

        .catInsurance: "Страхование",
        .catOther: "Другое",
        .catMortgage: "Ипотека",
        .catHealthInsurance: "Медицинская страховка",
        .catSerafe: "Радио/ТВ (Serafe)",
        .catPublicTransport: "Проездной",
        .catChildcare: "Уход за детьми",
        .catMembership: "Членские взносы",
        .catAlimony: "Алименты",
        .catTaxes: "Налоги",
        .catClothing: "Одежда",
        .catHealth: "Здоровье",
        .catLeisure: "Досуг и хобби",
        .catEntertainment: "Развлечения",
        .catChildren: "Дети",
        .catPets: "Питомцы",
        .catGifts: "Подарки",
        .catTravel: "Путешествия",
        .catCharity: "Благотворительность",
        .catEducation: "Образование",

        .settingsTitle: "Настройки",
        .settingsLanguage: "Язык",
        .settingsTheme: "Цветовая тема",
        .themeSwissRed: "Швейцарский красный",
        .themeOrange: "Оранжевый",
        .themeSand: "Песочный",
        .themeGreen: "Зелёный",
        .themeTeal: "Бирюзовый",
        .themeBlue: "Синий",
        .themePurple: "Фиолетовый",
        .themePink: "Розовый",
        .settingsData: "Данные",
        .settingsHousehold: "Хозяйство",
        .settingsCanton: "Кантон",
        .settingsProfile: "Профиль",
        .profileName: "Имя",
        .profileChoosePicture: "Выбрать фото профиля",
        .profileNoPicture: "Без фото",
        .profileLocalNote: "Хранится только локально на этом устройстве.",
        .settingsSecurity: "Безопасность",
        .settingsAutoLock: "Автоблокировка",
        .settingsBiometric: "Биометрическая разблокировка",
        .settingsChangePassphrase: "Сменить пароль/PIN",
        .settingsBackup: "Зашифрованная резервная копия",
        .settingsRestore: "Восстановить",
        .settingsPrivacy: "Конфиденциальность",
        .settingsDangerZone: "Опасная зона",
        .settingsDeleteAll: "Удалить все локальные данные",
        .backupCreateTitle: "Создать зашифрованную резервную копию",
        .backupPassphrase: "Пароль резервной копии",
        .backupHint: "Выберите отдельный пароль для резервной копии. Он нужен для восстановления – восстановить пароль нельзя.",
        .restorePreview: "Предпросмотр",
        .restoreConfirm: "Заменить все локальные данные",
        .restoreWarning: "Это безвозвратно перезапишет все локальные данные.",
        .backupInvalid: "Недействительная резервная копия или неверный пароль.",
        .backupSavedHint: "Храните файл резервной копии и пароль в надёжном месте.",

        .reportTitle: "Сообщить о проблеме",
        .reportSummary: "Сводка",
        .reportExpected: "Ожидаемое поведение",
        .reportActual: "Фактическое поведение",
        .reportSteps: "Шаги воспроизведения",
        .reportArea: "Затронутая область",
        .reportRedactionNote: "Конфиденциальные данные удаляются локально. Вы просматриваете отчёт перед копированием.",
        .reportCopyHint: "Отчёт не отправляется автоматически. Вы копируете его сами.",

        .exportReport: "Экспортировать отчёт",
        .pdfTitle: "Финансовый обзор",
        .pdfSubtitle: "Личный отчёт по домохозяйству",
        .pdfSummary: "С первого взгляда",
        .pdfGeneratedOn: "Создано",
        .pdfConfidential: "Конфиденциально",
        .pdfPage: "Страница",
        .pdfTotal: "Итого",
        .pdfColProgress: "Прогресс",
        .pdfUnencryptedNote: "Отчёт – читаемый, незашифрованный PDF. Храните его в надёжном месте.",
        .pdfNoData: "Данных для экспорта пока нет.",
        .pdfDefaultHousehold: "Моё домохозяйство",

        .lockTitle: "Заблокировано",
        .lockWelcomeSetup: "Добро пожаловать в Kontiva",
        .lockWelcomeBack: "С возвращением",
        .lockSetupTitle: "Задать пароль",
        .lockEnterPassphrase: "Введите пароль или PIN",
        .lockWrongPassphrase: "Неверный пароль. Попробуйте снова.",
        .lockRecoveryWarning: "Восстановления нет. Без вашего пароля доступ к данным невозможен.",
        .lockRecoveryAcknowledge: "Я понимаю, что восстановления нет.",
        .securityNote: "Ваши данные хранятся локально и в зашифрованном виде (AES-256-GCM). Без облака, без сервера, без восстановления пароля.",

        .onboardingIntroBody: "Kontiva помогает спокойно следить за бюджетом вашего швейцарского домохозяйства – полностью на этом устройстве.",
        .onboardingStart: "Начать",
        .onboardingProfileTitle: "Создайте профиль",
        .onboardingProfileBody: "Дайте себе имя и выберите изображение. Оба остаются только на этом устройстве.",
        .onboardingSkip: "Пропустить",
        .onboardingFeaturePrivate: "Полностью локально – без облака, без слежки",
        .onboardingFeatureSecure: "Зашифровано с AES-256",
        .onboardingFeatureMoney: "Точно до сантима, без ошибок округления",
        .onboardingConfirmPassphrase: "Подтвердите пароль",
        .onboardingPassphraseNote: "Запишите пароль в надёжном месте – сбросить его нельзя.",
        .backupNudgeText: "Создайте зашифрованную резервную копию. Без неё вы потеряете данные, если забудете пароль.",
        .commonNext: "Далее",
        .navMore: "Ещё",
        .actionLock: "Заблокировать",
        .pinSetTitle: "Задать код",
        .pinConfirmTitle: "Подтвердите код",
        .pinRequirementNote: "Мин. 6 цифр · без восстановления",
        .pinMismatch: "Коды не совпадают",
    ]
}
