import Foundation

extension Localization {
    static let nl: [L10nKey: String] = [
        .appName: "Kontiva",
        .appTagline: "Een rustig, privé overzicht van je Zwitserse budget.",
        .notBetaNotice: "Vroege ontwikkelversie – nog geen bèta, geen V1.",

        .navOverview: "Overzicht",
        .navPlanning: "Maandplanning",
        .navBills: "Rekeningen",
        .navSettings: "Instellingen",
        .navReport: "Probleem melden",
        .navInsights: "Inzichten",
        .navSparen: "Sparen",
        .sparenSubtitle: "Terugkerende spaarbijdragen – en wat er al is opgebouwd.",
        .sparenEmpty: "Nog geen spaardoelen. Bepaal waarvoor je elke maand spaart.",
        .sparenMonthlyTotal: "Sparen / maand",
        .sparenAccumulatedTotal: "Al gespaard",
        .sparenPerMonth: "/ maand",
        .sparenContributions: "bijdragen",
        .sparenSince: "sinds",
        .sparenOpenEnded: "Geen streefbedrag",
        .sparenGoalsLabel: "Doelen",
        .savingsCatCar: "Auto",
        .savingsCatVacation: "Vakantie",
        .savingsCatHome: "Woning",
        .savingsCatRetirement: "Pijler 3a / Pensioen",
        .savingsCatEmergency: "Noodfonds",
        .savingsCatEducation: "Opleiding",
        .savingsCatOther: "Overig",
        .savingsCatWedding: "Bruiloft",
        .savingsCatFamily: "Gezin en kinderen",
        .savingsCatRenovation: "Verbouwing en inrichting",
        .savingsCatElectronics: "Elektronica",
        .savingsCatTaxes: "Belastingreserve",
        .savingsCatInvestment: "Beleggingen",
        .savingsCatHealth: "Gezondheid",
        .savingsCatGift: "Cadeaus",
        .overviewPlannedSavings: "Sparen deze maand",
        .overviewShowCalculation: "Berekening tonen",
        .overviewTrendTitle: "Trend · 6 maanden",
        .overviewStatusGood: "Gezond overschot",
        .overviewStatusTight: "Krap",
        .overviewStatusNegative: "In het rood",
        .overviewAllocationOf: "van het netto-inkomen",
        .formStartDate: "Sparen sinds",
        .formStartingBalance: "Beginsaldo (optioneel)",
        .insightsSubtitle: "Inzicht in je budget – waar je geld zit en waar je kunt sparen.",
        .insightOverspending: "Je geeft meer uit dan je verdient",
        .insightTightBudget: "Weinig ruimte deze maand",
        .insightHealthySurplus: "Gezond overschot",
        .insightHighFixed: "Hoge vaste lasten",
        .insightHighHousing: "Hoge woonkosten",
        .insightLargestFixed: "Grootste vaste-lastenpost",
        .insightLargestVariable: "Grootste variabele budget",
        .insightOverdue: "Achterstallige rekeningen",
        .insightNoSavings: "Nog geen sparen gepland",
        .insightGoodSavings: "Goede spaarquote",
        .insightAllHealthy: "Je budget ziet er gezond uit",
        .insightHousingHint: "Richtlijn: hoogstens een derde van het inkomen",
        .insightNoSavingsDetail: "Je hebt ruimte – een spaardoel kan helpen.",
        .insightAllHealthyDetail: "Niets springt eruit. Voeg meer gegevens toe voor scherpere inzichten.",
        .fragOfNetIncome: "van het netto-inkomen",
        .fragOfFixedCosts: "van de vaste lasten",
        .fragShortfall: "Tekort",

        .commonAdd: "Toevoegen",
        .commonEdit: "Bewerken",
        .commonDelete: "Verwijderen",
        .commonCancel: "Annuleren",
        .commandsAdd: "Item toevoegen",
        .billsAddCta: "Voeg je eerste rekening toe",
        .sparenAddCta: "Een spaardoel maken",
        .overviewAddCta: "Inkomen toevoegen",
        .commonSave: "Bewaren",
        .commonSaved: "Bewaard",
        .commonClose: "Sluiten",
        .commonDone: "Klaar",
        .commonShowSampleData: "Voorbeeldgegevens tonen",
        .commonHideSampleData: "Voorbeeldgegevens verbergen",
        .commonEmptyHint: "Nog geen gegevens ingevoerd.",
        .commonCopy: "Kopiëren",
        .commonOptions: "Opties",
        .commonMoveUp: "Omhoog",
        .commonMoveDown: "Omlaag",
        .monthToday: "Vandaag",

        .formName: "Naam",
        .formAmount: "Bedrag (CHF)",
        .formStatus: "Status",
        .formNotes: "Notitie",
        .formInvalidAmount: "Voer een geldig bedrag in.",
        .formThirteenthAmount: "13e maand (bedrag)",
        .formThirteenthModel: "Model 13e maand",
        .thirteenthModelSeparate: "Apart tonen",
        .thirteenthModelAveraged: "Verdelen over 12 maanden",
        .formTarget: "Spaardoel (bedrag)",
        .formSaved: "Al gespaard",
        .formMonthlyContribution: "Maandelijkse bijdrage",
        .formCategory: "Categorie",
        .formLimitedDuration: "Tijdelijke doorlopende opdracht",
        .formLimitedDurationHint: "Bijv. 6 belastingtermijnen – alleen in die maanden geteld en daarna automatisch verwijderd.",
        .formStartMonth: "Eerste termijn",
        .formInstallments: "Aantal termijnen",
        .planningStandingOrder: "Doorlopende opdracht",
        .catRent: "Huur",
        .catSubscription: "Abonnement",
        .catLeasing: "Leasing",
        .catUtilities: "Nutsvoorzieningen",
        .catTelecom: "Telecom",
        .catGroceries: "Boodschappen",
        .catFuel: "Brandstof",
        .catTransport: "Vervoer",
        .catPersonal: "Persoonlijk",
        .catDining: "Uit eten",
        .catHousehold: "Huishouden",

        .overviewTitle: "Overzicht",
        .overviewAvailableThisMonth: "Beschikbaar deze maand",
        .overviewNetIncome: "Netto-inkomen deze maand",
        .overviewThirteenthSeparate: "13e maand (apart getoond)",
        .overviewRecurringFixed: "Vaste lasten",
        .overviewPlannedVariable: "Variabele uitgaven",
        .overviewBillsDueThisMonth: "Openstaande rekeningen deze maand",
        .overviewOverdueBills: "Achterstallige rekeningen",
        .overviewSavingsTarget: "Spaardoel",
        .overviewSecurityStatus: "Beveiligingsstatus",
        .overviewFormulaExplainer: "Beschikbaar = netto-inkomen − vaste lasten − variabele budgetten − openstaande rekeningen deze maand − achterstallige rekeningen. Betaalde en toekomstige rekeningen verlagen het bedrag niet.",
        .overviewEmpty: "Voer inkomen en kosten in bij Maandplanning om je overzicht te zien.",
        .chartSpendingTitle: "Verdeling deze maand",
        .chartByCategory: "Per categorie",

        .planningTitle: "Maandplanning",
        .planningIncome: "Inkomen",
        .planningFixed: "Vaste lasten",
        .planningVariable: "Variabele uitgaven",
        .planningSavings: "Spaardoel",
        .planningFixedExplainer: "Vaste lasten komen elke maand terug: huur, verzekeringen, abonnementen, leasing.",
        .planningVariableExplainer: "Variabele budgetten plan je zelf: boodschappen, brandstof, persoonlijke uitgaven.",
        .planningOneOffHint: "Eenmalige rekeningen beheer je onder “Rekeningen”.",
        .planningEmpty: "Begin met je inkomen en voeg daarna vaste lasten en budgetten toe.",
        .planningBalance: "Gepland saldo",

        .billsTitle: "Rekeningen",
        .billsStatusOpen: "Openstaand",
        .billsStatusPaid: "Betaald",
        .billsStateOverdue: "Achterstallig",
        .billsStateDueThisMonth: "Vervalt deze maand",
        .billsStateFuture: "Toekomstig",
        .billsAffectsBalance: "Verlaagt het beschikbare bedrag",
        .billsNoBalanceImpact: "Geen effect deze maand",
        .billsDueDate: "Vervaldatum",
        .billsProvider: "Leverancier",
        .billsEmpty: "Nog geen rekeningen. Eenmalige rekeningen met een vervaldatum verschijnen hier.",
        .billsMarkPaid: "Als betaald markeren",
        .billsMarkOpen: "Als openstaand markeren",
        .billsOpenTotal: "Openstaand totaal",

        .navSchulden: "Schulden",
        .schuldenSubtitle: "Houd achterstallige rekeningen en incasso in de gaten.",
        .schuldenEmpty: "Geen schulden geregistreerd. Achterstallige rekeningen verschijnen hier automatisch – en je kunt incasso (Betreibung) of verliesverklaringen noteren.",
        .schuldenAddCta: "Schuld vastleggen",
        .schuldenTotal: "Totale schuld",
        .schuldenOverdueBills: "Achterstallige rekeningen",
        .schuldenRecorded: "Vastgelegde schulden",
        .schuldenManagedInBills: "Beheer achterstallige rekeningen onder “Rekeningen”.",
        .debtTypeOpenClaim: "Openstaande vordering",
        .debtTypeBetreibung: "Incassoprocedure",
        .debtTypePfaendung: "Loon-/beslaglegging",
        .debtTypeVerlustschein: "Verliesverklaring",
        .debtTypeOther: "Andere schuld",
        .debtCreditor: "Schuldeiser",
        .debtReference: "Referentie / dossiernr.",
        .debtDate: "Datum",
        .debtType: "Type",
        .schuldenGuidanceTitle: "Je weg uit de schulden vinden",
        .schuldenTipContactTitle: "Neem op tijd contact op",
        .schuldenTipContactBody: "Praat vroeg met schuldeisers. Een schriftelijke betalingsregeling is vaak mogelijk en voorkomt een formele procedure.",
        .schuldenTipBetreibungTitle: "Als de procedure start",
        .schuldenTipBetreibungBody: "Na het betalingsbevel heb je 20 dagen om te betalen – of 10 dagen om bezwaar (Rechtsvorschlag) te maken als de vordering onterecht is.",
        .schuldenTipExistenzminimumTitle: "Je bestaansminimum is beschermd",
        .schuldenTipExistenzminimumBody: "Bij beslaglegging blijft je bestaansminimum onaantastbaar – basisbedrag, huur, ziektekostenverzekering en sociale premies.",
        .schuldenTipVerlustscheinTitle: "Verliesverklaring",
        .schuldenTipVerlustscheinBody: "Een verliesverklaring verjaart pas na 20 jaar. Je kunt pas opnieuw worden aangesproken zodra je nieuw vermogen verwerft.",
        .schuldenTipCounselingTitle: "Gratis schuldhulpverlening",
        .schuldenTipCounselingBody: "Schuldenberatung Schweiz, Caritas en budgetadvies helpen gratis en vertrouwelijk. Betaal eerst de schulden met de ergste gevolgen af.",
        .schuldenDisclaimer: "Algemene informatie, geen juridisch advies.",

        .catInsurance: "Verzekering",
        .catOther: "Overig",
        .catMortgage: "Hypotheek",
        .catHealthInsurance: "Ziektekostenverzekering",
        .catSerafe: "Radio/tv (Serafe)",
        .catPublicTransport: "OV-abonnement",
        .catChildcare: "Kinderopvang",
        .catMembership: "Lidmaatschappen",
        .catAlimony: "Alimentatie en onderhoud",
        .catTaxes: "Belastingen",
        .catClothing: "Kleding",
        .catHealth: "Gezondheid",
        .catLeisure: "Vrije tijd en hobby's",
        .catEntertainment: "Entertainment",
        .catChildren: "Kinderen",
        .catPets: "Huisdieren",
        .catGifts: "Cadeaus",
        .catTravel: "Reizen",
        .catCharity: "Goede doelen",
        .catEducation: "Opleiding",

        .settingsTitle: "Instellingen",
        .settingsLanguage: "Taal",
        .settingsTheme: "Kleurthema",
        .themeSwissRed: "Zwitsers rood",
        .themeOrange: "Oranje",
        .themeSand: "Zand",
        .themeGreen: "Groen",
        .themeTeal: "Blauwgroen",
        .themeBlue: "Blauw",
        .themePurple: "Paars",
        .themePink: "Roze",
        .settingsData: "Gegevens",
        .settingsHousehold: "Huishouden",
        .settingsCanton: "Kanton",
        .settingsProfile: "Profiel",
        .profileName: "Naam",
        .profileChoosePicture: "Profielfoto kiezen",
        .profileNoPicture: "Geen foto",
        .profileLocalNote: "Alleen lokaal op dit apparaat opgeslagen.",
        .settingsSecurity: "Beveiliging",
        .settingsAutoLock: "Automatisch vergrendelen",
        .settingsBiometric: "Biometrisch ontgrendelen",
        .settingsChangePassphrase: "Wachtwoord/pincode wijzigen",
        .settingsBackup: "Versleutelde back-up",
        .settingsRestore: "Herstellen",
        .settingsPrivacy: "Privacy",
        .settingsDangerZone: "Gevarenzone",
        .settingsDeleteAll: "Alle lokale gegevens verwijderen",
        .backupCreateTitle: "Versleutelde back-up maken",
        .backupPassphrase: "Back-upwachtwoord",
        .backupHint: "Kies een apart back-upwachtwoord. Het is nodig om te herstellen – er is geen herstel van het back-upwachtwoord.",
        .restorePreview: "Voorbeeld",
        .restoreConfirm: "Alle lokale gegevens vervangen",
        .restoreWarning: "Dit overschrijft alle lokale gegevens definitief.",
        .backupInvalid: "Ongeldige back-up of onjuist back-upwachtwoord.",
        .backupSavedHint: "Bewaar het back-upbestand en het back-upwachtwoord op een veilige plek.",

        .reportTitle: "Probleem melden",
        .reportSummary: "Samenvatting",
        .reportExpected: "Verwacht gedrag",
        .reportActual: "Werkelijk gedrag",
        .reportSteps: "Stappen om te reproduceren",
        .reportArea: "Betrokken onderdeel",
        .reportRedactionNote: "Gevoelige gegevens worden lokaal verwijderd. Je controleert het rapport voordat je het kopieert.",
        .reportCopyHint: "Het rapport wordt niet automatisch verzonden. Je kopieert het zelf.",

        .exportReport: "Rapport exporteren",
        .pdfTitle: "Financieel overzicht",
        .pdfSubtitle: "Persoonlijk huishoudrapport",
        .pdfSummary: "In één oogopslag",
        .pdfGeneratedOn: "Gegenereerd op",
        .pdfConfidential: "Vertrouwelijk",
        .pdfPage: "Pagina",
        .pdfTotal: "Totaal",
        .pdfColProgress: "Voortgang",
        .pdfUnencryptedNote: "Het rapport is een leesbaar, niet-versleuteld pdf. Bewaar het op een veilige plek.",
        .pdfNoData: "Nog geen gegevens om te exporteren.",
        .pdfDefaultHousehold: "Mijn huishouden",

        .lockTitle: "Vergrendeld",
        .lockWelcomeSetup: "Welkom bij Kontiva",
        .lockWelcomeBack: "Welkom terug",
        .lockSetupTitle: "Wachtwoord instellen",
        .lockEnterPassphrase: "Voer wachtwoord of pincode in",
        .lockWrongPassphrase: "Onjuist wachtwoord. Probeer het opnieuw.",
        .lockRecoveryWarning: "Er is geen herstel. Zonder je wachtwoord zijn je gegevens niet toegankelijk.",
        .lockRecoveryAcknowledge: "Ik begrijp dat er geen herstel is.",
        .securityNote: "Je gegevens worden lokaal en versleuteld opgeslagen (AES-256-GCM). Geen cloud, geen server, geen wachtwoordherstel.",

        .onboardingIntroBody: "Kontiva helpt je een rustig overzicht te houden van je Zwitserse huishoudbudget – volledig op dit apparaat.",
        .onboardingStart: "Aan de slag",
        .onboardingProfileTitle: "Maak een profiel",
        .onboardingProfileBody: "Geef jezelf een naam en kies een afbeelding. Beide blijven alleen op dit apparaat.",
        .onboardingSkip: "Overslaan",
        .onboardingFeaturePrivate: "Volledig lokaal – geen cloud, geen tracking",
        .onboardingFeatureSecure: "Versleuteld met AES-256",
        .onboardingFeatureMoney: "Tot op de centiem nauwkeurig, zonder afrondingsfouten",
        .onboardingConfirmPassphrase: "Wachtwoord bevestigen",
        .onboardingPassphraseNote: "Schrijf je wachtwoord ergens veilig op – het kan niet worden gereset.",
        .backupNudgeText: "Maak een versleutelde back-up. Zonder back-up zijn je gegevens verloren als je het wachtwoord vergeet.",
        .commonNext: "Volgende",
        .navMore: "Meer",
        .actionLock: "Vergrendelen",
        .pinSetTitle: "Code instellen",
        .pinConfirmTitle: "Code bevestigen",
        .pinRequirementNote: "Min. 6 cijfers · geen herstel",
        .pinMismatch: "Codes komen niet overeen",
    ]
}
