import Foundation

extension Localization {
    static let ko: [L10nKey: String] = [
        .appName: "Kontiva",
        .appTagline: "스위스 가계 예산을 차분하고 사적으로 한눈에.",
        .notBetaNotice: "초기 개발 버전 — 베타도 V1도 아닙니다.",

        .navOverview: "개요",
        .navPlanning: "계획",
        .navBills: "청구서",
        .navSettings: "설정",
        .navReport: "문제 신고",
        .navInsights: "분석",
        .navSparen: "저축",
        .sparenSubtitle: "정기적인 저축 납입 — 그리고 이미 모인 금액.",
        .sparenEmpty: "아직 저축 목표가 없습니다. 매달 무엇을 위해 저축할지 정하세요.",
        .sparenMonthlyTotal: "저축 / 월",
        .sparenAccumulatedTotal: "이미 저축함",
        .sparenPerMonth: "/ 월",
        .sparenContributions: "회 납입",
        .sparenSince: "부터",
        .sparenOpenEnded: "목표 금액 없음",
        .sparenGoalsLabel: "목표",
        .sparenSortBy: "정렬",
        .sparenSortStartMonth: "시작 월",
        .savingsCatCar: "자동차",
        .savingsCatVacation: "휴가",
        .savingsCatHome: "주거",
        .savingsCatRetirement: "3a 기둥 / 연금",
        .savingsCatEmergency: "비상금",
        .savingsCatEducation: "교육",
        .savingsCatOther: "기타",
        .savingsCatWedding: "결혼식",
        .savingsCatFamily: "가족과 자녀",
        .savingsCatRenovation: "리모델링과 가구",
        .savingsCatElectronics: "전자기기",
        .savingsCatTaxes: "세금 대비금",
        .savingsCatInvestment: "투자",
        .savingsCatHealth: "건강",
        .savingsCatGift: "선물",
        .overviewPlannedSavings: "이번 달 저축",
        .overviewShowCalculation: "계산 보기",
        .overviewTrendTitle: "추세 · 6개월",
        .overviewStatusGood: "건전한 잉여",
        .overviewStatusTight: "빠듯함",
        .overviewStatusNegative: "적자",
        .overviewAllocationOf: "순소득 중",
        .formStartDate: "저축 시작",
        .formStartingBalance: "시작 잔액 (선택)",
        .insightsSubtitle: "예산을 위한 안내 — 당신의 돈이 어디에 있고 어디서 절약할 수 있는지.",
        .insightOverspending: "버는 것보다 더 많이 쓰고 있습니다",
        .insightTightBudget: "이번 달은 여유가 적습니다",
        .insightHealthySurplus: "건전한 잉여",
        .insightHighFixed: "고정 비용이 높음",
        .insightHighHousing: "주거 비용이 높음",
        .insightLargestFixed: "고정 비용 중 가장 큰 항목",
        .insightLargestVariable: "가장 큰 변동 예산",
        .insightOverdue: "연체된 청구서",
        .insightNoSavings: "아직 계획된 저축이 없습니다",
        .insightGoodSavings: "좋은 저축률",
        .insightAllHealthy: "예산이 건전해 보입니다",
        .insightHousingHint: "권장: 소득의 최대 3분의 1",
        .insightNoSavingsDetail: "여유가 있습니다 — 저축 목표가 도움이 될 수 있습니다.",
        .insightAllHealthyDetail: "두드러지는 것이 없습니다. 데이터를 더 추가하면 더 정밀한 분석을 얻습니다.",
        .fragOfNetIncome: "순소득 중",
        .fragOfFixedCosts: "고정 비용 중",
        .fragShortfall: "부족액",

        .commonAdd: "추가",
        .commonEdit: "편집",
        .commonDelete: "삭제",
        .commonCancel: "취소",
        .commandsAdd: "항목 추가",
        .billsAddCta: "첫 청구서 추가",
        .sparenAddCta: "저축 목표 만들기",
        .overviewAddCta: "수입 추가",
        .commonSave: "저장",
        .commonSaved: "저장됨",
        .commonClose: "닫기",
        .commonDone: "완료",
        .commonShowSampleData: "예시 데이터 표시",
        .commonHideSampleData: "예시 데이터 숨기기",
        .commonEmptyHint: "아직 입력된 데이터가 없습니다.",
        .commonCopy: "복사",
        .commonOptions: "옵션",
        .commonMoveUp: "위로 이동",
        .commonMoveDown: "아래로 이동",
        .monthToday: "오늘",

        .formName: "이름",
        .formAmount: "금액 (CHF)",
        .formStatus: "상태",
        .formNotes: "메모",
        .formInvalidAmount: "유효한 금액을 입력하세요.",
        .formThirteenthAmount: "13개월째 급여 (금액)",
        .formThirteenthModel: "13개월째 급여 방식",
        .thirteenthModelSeparate: "별도로 표시",
        .thirteenthModelAveraged: "12개월에 분산",
        .formTarget: "저축 목표 (금액)",
        .formSaved: "이미 저축함",
        .formMonthlyContribution: "월 납입",
        .formCategory: "카테고리",
        .formLimitedDuration: "기간 제한 자동 이체",
        .formLimitedDurationHint: "예: 세금 6회분 — 해당 월에만 계산되고 이후 자동으로 제거됩니다.",
        .formStartMonth: "첫 회차",
        .formInstallments: "회차 수",
        .planningStandingOrder: "자동 이체",
        .catRent: "임대료",
        .catSubscription: "구독",
        .catLeasing: "리스",
        .catUtilities: "공과금",
        .catTelecom: "통신",
        .catGroceries: "식료품",
        .catFuel: "연료",
        .catTransport: "교통",
        .catPersonal: "개인",
        .catDining: "외식",
        .catHousehold: "가계",

        .overviewTitle: "개요",
        .overviewAvailableThisMonth: "이번 달 사용 가능액",
        .overviewNetIncome: "이번 달 순소득",
        .overviewThirteenthSeparate: "13개월째 급여 (별도)",
        .overviewRecurringFixed: "고정 비용",
        .overviewPlannedVariable: "변동 지출",
        .overviewBillsDueThisMonth: "이번 달 청구서",
        .overviewOverdueBills: "연체된 청구서",
        .overviewSavingsTarget: "저축 목표",
        .overviewSecurityStatus: "보안 상태",
        .overviewFormulaExplainer: "사용 가능액 = 순소득 − 고정 비용 − 변동 예산 − 이번 달 미납 청구서 − 연체된 청구서. 납부 완료 및 향후 청구서는 금액을 줄이지 않습니다.",
        .overviewEmpty: "「월간 계획」에서 수입과 지출을 입력하면 개요가 표시됩니다.",
        .chartSpendingTitle: "이번 달 분포",
        .chartByCategory: "카테고리별",

        .planningTitle: "월간 계획",
        .planningIncome: "수입",
        .planningFixed: "고정 비용",
        .planningVariable: "변동 지출",
        .planningSavings: "저축 목표",
        .planningFixedExplainer: "고정 비용은 매달 반복됩니다: 임대료, 보험, 구독, 리스.",
        .planningVariableExplainer: "변동 예산은 직접 계획합니다: 식료품, 연료, 개인 지출.",
        .planningOneOffHint: "일회성 청구서는 「청구서」에서 관리합니다.",
        .planningEmpty: "수입부터 시작한 뒤 고정 비용과 예산을 추가하세요.",
        .planningBalance: "계획 잔액",

        .billsTitle: "청구서",
        .billsStatusOpen: "미납",
        .billsStatusPaid: "납부 완료",
        .billsStateOverdue: "연체",
        .billsStateDueThisMonth: "이번 달 마감",
        .billsStateFuture: "향후",
        .billsAffectsBalance: "사용 가능액을 줄입니다",
        .billsNoBalanceImpact: "이번 달 영향 없음",
        .billsDueDate: "납부 기한",
        .billsProvider: "제공자",
        .billsEmpty: "아직 청구서가 없습니다. 납부 기한이 있는 일회성 청구서가 여기에 표시됩니다.",
        .billsMarkPaid: "납부 완료로 표시",
        .billsMarkOpen: "미납으로 표시",
        .billsOpenTotal: "미납 합계",

        .navSchulden: "부채",
        .schuldenSubtitle: "연체된 청구서와 강제 추심을 살펴보세요.",
        .schuldenEmpty: "기록된 부채가 없습니다. 연체된 청구서가 여기에 자동 표시됩니다 — 강제 추심 (Betreibung)이나 손실 증명서도 기록할 수 있습니다.",
        .schuldenAddCta: "부채 기록",
        .schuldenTotal: "총 부채",
        .schuldenOverdueBills: "연체된 청구서",
        .schuldenRecorded: "기록된 부채",
        .schuldenManagedInBills: "연체된 청구서는 「청구서」에서 관리합니다.",
        .debtTypeOpenClaim: "미결 채권",
        .debtTypeBetreibung: "강제 추심",
        .debtTypePfaendung: "급여·재산 압류",
        .debtTypeVerlustschein: "손실 증명서",
        .debtTypeOther: "기타 부채",
        .debtCreditor: "채권자",
        .debtReference: "참조 / 사건 번호",
        .debtDate: "날짜",
        .debtType: "유형",
        .schuldenGuidanceTitle: "부채에서 벗어나는 길",
        .schuldenTipContactTitle: "일찍 연락하세요",
        .schuldenTipContactBody: "채권자와 일찍 상의하세요. 서면 분할 납부 계획은 종종 가능하며 공식 절차를 피할 수 있습니다.",
        .schuldenTipBetreibungTitle: "추심이 시작되면",
        .schuldenTipBetreibungBody: "지급 명령 후 납부에 20일 — 청구가 부당하면 이의 신청 (Rechtsvorschlag)에 10일이 주어집니다.",
        .schuldenTipExistenzminimumTitle: "최저 생계비는 보호됩니다",
        .schuldenTipExistenzminimumBody: "압류 시에도 최저 생계비는 침해되지 않습니다 — 기본 금액, 임대료, 건강보험, 사회보험료.",
        .schuldenTipVerlustscheinTitle: "손실 증명서",
        .schuldenTipVerlustscheinBody: "손실 증명서는 20년이 지나야 비로소 소멸합니다. 새 자산을 얻었을 때만 다시 추심될 수 있습니다.",
        .schuldenTipCounselingTitle: "무료 부채 상담",
        .schuldenTipCounselingBody: "Schuldenberatung Schweiz, Caritas, 가계 상담이 무료로 비밀을 지키며 돕습니다. 가장 결과가 심각한 부채부터 갚으세요.",
        .schuldenDisclaimer: "일반 정보이며 법률 자문이 아닙니다.",

        .catInsurance: "보험",
        .catOther: "기타",
        .catMortgage: "주택 담보 대출",
        .catHealthInsurance: "건강보험",
        .catSerafe: "방송 수신료 (Serafe)",
        .catPublicTransport: "정기권",
        .catChildcare: "보육",
        .catMembership: "회비",
        .catAlimony: "부양비",
        .catTaxes: "세금",
        .catClothing: "의류",
        .catHealth: "건강",
        .catLeisure: "여가와 취미",
        .catEntertainment: "오락",
        .catChildren: "자녀",
        .catPets: "반려동물",
        .catGifts: "선물",
        .catTravel: "여행",
        .catCharity: "기부",
        .catEducation: "교육",

        .settingsTitle: "설정",
        .settingsLanguage: "언어",
        .settingsTheme: "색상 테마",
        .themeSwissRed: "스위스 레드",
        .themeOrange: "주황",
        .themeSand: "샌드",
        .themeGreen: "초록",
        .themeTeal: "청록",
        .themeBlue: "파랑",
        .themePurple: "보라",
        .themePink: "분홍",
        .settingsData: "데이터",
        .settingsHousehold: "가구",
        .settingsCanton: "주(칸톤)",
        .settingsProfile: "프로필",
        .profileName: "이름",
        .profileChoosePicture: "프로필 사진 선택",
        .profileNoPicture: "사진 없음",
        .profileLocalNote: "이 기기에만 로컬로 저장됩니다.",
        .settingsSecurity: "보안",
        .settingsAutoLock: "자동 잠금",
        .settingsBiometric: "생체 인증 잠금 해제",
        .settingsChangePassphrase: "비밀번호/PIN 변경",
        .settingsBackup: "암호화 백업",
        .settingsRestore: "복원",
        .settingsPrivacy: "개인정보",
        .settingsDangerZone: "위험 구역",
        .settingsDeleteAll: "모든 로컬 데이터 삭제",
        .backupCreateTitle: "암호화 백업 만들기",
        .backupPassphrase: "백업 비밀번호",
        .backupHint: "백업에는 별도의 비밀번호를 선택하세요. 복원에 필요합니다 — 비밀번호는 복구할 수 없습니다.",
        .restorePreview: "미리보기",
        .restoreConfirm: "모든 로컬 데이터 교체",
        .restoreWarning: "이 작업은 모든 로컬 데이터를 영구적으로 덮어씁니다.",
        .backupInvalid: "유효하지 않은 백업이거나 비밀번호가 틀립니다.",
        .backupSavedHint: "백업 파일과 비밀번호를 안전한 곳에 보관하세요.",

        .reportTitle: "문제 신고",
        .reportSummary: "요약",
        .reportExpected: "예상 동작",
        .reportActual: "실제 동작",
        .reportSteps: "재현 단계",
        .reportArea: "영향 영역",
        .reportRedactionNote: "민감한 데이터는 로컬에서 제거됩니다. 복사 전에 보고서를 검토합니다.",
        .reportCopyHint: "보고서는 자동으로 전송되지 않습니다. 직접 복사합니다.",

        .exportReport: "보고서 내보내기",
        .pdfTitle: "재무 개요",
        .pdfSubtitle: "개인 가계 보고서",
        .pdfSummary: "한눈에",
        .pdfGeneratedOn: "생성일",
        .pdfConfidential: "기밀",
        .pdfPage: "페이지",
        .pdfTotal: "합계",
        .pdfColProgress: "진행",
        .pdfUnencryptedNote: "보고서는 읽을 수 있는 암호화되지 않은 PDF입니다. 안전한 곳에 보관하세요.",
        .pdfNoData: "아직 내보낼 데이터가 없습니다.",
        .pdfDefaultHousehold: "우리 가계",

        .lockTitle: "잠김",
        .lockWelcomeSetup: "Kontiva에 오신 것을 환영합니다",
        .lockWelcomeBack: "다시 오신 것을 환영합니다",
        .lockSetupTitle: "비밀번호 설정",
        .lockEnterPassphrase: "비밀번호 또는 PIN 입력",
        .lockWrongPassphrase: "비밀번호가 틀립니다. 다시 시도하세요.",
        .lockRecoveryWarning: "복구가 없습니다. 비밀번호 없이는 데이터에 접근할 수 없습니다.",
        .lockRecoveryAcknowledge: "복구가 없다는 것을 이해합니다.",
        .securityNote: "데이터는 로컬에 암호화되어 저장됩니다 (AES-256-GCM). 클라우드 없음, 서버 없음, 비밀번호 복구 없음.",

        .onboardingIntroBody: "Kontiva는 스위스 가계 예산을 차분히 살펴볼 수 있도록 돕습니다 — 모두 이 기기에서.",
        .onboardingStart: "시작하기",
        .onboardingProfileTitle: "프로필 만들기",
        .onboardingProfileBody: "이름을 정하고 사진을 선택하세요. 둘 다 이 기기에만 남습니다.",
        .onboardingSkip: "건너뛰기",
        .onboardingFeaturePrivate: "완전히 로컬 — 클라우드 없음, 추적 없음",
        .onboardingFeatureSecure: "AES-256으로 암호화",
        .onboardingFeatureMoney: "상팀 단위까지 정확, 반올림 오차 없음",
        .onboardingConfirmPassphrase: "비밀번호 확인",
        .onboardingPassphraseNote: "비밀번호를 안전한 곳에 적어 두세요 — 재설정할 수 없습니다.",
        .backupNudgeText: "암호화 백업을 만드세요. 없으면 비밀번호를 잊었을 때 데이터를 잃습니다.",
        .commonNext: "다음",
        .navMore: "더 보기",
        .actionLock: "잠금",
        .pinSetTitle: "코드 설정",
        .pinConfirmTitle: "코드 확인",
        .pinRequirementNote: "최소 6자리 · 복구 불가",
        .pinMismatch: "코드가 일치하지 않습니다",
    ]
}
