import Foundation

extension Localization {
    static let bs: [L10nKey: String] = [
        .appName: "Kontiva",
        .appTagline: "Smiren, privatan pregled vašeg švicarskog budžeta.",
        .notBetaNotice: "Rana razvojna verzija – nije beta, nije V1.",

        .navOverview: "Pregled",
        .navPlanning: "Mjesečno planiranje",
        .navBills: "Računi",
        .navSettings: "Postavke",
        .navReport: "Prijavi problem",
        .navInsights: "Uvidi",
        .navSparen: "Štednja",
        .sparenSubtitle: "Redovni doprinosi štednji – i ono što je već prikupljeno.",
        .sparenEmpty: "Još nema ciljeva štednje. Odredite za šta štedite svakog mjeseca.",
        .sparenMonthlyTotal: "Štednja / mjesec",
        .sparenAccumulatedTotal: "Već ušteđeno",
        .sparenPerMonth: "/ mjesec",
        .sparenContributions: "doprinosa",
        .sparenSince: "od",
        .sparenOpenEnded: "Bez ciljnog iznosa",
        .sparenGoalsLabel: "Ciljevi",
        .savingsCatCar: "Automobil",
        .savingsCatVacation: "Odmor",
        .savingsCatHome: "Stanovanje",
        .savingsCatRetirement: "Stub 3a / Penzija",
        .savingsCatEmergency: "Fond za hitne slučajeve",
        .savingsCatEducation: "Obrazovanje",
        .savingsCatOther: "Ostalo",
        .savingsCatWedding: "Vjenčanje",
        .savingsCatFamily: "Porodica i djeca",
        .savingsCatRenovation: "Renoviranje i opremanje",
        .savingsCatElectronics: "Elektronika",
        .savingsCatTaxes: "Rezerva za poreze",
        .savingsCatInvestment: "Ulaganja",
        .savingsCatHealth: "Zdravlje",
        .savingsCatGift: "Pokloni",
        .overviewPlannedSavings: "Štednja ovog mjeseca",
        .overviewShowCalculation: "Prikaži izračun",
        .overviewTrendTitle: "Trend · 6 mjeseci",
        .overviewStatusGood: "Zdrav višak",
        .overviewStatusTight: "Tijesno",
        .overviewStatusNegative: "U minusu",
        .overviewAllocationOf: "neto prihoda",
        .formStartDate: "Štedim od",
        .formStartingBalance: "Početno stanje (opcionalno)",
        .insightsSubtitle: "Smjernice za vaš budžet – gdje je vaš novac i gdje možete uštedjeti.",
        .insightOverspending: "Trošite više nego što zarađujete",
        .insightTightBudget: "Malo prostora ovog mjeseca",
        .insightHealthySurplus: "Zdrav višak",
        .insightHighFixed: "Visoki fiksni troškovi",
        .insightHighHousing: "Visoki troškovi stanovanja",
        .insightLargestFixed: "Najveća stavka fiksnih troškova",
        .insightLargestVariable: "Najveći promjenljivi budžet",
        .insightOverdue: "Dospjeli računi",
        .insightNoSavings: "Štednja još nije planirana",
        .insightGoodSavings: "Dobra stopa štednje",
        .insightAllHealthy: "Vaš budžet izgleda zdravo",
        .insightHousingHint: "Smjernica: najviše trećina prihoda",
        .insightNoSavingsDetail: "Imate prostora – cilj štednje mogao bi pomoći.",
        .insightAllHealthyDetail: "Ništa se ne ističe. Dodajte više podataka za preciznije uvide.",
        .fragOfNetIncome: "neto prihoda",
        .fragOfFixedCosts: "fiksnih troškova",
        .fragShortfall: "Manjak",

        .commonAdd: "Dodaj",
        .commonEdit: "Izmijeni",
        .commonDelete: "Obriši",
        .commonCancel: "Otkaži",
        .commandsAdd: "Dodaj unos",
        .billsAddCta: "Dodaj svoj prvi račun",
        .sparenAddCta: "Napravi cilj štednje",
        .overviewAddCta: "Dodaj prihod",
        .commonSave: "Sačuvaj",
        .commonSaved: "Sačuvano",
        .commonClose: "Zatvori",
        .commonDone: "Gotovo",
        .commonShowSampleData: "Prikaži primjere podataka",
        .commonHideSampleData: "Sakrij primjere podataka",
        .commonEmptyHint: "Još nema unesenih podataka.",
        .commonCopy: "Kopiraj",
        .commonOptions: "Opcije",
        .commonMoveUp: "Pomjeri gore",
        .commonMoveDown: "Pomjeri dole",
        .monthToday: "Danas",

        .formName: "Naziv",
        .formAmount: "Iznos (CHF)",
        .formStatus: "Status",
        .formNotes: "Napomena",
        .formInvalidAmount: "Unesite važeći iznos.",
        .formThirteenthAmount: "13. plata (iznos)",
        .formThirteenthModel: "Model 13. plate",
        .thirteenthModelSeparate: "Prikaži zasebno",
        .thirteenthModelAveraged: "Rasporedi na 12 mjeseci",
        .formTarget: "Cilj štednje (iznos)",
        .formSaved: "Već ušteđeno",
        .formMonthlyContribution: "Mjesečni doprinos",
        .formCategory: "Kategorija",
        .formLimitedDuration: "Ograničeni trajni nalog",
        .formLimitedDurationHint: "Npr. 6 rata poreza – broje se samo u tim mjesecima i zatim se automatski uklanjaju.",
        .formStartMonth: "Prva rata",
        .formInstallments: "Broj rata",
        .planningStandingOrder: "Trajni nalog",
        .catRent: "Kirija",
        .catSubscription: "Pretplata",
        .catLeasing: "Lizing",
        .catUtilities: "Režije",
        .catTelecom: "Telekomunikacije",
        .catGroceries: "Namirnice",
        .catFuel: "Gorivo",
        .catTransport: "Prijevoz",
        .catPersonal: "Lično",
        .catDining: "Obroci van kuće",
        .catHousehold: "Domaćinstvo",

        .overviewTitle: "Pregled",
        .overviewAvailableThisMonth: "Dostupno ovog mjeseca",
        .overviewNetIncome: "Neto prihod ovog mjeseca",
        .overviewThirteenthSeparate: "13. plata (zasebno)",
        .overviewRecurringFixed: "Fiksni troškovi",
        .overviewPlannedVariable: "Promjenljivi izdaci",
        .overviewBillsDueThisMonth: "Otvoreni računi ovog mjeseca",
        .overviewOverdueBills: "Dospjeli računi",
        .overviewSavingsTarget: "Cilj štednje",
        .overviewSecurityStatus: "Status sigurnosti",
        .overviewFormulaExplainer: "Dostupno = neto prihod − fiksni troškovi − promjenljivi budžeti − otvoreni računi ovog mjeseca − dospjeli računi. Plaćeni i budući računi ne smanjuju iznos.",
        .overviewEmpty: "Unesite prihode i troškove u Mjesečno planiranje da biste vidjeli pregled.",
        .chartSpendingTitle: "Raspodjela ovog mjeseca",
        .chartByCategory: "Po kategoriji",

        .planningTitle: "Mjesečno planiranje",
        .planningIncome: "Prihod",
        .planningFixed: "Fiksni troškovi",
        .planningVariable: "Promjenljivi izdaci",
        .planningSavings: "Cilj štednje",
        .planningFixedExplainer: "Fiksni troškovi ponavljaju se svakog mjeseca: kirija, osiguranja, pretplate, lizing.",
        .planningVariableExplainer: "Promjenljive budžete planirate sami: namirnice, gorivo, lični izdaci.",
        .planningOneOffHint: "Jednokratnim računima upravljate u „Računi”.",
        .planningEmpty: "Počnite s prihodom, a zatim dodajte fiksne troškove i budžete.",
        .planningBalance: "Planirano stanje",

        .billsTitle: "Računi",
        .billsStatusOpen: "Otvoren",
        .billsStatusPaid: "Plaćen",
        .billsStateOverdue: "Dospio",
        .billsStateDueThisMonth: "Dospijeva ovog mjeseca",
        .billsStateFuture: "Budući",
        .billsAffectsBalance: "Smanjuje dostupni iznos",
        .billsNoBalanceImpact: "Bez uticaja ovog mjeseca",
        .billsDueDate: "Datum dospijeća",
        .billsProvider: "Pružalac",
        .billsEmpty: "Još nema računa. Jednokratni računi s datumom dospijeća prikazat će se ovdje.",
        .billsMarkPaid: "Označi kao plaćeno",
        .billsMarkOpen: "Označi kao otvoreno",
        .billsOpenTotal: "Ukupno otvoreno",

        .navSchulden: "Dugovi",
        .schuldenSubtitle: "Pratite dospjele račune i prinudnu naplatu.",
        .schuldenEmpty: "Nema zabilježenih dugova. Dospjeli računi prikazuju se ovdje automatski – a možete zabilježiti prinudnu naplatu (Betreibung) ili potvrde o gubitku.",
        .schuldenAddCta: "Zabilježi dug",
        .schuldenTotal: "Ukupni dug",
        .schuldenOverdueBills: "Dospjeli računi",
        .schuldenRecorded: "Zabilježeni dugovi",
        .schuldenManagedInBills: "Dospjelim računima upravljajte u „Računi”.",
        .debtTypeOpenClaim: "Otvoreno potraživanje",
        .debtTypeBetreibung: "Prinudna naplata",
        .debtTypePfaendung: "Pljenidba plate/imovine",
        .debtTypeVerlustschein: "Potvrda o gubitku",
        .debtTypeOther: "Drugi dug",
        .debtCreditor: "Povjerilac",
        .debtReference: "Referenca / broj predmeta",
        .debtDate: "Datum",
        .debtType: "Vrsta",
        .schuldenGuidanceTitle: "Kako izaći iz dugova",
        .schuldenTipContactTitle: "Javite se rano",
        .schuldenTipContactBody: "Razgovarajte s povjeriocima rano. Pisani plan otplate na rate često je moguć i izbjegava formalni postupak.",
        .schuldenTipBetreibungTitle: "Ako počne naplata",
        .schuldenTipBetreibungBody: "Nakon platnog naloga imate 20 dana za plaćanje – ili 10 dana za podnošenje prigovora (Rechtsvorschlag) ako je potraživanje neosnovano.",
        .schuldenTipExistenzminimumTitle: "Vaš egzistencijalni minimum je zaštićen",
        .schuldenTipExistenzminimumBody: "Pri pljenidbi vaš egzistencijalni minimum ostaje netaknut – osnovni iznos, kirija, zdravstveno osiguranje i socijalni doprinosi.",
        .schuldenTipVerlustscheinTitle: "Potvrda o gubitku",
        .schuldenTipVerlustscheinBody: "Potvrda o gubitku zastarijeva tek nakon 20 godina. Možete biti ponovo gonjeni samo kada steknete novu imovinu.",
        .schuldenTipCounselingTitle: "Besplatno savjetovanje o dugovima",
        .schuldenTipCounselingBody: "Schuldenberatung Schweiz, Caritas i budžetsko savjetovanje pomažu besplatno i povjerljivo. Prvo otplatite dugove s najgorim posljedicama.",
        .schuldenDisclaimer: "Opće informacije, nije pravni savjet.",

        .catInsurance: "Osiguranje",
        .catOther: "Ostalo",
        .catMortgage: "Hipotekarni kredit",
        .catHealthInsurance: "Zdravstveno osiguranje",
        .catSerafe: "Radio/TV (Serafe)",
        .catPublicTransport: "Prevozna karta",
        .catChildcare: "Čuvanje djece",
        .catMembership: "Članarine",
        .catAlimony: "Izdržavanje",
        .catTaxes: "Porezi",
        .catClothing: "Odjeća",
        .catHealth: "Zdravlje",
        .catLeisure: "Slobodno vrijeme i hobiji",
        .catEntertainment: "Zabava",
        .catChildren: "Djeca",
        .catPets: "Kućni ljubimci",
        .catGifts: "Pokloni",
        .catTravel: "Putovanja",
        .catCharity: "Donacije",
        .catEducation: "Obrazovanje",

        .settingsTitle: "Postavke",
        .settingsLanguage: "Jezik",
        .settingsTheme: "Tema boja",
        .themeSwissRed: "Švicarska crvena",
        .themeOrange: "Narandžasta",
        .themeSand: "Pijesak",
        .themeGreen: "Zelena",
        .themeTeal: "Tirkizna",
        .themeBlue: "Plava",
        .themePurple: "Ljubičasta",
        .themePink: "Roza",
        .settingsData: "Podaci",
        .settingsHousehold: "Domaćinstvo",
        .settingsCanton: "Kanton",
        .settingsProfile: "Profil",
        .profileName: "Ime",
        .profileChoosePicture: "Izaberi profilnu sliku",
        .profileNoPicture: "Bez slike",
        .profileLocalNote: "Sačuvano samo lokalno na ovom uređaju.",
        .settingsSecurity: "Sigurnost",
        .settingsAutoLock: "Automatsko zaključavanje",
        .settingsChangePassphrase: "Promijeni lozinku/PIN",
        .settingsBackup: "Šifrirana rezervna kopija",
        .settingsRestore: "Vrati",
        .settingsPrivacy: "Privatnost",
        .settingsDangerZone: "Opasna zona",
        .settingsDeleteAll: "Obriši sve lokalne podatke",
        .backupCreateTitle: "Napravi šifriranu rezervnu kopiju",
        .backupPassphrase: "Lozinka rezervne kopije",
        .backupHint: "Izaberite zasebnu lozinku za rezervnu kopiju. Potrebna je za vraćanje – lozinku nije moguće povratiti.",
        .restorePreview: "Pregled",
        .restoreConfirm: "Zamijeni sve lokalne podatke",
        .restoreWarning: "Ovo trajno prepisuje sve lokalne podatke.",
        .backupInvalid: "Nevažeća rezervna kopija ili pogrešna lozinka.",
        .backupSavedHint: "Čuvajte datoteku rezervne kopije i lozinku na sigurnom mjestu.",

        .reportTitle: "Prijavi problem",
        .reportSummary: "Sažetak",
        .reportExpected: "Očekivano ponašanje",
        .reportActual: "Stvarno ponašanje",
        .reportSteps: "Koraci za reprodukciju",
        .reportArea: "Zahvaćena oblast",
        .reportRedactionNote: "Osjetljivi podaci uklanjaju se lokalno. Pregledate izvještaj prije kopiranja.",
        .reportCopyHint: "Izvještaj se ne šalje automatski. Sami ga kopirate.",

        .exportReport: "Izvezi izvještaj",
        .pdfTitle: "Finansijski pregled",
        .pdfSubtitle: "Lični izvještaj domaćinstva",
        .pdfSummary: "Na prvi pogled",
        .pdfGeneratedOn: "Napravljeno",
        .pdfConfidential: "Povjerljivo",
        .pdfPage: "Stranica",
        .pdfTotal: "Ukupno",
        .pdfColProgress: "Napredak",
        .pdfUnencryptedNote: "Izvještaj je čitljiv, nešifrirani PDF. Čuvajte ga na sigurnom mjestu.",
        .pdfNoData: "Još nema podataka za izvoz.",
        .pdfDefaultHousehold: "Moje domaćinstvo",

        .lockTitle: "Zaključano",
        .lockWelcomeSetup: "Dobro došli u Kontivu",
        .lockWelcomeBack: "Dobro došli nazad",
        .lockSetupTitle: "Postavi lozinku",
        .lockEnterPassphrase: "Unesite lozinku ili PIN",
        .lockWrongPassphrase: "Pogrešna lozinka. Pokušajte ponovo.",
        .lockRecoveryWarning: "Nema oporavka. Bez vaše lozinke vašim podacima nije moguće pristupiti.",
        .lockRecoveryAcknowledge: "Razumijem da nema oporavka.",
        .securityNote: "Vaši podaci čuvaju se lokalno i šifrirani (AES-256-GCM). Bez oblaka, bez servera, bez oporavka lozinke.",

        .onboardingIntroBody: "Kontiva vam pomaže da imate smiren pregled budžeta vašeg švicarskog domaćinstva – u potpunosti na ovom uređaju.",
        .onboardingStart: "Započni",
        .onboardingProfileTitle: "Napravi profil",
        .onboardingProfileBody: "Dajte sebi ime i izaberite sliku. Oboje ostaje samo na ovom uređaju.",
        .onboardingSkip: "Preskoči",
        .onboardingFeaturePrivate: "Potpuno lokalno – bez oblaka, bez praćenja",
        .onboardingFeatureSecure: "Šifrirano sa AES-256",
        .onboardingFeatureMoney: "Tačno do centima, bez grešaka zaokruživanja",
        .onboardingConfirmPassphrase: "Potvrdi lozinku",
        .onboardingPassphraseNote: "Zapišite lozinku na sigurno mjesto – nije ju moguće poništiti.",
        .backupNudgeText: "Napravite šifriranu rezervnu kopiju. Bez nje gubite podatke ako zaboravite lozinku.",
        .commonNext: "Dalje",
        .navMore: "Više",
        .actionLock: "Zaključaj",
    ]
}
